mongodb/TranslateMetrics/TranslateMetricsAggregationByBook.mongodb
mongodb/TranslateMetrics/TranslateMetricsAggregationByChapter.mongodb

- we need to sum the max word count of each segment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1149)

Fix metric word count again

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

====
(And so this shouldn't break as a result of coming changes.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1178)

SF-1417a Specify behaviour when dragging to earlier in segment

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

* move getVerseSegments method to text-view-model
* move verseSlug to shared utils
* filter for question verses for a given chapter in checking-text component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1180)

SF-1433 Highlight combined verse segments

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts

- also changed the change password failure message to a dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1095)

Add some auth service tests

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts

- Split out some drag-and-drop functionality into methods since
addEventListener('drop') is growing.
===
This was produced by pulling apart a git commit on its way to develop branch, to merge the refactor to master first. Content here was originally in #1179. Some parts of #1179 were removed when making this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1184)

SF-1417b Refactor growing method in drag-and-drop

---

src/SIL.XForge/Realtime/RichText/Delta.cs
test/SIL.XForge.Tests/Realtime/RichText/DeltaTests.cs

When text formatting has changed, we need to update the CIDs for the entire string of text that was affected, not just the substring within the text. Otherwise the CIDs on the affected substring is inconsistent with the CIDs on the other part of the string.
This is the result with CIDs are inconsistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1185)

SF-1435 Update char Ids when text or text formatting has changed

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* detect when an update is local
* apply remote updates to current editor content
* update adjustDeltaForEmbeddedElements to handle converting to text doc and from text doc
* move method for getting the editor position to text view model
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1172)

SF-1413 Notes respond to realtime remote edits

---

src/RealtimeServer/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1181)

Fix some npm dependencies

---

src/SIL.XForge/Realtime/RichText/Delta.cs

===
@RaymondLuong3 What do you think of these further edits? In particular, are the comments accurate?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1188)

delta: comments, edit

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts

The change to the tests re-orders two of the questions with no other changes to those questions. This is difficult to see just by looking at the diff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1201)

SF-1449 Sort questions by canonical order on overview page

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

- text.component.ts update(), editor.component.ts onTargetUpdated(),
and updateVerseNoteThreadAnchors() run with the assumption that the
editor's selection is in the current segment, and that the incoming
delta ops regard that segment. This has not been so for
drag-and-drop, where text is inserted in a destination segment while
there may be a selection in a different segment.
- Modify drag-and-drop to (optionally) remove the selection, set the
insertion point in the destination, and then insert text. Let the
activity be interleaved with TextComponent.updated events. Behaving
more like a user in this regard allows TextComponent and
EditorComponent to continue their assumptions. This allows threads to
be re-anchored correctly. Deletes happen in the segment with text
being deleted. In this …

SF-1417d Order drag-and-drop activity like user

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* add the embed count to the text anchor length
* the text anchor consists of the text anchor length and the number of embeds within the text length
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1200)

SF-1425 Fix detecting when a deletion occurs within a text anchor

---

scripts/db_tools/find-problem-cids.ts
scripts/db_tools/list-projects.ts
scripts/db_tools/package-lock.json
scripts/db_tools/package.json
scripts/db_tools/text-doc-history.js
scripts/db_tools/tsconfig.json
scripts/db_tools/utils.d.ts
scripts/db_tools/utils.js

(Please don't squash, but rebase the  commits to master)
This new script doesn't fix anything, but it identifies potential problem areas in the SF DB where character formatting may be using cids that are inappropriately not the same as adjacent cids.
I added another script called list-projects.ts. Sometimes I have an SF ID and need a PT ID or similar situation. This will let us lookup a project by shortName, SF ID, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1192)

[no squash] revise, add utils - cid problem detection

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1212)

SF-1326 Fix exception when deleting book that has answers with audio

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1216)

SF-1453 Prevent import of exact duplicate questions from CSV file

---

scripts/db_tools/find-problem-cids.ts

===
This was helpful when doing some investigation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1215)

utils: find-problem-cids filters by --proj

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html

This is a change to the checking overview page that improves question import speed. Looking at the changes may lead one to believe this is premature optimization, but the data consistently says otherwise.
This chart shows how long it takes to import questions. The vertical axis is milliseconds, and the horizontal axis shows how many questions have been added. So what this chart is showing is that when you import questions, each question takes longer (on average) to import than the previous question. This pull request doesn't fix this entirely, but it makes the slope much more gradual. The total width of the chart is 1533, corresponding to the total number of questions I had to import. The blue line doesn't reach all the way to the right side of the chart because it was progressing too …

Optimize checking overview page to speed up question imports

---

.vscode/settings.json

- also reorder items alphabetically
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1222)

Set VS Code tabSize to 2 spaces

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

The actual change is trivial; the tests have a much bigger diff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1228)

SF-1476 Prevent importing blank questions from CSV file

---

scripts/db_tools/show-projects.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1229)

utils: fetch text docs

---

scripts/db_tools/import-doc.js

This makes it easy to check out a doc locally, or push a local doc to a remote server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1231)

Add script to import or clone a text doc

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.spec.ts

- Prevent editing of known corrupt text docs
- Inform user doc is corrupt
- Make editor border color consistent with other borders
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1238)

SF-1488 Prevent editing of known corrupt text docs

---

src/RealtimeServer/common/exception-reporter.ts
src/RealtimeServer/common/index.ts
src/RealtimeServer/common/metadata-db.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1246)

Linting: add return types

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

---
This PR is some followup after doing SF-1454.
I prefer for this PR to have its individual commits retained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1233)

drop: simplify blank and specify when sibling

---

src/Help/UpdateHelp/Program.cs

There were some instructions that I didn't fully understand. I've added some information to help clarify the instructions. Let me know if I interpreted things right.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1256)

Clarify instructions to localize helps

---

mongodb/databases/dropDBNonSF.mongodb

This has already been run on QA and Live. It might not make our QA Mongo more stable but it is worth a try and the cleanup was overdue anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1255)

Add Mongo databases cleanup script

---

src/SIL.XForge.Scripture/Services/InternetSharedRepositorySourceProvider.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs

===
@Nateowami Here is some requested followup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1262)

Improve error messages

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1261)

Add logging when SharedProject is null

---

src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts
src/SIL.XForge.Scripture/Models/SFProjectUserConfig.cs

commit-id:7570faa8
---
**Stack**:
- #1270
- #1269
- #1268
- #1267
- #1266 ⮜

Move NoteRefsRead out of checking area.

---

src/RealtimeServer/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json

- npm audit fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1275)

Fix dependencies minimist & ansi-regex

---

.vscode/launch.json
src/Migrations/SyncUserToPTUser/SyncUserToPTUserService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1279)

Write Paratext users when list is empty

---

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1280)

SF-1472 Bump version number on indexeddb

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1290)

merge: clean-up

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts

- Note that it will look differently depending on whether it's part of
a verse number or in the middle of a verse text.
---
**Stack**:
- #1297
- #1289
- #1288
- #1287
- #1286
- #1278 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1278)

SF-1506 Support USFM tag va - verse number alternate

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- ParatextService calls
IInternetSharedRepositorySource.GetRepositories() in a number of
places. Almost all of these locations were associated with recent 401
Unauthorized errors. Understanding and preventing these errors may be
helped by having a better understanding of the context, such as
whether or not SF thought the user had a project role. Each call to
GetRepositories() happens in a context with different information
available. This patch logs what information is available and re-throws
the exception.
---
**Stack**:
- #1297
- #1289
- #1288
- #1287
- #1286 ⮜
--- …

Log more when trouble fetching repositories

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

**Stack**:
- #1297
- #1289
- #1288 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1288)

tidy: wrap lines

---

src/SIL.XForge/Models/Project.cs

**Stack**:
- #1297
- #1289 ⮜
- #1288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1289)

Comment on Project.UserRoles

---

scripts/db_tools/show-projects.ts

To clarify whether we are waiting for the connection to timeout, or
data to be fetched over a successful connection.
---
**Stack**:
- #1297 ⮜
- #1289
- #1288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1297)

utils: print more status

---

src/SIL.XForge/Controllers/UsersRpcController.cs

This was removed by mistake in #1265 due to a rebase gone awry before merging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1310)

Add CheckUserNeedsMigrating endpoint back to UsersRpcController

---

test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- So that it is more easily adjustable in tests.
- The implementation in this change is designed to mimic class
TestGuidService.
---
**Stack**:
- #1311
- #1308
- #1307
- #1306
- #1305 ⮜
- #1304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1305)

test: refactor from TestGuidService

---

src/SIL.XForge.Scripture/Models/Comment.cs
src/SIL.XForge.Scripture/Models/NoteThread.cs
src/SIL.XForge/Models/Project.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1270)

Improve sync tests, comment

---

mongodb/Users/duplicate_paratextid.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1316)

Add Mongo query to find users with indentical Paratext user ids

---

src/RealtimeServer/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1317)

Fix some vulnerabilities

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This PR is against master, but there's also a PR to hotfix against live. See #1319.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1320)

Hotfix: Skip updating Paratext comment thread with notes

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

This is a hotfix to pull in changes made in #1318
(cherry picked from commit 7b31ea7dba0790db07cd0c464e87940d6c627713)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1321)

SF-1546 Get sync to succeed with duplicate project notes (#1318)

---

scripts/db_tools/manipulate-sharedb.ts
scripts/db_tools/package.json
scripts/db_tools/utils.d.ts

- This can be used to modify the db thru sharedb.
---
**Stack**:
- #1325
- #1324
- #1323 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1323)

tool: add manipulate-sharedb.ts

---

mongodb/Users/findDuplicateParatextId.mongodb

commit-id:188c87f5
---
**Stack**:
- #1325
- #1324 ⮜

tool: rename, comment on find-dup-ptId

---

mongodb/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1325)

doc: how to run monogodb scripts

---

src/RealtimeServer/common/diagnostics.ts
src/RealtimeServer/common/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1345)

SF-1556a Add ability to profile Node process by sending SIGUSR2 signal

---

src/RealtimeServer/common/diagnostics.ts
src/RealtimeServer/common/index.ts

See the main PR, #1345. This PR is a hotfix against qa with the same commit (cherry-picked).
(cherry picked from commit 99bf33c76f38dec2483247541777c927efe80987)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1346)

qa-hotfix: SF-1556a Add ability to profile Node process by sending SIGUSR2 signal

---

mongodb/Texts/TextsWithMultipleChapters.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1352)

Add Mongo query to find texts with multiple chapter inserts

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* refresh project comment manager when updating note thread docs
* also update to latest Paratext Data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1357)

SF-1559 Explicitly get up-to-date notes from Paratext Data

---

scripts/db_tools/package-lock.json
scripts/db_tools/package.json

I went through the packages in this package.json and looked to see what versions they were at in other package.json files. Then I updated this package.json with those versions and ran `npm install`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1358)

Update packages in db_tools to match other package.json files

---

mongodb/Users/CountUsersByInterfaceLanguage.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1359)

Add Mongo query to count users by interface language

---

mongodb/Projects/FindProjectsWithAnswers.mongodb

This gives us some insight into how widespread the user of audio questions and answers is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1361)

Update Mongo query to find questions and answers with audio

---

scripts/db_tools/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1363)

Update README.md in db_tools

---

deploy/dependencies.yml

@marksvc I think this is an OK first step for updating Node, but please correct me if you think otherwise. I think we would merge this in and have developers run Ansible, and then test that everything is still working fine in development before making the update on QA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1362)

SF-1568 Update dependencies.yml to specify Node 16

---

scripts/db_tools/import-project.ts

commit-id:11ee03e4
---
**Stack**:
- #1370
- #1369
- #1367
- #1366
- #1365
- #1364
- #1351 ⮜

tool: add import-project.ts

---

scripts/db_tools/manipulate-sharedb.ts

commit-id:a0d6188e
---
**Stack**:
- #1370
- #1369
- #1367
- #1366
- #1365
- #1364 ⮜

tool: update mongo syntax in manipulate-sharedb.ts

---

scripts/db_tools/manipulate-sharedb.ts

**Stack**:
- #1370
- #1369
- #1367
- #1366
- #1365 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1365)

tool: add example to manipulate-sharedb

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

commit-id:11445220
---
**Stack**:
- #1370
- #1369
- #1367
- #1366 ⮜

sync: also report SR results if throw

---

src/RealtimeServer/scriptureforge/models/sync.ts

It is present on Sync.cs.
commit-id:ac568990
---
**Stack**:
- #1370
- #1369
- #1367 ⮜

model: add missing sync.syncedToRepositoryVersion

---

scripts/db_tools/find-problem-cids.ts
scripts/db_tools/manipulate-sharedb.ts
scripts/db_tools/show-projects.ts
scripts/db_tools/utils.d.ts

**Stack**:
- #1370 ⮜
- #1369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1370)

tool: style: where license is stated

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1376)

SF-1574 SF-1575 Disable multicursor presence when readonly

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1378)

SF-1573 disable multi-cursor presence when offline

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* keep font size up-to-date
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1383)

Set default font size for source text

---

scripts/db_tools/show-doc.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1397)

Add script to show text doc

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

The current logging has raised more questions.
More information is in SF-1507.
---
**Stack**:
- #1403 ⮜
- #1402
- #1401
- #1400
- #1395
- #1393
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1403)

log: report more when duplicate PT username problem

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- Although we adjust selections after the fact to be valid, if a user
starts to make a selection, and begins typing text before letting go
of the mouse, we end up replacing the selection with the new input.
This can allow selecting over verse numbers and losing
those verse numbers.
- Listen for 'beforeinput' and cancel processing the input if the
selection is not valid.
---
**Stack**:
- #1406
- #1405
- #1402
- #1401
- #1400
- #1395
- #1393 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1393)

SF-1565a Cancel input when invalid selection

---

src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

commit-id:b4ff72a3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1411)

SF-1626 Prompt for contact if last sync was failure

---

mongodb/Projects/ProjectFontUsage.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1407)

Add query to count projects using each font

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs
src/SIL.XForge.Scripture/Services/SFScriptureText.cs
test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1429)

Update to Machine 2.5.11

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

This PR fixes a crash that occurs when running `EngineRuntime.BuildRunner.RunAsync()` in Hangfire when connecting to a new project and resource, that occurs because the project document and text documents have not yet been committed to Mongo.
This crash is fixed by starting the machine engine training only after the project and text documents have been committed to Mongo.
The stack trace from the crash is:
```
An exception occurred during performance of the job.
System.Collections.Generic.KeyNotFoundException: The given key 'bleu' was not present in the dictionary.
at
System.Collections.Generic.Dictionary`2.get_Item(TKeykey)at SIL.Machine.WebApi.Services.EngineRuntime.<>c__DisplayClass40_0.<BuildAsync>b__0(Enginee)
SIL.Machine.WebApi.DataAccess.DataAccessExtensions.ConcurrentUpdateAsync[T] …
```

SF-1639 Delay machine engine training until after document transaction commit

---

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/Services/SyncService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs

* also fix sync progress bar to show progress of based on text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1435)

SF-1638 Sync based on text even when suggestions disabled

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

Before
After
(When suggestions are disabled at the project level)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1439)

SF-1636 Hide suggestion settings when suggestions disabled

---

README.md

commit-id:12d4f2fa
---
**Stack**:
- #1452
- #1406
- #1445
- #1444
- #1443 ⮜

doc: move prettier section

---

README.md

commit-id:8f818b8d
---
**Stack**:
- #1452
- #1406
- #1445
- #1444 ⮜

doc: add C# formatting

---

src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs
src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
src/SIL.XForge/Realtime/RealtimeService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1452)

style: adjust C#

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1457)

SF-1624 Fix training indicator for RTL UI

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

Before | After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1462)

SF-1667 Fix stars on suggestion card for RTL UI

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

- Created new dialog component for showing text notes
- Set background colors for end notes, cross-references, and end notes and made them clickable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1448)

SF-1635 Open footnotes in dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- Check the translation engine setup again if editing rights have changed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1465)

SF-1630 Fix Machine API 400 error when PT role changes

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts

- Prevent scrollbar (caused by overflow)
- Mirror play button
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1472)

SF-1627 Fix audio player in RTL mode

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1471)

SF-1680 Internationalize share control role

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1477)

SF-1692 Fix order of books on translate overview page

---

src/SIL.XForge.Scripture/locales.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1470)

SF-1554 Enable Arabic localization in production

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

This is done in hope that projects that have had a sync failure are more likely to notice and reach out to us.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1475)

SF-1691 Show indication in menu when sync has failed

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1463)

SF-1390 Users with a project role can join project via share link

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts

- Moved filtering questions to where questions are toggled
- Fix to remove the active verse if the text changes
- Added missing selector ] in tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1478)

SF-1693 Fix question icons not showing up

---

.github/workflows/build-and-test.yml

commit-id:3a00b36b
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1490)

ci: gha: add OS ubuntu-22.04

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json

This fixes two out of three vulnerabilities listed by `npm audit`, but running `npm audit fix`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1500)

Update moment and npm using npm audit fix

---

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts

This creates a new generic dialog for showing messages and offering options. Here's how it looks in the collaborators component (and this is the only new dialog introduced in this commit):
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1497)

SF-1736 Confirm before removing user

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- Allow any time of note to be clicked
- Added support for hidden notes
- Use cross character for cross-references when a custom caller is not used
- Improved support for customer callers that are more than 1 character
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1499)

SF-1702 Improve support for other footnote callers

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss

**Note the target branch of this pull request is `feature/edit-notes`.**
This is a suggested change to #1486.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1498)

Simplify responsiveness of note dialog edit and delete buttons

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1509)

SF-1704b Show edit options only when feature enabled

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

(cherry picked from commit 4d96fbd7b3774233553eb4796606be25d3605822)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1513)

SF-1750a Temporarily disable writing of currentProjectId (#1512)

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

(cherry picked from commit d8c45e1e383834ad5b444f17bdec3ca1c07b7ed3)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1516)

SF-1743a Stop sync if repo mismatch (#1515)

---

test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

commit-id:c9566689
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1517)

SF-1743b Revise test comments

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts

This should also fix SF-1017.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1518)

SF-1750 SF-1017 Fix infinite loop when user doc updated

---

src/SIL.XForge.Scripture/Models/Sync.cs
src/SIL.XForge.Scripture/Services/IJwtTokenHelper.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/IScrTextCollection.cs
src/SIL.XForge.Scripture/Services/JwtTokenHelper.cs
src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

**Stack**:
- #1521
- #1520 ⮜
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1520)

Add some nullable annotations

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

* show a confirmation dialog when a user clicks to delete a note
* delete the note from the thread if the user confirms
* delete the note thread doc if the note is the last one in the thread
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1496)

SF-1724 Allow a user to delete a note from a thread

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

* create or modify note thread on dialog save
* return boolean on dialog close to indicate if notes need to be refreshed
* update tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1525)

Move note creation and edit logic into the dialog component

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- Subscribe to remote note thread changes
- Re-embed note threads to ensure any changes are implemented i.e. remove resolved
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1536)

SF-1757 - Note icon does not disappear when resolved in PT

---

src/SIL.XForge.Scripture/Models/Sync.cs
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/IJwtTokenHelper.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/IScrTextCollection.cs
src/SIL.XForge.Scripture/Services/JwtTokenHelper.cs
src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge/SIL.XForge.csproj
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Tests/SIL.XForge.Tests.csproj

commit-id:b85bd114
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1560)

dev: broaden C# to project-wide nullable annotations

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts

Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1548)

SF-1780 Update share link to material

---

src/SIL.XForge.Scripture/Properties/launchSettings.json

commit-id:72a09221
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1565)

dev: do not launch browser after compile

---

.vscode/launch.json
README.md
src/RealtimeServer/tsconfig.json
src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs
src/SIL.XForge.Scripture/Startup.cs
src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs

commit-id:c1504a7d
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1559)

dev: add attach to realtime server

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

commit-id:5cb138e0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1567)

SF-1789 Skip non-PT users when querying unregistered project PT roles

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

I did the initial work for this some time ago and only now got around to finishing it up. Likely to slightly conflict with #1549.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1553)

SF-1781 Add role description to role selector

---

scripts/db_tools/text-doc-history.js

- Add more console output to add clarity whether the connection is
working, and how much information is going to be displayed.
- Cope with situations where we may not be able to query a user by id.
- Provide easy toggles for collapsing and showing op attributes.
commit-id:87be40c8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1561)

tool: enhance text-doc-history.js

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

Such as from SF-1776.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1573)

Clarify source of NullReferenceException

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts

Before | After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1568)

SF-1790 Fix direction of text in snackbar

---

scripts/db_tools/utils.d.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1580)

tool: add deleteDoc to TS API for scripts

---

src/SIL.XForge/Models/Tokens.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1584)

doc: fix token expiration comment

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1588)

doc: fix level of section linting and formatting

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1593)

Replace deprecated trimLeft and trimRight with trimStart and trimEnd

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

- Reverts temporary app component changes from #1576 (the `throttleTime`, as well as changes to the tests)
- Improved the performance of determining which books have questions
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1577)

SF-1805 Improve performance of questions query in app component

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1599)

Implement onBlur again for Quill to help our tests

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

- A type should have been declared as `string | undefined`, but was instead declared as `string`.
- The observable for the project ID was subscribed two twice, making all its internal logic run twice, when it should have only run once.
More explanations for the changes have been commented on their respective lines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1578)

SF-1816 Fix app component observable type and behavior

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1594)

dev: reduce nesting in app component ngOnInit

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1590)

doc: update production build steps to use script

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Services/ProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

* enable inviting users as a reviewer
* only allow administrators to invite reviewers
* update endpoint to accept the reviewer role in the invite
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1549)

SF-1778 Add reviewer role for invitation and share links

---

.prettierignore
src/RealtimeServer/.prettierignore
src/SIL.XForge.Scripture/ClientApp/.prettierignore

commit-id:65813f17
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1566)

format: ignore angular cache files

---

scripts/db_tools/import-project.ts
src/RealtimeServer/typings/sharedb/lib/client.d.ts

- The state type is from considering
node_modules/sharedb/lib/client/connection.js.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1581)

tool: import-project: make it more plain if connecting

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* add insert note FAB when reviewer selects a verse
* make FAB appear at the same y-coordinates as the segment
* underline a selected verse when a user clicks the text
* remove note thread styling for reviewer users
* TODO: improve experience on mobile view
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1574)

SF-1782 Enable insert note FAB for reviewer users

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/Services/ParatextService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1582)

dev: clarify and adjust variable names

---

.github/workflows/build-and-test.yml

It looks like we were checking the version, but not actually doing anything to set it up, so we just got whatever version happened to be installed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1611)

Fix GHA workflow to set up .NET version

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json

This change was made by running npm audit fix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1609)

Fix vulnerabilities in engine.io and loader-utils

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1587)

doc: offline testing

---

scripts/db_tools/package-lock.json
scripts/db_tools/package.json
scripts/db_tools/ping-rts.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1583)

tool: add ping-rts.ts to query the state of the realtime server

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1608)

Update README to better reflect current status of MDC and Flex-Layout

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts

- Removed deprecated event with version updates
- Added a timer to check for new updates rather than just on load
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1603)

SF-1791 - Fix UpdateAvailableEvent deprecation in PWA service

---

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1617)

Fix catching of errors to be type safe

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1606)

SF-1821 Confirm before deleting answers

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json

This was done by running `npm audit fix`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1628)

Update decode-uri-component to fix vulnerability

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1630)

SF-1828 Fix generic dialog direction

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1589)

doc: add section .NET performance profiling

---

README.md
deploy/dependencies.yml
src/Help/UpdateHelp/UpdateHelp.csproj
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge/DataAccess/DataAccessApplicationBuilderExtensions.cs
src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
src/SIL.XForge/DataAccess/MongoRepository.cs
src/SIL.XForge/DataAccess/XFFieldDefinition.cs
src/SIL.XForge/Realtime/RealtimeJsonService.cs
src/SIL.XForge/SIL.XForge.csproj
src/SIL.XForge/Services/EmailService.cs
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Scripture.Tests/Services/JwtInternetSharedRepositorySourceTests.cs
test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
xForge.sln

This change updates .NET dependencies, and fixes .NET compiler warnings and removes all pragma warning suppressions. Changes include:
* Updated ParatextData to 9.3 and SIL.Core to 10.1
* Modified `MockScrText` to conform to `ScrText` more correctly
* Updated Hangfire and Hangfire.Mongo to the latest version, and modified the config to match the behavior changes in the new versions
* Updated MongoDB Driver to 2.18 (adds support for MongoDB 6.0), and updated dependent code
* Updated the ASP.Net Core dependencies to the latest 6.0.x version
* Changed the NetCore.MailKit dependency to MailKit, as we were using none of the extra functionality provided by NetCore.MailKit
* Updated Jering.Javascript.NodeJS, Autofac, EdjCase.JsonRpc.Router, HtmlAgilityPack, NSubstitute, NUnit, IdentityModel, …

.NET Dependency Updates

---

src/SIL.XForge.Scripture/Models/SFProjectRole.cs
src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Services/IUserService.cs
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* determine if a user is a community checker
* add username as content on the answer and comment
UPDATED
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1625)

SF-1827 Add username for community checkers

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1643)

doc: add section on invalidating refresh tokens

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1641)

doc: add section Cleaning

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1647)

Simplify usage of confirmation dialog

---

src/RealtimeServer/common/web-socket-stream-listener.ts
src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json

See https://github.com/sillsdev/web-xforge/security/dependabot for a description of the vulnerabilities.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1658)

Update jsonwebtoken and json5 to fix vulnerabilities

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

The tests on this are unfortunately failing. I opened the PR knowing this was the case.
Please see the linked issue for an explanation of the problem at hand and what this is trying to solve.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1575)

SF-1802 Throw exception when registry returns error fetching project

---

scripts/db_tools/show-jwt.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1674)

tool: show jwt issuedAt

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1679)

Update cookiejar and ua-parser-js using npm audit fix

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1680)

Log sync metrics to stdout

---

scripts/monitor-server-processes.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1681)

tool: add tool for process monitoring

---

src/RealtimeServer/common/models/project-rights.ts
src/RealtimeServer/common/services/project-data-service.spec.ts
src/RealtimeServer/scriptureforge/models/sf-project-rights.ts

- I've reformatted the permissions to make them more maintainable
- All Paratext roles have been given view permission on the note threads (thus fixing the actual bug).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1676)

SF-1854 Fix note thread permissions

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

This Pull Request fixes an issue when `CommentManager` reloads each comment XML file from disk every time that the Note Thread Docs are updated for a book.
This bug occurs because `CommentManager.LoadIfChanged()` reloads the comment XML files not only comment XML they have changed on disk, but also if each XML file has not been updated via `CommentManager.SaveUser()`.
This affects not only speed but memory usage as each note in each comment XML file is serialized into `Comment` classes, for every book.
To resolve this issue, the `CommentManager` loads the XML files from disk just once, immediately after the Paratext Sync has completed.
In my testing, the sync time for a project with 10,000 notes and 70 books reduced from ~2:00 minutes to ~1:30 minutes.
- - - …

Optimize Comment Manager Loading

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1699)

hotfix comment manager, hangfire

---

mongodb/Projects/FindLargestHangfireStateHistory.mongodb

This was helpful to me recently, and will be helpful to have if I need to do it again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1697)

tool: add FindLargestHangfireStateHistory

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

- Added bottom sheet to appear on mobile for specific viewports
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1672)

SF-1815 Improve adding notes in mobile view for reviewer users

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1700)

SF-1874 Hide community checking from SF reviewers and observers

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

commit-id:da23732e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1705)

log: report issuedAt time when trouble with token

---

tools/CommentGenerator/CommentGenerator.csproj
tools/CommentGenerator/CommentGenerator.sln
tools/CommentGenerator/Program.cs

I have created a program that can generate a Paratext Comments XML file, in a new directory called "Tools".
If you would rather this goes in another repository, and we just link to it from the SF wiki (when that is done), then that is not problem as it does not actually require any of the Scripture Forge components.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1702)

Paratext Comment XML Generator

---

.vscode/settings.json

commit-id:34cdfa5f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1706)

dev: vscode: set prettier and csharpier formatters

---

src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

- Updated project rights for admin to create answers
- Adjusted logic to still allow admin to view answers without being required to answer a question first
- eslint return type fixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1696)

SF-1783 Allow admins to answer questions

---

scripts/auth0-manage.ts

commit-id:44faa3d5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1713)

tool: add auth0-manage.ts

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1715)

SF-1880 Prompt before deleting comment

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

* add note dataId to the project user config when saving a new note
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1709)

SF-1878 Mark note read when inserting new notes

---

src/RealtimeServer/scriptureforge/realtime-server.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-service.ts

Projects shouldn't have this, but some have failed and kept this property around
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1720)

Add migration to remove percentCompleted from sync property

---

src/RealtimeServer/scriptureforge/realtime-server.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-service.ts

**This is a hotfix to live, cherry-picked from master.**
Projects shouldn't have this, but some have failed and kept this property around
(cherry picked from commit cedcd3a1778144e13bdb08b911734099e03f635c)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1721)

hotfix: Add migration to remove percentCompleted from sync property

---

mongodb/Projects/CountUserRoles.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1726)

Add Mongo query to count users by role

---

src/RealtimeServer/common/index.ts
src/RealtimeServer/common/realtime-server.ts
src/RealtimeServer/scriptureforge/migrator.ts
src/RealtimeServer/scriptureforge/realtime-server.ts
src/RealtimeServer/scriptureforge/tsconfig.build-esm.json
src/SIL.XForge.Scripture/Migrator.cs
src/SIL.XForge.Scripture/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1735)

SF-1906 Separate migration into distinct subprocess

---

.vscode/launch.json

commit-id:f1b8360a
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1738)

dev: add target to debug ts-node script

---

scripts/db_tools/show-projects.ts

- Run from any directory.
- Use for..of to finish processing before moving on to finally and
closing connection.
- Only .find specified texts, not all texts.
commit-id:0ef9173e
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1737)

tool: improve show-projects.ts

---

src/SIL.XForge.Scripture/Migrator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1739)

SF-1906b Fix migrator path in production environments

---

src/SIL.XForge/Realtime/MemoryExceptionHandler.cs
src/SIL.XForge/Realtime/MemoryRealtimeService.cs
src/SIL.XForge/Realtime/RealtimeJsonService.cs
test/SIL.XForge.Scripture.Tests/Services/MachineBuildServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/MachineCorporaServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/MachineTranslationServiceTests.cs

This Pull Request improves logging for the Realtime JsonService.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1741)

Improve logging in the RealtimeJsonService

---

src/RealtimeServer/scriptureforge/migrator.ts

(cherry picked from commit 75664930d6fcfa1b32c3d751e27c0484d095c9cc)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1750)

Fix migrator reading appsettings in production

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

- Removed the block for accessing the update display name dialog
- Return type fixes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1760)

SF-1927 Allow all users to update their display name

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- Removed button from toolbar
- Allow anyone with edit text rights to see the FAB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1755)

SF-1914 - Remove new note from toolbar and show FAB to admin

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

- Set type for sortBy to use date rather than string
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1747)

SF-1908 Fix order of comments that were added in Paratext

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

* Fixes a 403 error when a checker deletes their own answer if it has comments made by another user
* Fixes a display bug where deleted answers were included in the answer count on the Checking Overview screen
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1787)

SF-1953 Fix for checker receiving a 403 error when deleting an answer

---

scripts/db_tools/db-token-info.ts

commit-id:3d92d270
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1703)

tool: allow email arg to db-token-info

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/SFScriptureText.cs

- Update to version of Machine with suggestion fixes
- Text segments from SF should never be in a range
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1799)

Fix poor quality translation suggestions

---

mongodb/databases/DropXFDatabases.js

This is useful when testing old commits and needing to start from a clean slate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1802)

Add Mongo script to drop databases

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1804)

SF-1969 Do not add a tag id to notes on existing thread

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1803)

Add font size stories and fix font size picker in RTL mode

---

mongodb/TranslateMetrics/CountEditsByMonth.mongodb

This is very similar to the recently merged #1801, but for suggestion metrics instead of answers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1806)

Add Mongo query to show trends in suggestions and edits

---

.github/workflows/chromatic.yml
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

This should enable Chromatic to run visual tests on our PRs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1808)

Add Chromatic

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1813)

Hotfix: Skip updating Paratext notes

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

(cherry picked from commit c9811f649404e0aaafc8567c93dae4282b8cf984)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1815)

Hotfix: Skip updating Paratext notes (#1813)

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss

A | B
--|--
Before | ![](https://user-images.githubusercontent.com/6140710/236091811-e8c3fef8-4615-4162-8797-b0522e61763c.png)
After | ![](https://user-images.githubusercontent.com/6140710/236091805-5390700a-b756-4552-a03f-ca502361b4d9.png)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1817)

Fix height of send button in share control

---

mongodb/Questions/AnswerStats.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1818)

Add Mongo query to analyze use of answers and comments

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.stories.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1827)

Add write-status stories

---

mongodb/Texts/CountProjectsWithEdits.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1819)

Add query to count projects with lots of edits

---

.vscode/settings.json
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1844)

SF-2014 Convert checking comment form to Material

---

codecov.yml

See https://docs.codecov.com/docs/common-recipe-list#set-non-blocking-status-checks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1849)

Make Codecov checks informational only

---

src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs

A job is currently stuck which seems to take longer than the current 2 hours. This PR increases the Hangfire Invisibility Timeout to 3 hours, which should be enough time to complete the job.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1853)

Increase Hangfire Timeout to 3 hours

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1836)

SF-2006 Checking overview page to Material

---

src/SIL.XForge.Scripture/ClientApp/.storybook/preview-head.html
src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
src/SIL.XForge.Scripture/ClientApp/.storybook/util/mat-dialog-launch.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1848)

SF-2010 Convert system admin page to material

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1856)

SF-2017 Convert suggestions component to Material

---

src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts

@nigel-wells I had enough changes to suggest that I decided to just create a PR against your branch. Feel free to merge or close as you see fit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1876)

Simplify join component stories

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.stories.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1863)

SF-2016 Convert 'write status' component to material

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

commit-id:a0aacad7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1877)

log: resource needs updating or not

---

scripts/db_tools/text-doc-history.js

commit-id:30dc7691
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1824)

tool: enhance time output from text-doc-history

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1874)

SF-2008 Justified share dialog buttons without reversing the row direction

---

.github/workflows/chromatic.yml

See https://www.chromatic.com/docs/github-actions#enable-turbosnap for documentation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1883)

Enable Chromatic TurboSnap

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1866)

SF-2036 Checking comments components use mat-button

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n-story.module.ts

Before | After
-------|------
- Drop shadow has been added back (I think it used to be there)
- Border-radius is fixed
- Confidence is aligned to the right
Also, I added a Storybook story showing the component in RTL mode. This was a major motivation of this change; I wanted to be able to create localized stories to test components in RTL, but hadn't figured out how to do it before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1890)

SF-2069 Improve suggestion component

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1893)

SF-2075 Add Scripture audio feature flag

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1897)

SF-2078 Remove use of MDC in editor component

---

src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

This version number was chosen based on this table from Angular: https://angular.io/guide/versions#actively-supported-versions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1900)

SF-2082 Update TypeScript to 4.8.4

---

src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
src/SIL.XForge.Scripture/ClientApp/angular.json
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/overlay-container.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1862)

SF-2015 Convert font size component to material

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.stories.ts

This is a display-only component; it knows nothing about audio.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1898)

SF-2080 Create circular audio progress component

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj

@pmachapman Can you confirm this comment is correct?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1918)

Add comment to csproj file

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/project-notification.service.ts

When a user quickly navigates away from the sync page after clicking "Synchronise", errors can be triggered in SignalR. These are caused by the closing of the SignalR connection.
This Pull Request filters out these specific errors, but ensures that any other errors that maybe caused by a real issue, such as a server 500, etc, will be reported via our standard error reporting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1917)

SF-2060 Suppress SignalR errors related to user navigation

---

scripts/db_tools/show-projects.ts

commit-id:a830fcb1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1925)

tool: show-project: be resilient to unexpected db data

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs

This is a followup to #1924 to allow adding dummy audio data. Being able to delete data is important to be able to develop and test a feature like this.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1927)

SF-2112b Add button to delete timing data

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts

Just had to include the InfoComponent
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1933)

Fixing non-fatal test errors

---

src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

- Save audio files with names like MRK_001.wav so files that are manually copied to the upload directory can be played
- Minor changes to SF-2106 (#1928)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1931)

SF-2112c Improve mock audio files

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts

Here's what this looks like.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1932)

SF-2104 Add basic question component

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

It doesn't appear to me that the strings have been translated in Crowdin yet, so it's better to move them sooner rather than later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1936)

Move join component strings to checking_en.json

---

scripts/db_tools/manipulate-sharedb.ts

commit-id:50742e4d
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1926)

tool: manipulate-sharedb: use utils by namespace

---

mongodb/Questions/ExportQuestions.mongodb

This was created in response to a user request for an export of questions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1937)

Add Mongo script to export questions

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xfvalidators.ts

Validation for non-english emails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1930)

SF-1502 Make email validation more flexible

---

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts

Bump offline DB version to trigger creating the new text_audio store.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1944)

Fix: update offline store version

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1951)

Skip pushing notes to PT

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1952)

Hotfix: Skip push notes to PT

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1941)

SF-2114 Translate Overview to Material

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1956)

Add TODO comments for scripture audio

---

src/SIL.XForge.Scripture/Services/NotesFormatter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1820)

SF-2124 Rewrite NotesFormatter.ParseParagraph to use XElement

---

src/SIL.XForge.Scripture/ClientApp/angular.json
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/Startup.cs

I didn't plan to pick this up, but while working on something else I discovered how easy this was to do.
This changes the Angular build config, so you have to restart the Angular server to get it to work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1968)

SF-1015 Add link to open source license page

---

src/SIL.XForge.Scripture/Services/MachineApiService.cs
test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs

This Pull Request updates the GetCurrentBuild Machine API endpoint to retrieve the most recent pre-translation build when there are currently no pre-translation builds running.
This functionality means that the new back translation drafting functionality will be able to determine if the most recent pre-translation build was successful or not.
The only testing required is that the endpoint change functions correctly for the new back translation drafting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1970)

SF-2151 Retrieve the latest pre-translation build when finished

---

src/Migrations/BackoutCommits/.vscode/launch.json
src/Migrations/BackoutCommits/.vscode/tasks.json
src/Migrations/BackoutCommits/BackoutCommits.csproj
src/Migrations/BackoutCommits/IProgramLogger.cs
src/Migrations/BackoutCommits/ISFProjectTool.cs
src/Migrations/BackoutCommits/Program.cs
src/Migrations/BackoutCommits/ProgramLogger.cs
src/Migrations/BackoutCommits/SFProjectTool.cs
src/Migrations/BackoutCommits/Startup.cs
src/Migrations/BackoutCommits/build-production
src/Migrations/BackoutCommits/run-dev

This tool connects to the realtime server, runs the backout operation on a list of projects, then updates the syncedToRepositoryVersion on the project.
TODO: We probably want to automatically perform a sync so that the data in Paratext gets fixed. This shouldn't be too difficult sync we already have the connection to the realtime server.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1972)

SF-2144 Add backout commits tool

---

src/Migrations/BackoutCommits/BackoutCommits.csproj
src/Migrations/BackoutCommits/ISFProjectTool.cs
src/Migrations/BackoutCommits/ISyncAllService.cs
src/Migrations/BackoutCommits/Program.cs
src/Migrations/BackoutCommits/SFProjectTool.cs
src/Migrations/BackoutCommits/Startup.cs
src/Migrations/BackoutCommits/SyncAllService.cs

This forces the project to synchronize with PT after the backout commits have been committed to the local HG repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1976)

Add service to sync projects after backing out commits

---

src/Migrations/BackoutCommits/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1980)

Limit commit tool backout to problem dates

---

src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts

fixed error from merged SF-2079
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1977)

SF-2079b Fix snackbar panel class

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html

Checked this with buttons that are in the questions and answers. Let me know if code is incorrect
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1987)

SF 2072 Replace MDC buttons with Material in checking component

---

src/SIL.XForge.Scripture/ErrorPages/503.html

commit-id:08981ddd
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1986)

SF-2143 Adjust 503 error page wording

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

Some major mistakes slipped through testing.
Master | This branch
-------|------------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2005)

SF-2072b Fix nav buttons in checking component

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
src/SIL.XForge.Scripture/ClientApp/src/main.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/scroll-into-view.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2007)

SF-2190 Add explicit return types

---

.github/workflows/chromatic.yml
src/SIL.XForge.Scripture/ClientApp/angular.json
src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
src/SIL.XForge.Scripture/ClientApp/src/styles.scss

Before | After
-------|------
Build size before:
```
Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.861cb26fd8f3c21e.js      | main          |   2.70 MB |               549.34 kB
styles.879859f468656f4c.css   | styles        | 343.03 kB |                28.12 kB
polyfills.ea16a5aa8f970efc.js | polyfills     |  57.67 kB |                17.48 kB
runtime.d8c065bcd01beea3.js   | runtime       |   1.79 kB |               940 bytes
| Initial Total |   3.09 MB |               595.87 kB
```
Build size after:
```
Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.8b9e169b443e841e.js      | main          |   2.70 MB |               549.41 kB
styles.a99cfea21831cbbd.css   | styles        | 299.47 kB | …
```

SF-2117 Theme more Material components

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2012)

SF-2191 Fix "not a known element" in tests

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.scss

* Adjusted CSS on buttons, slider, and text
* Created Storybook for the audio player
This change just covers the audio player that appears over the text.
**BEFORE**
**AFTER**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2016)

SF-2196 Chapter Audio Matches Original Design

---

src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
src/SIL.XForge.Scripture/ClientApp/src/index.html
src/SIL.XForge.Scripture/ClientApp/src/styles.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2017)

SF-2205 Remove mdc-typography class from body element

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

This was fixed by https://github.com/sillsdev/machine.js/issues/19
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2031)

SF-2222 Fix verse too long message by updating Machine.js

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

When less than 10 verse pairs are in a source and target text, Machine will not be able to generated a BLEU score for Translation Suggestions.
This Pull Request displays a message on the Translate Overview screen when there are less than 10 verse pairs in the source and target texts, and if translation suggestions are enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2029)

SF-2208 Display a warning when less than 10 verses translated

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

* Show default text for questions that only have audio in the question panel
**BEFORE**
**AFTER**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2020)

SF-2201 Audio-only questions have text in the questions list

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2039)

SF-2225 Added error check for chapters property

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-test.utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts

* parse heading labels other than \s
* parse headings with an iteration value
* add checking utils tests
* show the most recently played verse when playing section heading audio
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2030)

SF-2219 Support audio timing files from HearThis

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2050)

Disable all failing test suites

---

mongodb/Questions/ChartAnswersByProjectAndMonth.mongodb

I wrote this query back in May and have been using it successfully since then. The output format (tab separated) is such that you can paste it into a spreadsheet and create a chart.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2043)

tool: Add query to group answers by project and month

---

src/SIL.XForge.Scripture/ClientApp/.storybook/story-utils.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2056)

Remove unused MDC imports from story-utils.ts

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2057)

Remove MDC from dialog service

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2058)

Update form validators to use ErrorStateMatcher from Material rather than MDC

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2073)

Update obsolete comments and variables that mention MDC

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2074)

SF-2235 Handle offline status on draft generation page

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2077)

Remove unneeded logging from biblical-terms.component.ts

---

scripts/build-and-ship
src/Migrations/ServalMigration/Program.cs
src/Migrations/ServalMigration/Startup.cs
src/Migrations/ServalMigration/build-production
src/Migrations/ServalMigration/process-by-chunk

The web host must be started for `LazyScrTextCollection` to work correctly. This PR fixes the migrator so that it runs the web application without the Realtime server, and adds some scripts to help with deployment and running on production.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2079)

Fixed Serval Migrator crash on run

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss

Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2022)

SF-2198 Position single button player with active text

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts

Commit history is wonky, since the original base branch was the Close button branch. The file diff is correct, though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2028)

SF-2209 Pause Audio When Navigating Away

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2100)

Remove unused icon-button mixin from app component

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.stories.ts

Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2023)

SF-2200 Add forum icon for questions without audio

---

src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts
src/RealtimeServer/scriptureforge/services/biblical-term-service.spec.ts
src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
src/RealtimeServer/scriptureforge/services/question-service.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-user-config-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/Models/SFProjectUserConfig.cs

* Store the verse ref as chapter audio is played in the user config
* Store the verse ref chapter audio has finished playing on a question
* Automatically select the question if chapter audio has been played for a question
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2092)

SF-2199 Scripture Audio "read" state persistence

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

* Pause audio when archiving a question
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2125)

SF-2216 Verse audio continues to play even after the question archived

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2116)

SF-2276 Hide font size changer when audio-only

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2139)

Add warning to prevent users from using feature flags

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2134)

Remove a TODO that has already been completed

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss

Video showing behaviour:
[offline-audio-upload.webm](https://github.com/sillsdev/web-xforge/assets/7265309/1309cccc-34d6-441a-a323-c1759c2e5bc9)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2107)

SF-2213 Disable chapter audio upload when offline

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

When a book is deleted from Scripture Forge which contains the first occurrence of a Biblical Term with a note, Scripture Forge will crash on sync.
This PR fixes this by only deleting notes that are not Biblical Term notes when deleting a chapter from Scripture Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2150)

SF-2303 Fix crash when deleting a chapter with BT Notes

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

Reduced throttle time which was causing the issue and moved the filtering to be within the rxjs pipable chain.
Also removed unnecessary `triggerUpdate()` function, as a local update was already triggered whenever this was called.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2154)

SF-2305 Fix timing issues with checking questions list

---

src/SIL.XForge.Scripture/Services/MachineApiService.cs

Bugsnag is not recording enough information when reporting BrokenCircuitExceptions that are reported but ignore by our code. These sorts of errors originate from the connection to Serval, and are ignored if the In-Process machine is running to ensure that the user is not interrupted.
This PR alleviates that by including endpoint information in the report to Bugsnag. See screenshot from bugsnag:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2166)

Record endpoint information in Bugnsag for Serval errors

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

The older version of the package is incompatible with Angular 16.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2174)

SF-2336 Update angular-file to 4.0.2

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2195)

SF-2350 Fix draft generation progress circle rerender on click

---

mongodb/count_document_revisions.mongodb

@pmachapman This was inspired by your work on milestones. I wanted to check on our assumptions about how much docs get edited on live.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2193)

Add Mongo query to count edits of most edited docs in each collection

---

src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.scss

Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2197)

Fix project picker height

---

src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2191)

SF-2378 Update to MDC-based MatTooltip

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2203)

Remove unneeded mat-slider CSS rules

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2205)

Enable translation drafting feature flags

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2186)

SF-2342 Remove vertical line question answered indicator

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/README.md
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2224)

Move strings for text component to checking_en.json and add i18n docs

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.ts

The form field names have changed.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2227)

Fix link to drafting sign up form

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

Appearance at given range (992px-1080px) after fix:
Though I didn't verify on an actual Ipad Mini, I was able to see the bug on my laptop before fixing it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2212)

SF-2289 Fixed rightward runoff at medium resolutions

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

Adds ability for user to independently select training and translation books.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2222)

SF-2379 Allow selection of draft translation books

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2237)

audio: localize Uploading string

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

Adds to the draft generation stepper a display of books that are in target but not in source texts or in source but not in target texts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2242)

SF-2393 Display unusable drafting books

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts

Minor fixes for remaining code review items:
https://reviewable.io/reviews/sillsdev/web-xforge/2242#-
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2247)

Fix minor items related to SF-2393

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss

Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2253)

Fix alignment in BookChapterChooser component

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/anonymous.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

Based on my testing, I think we need to upgrade to RxJS 7 before upgrading ngx-quill, before upgrading to Angular 16. We need to update RxJS at some point one way or another. Unfortunately there are a number of breaking changes. See https://rxjs.dev/6-to-7-change-summary
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2217)

SF-2388 Update to RxJS 7

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2261)

SF-2431 Sort books on draft generation page

---

src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts

This is causing consistent failure to run the migration on QA. I am going to self approve and merge for the sake of getting the QA site back up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2264)

Fix note tag migration

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2225)

SF-2399 Sort books in community checking book list

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts

This update is now possible since updating Rxjs to v7. When we update to angular 16, we will need to update this again to v22 or v23.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2262)

SF-2338 Update ngx-quill to v21.0.2

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

This was broken in PR #2237 on the audio upload dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2278)

SF-2438 Localize error message strings in chapter audio dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

The added verse ref is on a second line along with the "answers" indicator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2282)

SF-2449 Add verse ref to checking question list items

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts

- Added filtering for canonical books
- Refactored fetching the draft sources to a service
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2294)

SF-2461 Restrict draft training books to canonical

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2303)

SF-2467 Prevent Google Translate from deleting editor text (#2302)

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2316)

SF-2477 Menus do not automatically close when opening another menu

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2321)

SF-2474 Set selectedTask when navigating to Manage Questions

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts

This does mean that to add audio to a chapter (from this page), it must have a question on it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2327)

SF-2496 Move "add chapter audio" to chapter menu on questions dashboard

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

These logs should be removed to limit the information being logged. There were initially added when writing SF notes to PT was first released, but there are no longer likely to be useful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2336)

Remove note thread update logs

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2353)

SF-1588 Suggestions settings also requires general edit permission

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

Here's a screenshot of one of the selection options activated:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2335)

SF-2499 Add quick buttons for selecting books when drafting

---

scripts/db_tools/utils.d.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2360)

dev: add createDoc to utils API

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

In rare cases, multiple comment threads will be listed that are actually a single thread. The most likely cause is that the thread loading algorithm in Paratext.Data has a problem that only occurs in rare situations. When it happens, Paratext shows two icons for the same thread, but this prevents SF from synchronizing with PT.
This change uses `CommentManager.FindThread()` to extract a single thread from all comments with the same thread Id where as previously an error would occur when querying from a list. Unfortunately, I could not get a test to successfully demonstrate the problem state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2359)

SF-2518 Fix sync failure when multiple threads have the same Id

---

.github/workflows/release-to-qa.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2376)

Create release-to-qa gh workflow

---

.github/workflows/release-to-qa.yml

@Nateowami Let's try this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2378)

ci: release-to-qa: not shallow

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2367)

SF-2596 Add text to button to show/hide changes in chapter history

---

src/SIL.XForge.Scripture/Services/MachineProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2389)

hotfix: SMT crash fix

---

mongodb/Projects/ProjectsOverTime.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2395)

Add query to measure the number of projects over time

---

mongodb/Questions/CountAnswersByMonth.mongodb

A demo project has a number of answers that I want to exclude from our usage stats.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2409)

Update answer query to ignore test projects with lots of answers

---

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
src/SIL.XForge.Scripture/appsettings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2417)

Update help email address

---

src/SIL.XForge.Scripture/Services/InternetSharedRepositorySourceProvider.cs
src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/appsettings.json
test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
test/SIL.XForge.Scripture.Tests/Services/JwtInternetSharedRepositorySourceTests.cs

(cherry picked from commit a04356e1a16b08854ad6bc366c2b421e07e7763f)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2424)

Log response times from Paratext registry (#2423)

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html

This PR adds internationalization for Select label in the book multi select component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2426)

SF-2701 Add i18n for Select label in book multi select

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts

This PR fixes the following issues with the editor tabs "add" menu:
- Multiple requests are being made to `getLastCompletedPreTranslationBuild` when visiting the editor page.
- Fixed by returning the same observable when `getMenuItems()` is called and adding a `shareReplay`.
- A "network request failed" error is shown when going to the editor page when offline due to attempting to request `getLastCompletedPreTranslationBuild`.
- Fixed by requesting `getLastCompletedPreTranslationBuild` only when online.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2445)

SF-2724 Fix editor tab menu duplicate requests and handle offline

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

So now that SF-2589 is in, the task originally planned for SF-2445 has been merged into this task.
-------------------------------------------------
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2391)

SF-2443 Apply button for draft tabs

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

Rebase included removal of 'sendAllSegments', which was being checked to determine if 'legacy' draft fetch should be used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2452)

SF-2443 Apply draft in editor draft tab

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html

I think this accidentally got reverted in a rebase in #2455
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2468)

SF-2726b Remove wrapping card from generate draft page

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

This PR adds the user id via the Bugsnag API (as documented in https://github.com/bugsnag/bugsnag-js/issues/171), to ensure that the user's ID is used rather than their IP address.
To test, see the process Nathaniel outlines at https://github.com/sillsdev/web-xforge/pull/2488#issuecomment-2135761156
I also took the opportunity to update Bugsnag to the latest version, as it contains some minor performance and bug fixes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2493)

SF-2743b Add user id for bug reporting via Bugsnag API

---

src/SIL.XForge.Scripture/Services/MachineApiService.cs
test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs

This PR fixes the DataNotFound exceptions and 409 ServalApiException errors logged in bugsnag.
I also took the opportunity to record the project identifier in bugsnag to help make the debugging of these sorts of issues easier in future.
This PR does not require testing, as the issue only occurs on QA and production when builds fault and the webhook is triggered. Success will be determined by the decrease in these errors after deployment.
See also
* https://app.bugsnag.com/sil-international/scripture-forge-v2-plus/errors/664cfde52083380008e3eb61
* https://app.bugsnag.com/sil-international/scripture-forge-v2-plus/errors/6645a2cf902d260008d17d53
- - - …

SF-2777 Fix 409 errors in webhook execution

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This PR corrects one of the code review comments in #2506.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2526)

SF-2762b Correct the credentials expired message

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2472)

SF-2365 Upgrade from legacy list

---

src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss

This should remove all remaining vestiges of legacy Material components.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2547)

Remove legacy Material styles

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2546)

SF-2800 Remove forced ripple setting

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2552)

SF-2809 Allow wordwrap for date archived in CC

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
src/SIL.XForge.Scripture/ClientApp/src/styles.scss

Before
After
Before
After
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2530)

SF-2792 Restore 40px size for icon buttons

---

scripts/build-and-ship

This was broken in #2534
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2563)

SF-2824 Fix build-and-ship script

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs-config.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab/tab.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.ts

This PR adds tooltip to display the project/resource long name on hover of tab header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2532)

SF-2797 Add editor tab header tooltips

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2567)

Fix duplicate add-question-button ID on checking overview

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.ts

Problem  | Project | Resource
---------|---------|---------
Fallback | ![](https://github.com/sillsdev/web-xforge/assets/6140710/deb6bdf3-c413-4105-892c-c8860858d0a2) | ![](https://github.com/sillsdev/web-xforge/assets/6140710/3dc43703-7e4b-40e6-8376-5dea69d2aea3)
Graphite | ![](https://github.com/sillsdev/web-xforge/assets/6140710/231577ad-e990-4a78-bba9-b5056622d9fd) | ![](https://github.com/sillsdev/web-xforge/assets/6140710/edf95387-e8e3-404c-902c-8cf100a98527)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2548)

SF-2640 Warn when font unsupported

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2558)

SF-2810 Add tooltips to CC answers

---

mongodb/Projects/FindProjectFromEngineId.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2577)

Add query to find project given engine ID

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

This PR fixes a bug caused by certain methods not being called when the question count goes to 0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2588)

SF-2747 Update question refs and donut summary when archiving last visible question

---

mongodb/Projects/ProjectsOverTime.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2590)

Update projects query to better count real projects

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2591)

Default autofocus in dialogs to false

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

Removed Audio Button code from `ng-container` for Add/Edit Questions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2587)

SF-2691 Fixed manage audio button not displaying for non-admin users

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2598)

SF-2839 Align draft download spinner with other content

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts

(cherry picked from commit 5b171944541fb3f116aef92d5e3cd20b8a0799e4)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2609)

hotfix: SF-2865 Fix nav to open 'Auto Draft' tab from draft gen (#2601)

---

tools/ServalBuildReport/Program.cs
tools/ServalBuildReport/README.md
tools/ServalBuildReport/ServalBuildReport.csproj
tools/ServalBuildReport/ServalBuildReport.sln
tools/ServalBuildReport/appsettings.json

This PR contains a tool that can be used to generate reports on Serval build success or failure, with a Summary worksheet formatted to help graph making easier.
Please see the README.md file in the tool directory for the configuration that is required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2583)

Add Serval Build Report Generator

---

scripts/build-and-ship

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2619)

deploy: use defined credentials

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html

Feel free to propose better icons
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2607)

SF-2872 Add icons to help menu

---

src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts

- Fixed layout of cards
- Reduced font weight of titles
- Reduced spacing of titles
- Fixed cards starting out narrow and then expanding wider roughly 1 second after page load
- Fixed long words in names not wrapping
To see the biggest difference in behavior, check out the "Layout lengths" story on a small screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2602)

SF-2870 Improve layout on my projects page

---

.github/workflows/compute-next-version.py
.github/workflows/compute-next-version.yml
.github/workflows/release-live.yml
.github/workflows/release-qa.yml
.github/workflows/release.yml

---
This PR makes a number of adjustments to the SF QA and SF Live release workflows, based on testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2620)

deploy: fix and enhance release workflow process

---

.github/workflows/release-live.yml
.github/workflows/release-qa.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2630)

deploy: improve UI wording

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2628)

SF-2887 Update announcements link

---

.github/workflows/build-and-test.yml
.github/workflows/chromatic.yml
.github/workflows/ci-lint-prettier.yml
.github/workflows/ci-production-build.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2633)

Retry npm ci in workflows when it fails

---

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2641)

Make roles message on users page clearer

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts

This PR fixes tests with missing expectations which were resulting in warnings in the console when running tests, and corrects some minor import typos.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2644)

Fix tests with missing expectations and import typos

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2624)

SF-2876 Link logo on my projects page to previous project

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2596)

SF-2749 Refactor scrolling to active verse

---

mongodb/Projects/FindProjectsUsingProjectAsSource.mongodb

I wrote this to try to figure out which project was preventing another from being deleted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2647)

Add query to find projects that are using a given project as a source

---

scripts/db_tools/report-user-comments.ts

This PR creates ts-node script `report-user-comments.ts` that takes a project and time window and outputs a TSV file summarizing note thread counts by user and book/chapter.
Note: Testing will be done by reviewer instead of test team.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2564)

SF-2822 Create 'user comment count' report script

---

mongodb/SyncMetrics/SyncStatusOverTime.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2649)

Update sync status query to make order of states consistent

---

mongodb/SyncMetrics/FindCommonSyncFailureReasons.mongodb

I also added a new failure reason that was not previously included in the list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2650)

Update Mongo query to filter for only recent failure causes

---

.github/workflows/build-and-test.yml
.github/workflows/ci-lint-prettier.yml

* Removes linting from "Build and Test" GHA workflow.
* Enables the "Lint and Prettier" GHA workflow on push to `sf-live` or `sf-qa`.
The success of this PR is determined by a successful merge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2668)

SF-2907 Remove linting from build and test workflow

---

.github/workflows/compute-next-version.yml
.github/workflows/release-live.yml
.github/workflows/release-qa.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2648)

deploy: add more details on build_commit being used

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

This PR allows history to be viewed for projects that are missing the Paratext sync directory. This is useful when viewing the history for a project that has been restored.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2674)

SF-2926 Allow viewing history if Paratext sync directory is missing

---

scripts/extract-project.bat
scripts/extract-project.sh

This PR contains a script to extract a project from MongoDB. This is useful when restoring a project from backup.
I wrote the script in MS-DOS Batch File format, and ported it to a Bash script via ChatGPT. Please let me know if there are any improvements that can be made to the Bash script (Bash scripting is not a strength of mine).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2673)

SF-2918 Create extract project script for Windows and Linux

---

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2688)

Fix padding of offline message on users page

---

src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts

My Projects page will not download all the necessary data for projects to be accessed offline (texts, notes, questions).
"Offline Access" will display on the Projects card once data is accessible in the IndexedDB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2621)

SF-2860 Users notified when offline on My Projects page

---

.github/workflows/release.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2690)

deploy: include ALTERNATE_DOMAIN info

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.ts

This PR fixes a bug where the browser tab will freeze when uploading training data CSV files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2685)

SF-2937 Fix uploading of training data files

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2697)

SF-2725 Show Apply Draft for invalid and unsupported USFM cases

---

src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts

This adds the "Type" column:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2706)

Display project type for sources on Serval admin page

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html

This PR adds a hotfix and updates the sf-live branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2715)

hotfix: Warn draft not working

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress-service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts

The former may have been a carryover from the previous code. It didn't appear to be behaving as intended, or at least not as valuable as intended, given that changes to the project (e.g. adding a chapter) were the only things being listened to. It certainly wasn't picking up text changes, and it's unlikely we were ever updating progress without refreshing the page (or some other similar action).
This implementation merges the changes$ for all chapters into one subscription. It's still throttled to once a second.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2712)

SF-2951 Fix ProgressService not subscribing to chapter updates

---

src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts

See Chromatic to see what has changed. Also replaced `data-project-type` with a classes.
EDIT: Several other stories had the same background problem, but Chromatic only shows two, and I can't figure out why. All of them were fixed as far as I can tell.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2717)

Fix background color of notices on my projects page

---

mongodb/SyncMetrics/FindAndGroupSyncFailures.mongodb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2720)

Find and group sync failures by cause

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2723)

SF-2835 Add message for invalid markers in para USFM

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2724)

SF-2805 Only add source tabs if user can access the source

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2732)

Minor test improvements for tab groups

---

CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2745)

Add commit guidelines in CONTRIBUTING.md

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts

This is intended to help us track down components that never call `loadingFinish`, or that call `loadingFinished` without first calling `loadingStarted`
This change makes it quite clear that `CollaboratorsComponent` is currently broken, as it consistently calls `loadingFinished` without a corresponding `loadingStarted` call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2746)

Add tracking of components using notice service

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2754)

Fix SubscriptionDisposable subclasses failing to call ngOnDestroy

---

src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts

The biggest change is reverting user-projects.service.ts to the state it was before #2621. Everything else is deleting references to what is then removed. Testing not required, because we have no repro steps for the bug.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2756)

SF-3009 Fix error reading projectRef in SFUserProjectsService

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2757)

SF-3010 Fix error activating undefined question

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2752)

SF-3008 Fix error destroying Biblical terms component

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2767)

SF-3015 Fix error reading undefined _selectedProjectDoc in app component

---

src/RealtimeServer/common/models/project-rights.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2769)

Deprecate ProjectRights.roleHasRight

---

.vscode/extensions.json

This PR updates the project extension recommendations to reference the Karma Test Explorer which is a rewrite of the depreciated Angular/Karma Test Explorer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2778)

Update extensions.json recommendations

---

scripts/db_tools/package-lock.json
scripts/db_tools/package.json
src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

This PR updates ws to 8.18.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2782)

Update ws to 8.18.0

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2758)

SF-3005 ProgressService bugged when Suggestions are enabled

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2785)

Fix text overflow ellipsis on checking overview page

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.ts

This PR fixes issues that prevent audio playback and recording on iOS devices and on Safari for macOS.
If you have a mac and wish to test this, please follow the instructions at https://github.com/sillsdev/web-xforge/wiki/Debugging-on-another-computer.
If not, it will be sufficient to ensure that the functionality continues to work as it did previously on Chrome or Firefox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2751)

SF-3006 Fix bugs with audio playback and recording on iOS

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts

Here's how it now looks:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2789)

Add loading indicator information to developer diagnostics

---

.github/workflows/docker-dev.yml
.vscode/launch.json
src/.dockerignore
src/Docker/docker-compose.override.yml
src/Docker/docker-compose.win.yml
src/Docker/docker-compose.yml
src/RealtimeServer/Dockerfile
src/RealtimeServer/start.sh
src/SIL.XForge.Scripture/Dockerfile
src/SIL.XForge.Scripture/Migrator.cs
src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs
src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs
src/SIL.XForge/Realtime/RealtimeServer.cs
src/SIL.XForge/Realtime/RealtimeService.cs
src/SIL.XForge/Utils/Product.cs

* Splits Scripture Forge into two Docker containers
* Adds Docker image creation of Development images via a manually triggered GHA
Testing should be done by a developer. This can be done following the instructions at https://github.com/sillsdev/web-xforge/wiki/Docker
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2779)

SF-2954 Split Scripture Forge into two Docker containers

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/_breakpoints.scss
src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.scss

* Remove bootstrap package
* Refactor show/hide helper classes to use the same @media query logic
* Change over from @import to @use
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2733)

SF-2914 Remove Bootstrap

---

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

This PR stops  a project from being deleted while it is syncing, and adds a log message when the project is deleted.
This should stop the issues that are occurring where the Paratext directory for a project is present when a project is in the process of creation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2798)

SF-3022 Do not allow a project to be deleted while it is syncing

---

.vscode/launch.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2827)

dev: omit node_modules from stack

---

src/SIL.XForge.Scripture/Pages/Shared/Components/Footer/Default.cshtml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2826)

SF-3062 Fix broken landing page help link

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2839)

SF-3065 Notify user to reconnect internet to restore previous version

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts

Errors from applying drafts to a book should be reported so that we can determine the causes of failures to applying drafts. This PR adds reporting for when getting drafts of a book fails and when applying drafts of a book fails. Users will not notice any changes since this is only internal error reporting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2844)

Report draft apply failures to bugsnag

---

.github/workflows/release.yml

This caused a failure of the automated deploy to QA last night: https://github.com/sillsdev/web-xforge/actions/runs/11809173839
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2848)

Fix mismatched curly braces in release.yml

---

deploy/dependencies.yml
deploy/vagrant/sfdev/base/provision

ansible: Use Mongo 7. Increase support for Debian. 
vagrant: Install Paratext from beta channel. Include an expectation of what the microsoft.gpg key will be.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2856)

dev: update machine setup

---

src/SIL.XForge.Scripture/Pages/Index.cshtml

Updated the callback URL to match what it actually is in Auth0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2861)

Fix Auth0 callback URI on razor home page

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts

In my testing this makes the draft page books load much more quickly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2860)

SF-3091 Load text docs in progress service in parallel

---

src/Docker/docker-compose.yml
src/RealtimeServer/Dockerfile
src/SIL.XForge.Scripture/Dockerfile

This PR replicates the change in #2856 to the Docker compose script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2857)

Update mongo version in docker compose to 7.0

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This PR has cherry-picked 3 bug fix commits from master, in order to send them directly to live.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2863)

hotfix: Fix list of books being slow to load, and occasional error

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts

This PR prompts the user for microphone access before the countdown begins on the audio recorder dialog. I also removed the dependency on the SubscriptionDisposible class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2871)

SF-3078 Prompt user for microphone access before recorder countdown

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2879)

Remove unneeded this from template files

---

src/SIL.XForge.Scripture/ErrorPages/503.html

---
The DOCTYPE -> doctype change is coming from our auto formatting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2882)

Update error page news link

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2883)

hotfix: Add upcoming downtime notice

---

src/SIL.XForge.Scripture/ErrorPages/503.html

(cherry picked from commit 920a3008f6ee347f32bd8cd6c8347cd3f5b3e934)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2884)

hotfix: Update error page news link (#2882)

---

.github/workflows/update-localizations.yml
scripts/update_from_crowdin.mts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2866)

Add script and workflow to fetch translations from Crowdin

---

src/RealtimeServer/common/models/writing-system.ts
src/RealtimeServer/scriptureforge/services/sf-project-service.ts
src/SIL.XForge.Scripture/Models/ParatextProject.cs
src/SIL.XForge.Scripture/Models/ParatextSettings.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/MachineProjectService.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Models/WritingSystem.cs
test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This PR should be tested by a developer, as the values are written to the database, and do not yet affect the frontend UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2880)

SF-3097 Set WritingSystem Region and Script

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

This reverts commit 8c45b5a1e900615b30981cd90db4f262b0580326.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2886)

Revert "hotfix: Add upcoming downtime notice (#2883)"

---

mongodb/Projects/ActiveTranslateProjects.mongodb

This query didn't work as I wanted to write it due to the older version of Mongo. It can now be updated since that's no longer a problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2889)

Update query for active translate projects

---

src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts

This PR queues getWordGraph API calls so that Serval is not sent too many requests to the same translation engine at once when a user rapidly moves around verse segments in the editor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2881)

SF-3088 Queue getWordGraph API calls

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts

Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2899)

Improve draft generation enumeration of unselectable books

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts

After discussion, it's been decided that this notice should be removed 60 days after it went live.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2902)

Hide learning rate notice after 60 days

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2892)

SF-3086 Fix Checking Overview Not Updating for Bulk Import

---

src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/subscription-disposable.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2920)

SF-3121 Upgrade old subscribe calls to use observers

---

src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/mobile-not-supported/mobile-not-supported.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/mobile-not-supported/mobile-not-supported.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2914)

Add message on certain pages about mobile not being supported

---

src/SIL.XForge.Scripture/ParatextMerge.py
src/SIL.XForge.Scripture/changedChapter.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2930)

Add Python 3 versions of PT Mercurial extensions

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2940)

Fix link from draft page to help site

---

.vscode/settings.json
deploy/dev-server.playbook.yml
deploy/vagrant/sfdev/Vagrantfile
deploy/vagrant/sfdev/base/instructions.md
deploy/vagrant/sfdev/base/provision.sh

This includes some autoformatting done to instructions.md and provision.sh.
In provision.sh, I am letting the package upgrade list be updated, and package upgrades be pre-downloaded, tho still not automatically applied.
The optional `XF_BRANCH` will ease testing of the provision.sh script.
-----------
In this PR, I apply some updates to the vagrant provisioning pieces, in preparation for re-generating the sfdev basebox with mongodb 8. 
Provisioning and testing the basebox went well so far.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2953)

dev: update vagrant scripts

---

scripts/build-and-ship

To make it more explanatory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2973)

deploy: spell out the arguments

---

.github/workflows/compute-next-version.yml
.github/workflows/release-live.yml
.github/workflows/release-qa.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2972)

deploy: specify OS version, note a need on bump

---

src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2985)

SF-3179 Fix Serval Admin training books

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2989)

SF-3171 Add icons to draft generation steps buttons

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3004)

Remove dead code from AppComponent

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts

(cherry picked from commit 6947dbec1315daad8f6fb53a212d510225c429c8)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3006)

hotfix: SF-3201 Fix broken editor jump links (#2999)

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3011)

Fix unsafe use of ::ng-deep

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts

This reverts commit dffcad44664ae3d75054c062c6340b84444e35ba.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3015)

Revert "hotfix: SF-3201 Fix broken editor jump links (#2999) (#3006)"

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts

This reverts commit 6947dbec1315daad8f6fb53a212d510225c429c8.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3016)

Revert "SF-3201 Fix broken editor jump links (#2999)"

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

On Live the GNTD resource contains multiple users that have a role on the project, but their book and chapter level permissions were not updated correctly. In my investigation I did not see a clear way to reproduce this.
To correct this issue, I have updated code to update permissions for a user on a resource when a new resource is selected for a target project and users are automatically added as users on the resource.
This will have to be tested by a developer since the steps to get into the bad state is quite technical.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3013)

SF-3208 Fix resource not showing when user has permission

---

scripts/db_tools/manipulate-sharedb.ts

Added a bit to boilerplate structure.
Added some more examples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3024)

dev: add to manipulate-sharedb tool

---

.github/workflows/build-and-test.yml
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3025)

Fix tests with verify that do not actually verify

---

src/SIL.XForge.Scripture/fonts.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3031)

Update font list

---

.github/workflows/build-and-test.yml
.github/workflows/chromatic.yml
.github/workflows/ci-lint-prettier.yml
.github/workflows/ci-production-build.yml
.github/workflows/codeql.yml
.github/workflows/compute-next-version.yml
.github/workflows/docker-dev.yml
.github/workflows/grit.yml
.github/workflows/release-live.yml
.github/workflows/release-qa.yml
.github/workflows/release.yml
.github/workflows/update-localizations.yml
.github/workflows/zizmor.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3038)

SF-3227 Investigate and fix zizmor alerts

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3044)

SF-3229 Remove bulk book selection from "Drafting" step

---

.github/workflows/release.yml

This file name was misspelled. I checked the other locations where we use the cache and they are correct in those files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3046)

Fix workflow cache file path

---

.github/workflows/release-live.yml
.github/workflows/release-qa.yml
.github/workflows/release.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3048)

ci: pass and require secrets in deploy workflows

---

.github/workflows/release-live.yml
.github/workflows/release-qa.yml
.github/workflows/release.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3049)

ci: fix release workflow permission

---

src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3056)

Improve wording of role refresh

---

src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.stories.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3058)

Add stories for project select

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

~This is a draft because I want to run it by the EITL team first.~
The wording has now been approved by @bhartmoore 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3055)

Improve wording of language codes confirmation

---

.github/workflows/update-localizations.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3071)

Fix permissions of update-localizations.yml

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

Apologies for the previous PR, it looks like this wording is what everyone wants!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3078)

SF-3226 Further clarify wording for canceling draft

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts

This issue was the source of most of the failing test cases on our regression run.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3081)

SF-3249 Fix error when commenter and viewers navigate to project texts

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3073)

SF-3248 Refactor DraftSourcesService to support an arbitrary number of sources

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3090)

Update link on draft generation steps to config sources

---

src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3095)

Update notice to Serval admins about downloading projects

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3106)

Remove unused locale code logic from draft utils

---

mongodb/EventMetrics/CountDraftJobsByDate.mongodb

You can see the results of this query in the file "Draft jobs by date" in the metrics folder of the team drive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3111)

Add Mongo query to count draft jobs by date

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3121)

Remove auto draft terminology for consistency

---

src/Help/UpdateHelp/UpdateHelp.csproj
src/Migrations/BackoutCommits/BackoutCommits.csproj
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/packages.lock.json
src/SIL.XForge/SIL.XForge.csproj
src/SIL.XForge/Services/AuthServiceCollectionExtensions.cs
src/SIL.XForge/Services/UserAccessor.cs
src/SIL.XForge/packages.lock.json
test/SIL.Converters.Usj.Tests/SIL.Converters.Usj.Tests.csproj
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Tests/DataAccess/BsonValueConverterTests.cs
test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
test/SIL.XForge.Tests/Services/TokenHelper.cs
test/SIL.XForge.Tests/Services/UserAccessorTests.cs
tools/RepoInfo/Program.cs
tools/ServalBuildReport/ServalBuildReport.csproj

This PR contains the following package updates:
**Replace IdentityModel 7.0 with Duende.IdentityModel 7.0**
* IdentityModel was deprecated. This is by the same provider, but includes a namespace change.
**Update Bugsnag.AspNet.Core from 3.1.0 to 4.0.0**
* Release notes: https://github.com/bugsnag/bugsnag-dotnet/releases
* Fixes vulnerable dependencies.
**Update Microsoft.FeatureManagement.AspNetCore from 3.4.0 to 4.0.0**
* Release notes: https://github.com/microsoft/FeatureManagement-Dotnet/releases
* Adds support for us to have different feature flags for different users via `IVariantFeatureManager`
**Update NPOI from 2.7.2 to 2.7.3**
* Release notes: https://github.com/nissl-lab/npoi/releases
* This is used for Excel import for additional files for Serval.
* Updated vulnerable …

Update dotnet dependencies

---

src/SIL.XForge.Scripture/Services/MachineApiService.cs
test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs

This PR fixes an issue where syncs will run multiple times for the same project if it is configured for more than one of the draft training or translation sources.
I have marked the PR as not requiring testing, as developer testing will be sufficient given this is an under the hood change only visible in Hangfire.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3140)

SF-3304 Do not sync each project more than once on build

---

.github/workflows/update-font-list.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3143)

Add workflow to update list of supported fonts

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/_book-multi-select-theme.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/_confirm-sources-theme.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/_draft-sources-theme.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss

This touches most community draft generation related components where needed.
There are some colors left which need to be addressed separately i.e. the event log icon colors.
Dark mode improvements have been made.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3154)

Improve theme support for drafting

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
src/SIL.XForge/Services/FileSystemService.cs
src/SIL.XForge/Services/IFileSystemService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

(cherry picked from commit 38cb718354a22e050e49edebce9dcfa33740dade)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3163)

SF-3314 Fix installation of new DBL resources (#3149)

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss

Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3164)

SF-3326 Fix spacing of invite form on mobile

---

src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs

This PR adds a 5 minute timeout for HTTP requests to Serval.
This should ensure that scenarios like the webhook Hangfire job execution getting stuck for hours while Serval keeps the connection open no longer occur.
I have marked this as not requiring testing, as a normal regression run should be sufficient to determine if the timeout is too short and needs to be extended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3181)

Add a 5 minute timeout for HTTP requests to Serval

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.ts

This fixes a race condition bug where sometimes, notably on page refresh, the progress donut would be populated with wrong data. This was because the animation was referencing field members, which can change at any time, with its runOutsideAngular call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3202)

SF-3337 Fix CC progress donut on page refresh

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3201)

SF-3331 Fix training source checkbox runoff for small screens

---

.config/dotnet-tools.json
.csharpierignore
.lintstagedrc.yml
src/Migrations/PtdaSyncAll.Tests/PtdaSyncRunnerTests.cs
src/SIL.XForge.Scripture/Services/NotesFormatter.cs
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/DataAccess/MemoryUpdateBuilder.cs
src/SIL.XForge/DataAccess/WritableContractResolver.cs
src/SIL.XForge/Realtime/Json0/Json0OpBuilder.cs
src/SIL.XForge/Realtime/RichText/Delta.cs
test/SIL.Converters.Usj.Tests/TestData.cs
test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
test/SIL.XForge.Scripture.Tests/Services/JwtTokenHelperTests.cs
test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/SharingLogicWrapperTests.cs
test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/TrainingDataServiceTests.cs
test/SIL.XForge.Tests/DataAccess/MongoRepositoryTests.cs
test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

This PR updates CSharpier to 1.0.1, and runs it on the web-xforge repo.
Changelog: https://github.com/belav/csharpier/releases
I have added a `.csharpierignore` file, as CSharpier now formats XML files and I don't think we really want that - it started making changes to the csproj XML which I thought may break things in the build chain.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3209)

Update CSharpier to 1.0.1

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss

Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3215)

Fix button color in diagnostics panel

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This reverts 1dc066fa8dc36123d6739522562b2947983fc739
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3234)

SF-3219b Remove draft improvement notice

---

src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3239)

SF-3414 Show language tags on Serval admin page

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights.module.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This PR enhances the Lynx problems panel by introducing progressive loading for groups with many children.  These changes should drastically improve problems panel load times and also improve performance moving between "scope" tabs (Chapter/Book/Project) for projects with large numbers of insights.
* Added a new `panelOptimizationThreshold` property to `LynxInsightConfig` to enable progressive loading for nodes with many children (set at 100).
* Enhanced the problems panel to display a "Show more" button for nodes exceeding the threshold, with a progress bar for displaying additional children.
* Added a spinner with loading text when a node is loading.
* Added a test file for the component.
- - - …

SF-3406 Improve lynx problems panel performance

---

src/SIL.XForge.Scripture/Controllers/ParatextController.cs
src/SIL.XForge.Scripture/Models/SFProjectCreateSettings.cs
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/packages.lock.json
test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

This PR adds an API endpoint so that the Paratext editor can connect to or sync projects.
As this PR is not accessible by the frontend, it can be tested by a developer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3242)

SF-3415 Add sync and connect endpoints to the paratext-api

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel-header/lynx-insights-panel-header.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/tsconfig.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3256)

SF-2996 Warn on unused private class members and fix current warnings

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts

@pmachapman I meant to do this in #3236, but merged it before I realized I'd forgotten to push the changes. Not sure if this should require testing or not. There's not really an issue to tie it to.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3255)

Deduplicate date format function for file names

---

src/SIL.XForge.Scripture/ClientApp/e2e/e2e-globals.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3270)

Increase the sync timeout in e2e tests to two minutes

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3274)

Remove UntypedFormControl from import questions dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-role-info.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3279)

Remove UntypedFormControl from share control

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3260)

SF-3423 Inform user when lacking permission to import chapter

---

src/SIL.XForge.Scripture/ClientApp/e2e/workflows/generate-draft.ts

I've changed the role of the user this job runs as to no longer be a Serval admin. This makes for a more realistic test, and the screenshots taken by the localized_screenshots workflow no longer show the Serval admin UI elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3286)

Update e2e draft generation to not require being a Serval admin

---

src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3293)

Add types to project select form control

---

src/RealtimeServer/scriptureforge/services/sf-project-service.ts

This PR corrects the sf_project validation schema to correctly validation the usfmConfig property.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3294)

Fix usfmConfig in the sf_project validation schema

---

src/SIL.XForge.Scripture/ClientApp/e2e/characterize-tests.mts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3301)

Update test characterization script to eventually terminate

---

src/SIL.XForge.Scripture/ClientApp/e2e/characterize-tests.mts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3299)

Fix e2e test characterization saving Playwright trace

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3304)

Include feature flags in error report metadata

---

src/SIL.XForge.Scripture/ClientApp/src/app/event-metrics/event-metrics-log.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3308)

SF-3462 Add timezone to event log timestamp

---

src/RealtimeServer/common/resource-monitor.ts

Throws.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3331)

metrics: Do not jsonSizeOf(undefined)

---

mongodb/Projects/ProjectsOverTime.mongodb

I've updated this query to be able to exclude projects that are marked as test projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3329)

Update project query count to be able to exclude test projects

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3358)

Add project short name to unconnected projects on draft page

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/job-events-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/job-events-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/job-events-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/site-event-metrics.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/site-event-metrics.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/site-event-metrics.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.scss
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
src/SIL.XForge/Services/EventMetricService.cs
src/SIL.XForge/Services/IEventMetricService.cs
test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
test/SIL.XForge.Tests/Services/EventMetricServiceTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3368)

Add component to list Serval draft jobs

---

src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3371)

Update localized screenshots workflow to be more robust

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

This will be tested on QA by doing a full regression run. If we didn't make this change ourselves, the cut over would be coming, and we just wouldn't have as much control over it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3385)

Switch to new DBL server in prod environment

---

src/SIL.XForge.Scripture/Services/MachineProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs

This PR fixes an issue where legacy text files that contain Unicode characters in their name are unable to be zipped on Linux servers. As these files are legacy, they are not needed for translation, and so can be skipped when sipped for upload to Serval, or download from Serval Admin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3403)

SF-3530 Ignore file not found errors when zipping a Paratext directory

---

src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts

I temporarily commented out part of the test to make it run faster when working on a previous PR (#3389). That was not intended to be committed. This PR uncomments it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3408)

Re-enable portion of e2e tests that were mistakenly disabled

---

.github/workflows/build-and-test.yml
.github/workflows/chromatic.yml
.github/workflows/ci-lint-prettier.yml
.github/workflows/ci-production-build.yml
.github/workflows/codeql.yml
.github/workflows/compute-next-version.yml
.github/workflows/docker-dev.yml
.github/workflows/e2e-tests.yml
.github/workflows/grit.yml
.github/workflows/release-live.yml
.github/workflows/release-qa.yml
.github/workflows/release.yml
.github/workflows/update-font-list.yml
.github/workflows/update-localizations.yml
.github/workflows/zizmor.yml

This PR updates actions/checkout and actions/setup-dotnet in the GHAs to version 5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3423)

Update actions/checkout and actions/setup-dotnet to version 5

---

src/SIL.XForge.Scripture/ClientApp/e2e/e2e.mts

Retrying tests is not as effective when a new browser context isn't created, since the first test can log the user in, and then the rerun will start in the same context, with the user still logged in. There are probably other drawbacks as well. This PR changes the logic to create a new browser context for every run.
Also added a summary that is printed at the end.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3424)

Create new browser context for every e2e text run

---

.grit/patterns/no_mock_patterns_outside_mocks.md
src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts

Note: The Grit check is supposed to fail.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3405)

Add Grit check to prevent incorrect mock patterns

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3441)

SF-2935 Use mat-tooltip consistently

---

scripts/db_tools/package-lock.json
src/RealtimeServer/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json

This PR fixes the following issues raised via `npm audit`:
```
axios  <1.12.0
Severity: high
Axios is vulnerable to DoS attack through lack of data size check - https://github.com/advisories/GHSA-4hjh-wcwx-xvwj
fix available via `npm audit fix`
node_modules/axios
form-data  4.0.0 - 4.0.3
Severity: critical
form-data uses unsafe random function in form-data for choosing boundary - https://github.com/advisories/GHSA-fjxv-7rqg-78g4
fix available via `npm audit fix`
node_modules/form-data
on-headers  <1.1.0
on-headers is vulnerable to http response header manipulation - https://github.com/advisories/GHSA-76c9-3jph-rj3q
fix available via `npm audit fix`
node_modules/on-headers
compression  1.0.3 - 1.8.0
Depends on vulnerable versions of on-headers
node_modules/compression
morgan  1.6.0 - …
```

Update node dependencies

---

.github/workflows/build-and-test.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3484)

ci: make the disallowed tokens error more clear
