- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- src/SIL.XForge.Scripture/Models/MachineApi.cs
- src/SIL.XForge.Scripture/Services/IMachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ServalApiExceptions.cs
This Pull Request adds another endpoint to the V3 machine-api to allow the translation drafting frontend to discover if there have been any successful pre-translation builds in the past. If such a build exists, this means that the pre-translation draft for a chapter can be retrieved from Serval.
The new endpoint (which can be tested with Swagger) is: `/machine-api/v3/translation/engines/project:{sfProjectId}/actions/getLastCompletedPreTranslationBuild`
I also took the opportunity with this PR to plug a couple of minor gaps in the test coverage I found when calculating the test coverage data for the new API endpoint.
As this is a new API endpoint, regression testing is not needed, but developer acceptance testing that the endpoint serves the functionality requirement for the …
> SF-2159 Added GetLastCompletedPreTranslationBuild

- src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
The problem was that the thread Id for new notes on a thread was mistakenly being set to the thread data Id. The result was the thread Id for new notes was different than the first note in the thread, so when the note was synchronized, the note ended up on a new thread.
This change ensures that the correct thread Id is used for subsequent notes on a thread.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1958)
> SF-2137 Add notes on threads with the correct thread Id

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge/Services/FileSystemService.cs
- src/SIL.XForge/Services/IFileSystemService.cs
- test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
- test/SIL.XForge.Tests/Services/FileSystemServiceTests.cs
This Pull Request changes the method to write Comment XML files to use a custom XML Serializer rather than ParatextData's `CommentManager SaveUser()` method which uses `Momento.SetXml()`.
A benefit of this method is the fact we can now force the BOM to be written (matching the behavior of ParatextData running on the .NET Framework), and we can also unit test comment writing, to flag in future if either Paratext changes its XML schema for the Comment class or if future versions of .NET change the XML Serialization (as happened with the upgrade to .NET 6.0).
This implementation does not create the .bak file when the new comment XML is written - if this is a blocker we may want to look at our own method of storing this (i.e. versioned .bak files or in a different directory).
- - -
This …
> SF-2146 Write Comment XML Files with the BOM

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Indeterminate progress indicators may be helpful when a process is
running and the user can be shown that they need to wait for
something.
When debugging, or when working with unfinished code, the
indeterminate progress indicator may go forever until Continuing the
debugger, or closing the tab.
This patch adds a Stillness feature flag to change indeterminate
progress indication into determinate. There is still a visual
indication, but it is not distracting from studying code in an
adjacent window.
commit-id:747ab149
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1965)
> Add Stillness feature flag

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
While the notes feature is behind a feature flag, we do not expect user to be pushing comments to PT. This change introduces warning logs when a project is attempting to push those changes, but prevents those changes from being pushed. We can monitor these logs to see when we have a more robust note roundtripping system. To test this, you can enable the feature flag and create a note in SF and see the warning in the output console when you try to synchronize the project with PT.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1978)
> SF-2136 Log warnings when SF attempts to push comments to PT

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Section headings and other headings do not need to be highlighted when a verse is highlighted in the community checking tool. This change filters out segments that do not belong to a specific verse and only highlights those segments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1981)
> SF-2150 Do not highlight section headings in community checking

- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
When pasting a sharing link into an already logged in session, an error stating "Please connect to the internet to join a project using a link." is displayed and the user is redirected to the /projects page, and then the last project open.
This bug occurs because of incorrect logic that checks if the user is offline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1984)
> SF-2141 Do not show an offline error when pasting a sharing link twice

- src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
- src/SIL.XForge/Services/AudioService.cs
- src/SIL.XForge/Services/IAudioService.cs
- src/SIL.XForge/Services/IProjectService.cs
- src/SIL.XForge/Services/ProjectService.cs
- test/SIL.XForge.Tests/Services/AudioServiceTests.cs
- test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
* Allows audio file uploads of up to ~300MB (can be changed to any larger value as required)
* Changes the audio upload endpoint to stream incoming data to a temporary file to allow large file upload support
* Updated MP3 checking and audio file conversion to use the file path directly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1973)
> SF-2158 Support for uploading large audio files

- src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.scss
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1994)
> SF-2115 No projects connected page to material

- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
When multiple notes were deleted from a thread with 3 or more notes in PT, the result was not consistent in SF because when we removed notes from the notes property of a note thread, the operation depends on a static list. But when we remove multiple notes, the list changes for each note removal, and the result is that the wrong notes might be removed from the thread.
This change removes notes from the end of the list to the start of the list so that subsequent removal ops are correct with each note removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1993)
> SF-2147 Fix notes deleted in PT not deleted in SF

- src/SIL.XForge.Scripture/Models/FeatureFlags.cs
- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
This Pull Request adds support for developers to use the Echo engine for Pre-Translation Drafting.
The Echo engine "echos" the source text for the pre-translation draft, which removes the requirement to wait for the pre-translation draft to be generated in Nmt. This means that when the Echo engine is enabled on the developer's machine, the UI for pre-translation drafting can be more rapidly tested.
**Enabling Echo for Pre-Translation**
Echo is enabled via a feature flag. Enabling this feature flag will only affect new pre-translation translation engines, not existing ones.
```
dotnet user-secrets set "FeatureManagement:UseEchoForPreTranslation" true
```
- - - …
> SF-2170 Echo Support for Pre-Translation Drafting

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
The height of the app is set to 100vh, but on mobile this is (generally, in most browsers) too tall and requires the user to scroll because of the browser UI elements.
See:
- https://developer.chrome.com/blog/url-bar-resizing/
- https://www.youtube.com/watch?v=xl9R8aTOW_I
This needs to be tested on a physical device, which is beyond the ability of the test team, before the code is on QA, so we'll want to have the reviewer test it well before merging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2001)
> SF-2187 Fix app height on mobile

- src/SIL.XForge.Scripture/Services/ParatextService.cs
This change logs the content of notes that are storing xml that is not correctly being encoded to be set to the InnerXml of the Contents note of a Paratext Comment. Since SF notes are not currently being exported to PT, this code is only run to provide warnings in the logs, so it is OK to modify it and skip over updating those comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2000)
> SF-2186 Skip syncing notes with invalid content to prevent sync failure

- src/SIL.XForge.Scripture/Services/ParatextService.cs
This is a PR against sf-live to hotfix #2000.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2002)
> hotfix: SF-2186 Skip syncing notes with invalid content to prevent sync failure

- src/RealtimeServer/scriptureforge/models/note.ts
- src/RealtimeServer/scriptureforge/services/note-thread-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Models/FeatureFlags.cs
- src/SIL.XForge.Scripture/Models/Note.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
**Summary**
This Pull Request restricts note editing and writing to Paratext to only those notes that are created in Scripture Forge.
**New Features and Changed Behavior**
* A C# Feature Flag to enable Note writing to Paratext
* Disabled the ability to edit or delete comments created or edited in Paratext by the logged in user
**Testing**
To enable writing Notes to Paratext, enable the feature flag by running the following in `src/SIL.XForge.Scripture/`:
```
dotnet user-secrets set "FeatureManagement:WriteNotesToParatext" true
```
See also the Acceptance test for the corresponding JIRA ticket.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1988)
> SF-2173 Restrict note updating in Scripture Forge

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
This PR fixes the build state returned from the Machine API while Serval is being updated to be upper case, so that the frontend does not need to change the case of the string before reading it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2004)
> SF-2053b Fix Build State case during Serval upload

- deploy/vagrant/sfdev/Vagrantfile
By default the version of Chromium in the Vagrant VM does not support MP3 files. This poses issues when using Chromium to test the audio functionality of Scripture Forge out of the box (an audio unavailable message is displayed instead of the play controls).
To resolve this, this PR adds MP3 support to Chromium when the VM is being configured by Vagrant.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1990)
> dev: vagrant: Add Chromium MP3 Support

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1998)
> SF-2179 Refreshing scripture audio when timing data changes

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
* encode note content to be valid xml to be stored in mongo
* parse xml to html for display using a tree walker
* remove regex used for html display
This change makes improvements for how we display and save note content. Previously, if a user entered a reserved symbol like & into their SF note, the result would be an error would occur while synchronizing the data because Paratext expects comment content to be valid xml. This change ensures that notes are saved as valid xml. This also replaces the existing method for parsing html from note content which used regular expressions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2010)
> SF-2185 Fix error when user creates notes with invalid xml symbols

- src/RealtimeServer/package-lock.json
- src/RealtimeServer/package.json
- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bugsnag.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Currently when running the unit tests, there is a lot of noise in the console from Bugsnag:
```
INFO: 'Bugsnag.leaveBreadcrumb() was called before Bugsnag.start()', [[[]]]
INFO: 'Bugsnag.notify() was called before Bugsnag.start()', [[[]]]
```
This PR fixes these messages by updating Bugsnag, and checking if Bugsnag has been initialized using `Bugsnag.isStarted()` before calling `Bugsnag.leaveBreadcrumb{}` or `Bugsnag.notify()`.
See https://docs.bugsnag.com/platforms/javascript/faq/#how-can-i-tell-if-bugsnag-has-finished-initializing for details.
As this affects unit test output, success is determined by successful unit test passing, with none of the following messages in the test output:
* `INFO: 'Bugsnag.leaveBreadcrumb() was called before Bugsnag.start()', [[[]]]`
* `INFO: …
> SF-2207 Leave breadcrumbs only if Bugsnag has started

- src/Migrations/ServalMigration/Program.cs
- src/Migrations/ServalMigration/ServalMigrator.cs
- src/Migrations/ServalMigration/Startup.cs
- src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs
- src/SIL.XForge/Configuration/RealtimeOptions.cs
- src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs
- src/SIL.XForge/Realtime/ExistingNodeJSProcessFactory.cs
- src/SIL.XForge/Realtime/RealtimeService.cs
- src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
This Pull Request allows a Scripture Forge process, such as a migrator, use an existing NodeJS/Realtime Server process.
This is possible because of the custom `INodeJSProcessFactory` which acts as a stub for the process management features of the Jering.NodeJS. By stubbing these methods out, and specifying the port that NodeJS will use (port 5002), only the main process that started the Realtime Server will have the capability to perform the process management functions which are a part of Jering.NodeJS's tight coupling between the NodeJS process and the .NET process.
The Serval Migrator has been updated to use this new feature, as well as fixing support for the most recent Serval pre-translation changes in Scripture Forge.
- - - …
> SF-2148 Migrators can use an existing NodeJS process

- src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
* query the chapter specific notes each time the text changes
* extract note display information when the dialog opens
* remove test for html display of note content
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2011)
> SF-2192 Optimize note thread query and display

- .vscode/settings.json
The latest C# extension for Visual Studio Code (v2.0.413) prompts for the default solution.
This PR specifies the main xForge.sln file as the default solution in settings.json.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2024)
> dev: Specify default solution for dotnet

- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Currently when a note thread is deleted in SF because it no longer contains any notes (i.e. it was deleted in Paratext), then the `sync_metrics` collection will not be updated with a count of the thread being deleted. This PR fixes this issue.
As this is not a frontend user facing bug, developer acceptance testing is sufficient (see acceptance criteria in the JIRA ticket SF-2214).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2025)
> SF-2214 Update SyncMetrics on Note Thread Deletion

- src/SIL.XForge.Scripture/ClientApp/angular.json
Small fix so that angular cli uses .scss file extension when generating a new component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2034)
> Generate .scss instead of .css file when generating component with ng-cli

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR fixes a bug where the create audio timing data endpoint would cause an error if the audio timing data was updated.
In addition, this PR adds unit tests for the creating and deleting audio timing data (including this use case).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2027)
> SF-2212 Allow updating of audio timing data

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Previously Serval would remove the pre-translations when a pre-translation build is queued. This behavior has since been changed so that the pre-translations are only removed when a build completes.
As such, we no longer need this check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2040)
> Removed check for queued Pre-Translation builds

- src/.dockerignore
- src/SIL.XForge.Scripture/Dockerfile
Based on feedback I have optimized the build order in Docker so that modifications to C# code do not result in the rebuilding of the Angular front end, and that modifications to the Angular frontend.
This Pull Request fixes the Docker build order to run in the following order:
1. Realtime Server
2. Angular Frontend
3. Dotnet Backend
What this means is:
* Changes to the Realtime server will rebuild the Realtime server, the Angular frontend, and the Dotnet backend.
* Changes to the Angular frontend will rebuild the Angular frontend and the Dotnet backend, but not the Realtime server.
* Changes to the Dotnet backend will rebuild the Dotnet backend, but not the Realtime server and the Angular frontend.
Note: The dotnet project will still execute `npm run build` on the Realtime server, as a …
> Fix: Optimized Docker Build Order

- src/SIL.XForge.Scripture/Models/ServalData.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Currently, while a pre-translation build is being uploaded to Serval, cancelling it before it has finished uploading does nothing.
This Pull Request changes this so that when a pre-translation build is cancelled in this state, the Hangfire job is stopped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1991)
> SF-2228 Allow Pre-Translation build cancellation during upload to Serval

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
The time update event fires about 4 times each second. We don't necessarily need that level of granularity, but it is a logical place to emit the timeUpdated$ EventEmitter from.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2032)
> SF-2223 Use the timeupdate event listen to get time updates

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player-new.stories.ts
This story has  been creating very inconsistent snapshots because it's taking screenshots while the slider is updating, and the timing isn't always the same.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2044)
> Disable Chromatic snapshot of playing audio player

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts
This has been causing a lot of build failures. We need to fix the test, but in the meantime we don't want our builds constantly failing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2045)
> Disable flaky test of SingleButtonAudioPlayer

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts
- A build job state of `Faulted` will now result in a warning shown to user with a prompt to start a new build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1996)
> SF-2175 Recover from build status 'Faulted'

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.stories.ts
The Material input with the outlined appearance renders inconsistently, and that's caused it to constantly show up as a change in Chromatic. Try opening these two images, A and B, in different tabs, and switching between them, and you should see the difference.
The line sometimes gets closer to the label than at other times. This is a bug, but not one we care about that much, and hopefully it's been fixed in newer versions of Material.
In any case, Chromatic lets us set a diff threshold, and has a tool that lets you upload two screenshots and see what changes are found with a given threshold. I previously "solved" the problem by changing the threshold to 0.7, which I found to be sufficient.
But then the problem came back, and I think I know why. I recently updated the Material theme, and …
> Remove comment form from Chromatic diff due to rendering inconsistencies

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
* Introduced a grace period for skipping to previous verses
* Skipping to the next verse can now skip to the start of the current verse if it hasn't started yet
* Fixed bug when skipping to the start of the first timing data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2037)
> SF-2197 Chapter Audio Error Handling for Bad Timing Files

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
The Pull Request for SF-2208 has a bug where an error dialog appears if the user does not have permission to view the source text.
This scenario can happen if the Administrator sets the source project to a resource that a Translator does not have access to.
This PR resolves this bug by checking for the chapter permissions before retrieving the source chapter text then checking for non-empty verses.
To test this PR, it will be sufficient for a developer to via the Translate Overview screen for a project that has Translation Suggestions enabled, as the supplied unit tests confirm the positive and negative cases. The correct display of the Suggestion Engine card (i.e. without any warning messages) will confirm that the permission check is accurate.
- - - …
> SF-2208b Fix error when no source text permission

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
The header is now no longer covered by the drawer when it's open. I don't have a strong opinion on whether this is better or not, but it doesn't seem that there's a good way in Material to have it cover the header.
Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1868)
> SF-2039 Convert drawer to Material

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.ts
The audio player uses a mat-slide for UI to indicate the progress of the audio clip. In RTL, we forced the mat-slider to be in LTR mode so that it plays left to right. However, there seems to be some bug and the slider players left to right, but the green fill goes right to left.
This sets the slider to the direction indicated by the locale, but in RTL languages, it rotates the slider so that it plays equivalent to the LTR mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2048)
> SF-1627 Fix audio player in RTL UI

- src/SIL.XForge.Scripture/ClientApp/src/styles.scss
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2054)
> SF-2234 Fix number flipped on icon badge for RTL UI

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
This regressed in 22995b91d83b5ffb8d9424d8c05a56a78bafcad8 (#1868)
Before | After
-------|------
Since this regression got to QA, it is holding up our ability to release (QA hasn't passed testing, but it won't pass due to this). In the interest of getting back to a non-regressed state, this doesn't need to be formally tested until after merging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2065)
> SF-2241 Fix project name overflowing in project select

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
It was added by mistake, and the documentation warns about potential layout thrashing.
See https://v14.material.angular.io/components/sidenav/api#MatDrawerContainer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2072)
> Remove autosize attribute from mat-drawer-container

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
This makes the behavior consistent with Android 12 and Paratext Lite.
This PR probably wins some record for triviality. 
I picked 10 because I thought that's what Android did. However, after experimentation, I discovered I was mistaken.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2071)
> Only require 7 taps on version to enable feature flags

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
When translation suggestions are disabled by the user, training still occurs in the background.
Because of this, the "verse too long" error message can appear when the user does not expect it (due to their having disabled translation suggestions in the Translation Settings dialog).
Included in this PR are two unit tests confirming the correct behavior for the "verse too long" notice when a verse is too long.
Please see [SF-1656](https://jira.sil.org/browse/SF-1656) for details on how to recreate this issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2059)
> SF-2211 Do not show the verse too long error when suggestions are disabled

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
For the Echo translation engine to work correctly, the source and target language must be the same.
This PR updates `CreateServalProjectAsync()` so that it sets the source and target language to the same value on Serval if the Echo Pre-Translation engine is enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2036)
> SF-2227 Fixed Echo Pre-Translation Engine support

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
A few months ago I added this condition in the tests so this method could support Material and MDC at the same time. It's no longer needed (as proven by the fact that the tests are still passing after I've removed the path that was there to accommodate MDC).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2070)
> Remove obsolete test condition for MDC

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
In mobile view, when selecting an item, the drawer closes, _except_ for when back translation drafting is clicked. This fixes that.
I didn't deem it worth creating a test or manually testing this. This entire sidebar is about to be replaced anyway, and it's a super trivial issue.
(And in case you're wondering, this bug does not exist in #1825. So maybe I shouldn't have even tried to fix it).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2069)
> Fix sidebar not closing when opening back translation drafting

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
All the package names are in the `@material` namespace, but they need to be removed because they are only installed due to being dependencies of `@angular-mdc/web`
I'm pretty sure because these are `@use` statements, there shouldn't be any changes caused by removing them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2067)
> Remove unused SCSS imports from MDC-related packages

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/utils.spec.ts
This pull request is for the editor component integration for the back translation drafting. It is hidden behind feature flag 'Show NMT drafting'. Once enabled, there will be a 'Generate draft' menu item that will take the user to the draft generation page.
**Draft preview page**
* User can click the 'Edit' button anytime to navigate to the editor for the current book and chapter.
**Editor page additions**
* If there are any unapplied pre-translations for the current chapter _(available pre-translations for untranslated segments)_, there will be a 'Preview draft' button that will navigate user to draft preview page for the current book and chapter.
* In this way, user can work and is 'notified' by the presence of the 'Preview draft' button when draft is available.
**Notes**
- To …
> SF-2177 Back translation draft UI - Editor integration

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-test.utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts
This greatly improves performance for these tests. Theoretically it removes the flakiness, as well, since we no longer depend on playing actual audio files.
The new tests use a stub child component, which itself uses (via implicit override) a stub audio player, which itself uses a mocked html audio element. This all was necessary to work around the inabiliity to mock Angular child components and the limitations in ts-mockito surrounding property setters. ts-mockito doesn't allow verification on property set actions, and it frequently fails at runtime often ever reaching the verification. The current setup subclasses (you could use Partial, as well) AudioPlayer and overrides the critical methods and properties. This effectively removes any dependency on realtime audio data.
- - -
This …
> SF-2231 Flaky audio tests

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
This is doing two things:
1. Removing dead code in `src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts`
2. Removing a reference in the SCSS to `top-app-bar.$mobile-row-height`, and replacing it with `56px`, which is what the value was anyway.
I have marked this as "testing not required" because in order to test it the "update available" banner needs to be present. I tested it myself manually by turning the banner on and making sure it worked as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2068)
> Remove unneeded references to MDC top app bar

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
When both the Serval and InProcessMachine feature flags are enabled, the Generate Draft screen does not return the build status for the pre-translation builds.
This PR fixes that by ensuring that the InProcess Machine instance is not queried for the build status of pre-translation builds.
See the Acceptance Test for [SF-2240](https://jira.sil.org/browse/SF-2240) for details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2063)
> SF-2240 Fixed pre-translation builds not returning build status when Serval and In-Process feature flags enabled

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextNoteExtensions.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR fundamentally does two things. The first is it copies the version number of an SF note to the PT comment when it is first created. Previously, this was not done, and the default comment version was 0.
Secondly, this updates the logic to detect when an SF comment created in SF by a commenter is updated in PT. We want to revert any changes made by PT users in PT, since the authoritative source for the content of commenter comments should be the SF version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2081)
> SF-2252 Fix PT note not updated when commenter updates SF comment

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
The editor was correctly trying to apply an undo operation to a verse, but there was a bug that appeared if the undo causes the selection to change to another verse. This only seemed to happen if the undo deleted all of the text and introduced a blank. The solution I found was to set the commenter-selection attribute on the undo delta to be null. Then when the selection changes to the original verse, it gets the verse highlighting as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2085)
> SF-2242 Fix verse not selected when undo moves cursor to another verse

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
This PR adds a feature flag that overrides the checks in back translation drafting for:
* Whether the translation is a back translation
* Whether the language is in the NLLB
This means that when this feature flag is enabled, testing of forward translation drafting can be done using Serval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2087)
> Add Forward Translation Drafting feature flag

- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/biblical-term-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
When changing to a language that does not have a gloss translated for a Biblical Term (i.e. ἅγιος-1 in Romans 1:2 in Spanish), a blank definition is shown. Instead, it should show the definition in the default language (English).
This PR provides fallbacks for blank Biblical Term translations for glosses, categories, and notes where they are blank in the translation file. This occurs most often for Spanish, as the Spanish XML file only has some translations where French is more complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2084)
> SF-2255 Show biblical terms in default locale when blank

- src/SIL.XForge.Scripture/Terms/Lists/BiblicalTermsId.xml
This PR fixes a typo in the Indonesian Biblical Terms Localization file that causes a gloss to not be loaded correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2096)
> Fix broken gloss in Indonesian Biblical Terms

- src/SIL.XForge.Scripture/ClientApp/.storybook/main.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player-new.stories.ts
This PR fixes a broken storybook Checking Audio test.
The test was broken because the webm file the test played was moved, and a declaration for a new subcomponent was required.
**Testing Instructions**
***Prerequisite:** Scripture Forge is in the directory `~/src/web-xforge/`*
1. In a terminal run:
```sh
cd ~/src/web-xforge/src/SIL.XForge.Scripture/ClientApp
npm run storybook
```
2. Once Storybook has started, run the following in a new Terminal:
```sh
cd ~/src/web-xforge/src/SIL.XForge.Scripture/ClientApp
npm run test-storybook
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2097)
> Fix broken Storybook Checking Audio Test

- src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Scripture Forge is incorrectly checking the length of the string instead of checking the number of word tokens.
This PR updates Scripture Forge to use the `InteractiveTranslator.isSegmentValid` property to determine if the segment is too long instead, as recommended by the Serval team.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2083)
> SF-2222 Fix verse too long error for suggestions

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Backslashes can cause problems when we synchronize to Paratext. PT will show backslashes as errors in the editor, so it is better if we disallow backslashes altogether in SF.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2089)
> SF-2246 Disallow typing or pasting backslashes

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts
This PR fixes many of the test execution warnings that were providing noise during test execution in Jasmine.
Not all are fixed, as some are caused by components that should not or cannot be mocked, but the net result of this PR is less noise in the test execution console output.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2099)
> Fix Angular Test Execution Warnings

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextNoteExtensions.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR specifies the Note Status for Paratext Comments. This ensures that if a note (particularly a Biblical Terms note) is reopened in Scripture Forge, it will be reopened in Paratext.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2086)
> SF-2256 Specify Note Status for Paratext Comments

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss
I think this is most easily tested by a developer, since making sure the old rule was doing what I think it was doing is more than 50% of the challenge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2101)
> Remove button mixin from training progress component

- src/RealtimeServer/scriptureforge/models/checking-config.ts
- src/RealtimeServer/scriptureforge/models/sf-project-test-data.ts
- src/RealtimeServer/scriptureforge/models/text-audio-test-data.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.html
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/json-realtime-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- src/SIL.XForge.Scripture/Models/CheckingConfig.cs
- src/SIL.XForge.Scripture/Models/SFProjectSettings.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
Note that this PR introduces a regression: "Audio unavailable" is not shown when the user navigates to a chapter that does not have audio. This can be addressed in followup.
----
Note that this PR is composed in different commits. There are two refactor commits at the beginning of the PR that are separate from other changes. Hopefully that will make the review easier. **It is okay if the whole PR is squashed together for submitting. Although I would like for all the commit messages to be retained.** The individual commits were not individually tested.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1967)
> SF-2028 Hide community checking text when requested

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
A white padding was maintained at the top and bottom of the answer area. Unlike for the Scripture text area.
Maintain having the same padding, but allow the padding itself to scroll up and down with the answer area.
---
Video of behaviour before:
[answer-panel-before.webm](https://github.com/sillsdev/web-xforge/assets/7265309/ee0bd682-811d-4122-ae6c-577b098cc1cb)
Video of behaviour with this patch:
[answer-panel-after.webm](https://github.com/sillsdev/web-xforge/assets/7265309/1e5ffbb1-3722-4bf8-b23e-8737b90c11a3)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2047)
> Allow answers to scroll up closer to splitter

- src/SIL.XForge.Scripture/ClientApp/src/_text.scss
I removed the typography mixin and added the declaration `letter-spacing: 0.03125em;`. As far as I could tell (in the project I was testing), it was the only declaration crated by the mixin that appeared to have any visual effect. However, I can't be certain it doesn't have an impact on any other project, but it's hard to write test steps ("make sure every project looks identical before and after this change" is hard to test without creating screenshots of every project and then switching between them).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2104)
> Remove typography mixin from editor styles

- .vscode/settings.json
Before:
After:
The different colour helps distinguish it from syntax and other compilation errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2108)
> dev: in IDE, show eslint as warnings, not errors

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Note that attempting to simplify this by putting the logic in `get
scriptureAreaMaxSize` resulted in "Expression has changed after it was
checked".
---
Following up from #1967, this PR sets `maxSize`. Please note that this PR is temporarily targeting unmerged branch `task/745682c8` for code review reasons, but is ultimately intended for master. 
Video showing new behaviour:
[scripture-audio-max-size.webm](https://github.com/sillsdev/web-xforge/assets/7265309/02381a52-a9e8-4d3f-9ae0-75fa33fd2619)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2090)
> SF-2261 Set Scripture audio player max size when hiding text

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/PreTranslationService.cs
- test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
The Serval API has changed the API endpoint where draft pre-translations are generated. Serval.Client 0.5.4 contains an update that allows use of this updated endpoint.
This PR updates SF to use the updated client, and modifies calls to affected methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2113)
> Update Serval.Client to 0.5.4

- src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs
- src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
- test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs
This Pull Request fixes the upload of Biblical Terms to Serval based on feedback from the Serval team. In particular it:
* Cleans renderings to not contain Paratext specific syntax
* Loads Biblical Terms from MongoDB with fallback to the XML file if the terms are not yet populated in the database
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2091)
> SF-2258 Fix uploading of Biblical Terms to Serval

- .github/dependabot.yml
To ensure that we no longer miss out on updates to Serval.Client, this PR configures dependabot to create Pull Requests whenever an update to Serval.Client is published to NuGet.
The success or failure of the created PR's build will help determine whether this is a breaking change to the Serval API or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2115)
> Add dependabot updates for Serval.Client

- src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
Up until now, comments on answers would not be deleted when an answer was deleted. This was because the deleted property was never set on the answer comments. It is not possible to set the deleted property on the front end because the user does not have permission to edit other users' comments.
This change determines whether to delete an answer comment should be deleted based on whether the answer or comment has been deleted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2105)
> SF-2260 Delete comments on deleted answers during synchronize

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
When the user's Internet connection goes offline, the functionality to preview the pre-translation draft and apply the draft to the project remains visible.
This PR hides that functionality when the connection goes offline, as the pre-translation drafting functionality requires a live connection to Serval via SF's Machine API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2114)
> SF-2254 Hide Pre-Translation Draft UI When Offline

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
Show button to preview draft while a build job is running if a previous draft exists.  Now UI should conform to flow chart:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2112)
> SF-2230 Display draft preview button while build running

- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
This PR fixes a bug where the "Hide Scripture Text" setting would always tick as updated when viewing the Settings screen.
I have also taken the opportunity to add the `hideCommunityCheckingText` field this setting corresponds to into the `sf_project` validation schema.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2119)
> SF-2279 Fix Hide Scripture Text settings updates

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
I think ideally this text would overflow with an ellipsis, but I was struggling to get that to work. However, I was able to get the text to wrap, which looks good to me.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2118)
> SF-2282 Wrap text when question filter text overflows

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
When user selects to generate a draft, the user is now shown pre-generation steps in which he will select books for training.
This pull request just implements the initial UI concept.  The selected books are not currently sent to the API with the draft request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2120)
> SF-2278 Display book selection for draft training (UI only)

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts
The book dropdowns in the chapter audio, community checking, and draft preview screens are sorted by database order, not canonical order.
This PR fixes this by sorting the book number arrays in these three locations by the book number.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2123)
> SF-2287 Sort books canonically in dropdowns

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
This PR temporarily disables remote feature flags, which due to an injection hierarchy issue on QA causes a blocking error.
A later PR will correctly fix this issue, however this PR will resolve the current impasse on QA.
Due to the nature of this bug, the only real effective test of it will be deployment and execution on the QA environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2128)
> FIX: Disable Remote Feature Flag Support

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
Removed the redundant large corner filter icon since the filter text is now an always-visible button, displays the icon, and triggers the filter menu.  Also added some top and bottom padding to the filter button.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2126)
> SF-2293 Remove redundant question filter icon

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
* Moved navigation project select into its own component
* Convert from MDC to Material
The conversion to Material isn't as ideal as it currently looks on MDC. Once we upgrade to Material 15+ we'll be able to get it a lot closer to the current MDC look and feel.
**MDC**
**Material 14**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2103)
> SF-2264 Convert navigation project selector to Material

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR resolves the "403" errors when viewing a chapter for a project when Pre-Translation drafting is enabled.
Please see the JIRA ticket for further details, and the steps to reproduce.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2111)
> SF-2247 Fix pre-translation drafting permission error

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Minor fix to ensure filter translation key has a value, as the list of question filters might not have been populated yet when first accessed.  This fix just clears up a console error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2133)
> Fix 'missing translation' error in checking component template

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/anonymous.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
- src/SIL.XForge.Scripture/Controllers/AnonymousController.cs
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- test/SIL.XForge.Scripture.Tests/Controllers/AnonymousControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
Remote Feature Flag retrieval have been disabled on master due to a race condition discovered on QA.
This PR fixes the issue by retrieving the feature flags from an anonymous controller. This is required because the `AuthService` is dependent on services that use the `FeatureFlagService`, creating a circular reference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2131)
> SF-2294 Fix remote feature flag retrieval

- src/SIL.XForge.Scripture/appsettings.json
The Serval Auth0 audience has changed from `https://machine.sil.org` to `https://serval-api.org/` across all environments.
All branches/PRs will need to be rebased to use this updated audience or Serval support will not work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2143)
> Update the Serval audience

- src/SIL.XForge.Scripture/appsettings.json
This PR updates the production configuration for the Serval API server to be the correct server address.
This change does not affect dev or QA environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2144)
> Update Serval Production API Server Url

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
* Calculate scripture slider position on window resize
This fix relates to changing the split component size and then dynamically resizing the screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2124)
> SF-2266 Resize bug when audio-only

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/karma.conf.js
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.spec.ts
This PR fixes the following warnings, messages, and items missed in some of the frontend unit tests:
* **Updated:** The tests for `NavigationProjectSelectorComponent` to use the new `TestOnlineStatusService`
* **Fixed:** The following expectations were not always triggered: 
* `WARN: 'Spec 'DraftGenerationStepsComponent should set availableBooks$ correctly' has no expectations.', [[]]`
* `WARN: 'Spec 'DraftGenerationStepsComponent should select all books initially' has no expectations.', [[]]`
* **Fixed:** The following message in the test log: `ERROR: HttpErrorResponse{headers: HttpHeaders{normalizedNames: Map{}, lazyUpdate: null, headers: Map{}}, status: 504, statusText: 'Gateway Timeout', url: 'http://localhost:5000/machine-api/v3/translation/engines/some-end-point', ok: false, name: …
> Fix warnings and messages in Angular unit tests

- src/SIL.XForge.Scripture/locales.json
The Nepali locale is visible on the home page on development machines before any of the translations are ready. Disable it for the time until translations and auth0 configs are put in place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2146)
> SF-2292 Disable Nepali locale

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss
Before | After
-------|------
Note the difference in scrollbar. In the "before" screenshot, the scripture goes below the audio player, and you can't scroll all the way to the bottom.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2026)
> SF-2218 Fix audio player covering scripture scrollbar

- src/RealtimeServer/common/migration.ts
- src/RealtimeServer/scriptureforge/services/note-thread-migrations.ts
- src/RealtimeServer/scriptureforge/services/question-migrations.ts
- src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
- src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
Every migration implements an empty op migration:
```ts
migrateOp(_op: RawOp): void {
// do nothing
}
```
This PR creates an abstract class `DocMigration` that implements this empty op migration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2136)
> Refactor migrations to reuse migrateOp

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
When a Serval API Exception is reported by Serval when both Serval and the In-Process machine are enabled, this error incorrectly is returned to the frontend.
This PR instead reports the exception to bugsnag and calls the appropriate method in the in-process machine instance, returning the output of that method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2149)
> SF-2302 Improve Serval API Exception Error Handling

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
When editing a text doc offline, the ops for the edits are stored in IndexedDB and sent to the real-time server when coming back online. However, the way that our text component handles ops that include inserting a blank embed has a bug that incorrectly interprets the delta from that op. If only one user is editing a doc while offline, there is no issue. But when two users edit the same doc while offline, the merge event results in duplicated verses.
To prevent this issue from happening, I decided to skip the code that inserts blank embeds when text is deleted from a verse. The negative impact of this fix is that blanks do not get automatically inserted if a user removes all text from a verse, but I think this will have a minimal impact because:
- I don't expect users to be intentionally …
> SF-2272 Prevent corrupting text when user deletes all verse text offline

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
When the URL of either the Translate or Preview Draft screen is manually changed to a book that is not in the target project, the draft viewer component should now route to the first valid book/chapter of the project, and the editor component routes to the 'projects' route, which should send the user to the last selected book stored in SFProjectUserConfig.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2147)
> SF-2249 Handle invalid url book in draft preview and editor pages

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This fix hides the next/previous chapter buttons and increases the breakpoint width for hiding the questions list to 700px (was 600px).
The next/previous chapter buttons were prevent the page from shrinking:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2155)
> Fix checking UI for some screen widths

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
This PR updates npm `typescript` and `@types/node` packages in preparation for update to Angular 16.
Updating only the typescript package causes a compilation error due to conflicting type definitions.  Updating package @types/node fixes this issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2162)
> SF-2321 Update typescript and @types/node

- src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- src/SIL.XForge.Scripture/Services/ISFProjectService.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR is the backend change to allow setting of the `preTranslate` flag via the system administration area of Scripture Forge.
This code does not yet change the frontend, but a separate PR (SF-2269) will address this.
Developer testing will be sufficient as this is a change that is only accessible by developers and it updates a database field (`sf_projects.translateConfig.preTranslate`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2156)
> SF-2313 Ability to enable MT drafting in System Administration

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts
Eli pointed out that Serval returns the percent complete for a build as a 0-1 percentage, while our frontend is expecting a 0-100 percentage. Thus, the value never goes above 1 in the progress circle.
The translation suggestions engine already works with a 0-1 percentage, so I have updated the frontend to use the 0 to 1 percent complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2164)
> SF-2325 Fix draft percent complete display

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
This is necessary before updating to Angular 16, because Angular 16 no longer compiles from the View Engine format to the Ivy format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2163)
> SF-2324 Update angular-split to 15.0.0

- src/RealtimeServer/scriptureforge/models/sf-project.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Models/ParatextSettings.cs
- src/SIL.XForge.Scripture/Models/SFProject.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Some translations specifically request that a copyright banner is displayed above the text in Paratext.
This PR updates Scripture Forge so that translations that request a copyright notice to be displayed have the copyright notice of their specification displayed. Because this message is stored in the Project's Settings, it is not localized.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2161)
> SF-2322 Display copyright banner for translations that request it

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
* Check if a TextAudioDoc is available when opening the chapter audio dialog
* Enable edit chapter audio from checking overview
* Disable book and chapter selectors in edit mode
* Can edit chapter audio from checking overview
* Timing data and audio is pre-populated in the chapter audio dialog
* Audio can be played from the chapter audio dialog
* Book and chapter is disabled in the chapter audio dialog
* Overwriting with different audio and/or timing data should save and overwrite what was previously saved
**Checking Overview**
**Chapter Audio Dialog**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2165)
> SF-2297 Allow editing of scripture audio data

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.scss
This PR fixes two bugs and makes one layout improvement.
- The buttom of the play/pause button was partially hidden underneath the slider, which was not visually apparent, but caused some clicks to go to the slider when the user would expect the audio to play/pause. See SF-2308.
- The skip forward/backward buttons were inverted in RTL mode (i.e., they did not match the direction of the slider). See SF-2307.
- The reference of the verse being played has been moved from below the slider, to above the slider. See screenshots.
Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2153)
> SF-2307 SF-2308 Fix scripture audio play button and RTL skip buttons

- src/SIL.XForge.Scripture/ClientApp/src/_text.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This change adds padding to the quill editor on the side where the FAB for adding comments is showing. This makes it much less likely for the FAB to cover text as a user is typing or reading.
Translators and Admins
Commenters
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2159)
> SF-2317 Improve comment FAB position to not cover text

- src/RealtimeServer/package-lock.json
- src/RealtimeServer/package.json
- src/SIL.XForge.Scripture/ClientApp/package-lock.json
We already updated TypeScript and `@types/node` in ClientApp, but didn't do so for the realtime server. We should keep package versions in sync as much as possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2180)
> Update TypeScript to 4.9.5 in realtime server

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
- Removed headset icon from question list
- Used circle play icon for playing chapter audio
- The audio file icon is used for indicating upload of audio
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2177)
> Make audio icons in checking area more consistent

- src/SIL.XForge.Scripture/ClientApp/src/_text.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
Question marks should be mirrored in a RTL context, per https://rtlstyling.com/posts/rtl-styling#bidirectional-icons. This makes sense, since Arabic uses question marks, and they're the other way around.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2184)
> SF-2348 Mirror question mark in RTL contexts

- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR makes changes to the book selector that is presented when generating a new draft.
- Changed info message to be always visible under step heading, and update the text to say: "Select books that have been proofed".
- Removed unnecessary second step.
Additionally:
- Changed the stepper and book selector components to be 'standalone'
- Migrated the `MatChipsModule` to not refer to the legacy module using `ng generate @angular/material:mdc-migration`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2181)
> SF-2344 Adjust pre-translation book selection

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
The text audio query does not update automatically when audio is uploaded. Local update needs to be called on the query so that the locally uploaded audio is added to the query. I would have expected this to be automatic, but in other PRs such as SF-993 it appears to be the responsibility of the component to update the query.
I spend a couple hours trying to add a test for this behaviour, but didn't get far and decided it was not worth the effort.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2158)
> SF-2311 Allow playing chapter audio immediately after upload

- src/SIL.XForge.Scripture/Services/PreTranslationService.cs
- test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
This Pull Request updates the data retrieved from Serval for Pre-Translation drafting so that verses that are broken into multiple style segments, e.g. `\p` or `\q1` are combined into one verse segment.
This will improve the quality of translation drafts for back translations and forward translations where the source translation uses these features.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2171)
> SF-2332 Improve verse segment alignment for MT Drafting

- src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
Project picker in RTL mode:
Before | After
-------|------
Rationale: Aligning some projects to the right, and some to the left, is not very helpful. Additionally, every line starts with the project short name, which is always going to be in a Latin script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2190)
> SF-2349 Align all projects to the left in project picker

- src/RealtimeServer/scriptureforge/models/translate-config.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- src/SIL.XForge.Scripture/Models/DraftConfig.cs
- src/SIL.XForge.Scripture/Services/ISFProjectService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR adds support for custom configuration for MT drafting. This config can be set in the Settings page for a project, and for security reasons, can only be set by a System Administrator.
A sample configuration to use on QA that would make it behave like Production would be:
```json
{"max_steps":20000}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2173)
> SF-2268 Custom Configuration for MT Drafting

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.scss
- The setting should only affect forward translation drafting. Wording has been fixed.
- The layout was quite bad because CSS constrained the width of the table to 800px. I increased it to make it more usable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2198)
> Fix description of admin page drafting setting

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
This tool-tip is now removed:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2196)
> Remove tooltip from question list

- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
The previous string suggested one chapter at a time, which is likely more than our compute resources can keep up with. Field trials in the past have been mostly one book at a time (sometimes several books at a time, if the books are very short).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2192)
> Update drafting message to suggest one book at a time

- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
The dialog can be opened while offline, but the fields are still not editable. I added some text to indicate this in the dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2182)
> SF-2314 Allow opening roles & permissions dialog offline

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
The NMT auth guard did not exist when I last set up the logic for whether to show NMT drafting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2204)
> Update sidebar to use NMT auth guard

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
@pmachapman I don't know if this is the right approach for turning on a feature flag or not. It's not as clean as I'd like. But I do want feature flags to be able to be turned on by hard coding a new value, so they can be turned on and off by shipping features (rather than having to be separately controlled by changing environment variables). There's a place for changing feature flags using environment variables (e.g. the Serval switchover would be much more of a pain if we had to ship every time). But being able to change them in code and have commits go through our normal shipping process makes the whole testing process so much easier. If something can be handled by version control, keeping it in version control means everything is simpler.
- - - …
> SF-1715 Enable scripture audio feature flag

- src/SIL.XForge/Realtime/RealtimeService.cs
- test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
Currently milestones are only recorded for texts. When a project is deleted, all supporting data is deleted too, including texts.
This PR ensures that the texts collection's milestones are deleted, and any future milestones for any related collections are deleted too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2189)
> SF-2352 Delete milestones when projects and users are deleted

- src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This PR modifies the Serval integration layer to correctly pass a 409 error to the frontend.
When these occur, the user is given the option of retraining the model, and is redirected to the translate overview to view the progress of the build.
To trigger the error scenario, the backend must be temporarily modified by a developer (see the JIRA ticket), so testing should be performed by a developer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2207)
> SF-2353 Correctly handle a 409 error from Serval

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
- Removed this rogue quote
- On admin pages, generate draft no longer looks like it means "edit"
- The icon for "manage questions" has been changed to the list icon, for consistency with the sidebar. Also, what follows that heading is a list of books, so there's a visual match.
- The project stats icon has been changed from a donut chart icon, to a bar chart icon
For community checkers, I thought it was weird that there were actual donut charts by each book, but we used the donut chart icon for the section with numerical stats. That seemed like a mismatch:
So I changed it to the bar chart icon, which matches with the icon in the sidebar. I don't like that the top heading on this page is "my progress" and the icon doesn't match the icon in the sidebar, but that's related to the fact that …
> Fix inconsistent use of icons, and remove unneeded quote

- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
The Q&A icon, and the users icon, were both being clipped by the mat icon border-radius.
This could be fixed by just setting border-radius to 0, but the reason this was a problem is because I had set the padding on the icons to 0. I did this to get the spacing how I wanted it. However, there's a more straightforward way to get the spacing than removing the padding.
Before, with padding removed from icon:
After, with padding restored to icon, padding reduced on left side of icon, and gap between icon and the text adjusted.
See Storybook for a comprehensive understanding of what actually changed visually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2214)
> Fix clipping of icons in nav component

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Only books that are both in the source and target can be used for training. This PR updates SF so that only the source and target books are passed to Serval. The passing of any other source books results in unnecessary processing taking place on the Serval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2208)
> SF-2386 Only allow selection of books available in the source and target

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This Pull Request correctly traps and handles 409 errors from Serval and stops them throwing exceptions in the editor when checking to see whether or not pre-translations exist for a given book/chapter.
A 409 error means that the Serval translation engine is not ready for retrieving the pre-translations yet.
**Note:** Testing should be completed by a developer, due to the requirement to modify the code to throw the exception (see the JIRA ticket).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2220)
> SF-2396 Handle pre-translation 409 errors in the editor

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.html
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Before there was a mix of tool tips, no tool tips, different types of tool tips (hover text, versus Material).
- No tool tip on "Add question" button when the text is shown
- Tool tip on "Play chapter" is shown, but not for pause. If you've already hit play, it should be pretty obvious what the button is for.
https://github.com/sillsdev/web-xforge/assets/6140710/ec544509-2301-41dd-a802-739937a23db1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2223)
> SF-2398 Make tooltips for icon buttons in checking area consistent

- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
Currently the pre-translation settings are visible for all projects. This PR changes the settings screen so that they are only visible if:
* The project is a back translation.
* The project has been approved for pre-translation drafting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2218)
> SF-2389 Hide pre-translation settings when not approved

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
Simplified the overflow repositioning logic a little. Before, it was basing its calculations off of the entire body, which resulted in some incorrect assumptions, namely that that logic was not accounting for margins. The old code only resized when the overflow was greater than the body width, but there could have been and was nonetheless cutoff due to the righthand margin between the editor and the right side of the body.
The updated logic bases its computations off of the editor alone, resulting in a cleaner and more accurate solution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2188)
> SF-2318 Right align suggestions when there's overflow

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
This PR allows pre-translations for verses that are combined (i.e. `\v 1-2`) in the source to be correctly added to the draft preview and generated draft when the target does not have a combined verse at that same position.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2209)
> SF-2382 Fix combined verse support for pre-translation drafts

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-test.utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
Timing files can be broken down into phrase level (and even word level) components. The Single button audio player accepts the timing for the section of the audio for the verse that a question pertains to. Previously, the component that extracted the data for the timing range did not account for the phrase level timings, meaning that for a single verse, there may be multiple timings.
This change ensures that all the timings for a timing range is considered so that single button audio player is given the correct timing information for the verse.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2199)
> SF-2381 Support phrase level audio scripture playback on questions

- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
Keeping this change minimal.
- Left aligned
- No divider
- Added spacing
Here's how it looks now:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2232)
> Improve sidebar headings

- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- src/SIL.XForge.Scripture/Controllers/MachineApiV2Controller.cs
- src/SIL.XForge.Scripture/Models/ServalBuildAdditionalInfo.cs
- src/SIL.XForge.Scripture/Models/ServalBuildDto.cs
- src/SIL.XForge.Scripture/Services/IMachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiV2ControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This Pull Request adds a new Diagnostic Information section to the Generate Draft screen that appears only for System Administrators.
**Note:** This new section is not localized, as it is for System Administrators only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2210)
> SF-2354 Display Serval Build diagnostic information to System Admins

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
There are definitely arguments for "translate" over "edit", but there doesn't seem to be a clear consensus, except that both "edit" and "translate" are preferable to "draft", and the changing of the icon.
Here's how it looks now:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2233)
> Update translate link to "Edit & review"

- src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
* specify status when note dialog is closed
* update note thread status to be the status of the saved note
* allow note content to be optional
* add trigger for save options menu next to save button
The PR introduces the logic to allow Paratext users with permission to add notes to resolve a note thread. Users with the Commenter role are unable to resolve note threads. When a thread is resolved, they can no longer be viewed in SF unless a user synchronizes their project to PT and the note is unresolved in PT. I don't expect that it will be often that a user will need to unresolve a note, but it can be done.
Resolve button translator view
Save button commenter view
- - - …
> SF-2301 Enable resolving note threads in SF

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.types.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.spec.ts
Updated notice component to have softer styles and more styling options as mentioned in [this github comment](https://github.com/sillsdev/web-xforge/pull/2182#pullrequestreview-1751463413).
`<app-notice type="normal">` will still work, but the new way is to use 'primary' `<app-notice type="primary">`.
`<app-notice [outline]="true">` will still work, but the new way is to use the `mode` input `<app-notice mode="outline">`.
- Updated Storybook with the new options.
- Converted NoticeComponent to be a standalone component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2200)
> SF-2383 Adjust and add styling options to notice component

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
The timing files that are exported from HearThis likely have headers. This change assumes that any timing file with some row with 3 columns is audacity style, the same style that HearThis uses. It then allows parsing the entries. Previously, if the first entry does not have 3 columns, it would mark the files as invalid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2235)
> SF-2406 Support timing files with headings

- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
- src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This Pull Request improves the stability of Scripture Forge for the two following scenarios:
* When the project's translation engines are deleted from Serval
* When the `ServalData` property is removed from `sf_project_secrets`
When these scenarios occur, the user can rebuild the SMT or NMT translation engines, and recover from the scenario.
***Note:** Testing should be performed by a developer, as it requires modification of the Mongo database.*
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2229)
> SF-2397 Allow rebuilding when Serval data is missing from SF or Serval

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
This PR adds support for combined verse in the target text that are separate in the source text.
In this case, the verses that are in the draft that are separated, are placed into the combined verse in the target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2231)
> SF-2309 Support for combined verses in the target text

- src/SIL.XForge.Scripture/Models/ISFText.cs
- src/SIL.XForge.Scripture/Models/SFTextSegment.cs
- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/ISFTextCorpusFactory.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs
- src/SIL.XForge.Scripture/Services/SFScriptureText.cs
- src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MockText.cs
- test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs
Because Serval performs its own, more accurate tokenization, we should not do that before sending the data to Serval. However, until the In-Process machine is removed from SF, that logic will need to remain.
This is achieved by:
* Creating data structures that override and are parallel to the SIL.Machine data structures that includes the entire Segment text.
* Only sending verse segment data to Serval Nmt for Pre-Translation.
* Refactoring SFScriptureTextTests for clarity.
In addition, this PR alters the data sent to Serval to Pre-Translation to only include verse data. This will improve the quality of data generated. A later PR (SF-2410) will re-enable this support via a project setting.
- - - …
> SF-2409 Remove tokenization of data sent to Serval

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
This PR fixes the following error in the unit tests that was being logged in the console:
```
'ERROR', [[TypeError: Cannot read properties of null (reading 'then')
TypeError: Cannot read properties of null (reading 'then')
at TranslateOverviewComponent.startTraining (http://localhost:9876/_karma_webpack_/webpack:/src/app/translate/translate-overview/translate-overview.component.ts:168:43)
at listenerFn (ng:///TranslateOverviewComponent.js:120:41)
at executeListenerWithErrorHandling (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:13975:16)
at eventHandler (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2020/core.mjs:14008:22)
at HTMLButtonElement.apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@an …
```
> Fix error in TranslateOverview retrain unit test

- src/SIL.XForge.Scripture/appsettings.json
This PR changes the default feature flag configuration to enable Serval support, to reflect that Serval should be on permanently now for every environment.
There is no need to push this to QA or Production immediately, as these environments already have Serval support enabled in their respective environment variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2252)
> Enable Serval support across all environments

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
* Format audio source file when retrieving the duration
1. Upload a valid scripture audio and timing data to a book/chapter
2. Save the data
3. Edit the book/chapter from the overview or community checking screen
4. Upload another timing data file (not audio)
5. Save the data
6. Play the chapter audio in the community checking app and observe it functions as normal
The bug caused the timing data not to get parsed because `getDuration` returned zero when fetching an already uploaded audio file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2245)
> SF-2412 Overwriting audio timing data doesn't parse correctly

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
Phrase level timing files have multiple timing entries for a verse. When using a phrase level timing file, we do not currently support phrase level highlight, but we do need to account for phrases when a user clicks the skip next or skip previous buttons.
This PR handles the case where a user clicks skip next or skip previous. The first phrase of the next or previous verse will be used to update the current time of the audio player.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2228)
> SF-2403 Fix skip previous or next to skip past phrases

- src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
- src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
* synchronize note tag create resolve property
* add logic to detect if a user is allowed to resolve a thread
* hide the resolve note trigger when user is not allowed to resolve
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2241)
> SF-2411 Restrict resolve option on dialog when restricted tags used

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- src/SIL.XForge.Scripture/Controllers/MachineApiV2Controller.cs
- src/SIL.XForge.Scripture/Services/IMachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiV2ControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
It was decided that when translation generation failed (which may be more often at the beginning) we should show minimal details of the failure to the user. When a user decides to contact our team, if they included a screenshot, the details of the build will be easily included and we will be able to more quickly troubleshoot the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2249)
> SF-2425 Show user pretranslation failure info

- src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
The legacy form field appearance is the default, but is no longer supported in newer versions of Material. This PR sets the new default to the "outline" style.
Here's what each appearance looks like, taken from https://v14.material.angular.io/components/form-field/examples
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2260)
> Remove use of Material legacy form fields

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR upgrades mat-tabs from legacy to the Angular Material mdc version.  Used `ng generate @angular/material:mdc-migration` as a starting point.
Some differences:
- Header labels stretch by default to fill the container's width. This can be turned off by setting the `<mat-tab-group>` input `[mat-stretch-tabs]="false"` when desired.
- I added this attribute in some places to retain the old look. 
- The border under the tab headers is gone.
- I did not add it back. Should we custom style this to add back the header bottom border?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2259)
> SF-2375 Upgrade legacy mat-tabs

- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR upgrades mat-snackbar from legacy to the Angular Material mdc version. Used `ng generate @angular/material:mdc-migration` as a starting point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2265)
> SF-2373 Upgrade legacy mat-snackbar

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts
The ActivatedProjectService relies on the ActiveProjectIdService to emit the projectId from the router snapshot. When a new ID is available, it is emitted and the ActivatedProjectService will fetch the project and make it available. Unfortunately, this occurs when using the old style email specific share links, resulting in an error before the user can successfully join the project.
This PR accomplishes the following:
- detects the presence of the sharing query parameter in the URL and ignores the router change
- adds tests for the ActiveProjectIdService
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2271)
> SF-2433 Prevent error when joining a project with email specific link

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
I think there may still be some edge cases that aren't handled quite correctly, but I can't find any that I can consistently reproduce. And there were already some issues before this change (more pronounced, I think).
- Fixes editor width and height
- Removes JS calculation of editor height, instead using CSS for layout
- Removes some use of @angular/flex-layout in the process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2273)
> SF-2432 Style editor height with CSS instead of JS

- src/SIL.XForge.Scripture/ClientApp/src/_text.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
Letter spacing should generally be avoided for some scripts: https://rtlstyling.com/posts/rtl-styling#1.-letter-spacing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2269)
> Remove all use of letter spacing

- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR upgrades mat-radio-group from legacy to the Angular Material mdc version. Used `ng generate @angular/material:mdc-migration` as a starting point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2267)
> SF-2370 Upgrade legacy mat-radio

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
See QA to see what the current error is: https://qa.scriptureforge.org/projects
```
Uncaught TypeError: Cannot set property ɵfac of class extends Ws{constructor(i){super(),this.bugsnagClient=i||Lc()._client}handleError(i){const n=this.bugsnagC...<omitted>...}} which has only a getter
at <static_initializer> (exception-handling-service.ts:279:4)
at exception-handling-service.ts:33:47
at 8227 (exception-handling-service.ts:33:39)
at t (bootstrap:19:1)
at index.js:55:1
at f (jsonp chunk loading:34:1)
at main.adfd930d5184b905.js:1:83
```
It only happens in Angular production builds. In my testing, error reporting still works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xfor …
> SF-2335b Remove @bugsnag/plugin-angular to fix Angular prod build

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
A commit was made which accidentally focused the frontend tests to just run one test.
This PR changes the `fit` to `it`, and fixes three broken tests that the `fit` skipped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2279)
> Fix broken draft generation step tests

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
This is a fix for the same problem as #2280.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2281)
> Fix layout of editors when only one editor is shown

- src/RealtimeServer/scriptureforge/models/sf-project-test-data.ts
- src/RealtimeServer/scriptureforge/models/translate-config.ts
- src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
- src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- src/SIL.XForge.Scripture/Models/DraftConfig.cs
- src/SIL.XForge.Scripture/Models/SFProjectSettings.cs
- src/SIL.XForge.Scripture/Services/PreTranslationService.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- src/SIL.XForge.Scripture/Services/SFScriptureText.cs
- src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
- test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs
We currently only send verse data to Serval. We have been requested to add support for translating headings as well, but given Serval's current constraints, we can only provide this when the source and target structure matches exactly.
This PR adds a checkbox to Settings that allows sending all segments to Serval, and when the pre-translation is complete, will provide pre-translation drafting of those headings and verse paragraphs and prose sections.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2251)
> SF-2410 Allow user selection of sending just verse segments or all segments

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR upgrades `mat-progress-bar` from legacy to the Angular Material mdc version. Used `ng generate @angular/material:mdc-migration` as a starting point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2284)
> SF-2368 Upgrade legacy mat-progress-bar

- mongodb/Comments/find_commenters.mongodb
This query will need further refinement, but right now there aren't many comments created by the sf_commenter role, so it doesn't make much sense to work on it much more at this time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2288)
> Add Mongo query for comments created by sf_commenter role

- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
TC69 is run as part of a full regression test on QA, but unfortunately an error message would appear sometimes when going offline as part of the test steps. This was caused most likely from an error that was thrown in the sync progress component. Since the error is not helpful and the sync proceeds to completion anyway, I've chosen to swallow the error in the sync progress component.
I don't believe it will be beneficial to send this to testing. We will know if this works once we move this onto QA and TC69 is no longer flaky.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2285)
> SF-2347 Do not show error when getting project role times out

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2289)
> Update notices over editor to use app-notice component

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts
The logic to save a note thread was both in the editor component and the biblical terms component. This PR adds the logic to resolve threads in the biblical terms component. It is possible that the logic should be consolidated, but there are enough subtleties between the two components that it might not be a simple solution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2274)
> SF-2434 Allow resolving note threads for biblical terms

- src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
When a user deletes a book in PT, the project component is not made aware and tries to navigate to the delete book. This causes an infinite redirect when the editor component redirects back to the project component when it realizes that the book does not exist. This PR updates the project component to navigate to a book only if the book exists on the project.
To reproduce this issue easily, update the SFProjectUserConfig doc entry in mongo so the selectedBookNum is a book that does not exist on the project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2293)
> SF-2384 Fix flicker after project book is deleted

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
The ScriptureAudioPlayerComponent's verse label is inconsistent with the highlightActiveVerse functionality of the CheckingTextComponent in two scenarios:
1. If we are after the end of the timing data ScriptureAudioPlayerComponent will display that we are on verse 1 where CheckingTextComponent highlights the last verse in the timing data.
2. If we are in a gap between two entries in the timing data ScriptureAudioPlayerComponent will display that we are on verse 1 where CheckingTextComponent highlights the next verse.
This PR updates the ScriptureAudioPlayerComponent verse label to behave the same way as CheckingTextComponent's verse highlighting in those cases. 
Issue Replication Steps:
- Navigate to Community Checking > Manage Questions
- Add chapter audio using this audio file and this …
> SF-2430 Make verse label consistent with highlighted verse

- scripts/db_tools/parse-version.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
- src/SIL.XForge.Scripture/Models/FeatureFlags.cs
- src/SIL.XForge.Scripture/Models/ServalCorpus.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/PreTranslationService.cs
- src/SIL.XForge.Scripture/appsettings.json
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
This PR adds support for uploading data to Serval as a Paratext zip file.
Since Serval support has already gone live, this format will only be used for draft generation if:
* The **UploadParatextZipForPreTranslation** feature flag is enabled on the backend
* A draft has not been previously generated for the project
*This is to ensure that any new drafts will not wildly vary from previous drafts, until the feature is stable and formally released across Serval and Scripture Forge.*
When these two conditions are met, and a pre-translation build is started:
1. A sync is performed for the source & target to ensure the disk contains the most up to date version of the project.
2. The contents of the Paratext project directory are zipped into a memory stream.
3. This stream is uploaded to Serval. …
> SF-2310 Add Paratext zip file support for Serval

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
The PR #2273 changed the target to be on the left by default instead of the right. This PR reverses this by mapping the inverse of `isTargetTextRight` to the CSS class reverse-columns.
**Note:** The property `sf_project_user_config.isTargetTextRight` is set to `true` by default when this document is created (see SFProjectUserConfig.cs).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2295)
> FIX: Revert Target and Source flipped in SF-2432

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
**Problem Overview**
Paratext 7 Resources store the language definition in the file ldml.xml, while Paratext 8+ store this data in the file [lang_id].ldml. One such project on prod and dev is DYU, or just in dev (i.e. is correct in prod), NNRV.
When ParatextData reads the installed resource in Scripture Forge, it shows the Resources language as being the default, English.
This was previously not much of a problem for Resources in Scripture Forge, but as we send this language code to Serval, we need to ensure that this code is correct so that pre-translation drafting can occur.
**Solution Overview**
The Paratext migrators are quite complex, and locked in the Paratext source code (i.e. they are not in ParatextData.dll). Because of this, I have implemented the minimum required migrator to …
> SF-2463 Fix Paratext 7 Resources being marked as English

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ServalApiExceptions.cs
When a build is already in progress, and the user triggers another (usually due to connectivity issues, multiple windows open, or multiple users attempting to start a build at the same time), an error was reported to the user.
This PR resolves that by not reporting that specific error to the user. This means that the progress of the already started build will be displayed to the user, and upon completion of that build, they will be able to access the draft when that build is complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2298)
> SF-2462 Stop reporting pre-translation build in progress errors

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Two critical bugs have been found in SF-2310 (#2286):
* When the `UploadParatextZipForPreTranslation` feature flag is `true`, books selected are not specified in the Serval Build Configuration (d047c5d7dca924f518130343697870d56785ffc7)
* When the `UploadParatextZipForPreTranslation` feature flag is `false`, blanks segments in target texts are not sent to Serval - this results in no pre-translation being generated (31f154f944b89ad73771a663d1a86d0e563fac37)
As #2286 is currently in [SF-QAv418](https://github.com/sillsdev/web-xforge/releases/tag/SF-QAv418), this PR should be treated as a blocker to this version going to `sf-live`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/we …
> SF-2470 Fix incorrect books sent to Serval for Pre-Translation

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
When a user imports questions, one of the first steps is to check for duplicates. Transcelerator questions have an ID that is unique to that verse, but questions in a spreadsheet do not, so we just check if the text of the question is identical to a question already in the project. This involves `(existing number of questions) * (number of questions selected to be imported)` comparisons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2301)
> Improve question import speed when questions have already been imported

- .vscode/launch.json
- .vscode/tasks.json
- scripts/db_tools/manage-db.ts
- scripts/db_tools/trigger-resources-need-sync.ts
- src/Migrations/WhitespaceRestoreMigration/Migrator.cs
- src/Migrations/WhitespaceRestoreMigration/Program.cs
- src/Migrations/WhitespaceRestoreMigration/Properties/launchSettings.json
- src/Migrations/WhitespaceRestoreMigration/Startup.cs
- src/Migrations/WhitespaceRestoreMigration/WhitespaceRestoreMigration.csproj
- src/Migrations/WhitespaceRestoreMigration/WhitespaceRestoreMigration.sln
- src/Migrations/WhitespaceRestoreMigration/build-production
- src/Migrations/WhitespaceRestoreMigration/process-by-chunk
- src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Getting book USX from Paratext and then using XDocument.Parse()
produces an XDocument for further processing. Sometimes important
whitespace can be lost when doing this, such as the space between
`<char>In</char> <char>the</char>`.
Manually pre-process the whitespace, and ask XDocument.Parse() to
preserve the whitespace it is given.
Before this change:
With this change:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1764)
> SF-1444 Preserve important whitespace when get text

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
I couldn't figure out why my machine wouldn't let me record, despite having given permission. It just kept saying permission denied, which I figured was related to being on localhost (an insecure origin).
Actually I just didn't have a mic connected. Probably not a common situation, but even I couldn't figure that out without stepping through the debugger. :facepalm:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2304)
> SF-2469 Inform user when no mic is found

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
When searching for projects by short name, there are often multiple results, and you can't tell which one is the correct one because the short name isn't shown.
Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2318)
> Show project short name on system admin projects page

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Remove these two notices as well as another variation of the text
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2310)
> SF-2466 Remove warnings against selecting training data for NLLB languages

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
* Give direction preference based on text setting for RTL
* Flip direction if suggestions fit better in the other direction
* Force a CSS word break if needed
* Reset left/right/top properties when no selection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2312)
> SF-2355 Translation Suggestions don't align well in RTL

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
- src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
**Problem Synopsis**
Currently, Scripture Forge shows a note's owner as the note author. This is problematic for notes created in Paratext, as `Note.OwnerRef` will be the user who synced the note, not the user who created the note.
**Solution**
Re-implement `<app-owner>` in the Note Dialog Component, and calculate the user name.
**User Name Calculation**
The name calculation logic in `NoteDialogComponent.getNoteUserNameAsync()` could be represented as these rules (matching the new unit tests):
1. **If** the note was created by the currently logged in user **Then** Show "Me"
2. **If** the note has not been synced **Then** Show the SF note owner's name
3. **If** the currently logged in user is a checking user **Then** Show the SF note owner's name
4. **If** the note was created in Scripture …
> SF-2486 Show the correct username for notes created in Paratext

- mongodb/Projects/SyncFailureCause.mongodb
I fairly frequently need to find why a particular project failed to sync. This usually involves looking at the sync metrics to see what errors have happened, and then (sometimes) looking at the project on disk. This requires finding the Paratext project ID. I also want to get the stack trace. This script attempts to do all of this at once with just a project short name.
Here is some example output:
```
Project short name: <redacted>
Project Id: 65b1cd4b295ef91ee7b15fdb
Paratext project ID: a0fe9c0653f9f776081fc0d8856dd2a16631e0e8
The following error occurred 3 time(s):
System.InvalidOperationException: Sequence contains more than one matching element
at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 …
```
> Add query to find sync errors for a project

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-data-doc.ts
- src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
When uploading an audio file that was greater than 100mb, there was a failure on QA and live because cloudflare has a restriction of 100mb for file uploads. This PR changes the file size limit from 300mb to 100mb and shows an error in the audio upload dialog when a user tries to upload a file greater than 100mb.
In addition, this PR changes the behaviour of the audio upload dialog to show a failure when uploading is unsuccessful, whereas previously a failure was caught silently and the user was not made aware.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2325)
> SF-2437 Restrict audio upload to 95MB

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
No error is shown for the user invite email field if the send button is clicked while the email field is empty.
This PR marks the field as required.
Replication Steps:
- Navigate to users screen after logged In as project admin
- Click on the Send button under "Send a link"
- Note an error displayed only for the Invitation language field not for email field
Acceptance Tests
- Navigate to users screen after logged In as project admin
- Click on the Send button under "Send a link"
- Note an error under both the email and the invitation language fields
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2322)
> SF-1581 No error on empty email field when sending invite

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts
The SF editor interface prevents editing a chapter if:
* The USFM is invalid
* Editing the project is disabled
* The ops are corrupted
* The project is not in sync
* The user does not have project level edit permission
* The user does not have chapter level edit permission
This PR updates the draft preview screen to use these same checks.
As the draft viewer will be removed in the next few months, this PR does not display any warning messages about why the user cannot see the apply draft button (they could view these on the editor).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2338)
> SF-2524 Prevent applying drafts when editing is not permitted

- src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR fixes the language tags for alternate source and alternate training sources for back translations by updating these values after the initial sync of the alternate source or alternate training source.
This bug occurred because the Paratext API does not return the language tag for back translation projects, and so to retrieve this value the project must first be synced with Scripture Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2326)
> SF-2493 Fix training source language for back translations

- src/SIL.XForge.Scripture/appsettings.json
This PR changes the default feature flag configuration to disable In-Process Machine support, to reflect that In-Process Machine should be off permanently now for every environment.
A PR will follow later that complete removes code that references in the In-Process machine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2345)
> SF-2550 Disable In-Process Machine across all environments

- src/SIL.XForge.Scripture/appsettings.json
This is a hotfix against sf-live.
(cherry picked from commit db1dea23e15e14893c82183f6c545790ed5f42f9)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2348)
> SF-2550 Disable In-Process Machine across all environments (#2345)

- src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs
- src/SIL.XForge/Realtime/ExistingNodeJSProcessFactory.cs
- src/SIL.XForge/Realtime/RealtimeServer.cs
- src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
- src/SIL.XForge/SIL.XForge.csproj
This PR downgrades Jering to 6.3.1, which was the previous stable version (prior to #2292).
QA is currently experiencing unusual instability with the Realtime server, so this PR is to help determine if that instability is caused by the Jering upgrade to 7.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2351)
> Downgrade Jering to 6.3.1

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR enables support for all Paratext users to view chapter history, matching the behavior of Paratext.
SF Users (Commenters and Viewers) still do not have access to view the chapter history.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2349)
> SF-2568 Allow all PT users to view chapter history

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR fixes two issues discovered with SF's sending and specifying of alternate training sources to Serval:
- When the "use alternate training source" checkbox is checked but no source is selected, the `train_on` parameter is misconfigured, resulting in an error on Serval.
- When an alternate training source is configured, then disabled, the corpus remains on Serval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2344)
> SF-2563 Fix issues with Serval Alternate Training Sources

- src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
- src/SIL.XForge/Realtime/RichText/Delta.cs
- test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
- test/SIL.XForge.Scripture.Tests/Services/DeltaUsxTestExtensions.cs
- test: DeltaUsxMapper: Broaden finding of sample sfm files
- test: DeltaUsxMapper: split out roundtrip tester
- doc: Add comments
- test: add more roundtrip tests
- SF-2485 Handle table followed by char formatting
I intend that these commits will all be squashed together when merged. But it may help to review them separately.
Some more problem explanation is in the commit message at the end.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2339)
> SF-2485 Handle table followed by char formatting

- src/RealtimeServer/common/index.ts
- src/SIL.XForge/Realtime/DeleteOnSuccessAttribute.cs
- src/SIL.XForge/Realtime/IRealtimeServer.cs
- src/SIL.XForge/Realtime/RealtimeServer.cs
- src/SIL.XForge/Realtime/RealtimeService.cs
- test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
- test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
Implements a simple scheduled check to the realtime server to see if the server is not null and attempts to restart it if required.
**Acceptance tests**
1. Start a sync
2. Kill the realtime server node process
3. Observe SF displays the broken offline icon on the avatar
4. Wait for one minute
5. Observe SF has come back online
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2343)
> SF-1622 Restart Realtime Server

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/MutexAttribute.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
This PR throttles Hangfire jobs to run one at a time, per job type.
These job types are:
* Syncs
* Draft Builds
* Updating of Translation Sources
This was achieved by modifying the Mutex to make the `resource` parameter optional. When `resource` is not configured, the method name is used as the mutex key.
It was determined to allow this approach rather than allow just one job at a time for any job type to stop any potential dependency deadlocks (i.e. when a sync triggers a build, and that build may require a sync, etc). In addition, the three job types are different enough that I do not that that a Resource conflict is likely due to concurrent access, as the shared surface is the MongoDB, the Realtime server, and Paratext Settings.
- - - …
> SF-2551 Throttle Syncs to one at a time

- tools/ServalDownloader/Program.cs
- tools/ServalDownloader/ServalDownloader.csproj
- tools/ServalDownloader/ServalDownloader.sln
- tools/ServalDownloader/appsettings.json
I have created a small tool to download all files from Serval for a translation engine. This is useful in debugging what was sent to Serval.
To run: `dotnet run 65d5058f352b5d93e8a2ac7c` (substituting your translation engine id)
I have only tested this on Windows. It should load the Serval values used by Scripture Forge from the user secrets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2352)
> Add tool to download all files from Serval

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- src/SIL.XForge.Scripture/Models/LanguageDto.cs
- src/SIL.XForge.Scripture/Models/MachineApi.cs
- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/IMachineApiService.cs
- src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR adds a new API endpoint that queries Serval to determine if a language is supported by Serval or not.
When there are connection issues, fallback to the NLLB database in SF occurs. This database has not been removed, because it is still used to display the list of supported languages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2342)
> SF-2464 Use Serval to check whether a language code is supported

- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
When the Serval client credentials change, any actions for SMT or Pre-Translation engines return 403 errors. This PR allows the pre-translation projects to be recreated when this occurs, and provides better error help in the editor, prompting the user to rebuild the translation engine (which will fix these issues).
It was also discovered the HTTP POST methods in MVC Controllers return a 400 error when `Forbid()` is returned (which is supposed to return a 403 error). This bug has been fixed to ensure the frontend has an accurate error code.
As this bug currently affects QA, it should be deployed there for testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2357)
> SF-2582 Improve recoverability when Serval client credentials change

- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR allows proper error handling for invalid reattached notes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2334)
> SF-2527 Support for invalid reattached notes

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.scss
Here is how it looks after the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2362)
> SF-2586 Fix biblical terms dialog text overlap

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR updates mat-checkbox from legacy to the MDC version.
Styling changes were done to keep the style in line with before this change however there are some slight changes e.g. check-marks are now black instead of white for better contrast and letter-spacing on labels is slightly larger.
Some styling was also removed as it was no longer required with the new version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2317)
> SF-2360 Update Material legacy checkbox

- Directory.Build.props
I couldn't find a way to drop the revision number from the product version in our build steps, so I do a split on the product version. If there is a better way, I am happy to learn.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2361)
> SF-2480 Remove revision number from product version

- src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.scss
When the user has a lot of projects, it's not possible to scroll down to the connect project option.
See this screenshot, where I can't scroll down to the connect project option.
This change has not been tested, and was made from my phone during the conference. If you are going to review the change, please test it and make sure it actually fixes the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2371)
> Attempt to fix project selector height on mobile

- src/SIL.XForge/Realtime/RichText/Delta.cs
- test/SIL.XForge.Tests/Realtime/RichText/DeltaTests.cs
This PR fixes a bug where unnecessary ops that modify the `cid` are created when those ops are preceded by ops that have no properties.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2369)
> SF-2598 Stop unnecessary ops created on sync

- mongodb/Projects/ProjectFontUsage.mongodb
This font query is used to see what fonts are in use on live.
Analyzing the use of fonts is done in a spreadsheet, and it's a lot easier to move data from the query to a spreadsheet when cells are separated by tabs, rather than commas. Also, having the font name before the count makes it easier to process the data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2377)
> Update font use query to make charting font use easier

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab/tab-body/tab-body.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Fixed issues:
- Tab body was not always full screen height.
- For short chapters, the editor did not extend all the way down to the biblical terms splitter.
- Editor was scrolling to top after saving a note.
- Fixed editor notices to remain visible at top of tab.
Source editor should scroll sync to target verse containing the cursor, and note fab button should still track and stay within editor bounds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2380)
> SF-2635 Fix editor and biblical terms container height UI glitches

- src/RealtimeServer/scriptureforge/models/sf-project-user-config-test-data.ts
- src/RealtimeServer/scriptureforge/services/biblical-term-service.spec.ts
- src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
- src/RealtimeServer/scriptureforge/services/question-service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
Currently, adding new properties to the `SFProjectUserConfig` interface causes existing tests to need to be updated in order to add the property to their object initializations.
This PR creates a function that tests can call to retrieve an `SFProjectUserConfig` object with optional overrides.  Tests that use this function will not need to be updated when new, unrelated, properties are added to the the `SFProjectUserConfig` interface.
Also, this PR updates existing tests to use this function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2379)
> Create overridable default SFProjectUserConfig for tests

- src/RealtimeServer/common/services/doc-service.ts
- src/RealtimeServer/scriptureforge/models/note-thread.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This PR:
* Adds indices that match the querying patterns of the `note_threads` collection by `sf-project.service.ts`. This will speed up the realtime server's access of notes.
**Note:** Indexes cannot be created on existing object stores during a version change transaction, so the indexes will only be created locally on log out/log on.
* Optimizes of `ParatextSyncRunner.GetAndUpdateParatextBooksAndNotes()` to only update notes that are editable. This can speed up the pre-PT sync phase for projects with little or no notes created in SF.
* Optimizes retrieval of chapter deltas from the USFM on disk to only be loaded once per book (the conversion from USFM to USX to Deltas is expensive). This is a minor performance improvement, but one that results in a reasonable code clean up.
* Optimizes …
> SF-2583 Improve Note Speed

- .github/workflows/release-to-qa.yml
I want this to run every day, before the testers start working, except for Tuesday _in UTC_.
@Nateowami I think this will correct the schedule.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2382)
> ci: release-to-qa: run every day except Tuesday

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.spec.ts
This PR cleans up the warnings that flood the console when running unit tests via `npm test`. Removing these warnings makes it easier to find faulty code when running unit tests.
The changes in this PR include:
* Resolved warning: 'Detected a matBadge on an "aria-hidden" "mat-icon". Consider setting aria-hidden="false" in order to surface the information assistive technology.'
* Resolved warning: '%c Missing translation for 'en.tab_group_header.no_tabs_available''
* Removed the no longer needed diagnostic message 'Translated segment, length: 8, time: 0ms'
* Fixed warning 'Spec 'CheckingOverviewComponent Chapter Audio does not try to delete chapter audio if offline' has no expectations.'
* Fixed warning 'Spec 'RolesAndPermissionsComponent saves correct permissions without changing …
> Fix warnings thrown when running unit tests

- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
This PR fixes a warning that appears whenever the frontend is run (i.e. via `ng serve`) warning that the "The same color styles are generated multiple times."
This warning appears to be due to the order we are including the material styles. Although these are not supposed to overlap, the button and legacy-button themes appear to conflict over the density (which is not defined for the legacy button, but is defined for the button (see the description of this change in https://material.angular.io/guide/mdc-migration#theming)
Change the order of loading appears to fix this, but I am not entirely sure why (it appears to be a bug with the angular/material library rather than our code). No difference of display was noticed for buttons or legacy buttons after this change was made.
**Warning …
> Fix density styles warnings when running the front end

- src/SIL.XForge.Scripture/Models/SyncConfig.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- src/SIL.XForge.Scripture/Services/SyncService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
This PR:
* Stops alternate training sources from being deleted on SMT builds
* Fixes crashes caused by missing alternate training corpora and files
* Enqueues the SMT build job separately to the sync job
I also took the opportunity to update sync service and sync config to use .NET 8.0 features.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2386)
> SF-2647 Run SMT engine builds in a separate job to the project sync

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
When pasting text in the target editor in chrome (no issue in firefox), the editor would jump the scroll to the top.  This PR fixes this issue as well as adds tests to ensure the note FAB is tracking the selected verse while staying within the visible scroll area.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2390)
> SF-2643 Fix editor jump to top on paste

- src/SIL.XForge.Scripture/appsettings.Development.json
- src/SIL.XForge.Scripture/appsettings.Staging.json
- src/SIL.XForge.Scripture/appsettings.Testing.json
This PR updates SF QA to use the Serval Production server and authentication configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2396)
> Change QA to use Serval Production

- src/SIL.XForge.Scripture/ClientApp/src/_text.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/index.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.ts
This loads fonts from fonts.languagetechnology.org, based on the font specified on the Paratext project. I only added support for the most used fonts on Scripture Forge, as I want to keep this change small and make sure it works well before expanding the list too much.
Things I did not address:
- Preview draft page
- Question dialog
- Text chooser dialog
Initially I was going to add support for them, but they were going to take slightly more work, and I wanted to keep this change as small as possible, so I can easily address any changes that need to be made, without it being held up. We can follow up this PR with fixing those other components.
- - - …
> SF-2636 Add preliminary font support

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.spec.ts
This  PR fixes a recently introduced warning that appears when running the Angular unit tests:
```
WARN: 'No font definition for zyz123', [[[]]]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2400)
> Fix no font definition warning in test

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ServalApiExceptions.cs
With the rotation of the Serval QA credentials, it was noted that Serval returns 401 errors with the old credentials, which are displayed as 500 errors on the Angular frontend.
This PR causes these errors to be rethrown as `ForbiddenException`, which is emitted as a HTTP 403 error to the Angular frontend, and so handled in a more elegant way by the frontend.
This PR does not require full testing, but can be recreated by running this PR with the previous (now out of date) Serval QA credentials.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2397)
> Emit 401 errors from Serval as 403 errors on the Machine API

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
My primary display has display scaling turned on to 125% (I am running Windows 11). Because of this, some unit tests that are measuring pixel calculations with fail often (but not consistently) with errors like:
```
Error: Expected 262.45001220703125 to equal 262.4624938964844.
```
and:
```
Error: Expected 373.8000183105469 to equal 373.8000030517578.
```
To resolve this, this PR updates position checks to round up to same whole number, as within one pixel should be sufficient accuracy for positioning elements.
Note: These tests did not fail on my laptop's external display, which does not have display scaling enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2 …
> Fix Angular test failures when display scaling is enabled

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
This PR fixes the following errors displayed in the console while running tests:
```
ERROR: 'NG0304: 'transloco' is not a known element (used in the 'EditorDraftComponent' component template):
1. If 'transloco' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.', [[[...]]]
```
```
ERROR: 'NG0303: Can't bind to 'params' since it isn't a known property of 'transloco' (used in the 'EditorDraftComponent' component template).                                                                           
1. If 'transloco' is an Angular component and it has the 'params' input, then verify that it is a part of an @NgModule where this component is declared. …
```
> Fix transloco test errors in EditorDraftComponent

- mongodb/SyncMetrics/FindCurrentSyncErrors.mongodb
This query is an attempt to answer the question "What errors have caused the most projects to fail their most recent sync?" It does this by looking up the most recent sync failure for each project that has failed its last sync, then finding the most recent sync metrics for that project. Then it groups by error message, which somewhat works to find common errors, though sometimes the same error shows up with a different stack trace and doesn't get grouped properly. This is considered acceptable because we're just looking for most common errors.
This query is inefficient and slow to run.
The current top result, with a count of 17, is this:
```
System.Net.Http.HttpRequestException: HTTP Request error:
POST https://registry.paratext.org/api8/token
Response:
StatusCode: 429, ReasonPhrase: 'Too …
```
> Add Mongo query for errors that caused projects to fail last sync

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
A Graphite font, when used in a browser engine that doesn't support it, renders completely wrong. It turns out that for Urdu, using the Arabic script is significantly better, even though it's less readable than the Awami Nastaliq font. I've added it as a fallback in browsers that don't support Graphite.
I've added a story that shows all the fonts we support. This change can be tested by opening the story in both Chrome and Firefox, and using the dev tools to check that the proper font was used in each browser.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2406)
> SF-2636b Fallback from Awami to Scheherazade when Graphite unsupported

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
This is a followup to the recently-merged font support: https://github.com/sillsdev/web-xforge/pull/2346
The main part of this change is just passing around the project doc to components that are going to render a chapter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2398)
> SF-2662 Use project-specified font in question dialog

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/base-services/tab-menu.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.types.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab/tab.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
Add drag/drop reordering and moving of tabs between source/target tab groups.  Main source and target project tabs should remain fixed in place as first item in their respective groups.
This PR is currently based off `feature/sf-2439-editor-tabs`, which is not yet merged into master.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2363)
> SF-2528 Editor tabs drag/drop reorder

- src/SIL.XForge.Scripture/Pages/Index.cshtml
Linking to our help site isn't really ideal, but I think it's better than our extremely outdated learn more page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2410)
> Link learn more button on home page to help site

- .github/workflows/build-and-test.yml
It's very easy to accidentally include `fdescribe` and `fit` when opening a PR. This has happened multiple times, most recently in #2373 (which actually has an approved review, and I was about to merge).
This PR updates the build workflow to grep for `fdescribe(` and `fit(` across all `.spec.ts` files, and fails the build if they are present.
It's also possible to accidentally include `xdescribe` and `xit`, but sometimes those will be intentional, and generally it's only a few tests that would be skipped over.
This PR changes a `describe` to `fdescribe` to demonstrate that the change works. Therefore, it deliberately fails the build. After being reviewed, I will revert that one change so it can be merged.
- - - …
> Update build-and-test to prevent merging fdescribe and fit

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
This property was removed from `checking-question.component.ts` in #2374
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2418)
> Fix test warnings about projectUserConfigDoc not being needed

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
It's easy to forget when you are logged into the live site as an admin, since we often have SF opened in development mode, and it looks identical. This change adds a warning in the banner that is only shown to admins on the live site.
I considered having it be shown on QA as well, and weighed these factors:
- The purpose of QA is to be a simulation of what live does.
- The purpose of this features is to warn admins that they are on the live site, so actions taken have real-world implications.
I believe the second factor weighs a lot more heavily, and therefore only enabled this for live.
Here's what it looks like:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2419) …
> Add warning for admins on live site

- src/SIL.XForge.Scripture/Services/InternetSharedRepositorySourceProvider.cs
- src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
- src/SIL.XForge.Scripture/appsettings.json
- test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
- test/SIL.XForge.Scripture.Tests/Services/JwtInternetSharedRepositorySourceTests.cs
The registry seems to be slow a lot of the time, but not all of the time. We don't have concrete data. This PR adds logging regarding response times so we can analyze whether this is the cause of our problems, and determine if/when the problem is actually fixed.
This is not an ideal solution, but it's quick.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2423)
> Log response times from Paratext registry

- tools/RepoInfo/Program.cs
- tools/RepoInfo/RepoInfo.csproj
This PR fixes the repoinfo tool to work correctly on .NET 8.0, and also makes some minor code and comment clean up suggested by Resharper.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2411)
> Fix the repository info tool for .NET 8.0 and ParatextData 9.5

- scripts/db_tools/db-token-info.ts
- scripts/db_tools/find-problem-cids.ts
- scripts/db_tools/manage-db.ts
- scripts/db_tools/manipulate-sharedb.ts
- scripts/db_tools/package-lock.json
- scripts/db_tools/package.json
- scripts/db_tools/show-projects.ts
- scripts/db_tools/trigger-resources-need-sync.ts
- scripts/db_tools/validate-data.ts
- src/Help/UpdateHelp/UpdateHelp.csproj
- src/RealtimeServer/package-lock.json
- src/RealtimeServer/scriptureforge/migrator.ts
- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
- src/SIL.XForge/SIL.XForge.csproj
- test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
- test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
This PR contains the following important updates:
**1. Update C# MongoDB.Driver from 2.18.0 to 2.24.0**
* Release Notes: https://www.mongodb.com/docs/drivers/csharp/current/whats-new/
* See https://github.com/sillsdev/web-xforge/security/dependabot/70
* This version requires MongoDB 3.6 or higher.
* A major change in this update is the use of a new LINQ provider. Tests made when SIL.Machine.WebAPI was a dependency resulted in major issues, however the removal of that dependency meant no issues in my testing of the surface, particularly user actions, such as invitations, syncing, connecting to projects, and starting Serval builds.
**2. Update Hangfire from 1.7.32 to 1.8.12**
* Release Notes: https://github.com/HangfireIO/Hangfire/releases
* Major changes in this release include an updated …
> SF-2588 Update MongoDB drivers and other dependencies

- tools/ServalDownloader/Program.cs
- tools/ServalDownloader/ServalDownloader.csproj
This PR adds support for properly downloading Paratext zip files from Serval to the Serval Downloader tool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2402)
> Add support for Paratext Zip files to the Serval Downloader tool

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
This PR adds a message to the draft generation steps that lists books not found in the target text, but which are in the source text (and so the user would expect to be able to translate them).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2370)
> SF-2581 Add missing target books message when selecting drafting books

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.stories.ts
This story keeps creating changes in the Chromatic diff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2431)
> Disable Chromatic snapshot of ButtonWithIcon story

- scripts/monitor_pt_registry.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2428)
> Add script to monitor Paratext registry server

- scripts/build-and-ship
This PR adds support for the webhook secret to the build script.
Before this script is merged, `SERVAL_WEBHOOK_SECRET` will need to be set up in TeamCity (I can supply the QA and Prod secrets via PM when this needs to be done).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2420)
> Add webhook secret to build script

- .github/workflows/build-and-test.yml
This PR updates the Codecov GHA to use the token which is configured in GitHub Settings.
The success of this PR is determined by the presence of the comment by Codecov below.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2436)
> Update Codecov GHA to use token

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
I saw a weird error message while testing #2438 locally, and realized some extra `$` characters are included a few places.
(The error was supposed to happen; nothing was misbehaving)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2440)
> Remove extraneous $ from C# interpolated strings

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/cache-service/cache-service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/cache-service/cache-service.ts
This PR fixes 403 and 404 errors that have occurred in the Serval Administration area on production.
The 404 errors are caused by a project not being on disk, because it was never synced successfully in the first place. When this state occurs, a more informative error is displayed to the Serval Administrator.
The 403 errors are caused the the cache service attempting to background cache texts that the Serval Administrator does not have access to (and does not need access to). To resolve this, a permission check is performed before the cache service attempts to retrieve a text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2437)
> SF-2719 Fix 403 and 404 errors in the Serval Admin area

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2430)
> SF-2710 Clean up i18n of book-multi-select

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
* Move scripture audio player into its own split area
* Show audio player from bottom when text is visible and top when not visible
* Hide answer panel when audio player is visible
* Stop and hide audio when changing questions
* Change toggle audio behavior to close the player rather than pause
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2421)
> SF-2657 Chapter covered when audio is playing

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change is in conjunction with #2442, which will fetch only the generated draft from Serval and therefore overwrite any content already in the chapter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2444)
> SF-2445 Confirm before overwriting a chapter when adding draft

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/PreTranslationService.cs
- test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
This PR adjusts the pre-translations we retrieve from Serval to only include pre-translated text, not any of the existing scripture text sent to Serval.
It should not be merged into master before SF-2442 and SF-2443 are merged into master. These are required dependencies for this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2442)
> SF-2721 Get only pre-translated text from Serval

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
This PR updates zone.js from 0.13.3 to 0.14.5, a pre-requisite for Angular 17 and 18.
I have tested this update locally, and it performs satisfactorily.
No other changes are required for this update, as we were already correctly importing `zone.js` and `zone.js/testing`, as per the breaking change in 0.14.0.
Changelog: https://github.com/angular/angular/blob/main/packages/zone.js/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2446)
> SF-2717 Update zone.js to 0.14.5

- .github/workflows/build-and-test.yml
- .github/workflows/chromatic.yml
- .github/workflows/ci-lint-prettier.yml
- .github/workflows/ci-production-build.yml
- deploy/dependencies.yml
- src/SIL.XForge.Scripture/Dockerfile
This PR updates our workflows and Dockerfile to support Node v18.
No other code changes are required for support for Node v18.
A successful PR is determined by all of the CodeQL workflows passing. I have tested the Dockerfile.
Also, the Chromatic action's latest version (11.3.2) is faulty. To resolve this issue, I have fixed chromaui/action to version 11.3.0.
**Upgrading Node**
To upgrade your node version in your developer VM run:
```sh
sudo n 18.20.2
```
Alternatively, if you use nvm on your developer PC, run:
```sh
nvm install 18.20.2
nvm use 18.20.2
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2448)
> SF-2714 Upgrade to Node v18.20.2

- src/RealtimeServer/scriptureforge/models/translate-config.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
- src/SIL.XForge.Scripture/Models/BuildConfig.cs
- src/SIL.XForge.Scripture/Models/DraftConfig.cs
- src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/BuildConfigJsonConverterTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR enables support for specifying chapters for drafting or training when generating a draft. This is done in a backwards compatible way with the current "specify book only" method.
See https://github.com/sillsdev/serval/wiki/Filtering-Paratext-Project-Data-with-a-Scripture-Range for the syntax used.
When the frontend implements the corresponding change, it will need to generate the string using that syntax, and feed it through the updated `BuildConfig` object to the backend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2412)
> SF-2580 Add API backend for chapter selection UI

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
This PR adds a button to the Serval Administration area to run the webhook which updates the `hasDraft` property of the project's chapters.
This enables either re-running of the webhook on Production/QA, or executing the webhook for Developer machines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2438)
> SF-2718 Add button to run webhook manually

- src/SIL.XForge.Scripture/Controllers/AnonymousController.cs
This PR fixes the HTTP header that the webhook endpoint reads to be the correct value. The previous value was incorrect because it was mangled by the PHP script I used for testing the webhook.
This feature is currently broken on QA, resulting in 400 error codes:
```
162.158.79.96 - - [13/May/2024:02:02:25 +0000] "POST /anonymous/webhook HTTP/1.1" 400 4217 "-" "-"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2454)
> Fix webhook signature header name

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR fixes a bug where Serval returns a 400 error when starting a build that has no training books specified.
This bug currently affects QA.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2453)
> SF-2730 Specify null when scripture range is empty for Serval builds

- .vscode/settings.json
- src/RealtimeServer/scriptureforge/models/editor-tab-persist-data.ts
- src/RealtimeServer/scriptureforge/models/editor-tab.ts
- src/RealtimeServer/scriptureforge/models/sf-project-user-config-test-data.ts
- src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts
- src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.spec.ts
- src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
- src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-user-config-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-revision-format.pipe.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tabs.types.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/array-util.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/array-util.ts
- src/SIL.XForge.Scripture/Models/EditorTabPersistData.cs
- src/SIL.XForge.Scripture/Models/SFProjectUserConfig.cs
This PR adds persistence to the editor tabs.  Tab state is stored in `SFProjectUserConfig`.  Page reloads and route changes should maintain the tab state with the caveat that history does not currently maintain the last selected revision (it resets to the first revision in the list).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2413)
> SF-2592 Persist editor tabs

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR updates our use of Serval to handle more gracefully the following scenarios:
* Serval being offline (but Scripture Forge online)
* Scripture Forge being offline
* The user's connection being offline
This is achieved by limiting querying of the machine-api to projects that have pre-translation drafting enabled, and by handling most errors thrown by the machine-api when communicating with the draft generation service. When an error occurs with machine-api, a small red notice is displayed at the bottom of the screen:
Also, the draft generate service's tests have been rewritten to mock the HTTP requests correctly, as this was required for the online status service to function correctly in tests.
- - - …
> SF-2673 Gracefully handle Serval outages in the editor

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/paginator/paginator.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR updates the Material Paginator, and fixes the outstanding bugs with the paginator. These are linked in the JIRA ticket and include:
- The page dropdown has a transparent background
- The paginator does not allow moving beyond the first page
- Deleting the last user on the last page shows a blank page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2456)
> SF-2367 Update Material Paginator

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
The content for a note needs to have any xml related symbols such as `>` and `<` encoded to be stored in mongo. This was previously done when editing or adding a note to a thread in the note dialog, but adding notes through the bottom sheet was missed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2365)
> SF-2594 Allow saving comments with the bottomsheet with XML symbols

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html
Updates the Material Progress Spinner to use the new component instead of the legacy component.
There are no real changes, and it functions exactly the same. For this reason, it does not require formal testing.
To view the spinner in action, click the Generate draft button, and witness it briefly appear as the list of books is loaded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2460)
> SF-2369 Update Material Progress Spinner

- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2463)
> Fix spelling of "temporarily" on translate overview page

- src/SIL.XForge.Scripture/Models/SyncMetrics.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This PR stops sync metrics from being overwritten when a job is rerun from Hangfire.
This is achieved by taking the previous sync metrics (which this job is about to overwrite), and placing them in the PreviousSyncs collection.
This is achieved by utilizing the `record` feature of C# 10 (.NET 6.0) and the collection expressions added in C# 12 (.NET 8.0).
To test, I could only cause the erroneous case by killing the .NET process at the right time, and waiting for Hangfire to rerun, and then view the `sync_metrics` collection. For this reason, testing should be performed by a developer.
I chose to make `SyncMetrics.PreviousSyncs` nullable, as there are already `sync_metrics` documents, and it should be very few syncs that fail in such a way to trigger this feature.
- - -
This change …
> SF-2571 Stop overwriting the sync metrics from previous syncs

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR upgrades mat-menu from legacy to the Angular Material mdc version. Used `ng generate @angular/material:mdc-migration` as a starting point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2466)
> SF-2366 mat-menu legacy upgrade

- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
This PR changes Serval configuration and diagnostic functions to require the Serval Administrator role instead o the the System Administrator role.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2459)
> SF-2734 Change Serval Configuration permissions to Serval Administrators

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
The recent upgrade from the legacy MatCard introduced some changes that I think make the suggestion engine card layout worse.
Here's the timeline:
Before MatCard update | Current master | This branch
----------------------|----------------|------------
This branch does not cause a pixel-perfect match with the original, but that wasn't a goal. Instead, it fixes two problems:
- "Trained segments" always wraps, which looks bad
- The background for the stars didn't span the whole width, which makes it look odd
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2476)
> Improve layout of suggestion engine card

- src/RealtimeServer/scriptureforge/models/sf-project.ts
On production, due to the very large number of projects, paging to projects > 300 in the Serval Administration area or System Administration projects tab can result in the following crash:
The query parameters that cause this query to crash are in `ServalProjectsComponent.getQueryParameters()`.
To resolve this, an index is added to the sf_projects name field to enable to the sort operation in the query used in these Administration areas to use an index. See https://www.mongodb.com/docs/manual/tutorial/sort-results-with-indexes/
Because this only occurs on production, it is not testably locally or on QA, although my local tests confirmed that the index is used when paging through projects in the Serval Administration area.
This error is reproducible in MongoDB compass, so is not caused by …
> Fix crash when paging in Serval Administration area

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/usfm_sb.sty
Recently, a user attempted to use a Legacy Study Bible as a source for a project. Legacy Study bibles are a combination of a translation project and one or more Study Bible Additions projects. Some resources are also Legacy Study Bibles (see the JIRA ticket's Acceptance Criteria).
This PR adds the USFM file that allows Legacy Study Bible projects to be synced successfully.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2464)
> SF-2737 Add Legacy Study Bible support

- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
This PR fixes the margin above the divider in the connect project card to restore the padding that was lost in the upgrade.
The left hand side is `master`, the right hand side is `sf-live` (which the fix restores the padding of):
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2477)
> Fix margin above divider on connect project component

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR fixes a 400 error from Serval when specifying an alternate training source and no books to train on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2478)
> SF-2730b Fix trainOn Scripture Range for Alternate Training Source

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- Editor looks for URL query param `draft-active=true` to focus the draft tab.
- Modified `updateAutoDraftTabVisibility()` to only add a draft tab to 'source' if one isn't already in the tab state for either 'source' or 'target'.
- Removes 'draft-active' query string from url when another tab from 'source' is selected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2486)
> SF-2441 Focus draft tab on draft nav

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
Discussed with Peter. This should make it easier to trigger the webhook, rather than having to go to a separate page, search for a project, click the link, click the webhook button, and go back to the draft page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2481)
> Add Serval admin component to draft page

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
Before this change, the Material way of specifying a header wasn't being used, which leads to excessive spacing above the header. And mat-card-actions wasn't being used, which led to insufficient vertical spacing between the books and the buttons below the books. (It's not very obvious in this screenshot because the book is aligned left, and the new draft button is aligned right)
Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2485)
> Improve layout of draft card

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
In some cases the id of the user in events recorded in bugsnag is set to the user's IP address. It is unclear how that happens, but I suspect that if we provide an explicit id for the user, then the IP address will not be used.
Testing is not required. This PR should be verified by the reviewer. If you want to test this functionally, you can add a line to the error-reporting-service.ts to the notify method and verify the log output contains the user id property.
```
notify(error: NotifiableError, callback?: (err: any, report: any) => void): void {
console.log(this.metadata)
if (Bugsnag.isStarted())
Bugsnag.notify(error, event => ErrorReportingService.beforeSend(this.metadata, event), callback);
}
```
- - - …
> SF-2743 Explicitly add user id for bug reporting

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
This PR fixes a minor bug I noticed while writing SF-2616 where draft books for viewing were sorted by their order in the `project.texts[]` array, not their canonical order. This especially occurs if OT books are added to the project after NT books.
**Before**
**After**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2491)
> Fix: Sort draft books by their book number

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
This PR fixes the "Referenced element not an object (it was undefined)." error that occurs when syncing updates the texts array of the project.
This because occurs because the reference to the `texts` array for an `sf_projects_profile` in IndexedDB is sorted by `bookNum`.
To resolve this, I ensure that the copy of the texts array used for drafting is `slice()`'ed from the `sf_project_profile` object.
I also updated the code that performs the sort on this array to `slice()` from the object it was passed, as we should only `sort()` on a `slice()`'ed copy of an array, not the array the method was passed by reference.
Testing may be done by a developer, but given the change is very small with very low risk, I do not think testing is required. Full testing details are in the JIRA ticket, …
> SF-2729 Fix ShareDB apply ops crash due to array out of order

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
This is a simple change to hide the avatar menu until a user is logged in.
Currently a user can interact with any of the available options in the menu which don't make any sense yet i.e. edit name, my logout, etc.
**Before**
**After**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2494)
> Hide avatar menu until logged in

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/i18n-locale.ts
This PR moves the `LocaleDirection` type out of `TabGroupHeaderComponent` to `i18n-locale.ts` and replaces usages of `'ltr' | 'rtl'` type with `LocaleDirection`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2495)
> Refactor LocaleDirection type

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
When the old draft preview component was removed, one of the localization strings was accidentally dropped. This adds the string back in the `editor_draft_tab` area.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2500)
> Fix legacy draft warning localization unavailable

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Currently, when no books are selected for training, due to the way SF sends null values for both `textIds` and `scriptureRange` for the `trainOn` object, Serval ends up training on all books. This results in only blank verses being translated, instead of all verses.
This PR, based on the change https://github.com/sillsdev/serval/issues/383, specifies an empty array for train `textIds` collection when no books are selected for training. This means that all verses in the target will be translated by Serval, instead of just blank verses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2498)
> SF-2750 Do not train on all books when no books are specified

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-test.utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
Since rxjs calls its event handlers immediately after subscribing to them, the verse change subscription value gets initially set to -1, given the currentTime will be 0 and not resolve to any segment in the timing data. And since we're using distinctUntilChanged(), the handler isn't called again until we reach a found index, e.g. the chapter header/title.
This was causing the software to keep the previous highlight when playing chapter audio until the first timing index was reached. This was confusing for users.
My change ignores the handle called on subscribe, when the time was 0 and the audio hasn't fully loaded yet. Now, the first time the event is handled, the audio will be playing, and thus the checking component will update/clear the highlight correctly.
---
The above comment was …
> SF-2656 Fix Audio Highlight Bug

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR attempts to fix NG0911 errors that were occasionally being thrown when navigating away from the editor component.
A recent discussion in an open angular issue (https://github.com/angular/angular/issues/54527) suggests that NG0911 is happening when `takeUntilDestroyed` is used with a `DestroyRef` after component has been destroyed, such as when:
- subscription happens after awaiting an earlier promise,
- then navigation destroys component,
- then promise resolves and code flow subscribes with `takeUntilDestroyed`
I suspect that the observables subscribed in `initEditorTabs()` are the offenders.  The solution in this PR is to combine those observables and return them from `initEditorTabs()` so that they can be piped from projectDoc changes, allowing a single call to `subscribe` …
> SF-2751 Fix NG0911 error

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.ts
Every PR has had Chromatic showing a change to the fonts, because "Japa Sans Oriya" was no longer loading. It turns out this wasn't a network problem; the font is no longer available at the same URL. Updating this should get rid of the visual diff we're seeing in a number of PRs.
I plan to open a PR to add a script for updating this list; however, the script is more complicated and right now I just want to get this change in.
How to test this:
- Verify old URL for "Japa Sans Oriya" leads to 404
- Verify new URL does not
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2504)
> Update list of supported SIL fonts

- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Here's how the email template now looks on my local dev machine:
```
Please explain the problem.
--- Technical details ---
Scripture Forge: 9.9.9
Chrome: 125.0.0.0
Brave: Yes
Linux: Unknown
URL: http://localhost:5000/projects/65eb63b90a55c8594e4e9f17/translate/GEN/1
```
1. The request to explain the problem is the only thing at the beginning of the email so it's harder to miss. New lines separate it from the technical details.
2. A default subject is no longer provided
a. This prevents all our support requests from having the same "Scripture Forge issue" subject
b. Most mail clients ask a user if they're sure they want to send an email with no subject, so the user will at least have to write *something* about what the problem is
3. The old email template dictated what technical details …
> SF-2753 Shorten email template

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
Our production and QA web server hosts content in HTTP/1.1, while Cloudflare hosts content using HTTP/2 for clients that support it. HTTP/2 does not carry the status text from an HTTP/1.1 request. As such, when Angular encounters HTTP error status codes over HTTP/2, it substitutes "OK" for the status text.
This PR utilizes the Auth HTTP interceptor to intercept these errors, and correct the status text by looking up the status code in Angular's HttpStatusCode enum, and take that status codes' enum key, separate it by spaces and update the status text and message to have the corresponding text.
This PR cannot be tested on localhost, as Cloudflare is performing the HTTP/1.1 to HTTP/2 conversion, so should be merged into master, then tested on QA.
I have also included a fix for a bug in unit …
> SF-2752 Stop reporting errors as 500 OK

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
This was causing a compiler warning when doing a production build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2507)
> Fix optional chaining in app component

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
Some places we show the message dialog and don't need to wait for the user to close it, but in some places we take an action after the user closes it, for example, when a share key is invalid.
To test this, on master, in a browser where you are not logged in, open this bad share link: http://localhost:5000/join/1234567890
A message dialog will briefly open, but before you can read it you will be redirected to the home page. Then test again on this branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2513)
> SF-2770 Fix message dialog resolving before user closes dialog

- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
- src/SIL.XForge.Scripture/Services/AnonymousService.cs
- test/SIL.XForge.Scripture.Tests/Services/AnonymousServiceTests.cs
This is _kind of_ dependent on #2513, in the sense that the dialog won't properly show without that change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2514)
> SF-2771 Inform user when link has been used already

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2511)
> SF-2758 Stack import questions dialog buttons on small devices

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
This change will require a developer to test the changes and confirm that it is working as expected.
From Nathaniel
>Pro tip: If you edit enabledReleaseStages in exception-reporter.ts to include "dev", you can actually get Bugsnag to show errors that happen locally. This is useful for testing changes like this.
**Acceptance tests:**
1. Update the code to allow the `exception-reporter.ts` to report errors for dev environments.
2. Add a line to the code to throw an error (e.g. on the sync page when sync is clicked)
3. Build the app for PWA testing and open the app without installing the PWA
4. Cause the error to occur.
5. Install the PWA app
6. Cause the error to occur.
Expected: In bugsnag, there should be 2 different errors reported, one with the `isPwaInstalled` set to `true`, and one …
> SF-2764 Add pwa installed flag on bugsnag errors

- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2519)
> Make draft generation time estimates consistent

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
- src/SIL.XForge/Controllers/UsersRpcController.cs
Previously the front end would only trigger a pull of the user profile on localhost, and on production environments, it would be pushed from Auth0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2522)
> Always trigger pull of user profile from front end

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
- src/SIL.XForge/Controllers/UsersRpcController.cs
This is a hotfix, cherry-picking #2522
Previously the front end would only trigger a pull of the user profile on localhost, and on production environments, it would be pushed from Auth0.
(cherry picked from commit d419e50f578c1f1e0a7e3028655a35e14502093f)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2523)
> hotfix: Always trigger pull of user profile from front end (#2522)

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
In general we don't put a gap between Material icons, and it seems to work OK. You can see this in this screenshot where every icon button is hovered.
However, as you can see, there's a gap between the "cancel" and "save" buttons for the answer form. The gap feels excessive to me, and off balance with the rest of them, so I've removed it:
However, the gap is still present when the buttons are the larger size and need a gap to look good:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2525)
> Improve gap between save answer buttons

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.spec.ts
This PR fixes the following warnings displayed in the console when running the Angular tests:
* `WARN: 'Spec 'PermissionsService canSync does not use current user id if userId is provided' has no expectations.', [[[...]]]`
* `WARN: 'Spec 'PermissionsService canSync uses current user id if userId is not provided' has no expectations.', [[[...]]]`
* `WARN [web-server]: 404: /_karma_webpack_/base/app/checking/checking/test-audio/example.com/foo.mp3`
* `WARN [web-server]: 404: /_karma_webpack_/base/app/checking/checking/test-audio/path/to/audio.mp3`
* `WARN: '%c Missing translation for 'en.tab_group_header.no_tabs_available'', [[[...]]]`
- - - …
> Fix warnings in test console

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/online-status.service.ts
Each time the angular app is reloaded, a call is made to Auth0 to update the interface language. This was not necessarily a big problem, but it was unnecessary if the interface language still matched what was current in the browsing session.
The intended behaviour of the PR is as follows
- when the user logs in, the user's language is set to the language of the landing page (unchanged)
- upon opening the app (or on refresh) and the user is logged in, the user's language is updated if needed (changed)
- upon opening the app in 2 browsers, the most recently reloaded browser sets the user's language (unchanged)
- the user cannot change interface language while offline (unchanged)
- - - …
> SF-2754 Update user profile interface language only when needed

- src/SIL.XForge.Scripture/Services/SyncService.cs
This PR corrects the updating the of source and target project documents on sync so that the target queued count is updated before the source queued count.
This resolves an issue where the successful sync notification was appear when the sync started, due to the subscription to the source project firing before the subscription to the target document.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2528)
> SF-2790 Fix successful sync message appearing when starting sync

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.html
- src/SIL.XForge.Scripture/ClientApp/src/styles.scss
The `@angular/flex-layout` package is deprecated. One of the things we use it for the most is hiding elements on certain viewport sizes.
Throughout the repo we have 10 instances of `fxShow` and 22 instances of `fxHide`.
This PR adds a couple helper classes, and replaces a few instances with the use of these classes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2538)
> Add breakpoint classes

- src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
James Post pointed out that having an asterisk here is not particularly helpful and doesn't have a corresponding asterisk:
I understand the usefulness of denoting required form fields in a long form, but I don't think it's needed in the context of a one-field form, as it should be pretty obvious to the user that the field is required.
The longest form I could find is this:
And I don't think the asterisks are particularly meaningful here either. And if a user is at all confused and tries to continue, it's made explicit that these fields are required.
I think a proper use of asterisks to denote required form fields is in a long(ish) form where it is stated at the beginning that the asterisks denote required fields.
In addition to reviewing code changes, please make sure to review visual …
> SF-2319a Remove asterisk from required form fields

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
This PR updates the Scripture Reference box in the Add Question dialog to be marked as touched when the Scripture picker dialog is closed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2542)
> SF-2769 Mark the Scripture Reference box as touched on dialog close

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
This PR fixes a bug that causes the download/view draft functionality to disappear when you generate a new draft, and you already have a previous completed draft.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2516)
> SF-2776 Cannot download a previously generated draft when generating a new draft

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
This PR could also be title *Add new i18n interpolation function*, as that's what most of the change ended up being.
---
Users often send us screenshots of the error dialog, requiring me to use an OCR to extract the error ID from the error dialog. The OCR often makes mistakes, and I think making the error ID monospaced may help with that.
Trying to add that sent me down a rabbit hole to add better support for mixing localized strings with HTML elements.
`I18nService` has `translateTextAroundTemplateTags` which works with strings like this:
``` js
"Administrators can always invite people from the {{ templateTagBoundary }}Users{{ templateTagBoundary }} page."
```
The drawbacks are:
1. Requires planning ahead of time to use `templateTagBoundary` prior to translators translating the string. …
> Make error ID in error dialog monospace

- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss
Paratext login button was misaligned due to the mat-button mdc upgrade
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2524)
> SF-2789 Fix paratext login button content misaligned

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.spec.ts
IDs [are supposed to be unique within a page:](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id)
> The id [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) defines an identifier (ID) which must be unique in the whole document. Its purpose is to identify the element when linking (using a [fragment identifier](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Identifying_resources_on_the_Web#fragment)), scripting, or styling (with [CSS](https://developer.mozilla.org/en-US/docs/Glossary/CSS)).
Consequently, components that may appear multiple times on the same page ought not to use IDs. 
In practice, this is an extremely minor concern, and I'm not aware of anything that breaks due to duplicating IDs.
I found the …
> Replace ID with class in history component to eliminate collisions

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge/Services/AuthService.cs
- src/SIL.XForge/Services/IAuthService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Tests/Services/AuthServiceTests.cs
- test/SIL.XForge.Tests/Services/MockHttpMessageHandler.cs
This PR updates the auth service to allow querying of Auth0 for the last known `access_token` and `refresh_token`.
If the token has not been refreshed since the last login, the `refresh_token` value will be up-to-date, and cause a successful token refresh. If it is not up-to-date, the error will bubble to the frontend, and be handled by the logout prompt added in SF-2762/#2506.
As the testing is technical, this PR should be tested by a developer.
I also took the opportunity to add some testing infrastructure to `AuthService`, and updated some out-of-date code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2533)
> SF-2791 Check Auth0 for updated refresh token on rejection

- src/RealtimeServer/scriptureforge/models/sf-project.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.ts
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- src/SIL.XForge.Scripture/Services/ISFProjectService.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- src/SIL.XForge/Services/ProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This Pull Request allows Observers to connect to Paratext projects that have previously been connected to by the project's Administrators.
I have expanded this PR to fix this error for resources as well as projects. Resources that had previously been connected to were producing the following error: https://app.bugsnag.com/sil-international/scripture-forge-v2-plus/errors/666c5bb3c25a2f0008ccf510
Due to the frequency of these errors, I am pushing this to critical path.
I also took the opportunity to add an index to `paratextId` on the `sf_projects` collection, as it is what is queried, both in the previous verison of this logic and this re-implementation of the logic.
- - - …
> SF-2760 Fix Observer permissions opening projects as resources

- src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
Resource projects have a 16 character paratextId. This PR determines if the active project is a resource and will hide the option to show the project history in a tab.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2510)
> SF-2732 Hide history tab option when viewing a resource project

- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
This is a trivial issue found several years ago, that the link from the settings page to the sync page was broken when the user was offline, because the project doc isn't loaded. At the time there wasn't a trivial fix, but the ActivatedProjectService makes it easy to just get the project ID from the URL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2553)
> SF-961 Fix link from settings to sync when offline

- scripts/build-and-ship
This PR fixes an issue on QA, where the realtime server is blocking all requests because it expects them from scriptureforge.org, not qa.scriptureforge.org.
A new QA deployment should be made after this PR is merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2565)
> Fix realtime server origin on QA

- src/SIL.XForge.Scripture/Services/PreTranslationService.cs
- test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
Serval includes forward slashes in references to represent segments within verses. This can cause issues for the webhook when a target text's verses contain lots of different USFM tags (i.e. references and footnotes), instead of simple blank verses.
This PR resolves this by stripping off the section after the forward slash, as we only need the verse reference in the webhook.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2520)
> SF-2780 Correctly parse pre-translation references with slashes

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
This PR removes the legacy Codecov uploader that was a dev dependency of the frontend.
This package is not only deprecated, but was no longer used by Scripture Forge, as uploading to Codecov is done via the GitHub action (a supported method).
Our Code coverage files that are uploaded in the GitHub action are generated in the "test:tc" scripts in the `package.json` files for the frontend and the realtime server.
**Further Information**
* https://github.com/codecov/codecov-node
* https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2562)
> Remove Legacy Codecov Uploader

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.scss
- No vertical spacing
- Button on second line not left-aligned
- No spacing between anything
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2566)
> Simplify history chooser styles

- src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs
This PR adds an index to the `shareKeys.key` field of `sf_project_secrets`.
This index will speed up checking for share keys when users attempt to log in via a share key.
When running this PR, you will see a new index appear in the `sf_project_secrets` collection:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2531)
> Add index to sf_project_secrets.shareKeys.key

- src/SIL.XForge.Scripture/Models/ParatextProjectUser.cs
- src/SIL.XForge.Scripture/Services/IInternetSharedRepositorySource.cs
- src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
- src/SIL.XForge.Scripture/Services/IParatextService.cs
- src/SIL.XForge.Scripture/Services/ISFProjectService.cs
- src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
- src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR reduces calls to the Paratext Registry by combining:
* `ParatextService.GetProjectRolesAsync()`
* `ParatextService.GetParatextUsernameMappingAsync()`
Into `ParatextService.GetUsersAsync()`, and by passings the list of users from the Registry to `ParatextNotesMapper`, rather than having `ParatextNotesMapper` request the list of users from the Registry again.
I have also added a second commit that checks whether a project is registered, and if so, uses just that project's meta data and license to retrieve the repositories from the PT archives server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2529)
> SF-2788 Reduce calls to the Paratext Registry

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
At some point this must've gotten overwritten accidentally. The menu should look like:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2570)
> Hide share expiration radio button

- scripts/db_tools/parse-version.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
This PR hides the Mixed source UI in Settings behind a feature flag.
If the feature is enabled, then the UI will display, if it is disabled then it will only display if the feature flag is enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2568)
> SF-2825 Place Additional Training Source behind a Feature Flag

- scripts/db_tools/report-user-edits.ts
- Changed script arg 'project' to expect project short name instead of project id
- Added check to ensure that there is only one project with given short name
- Default outfile name is now [project]\_user-edit-counts\_([dateFrom]\_to\_[dateTo]).tsv
- Removed 'User ID' column from report
- Included project short name in report
- Modified date strings to be YYYY-MM-DD instead of YYYY/M/D in order to be used in outfile name.
Note: Testing will be done by reviewer instead of test team.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2560)
> SF-2823 Improve user-edit-counts script

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.html
Previously
Now
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2574)
> Change the history restore icon to "undo"

- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
* Make the error handler async
* Remove redundant test
* Update tests to return expected response codes
* Use error handler on unknown join errors
For testing an unknown error you can create a share key, expiry it, and then comment out `key_expired` as a known error code. I'm not sure of an easier way to do this for the test team.
As error dialogs are now async there will need to be a good amount of testing to make sure there aren't any side effects that need to be tidied up for existing errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2572)
> SF-2768 Join component supresses unknown errors

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts
Prevent logged in admin user from deleting their user in the System Administration page.
Removed word-break css so username displays nicely
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2573)
> SF-2828 Remove the delete user button on self on system admin page

- src/SIL.XForge.Scripture/Services/IParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This PR optimizes the syncing of notes to Paratext by optimizing the code that writes each book's notes to Paratext to only run once per project (well twice if you include the writing of biblical terms notes).
This is possible because previous work done to SF made the use of the book number sent to `ParatextService.UpdateParatextCommentsAsync()` to be redundant.
This change results in a speed increase when syncing projects with a many books and many notes, especially if few notes are created or edited in Scripture Forge. In my test project that has a full canon and note for every verse, a 2.5 minute sync was reduced to 2 minutes.
- - - …
> SF-2830 Optimise the syncing of notes to Paratext

- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This PR executes the ops that run outside of the transaction to run after the translation is committed or rolled back.
This ensures that the sync is displayed as complete only when it is complete. It also means that actions that modify the project data are not committed outside of the transaction.
As a part of this change, the backup of the Paratext repository now takes place before the transaction is committed. This is because the contents of the repo have been already synced to the Paratext Send/Receive server. If a failure (hypothetically) occurs during the `CommitTransactionAsync()`, then the next sync will just wind the repo back to the appropriate Mercurial commit id when the backup is restored.
- - - …
> SF-2711 Do not display sync complete before ops are written to Mongo

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Commenters and viewer users will not generally have access to view the source project. An error would be thrown at the moment when the source tab group is being instantiated because the user does not have permission to read the project data of the source. This PR adds a check if the user has source project access before trying to initialize the source tab group.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2586)
> SF-2847 Do not show source tab group if user does not have source access

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
The problem here was that the source GUI property hasn't been updated when the remote change arrives. So the hasSource check is true when the source is undefined. The block that was failing accounts for when the source changes from one source to another, but not for when the source doesn't exist. Ideally, we would have the source tab open after the source is set, which would prevent this, but I'm sure there's a reason we haven't done this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2584)
> SF-2831 Null check for remote changes

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss
This fixes a click area bug in roles and permissions dialog.
I did need a couple of these rules in the settings page, since the whole page is structured off the assumption that the checkboxes are that height. Using the default sizing really messes with the page layout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2557)
> SF-2687 Remove global styles for checkboxes

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
After doing a git bisect, I found that the commit that introduced the initial error when Commenters navigated to a project was on SF-2808. The id of the source text container was set in the html, causing the text component to try to access the source project, even when users did not have permission.
The change reverts some of the changes in PR #2586 that failed to fix the issue, and introduces a fix to only set the source id if that user has permission to see the source text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2593)
> SF-2851 Update source id when tab groups consolidate

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
Projects that are DBL resources will never have a draft build. This was causing a console error which would not be visible to users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2592)
> SF-2849 Skip getting draft build when project is a resource

- src/SIL.XForge.Scripture/Startup.cs
This fixes the numerous browser console errors when using "npm start" or "dotnet run" in developer environments. We're configured, in angular.json, to look for the host at 4200 for all dev config's, but the host would only start at that port when starting "ng serve" manually. Now, neither "start server" nor "listen" modes throw browser errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2597)
> Using default port when starting angular in dev env

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
Added back the 'draft-active' query param that was accidentally removed in SF-2617 (#2571).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2601)
> SF-2865 Fix nav to open 'Auto Draft' tab from draft gen

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.html
This improves the appearance of the copyright notice dialog (excessive space at the top is now gone).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2606)
> Allow generic dialog to have message with no title

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
On mobile, a focus was getting added to the first element in the sidenav, which makes it look active. This is now fixed.
(If you saw an earlier screenshot on this PR that didn't seem to show the problem, it's because the act of taking the screenshot removed the focus, and I didn't notice before uploading)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2608)
> SF-2868 Fix sidenav incorrect focus on mobile

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
The primary thing on the page is now first. Personally I think the "Draft in progress" section should be in a card too (or we should find something better than a card), but I'm trying to keep this change simple.
Before | After
-------|------
I felt the bold here was excessive and made it more subtle:
Before | After
-------|-------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2612)
> SF-2873 Show "Draft in progress" above "Preview last draft"

- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Relocated code for deleting directories and RealtimeServer data to be deleted before deleting serval data and project secrets on Project Deletion.
Added check for existing directory when Creating SF Project (Connecting) and error if directory exists.
Added Test case for directory check on creating project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2610)
> SF-2741 Delete project on server before deleting serval project

- mongodb/SyncMetrics/SyncStatusOverTime.mongodb
For the results of this query, see the doc "Sync failure stats" in the "Metrics" directory of the team drive. I suggest understanding the output before trying to understand the logic of this script, because it dictated an unusual approach for processing the sync metrics into the output.
The goal of this query is to measure not how many syncs are succeeding or failing, but how many projects are able to successfully sync. Each project then has a state it's in, which is the result of its most recent sync.
However, I wanted to be able to look at only active projects, so I added the ability to only look at projects within a certain time window, and if they don't try to sync for that time window, they stop being counted.
- - - …
> Add query to measure sync success rate over time

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Here's how it looks now (in one of it's four possible states):
You can review all the states at https://644bffe327c540a62f0fd260-gmceedwsox.chromatic.com/?path=/story/translate-font-unsupported-message--project-with-unsupported-font
I also moved it to its own component so we can put it wherever we want, rather than tied to the translate overview.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2611)
> SF-2842 Improve font unsupported notice

- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/Controllers/ParatextController.cs
- test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
When a user experiences issues connecting to the PT registry, we want to inform the user that they should try again later. This PR introduces a specific error message in the case where connecting with PT results in a timeout.
A look at bugsnag revealed that the most common errors from calling PT are CannotConnectExceptions. But there are instances of HttpRequestExceptions that throw the code 429: Too many attempts. I only covered the former, but perhaps I should also cover the latter. Let me know your suggestions.
This should be tested by a developer, since it relates to errors which are not possible to reproduce by testers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-x …
> SF-2783 Use a specific error message when PT registry is not responding

- .github/workflows/compute-next-version.yml
- .github/workflows/release-live.yml
- .github/workflows/release-qa.yml
---
This lets the compute_next_version.py and workflow .yml files be conceptually grouped together.
This uses [github.sha](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), which seems to be the right thing. 
When a scheduled workflow runs, it uses workflow files from the default branch (master).
When a workflow_dispatch'ed workflow runs, my understanding is that it uses workflow files from the "Use workflow from" branch. 
When the compute_next_version.py script runs, we first _checkout_ the repository to run it. Checking out the repository at  `github.sha`, as the commit from which to use the python script, will mean that the python script will also be used from the same branch that the workflow files are being used from.
Preliminary testing shows that it …
> deploy: use python script from workflow commit

- src/SIL.XForge.Scripture/Models/Note.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
A project has been having issues synchronizing with Paratext. It is still not clear how the user project got into the state where a note had no content and the owner of the note was a non-paratext users. The result is that the project cannot synchronize because of the expectation that notes with no content can only belong to Paratext users.
UPDATE: It turns out the user IS a paratext user, but their PT User Profile on the project is missing their user Id. This is normally saved the first time the project is created.
This change makes it possible for notes to have no content and not cause a crash. It is not necessary to restrict notes with no content to only belong to Paratext users.
I don't know if we should merge this Monday or Tuesday, and then releasing to live on Tuesday would …
> SF-2884 Fix sync problem when a note has no content

- mongodb/Users/SortLocalesByUsage.mongodb
- src/SIL.XForge.Scripture/locales.json
Previously I tried to sort locales by total number of speakers globally, but it's hard to find good consistent data, and even harder to add a new locale and figure out where it fits in the list.
Instead, I think it makes more sense to sort the locales by popularity, and we can update it from time to time.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2634)
> Sort locales by usage

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.scss
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2604)
> SF-2874 Improve draft preview books appearance and implementation

- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
Error messages that are returned from the server are typically CommandErrors that have a message in the form "Error invoking ... project_link_invalid". We can use the error message to determine if a known error code is included in the message, and then show a message to the user to inform them of the known issue.
This was not previously working because we were assuming the message was in the format that was just the error code, but in reality we should have been checking whether the error code was contained in the error message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2613)
> SF-2859 Inform user when the share link problem is known

- src/SIL.XForge.Scripture/Models/Note.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This is the hotfix for #2626
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2636)
> hotfix: SF-2884 Fix sync problem when a note has no content

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR fixes the date format when an a project has a short name that contains the numbers 1-12, and the UI language is set to Arabic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2639)
> SF-2877 Show correct date format for history tab

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/PreTranslationService.cs
- test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
This PR adds support for using the source chapter's USFM structure, a feature currently on Serval QA.
While testing this feature, I noticed that documents were visually corrupted when applying drafts, particularly if the draft had different segments to the target, something that will be much more common when using the source USFM. I have resolved that issue by rather than updating the editor (which resulted in segments getting mashed), I rebind the editor when resotirng from history or applying a draft.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2579)
> SF-2833 Use Source USFM for pre-translation drafts

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
When an alternate source project is selected, even if it is disabled, the logic uses the alternate source project language as the language for the serval translation engine build. This resulted in poor quality drafts because the source language of the project sent to serval was incorrect.
This PR updates the logic to retrieve the source language of the project based on the active source language that serval should be using to train on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2600)
> SF-2862 Get source project language from the active source for serval

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
* Moved the unread answers badge out of the icon container which was being mirrored in RTL
**Before**
**After**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2646)
> SF-2858 Fix position of unread count icon in RTL

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
This PR fixes the "The project has been deleted or is no longer accessible." dialog appearing when a serval admin enables or disables pre-translation drafting for a project that the user does not have access to.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2637)
> SF-2892 Fix error when Serval admin enables drafting

- scripts/db_tools/report-user-edits.ts
This grouping will make it easier for Biblica to see month-by-month updates.  The net word edits counts may be different from the old script due to the new grouping of version ops.
To view the net word diffs in the console, add `--log-diff` flag when executing script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2585)
> Change "user edit counts" report to group data by year, then month, then user, then chapter

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss
The weirdness of this layout has been bugging me:
Before | After
-------|------
The wording and the icon has not been consistent with the dialog:
Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2654)
> Improve layout of notice on feature flag dialog

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR fixes a bug where navigating to the translate area fails to show notes if multiple tabs are open in the target pane.
This bug occurs because the target ViewChild had not loaded when the code that retrieves the notes executes. The solution is to wait one tick for Angular's change detection, then retrieve the note.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2651)
> SF-2880 Note icon not appearing after navigating from Users page

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts
This PR ensures that the user's icon is updated if their name changes, and their icon is set to be their initials.
This was not taking place previously, because when the user's name did change, it was modifying a property in the `UserProfile` specified for the avatar, not changing the reference to the `UserProfile`. To resolve this, the `DoCheck` interface is implemented, which compares the two properties in the `UserProfile` for changes, and triggers the `OnChange` handler.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2657)
> SF-2866 Update the avatar icon after the user's name changes

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-revision-format.pipe.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR fixes the remaining localization bugs with the view history component, particularly updating the tab title and dropdown dates when the locale changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2658)
> SF-2604 Update history tab when the language changes

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts
This PR fixes a bug I noticed for the Telegu Study Bible, where the notes dialog had a missing translation string:
This PR fixes that by using "Footnote" or "Cross-Reference" as the dialog title for `\ef` and `\ex` notes:
I also corrected two incorrectly named unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2659)
> Fix the notes dialog title for Study Bible footnotes

- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change removes the project selector from the connect project page since it is no longer expected that users will be updating which project they intend to connect to.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2635)
> SF-2516 Remove project selector from connect project page

- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
The menu items in the main navigation have leading and trailing padding of 12px.
The leading padding is needed in order to give the items a consistent layout, but the trailing padding has no effect other than to cut off long menu items.
This is the padding I'm referring to:
This PR removes the trailing padding so that longer strings are not cut off.
Before | After
-------|------
I am marking this as "testing not required" since there is comprehensive test coverage of visual changes to this component.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2666)
> Remove unneeded trailing padding from nav menu items

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
This PR fixes moving to the previous verse with the arrow key, when the current verse has notes at the start of it (usually SF created notes).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2653)
> SF-2867 Allow moving backwards via verse with SF note using left arrow

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR fixes issue where 'Auto Draft' tab was not being selected when navigating from draft generation page in mobile view with a source text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2614)
> SF-2865 Fix autodraft open on nav when mobile view with source

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR fixes a crash noticed in production syncs when notes were incoming that had duplicate ids
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2662)
> SF-2906 Fix crash when syncing and notes with duplicate ids are incoming

- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts
Settled on option one as it gave more room for the text to grow in other languages.
**Option One**
**Option Two**
**Option Three**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2672)
> SF-2916 Change display name label on join component

- src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
- test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
This PR fixes a crash that affects a project on production which contains invalid chapters. Details on the crash are in the JIRA ticket.
A test has been added that recreates the crash (and confirms that it no longer crashes), while an old test that expected the crash to occur has been removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2660)
> SF-2905 Fix crash when syncing a book with invalid chapters

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This error was caused by attempting to parse `1&2` as XML (when the `&` should have been escaped).
It is not clear to me exactly how the situation was created, but what I did observe is:
1. A Paratext user commented on a key term
2. That comment ended up having the user's name added to the comment *as thought the user was a reviewer, even though the user was not*. Perhaps joining/leaving the project, or changing names, somehow confused SF. I'm not sure.
The partially redacted XML looked like this:
``` XML
<Comment Thread="BT_Δαυίδ" User="John Doe" VerseRef="MAT 1:1" Language="" Date="2024-08-05T04:00:02.6700000+00:00">
<SelectedText />
<StartPosition>0</StartPosition>
<ContextBefore />
<ContextAfter />
<Status>todo</Status>
<Type></Type>
<ConflictType>unknownConflictType</ConflictType> …
```
> SF-2927 Fix incorrect escaping of XML characters in notes

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
Right now it can be difficult to determine what settings a project used to generate its last draft if not an actual member of the project. 
This isn't an ideal solution, but it provides a bunch of contextual information for Serval admins. Ideally at some point in the future this will be presented better, but I expect there to be changes to how configuration is done that could make any work here obsolete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2681)
> Add draft configuration information to Serval admin page

- src/SIL.XForge.Scripture/Services/ParatextService.cs
This PR fixes a crash when connecting to or syncing older DBL Resources, such as the SBLGNT.
This crash occurs because the .SSF file does not contain the language identifier. Paratext usually works around this by running an migrator on the project, which only changes the project in memory.
To resolve the crash, I have reimplemented the migrator in a way that works with Scripture Forge.
If you wish to test this on your developer machine, use the resource "apw - The New Testament of our Lord and Saviour Jesus Christ" which suffers from the same bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2669)
> SF-2908 Fix crash when syncing specific Paratext Resources

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Sometimes when I hover over an element (sometimes by accident) that has a MatTooltip, and then try to leave the element, I end up hovering over the tooltip, so it doesn't close.
This changes it to close as soon as the element is not being hovered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2682)
> Fix annoying MatTooltip

- src/SIL.XForge.Scripture/ClientApp/.storybook/util/mat-dialog-launch.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
This functionality is NOT in use within the app. 
The intention of this new component is to provide a consistent way of recording audio anywhere in SF. It has been heavily based off the current `CheckingAudioRecorderComponent` component.
Stories have been created to show the intention of the different states. The main new flow is when this dialog opens it immediately starts a countdown for the user and then starts recording.
New Jira tasks can be created to integrate it into the Community Checking components to replace the existing `CheckingAudioRecorderComponent`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2676)
> SF-2894 Create new record dialog

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.ts
This PR moves the diagnostics info that was in a panel in the draft generation page and makes it its own component. Then this component was added to the serval administration page on projects so Serval admins can get access to the build information of the draft.
I set this one as Testing Not Required since this is visible only to serval admins and not normal users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2687)
> SF-2936 Show diagnostic information to serval admins

- src/SIL.XForge/Services/AuthService.cs
- test/SIL.XForge.Tests/Services/AuthServiceTests.cs
- test/SIL.XForge.Tests/Services/MockHttpMessageHandler.cs
This PR fixes a crash that occurs on production when syncing some resources that contain users who have had their account removed from Paratext.
Due to the destructive nature of the Acceptance Test, I have marked this Pull Request as Testing Not Required. If you disagree, please change the PR label.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2692)
> SF-2915 Fix crash when retrieving Paratext tokens for deleted users

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
This PR removes the obsolete dependency on the scripture audio feature flag. If desired, I can also remove the other unused feature flags (NMT Drafting, Forward drafting).
Developer testing will be sufficient, so I marked this as testing not required. If desired, we can move this to testers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2694)
> Remove obsolete scripture audio feature flag

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change introduces the ability to add a draft to a different project. Tests need to be fixed, but I wanted to get this under review before I can fully get the tests to work.
See the [balsamiq mockup](https://balsamiq.cloud/sghq53/pejrlz8/r1550)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2667)
> SF-2886 Allow adding a draft book to a different project

- src/SIL.XForge.Scripture/ClientApp/src/app/core/project-notification.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
When a user attempts to load a resource but losses internet connection they could receive a variety of Error Dialog popups as a result.
One minor change has to do with background loading the resource if it already exists in the IndexedDB. The dialog will stay open can close once the resource is sync.
Added additional error messages to be displayed in `editor-tab-add-resource-dialog`:
- User will be notified if loading resource failed due to being offline.
- User will be notified if loading project failed due to not being authorized.
Added offline checks to `realtime-service`, this may not be what we want in the long run. But this is an issue when we attempt to subscribe to anything with the realtime server that has not been loaded for offline access (Line 264 in the `realtime-doc.ts` …
> SF-2844 Notify user resource failed to load due to being offline

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html
If you select the error ID in the error dialog and press Ctrl, it clears the selection (there's probably a bunch of other ways to trigger this bug, but this is one). You can see this even in Storybook.
I think the reason is because it would trigger change detection, and the `track` option was wrong. The object it specifies changes each time, and so it would result in always creating new elements, which results in clearing the user's selection. Tracking by the text ensures that Angular understands nothing actually changed, and it doesn't need to re-render the elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2700)
> Fix @for track expression in error dialog

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- Hide project title when component is shown on the generate draft page
- Use flat Material buttons for consistency with rest of app
- Clarify that not all sources projects shown are necessarily in use
- Add download icon to download buttons
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2701)
> Allow downloading resources from Serval admin page, and other fixups

- src/SIL.XForge.Scripture/Models/BiblicalTermsChanges.cs
- src/SIL.XForge.Scripture/Services/IScrTextCollection.cs
- src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
- test/SIL.XForge.Scripture.Tests/Services/MockLazyScrTextCollection.cs
- test/SIL.XForge.Scripture.Tests/Services/MockResourceScrText.cs
- test/SIL.XForge.Scripture.Tests/Services/MockScrLanguage.cs
- test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
- test/SIL.XForge.Scripture.Tests/Services/MockZippedProjectFileManager.cs
- test/SIL.XForge.Scripture.Tests/Services/MockZippedResourcePasswordProvider.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR adds missing unit tests in ParatextService for:
* GetBiblicalTermsAsync()
* UpdateBiblicalTerms()
* InitializeCommentManager()
* LanguageId migration logic in the functions
* DetermineBestLanguageForResource()
* InstallResource()
* MigrateResourceIfRequired()
I have also fixed a bug for Biblical Terms where the Biblical Term's local gloss was not loaded when it should have been, corrected a bug in `BiblicalTermsChanges` where a property was incorrectly a field, and performed minor code formatting cleanups to the `ParatextServiceTests`.
The unit tests for language id migration required a reworking of how `ResourceScrText` objects are created to allow mocking. This has not changed what code is called, just where the code resides that is called. A usual QA regression test will be …
> SF-2929 Add missing unit tests in ParatextService

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss
Long lines in the draft config (e.g. when the user selected a lot of books) could flow off the page but didn't wrap.
This change causes new line characters to continue be respected, but long lines can still be wrapped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2702)
> Wrap long lines in draft config on Serval project page

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html
This fixes warnings that are shown when running `npm run build:stats`
My guess is that the previous template syntax resulted in a situation where you couldn't
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2705)
> Remove unneeded optional chaining in templates

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Updating the interface language in Auth0 only only occurs on login or if the user specifically changes it via the UI.
It is still possible to have the same user logged in via different browsers and have them in different languages based on a cookie.
Logging in will now update the UI to what is in Auth0 and not what is in a cookie from the Razor home page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2696)
> SF-2947 Only update interface language via UI

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
A layout bug was introduced in PR #2694 which resulted in duplicate questions shown on the checking app. This removed the obsolete question layout code and fixes the tests that depended on the obsolete question audio element.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2703)
> SF-2955 Fix checking question layout

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
This change adds the visualization of the active audio recording. See the Jira issue for the link to the tutorial for creating a frequency bar visualization of an audio recording.
Please feel free to make suggestions for improving the layout of the bar.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2691)
> SF-2895 Add recording visualizer to the audio recorder dialog

- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Users cannot join a project while they are offline because it requires hitting an endpoint on the server. This change will allow the error to be caught while the user is not online and notify the user that they failed to join the project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2708)
> SF-2934 Notify user when joining a project fails

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
This is supposed to be an error message, not a confirmation message.
This was broken in 28553e5451ed003cc25d85a505290033f387f5d3 when UserService.currentProjectId was changed from a gettter to a method that requires an argument, and AppComponent was not correctly updated. The result was that this dialog was shown after a user deletes a project. It should only be shown for _other_ users on a project, when the project is deleted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2625)
> SF-2885 Fix project deleted message being shown after deleting project

- src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- removed the buttons for connected items
- made connected items' cards clickable
- narrowed the cards
- removed the card containers from unconnected items (including the loading cards) and gave them a bottom line
and
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2677)
> SF-2919 Tweak UI for My Projects cards

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
I've added comments to the Jira card explaining the situation as well as some to our `auth.service`.
TLDR: Tokens had expired in Scripture Forge but were still valid when on the Auth0 website login page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2709)
> SF-2950 Fix authentication failure when joining a project with a link

- src/SIL.XForge.Scripture/ClientApp/src/styles.scss
The material stepper component was not highlighting the selected step for the draft generation stepper component. It looks like the reasoning is that our primary colour for our colour palette is grey, which look a lot like the default stepper icon colour.
To add the highlight colour, I specified the colours used on the mat stepper component, using the accent colour as the colour for the selected step.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2719)
> SF-2974 Add highlight to selected step in material stepper

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-breakpoint-observer.ts
This PR removes the dependency for the MediaObserver from the angular/flex-layout library and replaces it with the BreakpointObserver.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2711)
> SF-2958 Remove dependency on MediaObserver

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
The fxShow and fxHide attributes have been removed in favor of the classes in styles.scss. Developer testing will be sufficient to merge this PR as it is a simple change-over.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2718)
> SF-2959 Remove fxShow and fxHide from component templates

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
I noticed that when I moved the screen size close to the medium value (768px) the scripture viewer is cut off. I've updated the hiding of the side bar to get pinned only when the viewport size is large (992px) to better use of the screen on medium sized devices.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2726)
> Fix checking app cut off on medium-sized viewport

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
This Pull Request fixes support for recording audio for all browsers on iOS, and for Safari for macOS.
I was able to test this on the iOS simulator using a mac via the instructions at https://github.com/sillsdev/web-xforge/wiki/Debugging-on-another-computer.
I have marked this as testing not required, as the test team will need to test this on QA when this is deployed to QA.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2731)
> SF-2966 Fix support for audio recording on iOS and Safari

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.scss
Remove erroneous border on biblical terms page
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2736)
> Remove biblical terms tab top border

- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
These strings can be accessed by community checkers, and therefore should be in the community checking file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2738)
> Move checking strings that were in the wrong file

- scripts/db_tools/duplicate-doc.js
- src/RealtimeServer/scriptureforge/models/text-audio.ts
- src/SIL.XForge.Scripture/Models/TextAudio.cs
The previous doc ids for text audio docs incorrectly used the book number instead of the book ID. This PR updates how we calculate the text audio IDs and provides a script to update the mongoDB with docs with the updated text audio IDs by duplicating the docs.
Currently there are roughly 15 documents on live to update the doc ID for. It is important to update the mongo DB before shipping this code.
Developer testing will be sufficient. Once this gets to QA, regression tests will catch any errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2722)
> SF-2910 Add script to duplicate text audio docs in mongodb

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.ts
The editor resource component was incorrectly determining the right to left property from the resource's source project when it should be directly from the resource project. This PR updates the calculation to come from the resource project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2727)
> SF-2952 Fix resource tab not displaying right-to-left correctly

- src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts
- src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.spec.ts
- src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
- src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/Models/SFProjectUserConfig.cs
A bug was discovered on QA when a user had Biblical Terms enabled for their project and visible, the following error displays if the user has not yet updated SF to the latest version.
This PR fixes this by removing the migration, and restoring the `biblicalTermsEnabled` property in `SFProjectUserConfig` and making it nullable.
The downside of this PR is that users who previously had the Biblical Terms panel open will no longer have it open when the update their Scripture Forge PWA.
**Question**
Should we have Biblical Terms auto appear, like we do for Auto Draft if Biblical Terms is enabled for the project?
**Implementation Notes**
- The `biblicalTermsEnabled` property was restored and marked nullable because older clients will be able to set this value via their older version of the …
> SF-2998 Revert Biblical Terms migration

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
This was done using a global find and replace using this regex: `([^\s]+)="\{\{\s*(.*?)\s*\}\}"`
Matches were replaced with:
`[$1]="$2"`
The search was limited to files matching:
`*.html`
See https://angular.dev/guide/templates/binding for documentation
The before and after are not exactly equivalent. Using interpolation implicitly converts values to strings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2762)
> Remove unneeded interpolation from attribute bindings

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Added `app-notice` to `editor.component.html` to notify users to use Firefox if translation language is Korean, Japanese, or Chinese and the browser they are using is not Firefox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2699)
> SF-2942 Display warning message when editor does not support translation language

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR fixes a crash logged in Bugsnag which occurs when a project's source is cleared after the Serval draft generation is started for that project.
I also took the opportunity to do minor clean up of the MachineProjectService TestEnvironment, and add some missing unit tests that were in similar logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2741)
> SF-3000 Fix error logged when starting a build without a source

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This PR fixes a bug where draft generation jobs were not being cancelled if the cancel button was clicked soon after the build was started for the first time for that project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2742)
> SF-3002 Fix bug where pre-translation jobs are not cancelled

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR removes the angular flex-layout dependency and converts the component template files to work without using flex layout api. The best way to ensure that the conversion is adequate is by having 2 windows open, one on QA and one on this branch and check that each component still behaves as expected.
It would be good to check the layout of each component by varying the screen size and checking right-to-left interface.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2729)
> SF-2960 Remove flex-layout dependency

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
This PR fixes the NG0911 errors that occur when the editor moves between offline and online states.
These exceptions occur because the `bindQuill()` method is called after the component has been destroyed.
To resolve this, a simple flag, `isDestroyed` has been added to the `TextComponent` to ensure that `bindQuill()` is only executed if the component has not been disposed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2764)
> SF-2977 Fix NG0911 error when moving between online and offline

- src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/base-services/tab-menu.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
Even when the project has no pre-translation build, the tab menu service would attempt to get the last pre-translation build. The error would be caught, but it would still log in the console that there was a 404 error. This change skips attempting to get the pre-translation build when the project's draft config has no last selected translation book (the most direct indication that no pre-translation build exists)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2713)
> SF-2961 Skip getting draft build when project has no draft

- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
Biblical terms would visible as a menu item for any user who can view the translate app if it was enabled, but only Paratext users had permission to view it. This change adds a check in permissions service for whether the user had permission and uses the permission service when initializing tab menu items for a user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2768)
> SF-3017 Hide biblical terms tab item for users without permission

- scripts/db_tools/parse-version.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Android enables developer options as soon as the build number is tapped 7 times. Prior to this PR, SF only adds the "Developer settings" item to the menu, which then allows you to open the settings and enable the "show feature flags" setting. This is really a useless second step.
This PR changes it so that:
- The feature flag is immediately enabled upon clicking 7 times
- The flag is renamed to "Show developer tools"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2770)
> Enable dev options as soon as version number is repeatedly clicked

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/data-loading-component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html
The collaborator component had its own definition of the `isLoading` getter which was overriding the definition in the parent class. Changing the getter's name in the DataLoadingComponent fixed the console warning.
Developer testing will be sufficient to merge this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2771)
> SF-3016 Fix loading console error on collaborators component

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss
This change allows the book chapter select menu to fit on screen, especially on smartphone devices where there may be overlays that take up vertical screen space. Since this is difficult to test for the test team on localhost, we should merge this code and have it shipped to QA for the test team.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2772)
> SF-2978 Limit chapter and book chapter select height for mobile

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/location.service.ts
- src/SIL.XForge.Scripture/Startup.cs
- src/SIL.XForge/DataAccess/DataAccessApplicationBuilderExtensions.cs
- src/SIL.XForge/Services/HangfireDashboardAuthorizationFilter.cs
- src/SIL.XForge/Services/OpenIdConnectSigningKeyResolver.cs
- src/SIL.XForge/Services/UserAccessor.cs
This PR changes the Hangfire Dashboard so that it can only be accessed by a logged in System Administrator, and adds a Hangfire Dashboard menu item to the top right User menu.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2773)
> SF-3023 Add System Admin Authorization Filter for Hangfire

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-persistence.service.ts
This PR stops invalid tabs from causing an error when they are present in a user's configuration.
Testing should be done by a developer because it requires getting ids from MongoDB and running a custom script in the browser console.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2781)
> SF-2999 Silently hide unknown tab types without error

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
~The Jira issue for this hasn't been created yet but is coming.~
The cleanup code for this component is:
``` ts
if (this.isRecording) {
this.stopRecording();
}
```
This looks like it's fully handling stopping recording, but there's a loophole. Because there's a countdown to start recording, the component can start recording *after* it's been closed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2753)
> SF-3012 Fix audio dialog recording after closing

- src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Guests commenters should not be able to view generated drafts in the editor, this is for any invited SF guests and PT observer and consultant roles. This change adds a `drafts` permission to PT translators and admins to only show the draft tab to users with those rights.
SF-3003 has changes in some of the same files as this PR which may require an updated PR to fix any merge issues (namely specs) that may arise.
`npm run build` will need to be run in `web-xforge\src\RealtimeServer` to pick up the changes made in `sf-project-rights.ts`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2765)
> SF-2995 Hide drafts tab from guest commenters

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
This PR fixes the Flagged for review button height when the text is broken onto multiple lines due to window size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2774)
> SF-2975 Fix Flagged for review button with long captions

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
The audio source URL was not being updated when a question's verse ref is updated. This meant that in the case where a question's reference is changed, the audio url did not and the wrong scripture is played back. This PR adds an observable to the CheckingQuestionComponent that emits a URL based on the question's current chapter and verse.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2780)
> SF-2970 Fix scripture ref playback when question updated

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
The problem observable was already being unsubscribed in `ngOnDestroy()`, so it did not need `takeUntilDestroyed`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2784)
> SF-3019 Fix NG0911 error when loading editor on small screens

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
When editing with a source project and biblical terms the tab for Biblical terms can end up being hidden if they were opened in the source pane and the user navigates to a book that does not exist in the source. This change will keep the source pane open if a persistent tab (biblical terms, draft, resource, history) has been opened in it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2761)
> SF-3003 Fix Biblical Terms tab not showing in editor tabs

- src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/textsnapshot.ts
- src/SIL.XForge.Scripture/Controllers/ParatextController.cs
- src/SIL.XForge.Scripture/Models/TextSnapshot.cs
- src/SIL.XForge.Scripture/Services/IParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This involved subclassing Snapshot to add the IsValid property. It also involved processing, via DeltaUsxMapper, the snapshot from the RealtimeServer when a snapshot is requested from there. This is new behavior, as before it would only process a snapshot if it didn't exist on the RealtimeServer, and therefore was fetched from PT. The processing supplies IsValid. We opted to subclass Snapshot to avoid overhauling RealtimeServer etc.
Now that IsValid is updated when restoring, I wonder if it's safe to allow restoring when the current text is invalid. This is currently disabled, maybe due to the deficiency I'm addressing?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge …
> SF-2964 Update isValid when restoring a history snapshot

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Improves the visualization and functionality of the bulk-book selection when the user is setting up a new draft. Using an indeterminant checkbox allows the user to see if None/Some/All of the Old Testament, New Testament, or Deuterocanon books have been selected. The checkbox will change from None/Some to All or from All to None. When selecting individual books the checkbox will show an indeterminant state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2748)
> SF-2972 Improve drafting bulk-book selection UI

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
This is showing signs of memory leaks worse than I'd even guessed.
A known issue is that it triggers a scrollbar that breaks the layout. However, that will be fixed when #2791 is merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2792)
> Add subscriber and query counts to diagnostics overlay

- src/SIL.XForge.Scripture/locales.json
Sorted locales by using `mongodb/Users/SortLocalesByUsage.mongodb`.
I also removed ` (W. Kayah Li)` from a locale name, since we don't have that for any of the others.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2801)
> Update locales.json by sorting by locale usage

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
- src/SIL.XForge.Scripture/locales.json
The font picker was not actually being used because Material has a rule that directly applied to `.mat-mdc-menu-item-text`, and our rule only applied it to `.mat-mdc-menu-item` (the parent element).
You can tell what font is being used by going to the "computed" tab of the element inspector and scrolling to the bottom. You can also look at the network tab and filter for fonts, and see that the language picker font wasn't even being loaded.
I also removed ` (W. Kayah Li)` because the text was originally added in https://github.com/sillsdev/web-xforge/pull/594 for font reasons.
Please note that not all locale names are being rendered with the language picker font, because we haven't been updating the language picker font. However, it does have the Western Kayah Li font, so I feel …
> Fix language picker font not being used

- .github/workflows/build-and-test.yml
- .github/workflows/chromatic.yml
- .github/workflows/ci-lint-prettier.yml
- .github/workflows/ci-production-build.yml
- .github/workflows/release-live.yml
- .github/workflows/release-qa.yml
- deploy/vagrant/sfdev/Vagrantfile
- scripts/db_tools/package-lock.json
- src/RealtimeServer/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
This PR updates npm dependencies that have been flagged via dependabot as security issues.
This was done by:
* Updating npm to 10.9
* Running `npm audit fix`
I am marking this as testing not required, as a regression run on QA will be sufficient for testing.
The repsitory rules will need to be updated to check for npm 10.9
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2799)
> Update npm dependencies

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
This PR updates lint-staged to version 15.2.10.
This will resolve the following `npm audit` vulnerability alert:
```
micromatch  <4.0.8
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
fix available via `npm audit fix`
node_modules/micromatch
lint-staged  7.0.0 - 8.2.1 || 13.3.0 - 15.2.4
Depends on vulnerable versions of micromatch
node_modules/lint-staged
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2807)
> Update lint staged to 15.2.10

- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/data-loading-component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
On localhost, the component loading indicator diagnostics shows:
However, on QA and live, due to minification, we end up with this:
I think this change will fix it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2808)
> Fix loading indicator diagnostics not working in production

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/diagnostic-overlay.service.ts
If you open the diagnostics panel on master and look at the console, this error is present:
If you use the element inspector to look at the position of the `.cdk-overlay-pane`, it's at position `0, 0` on the page. The only reason the panel shows up in the correct place is because an element within it has `position: fixed;`.
We're not really using any of the built-in positioning logic, and instead have a overlay with zero size in the top left corner, that contains a positioned element.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2809)
> Fix diagnostic overlay position strategy

- src/SIL.XForge.Scripture/Services/IParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- src/SIL.XForge/Models/UserSecret.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This PR updates our current Paratext users records for a project prior to attempting to synchronize the notes. It was important to retain the records of users that have had their Paratext name changed, but the SF user ID would be removed from old records and moved to the new record for a Paratext user.
We do not expect too many users to need to update their usernames, but this allows it to happen and for a sync to continue to work. It would be critical to ensure that old notes created by the user before changing their name continues to work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2747)
> SF-2911 Support syncing notes when user has changed PT username

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
The lengthy placeholder text was getting cut off on mobile viewports.
This moves the instructive placeholder text above the input box, and
uses a smaller placeholder text.
A Storybook has been introduced for the dialog as it has a number of
states and messages.
------
I tried a couple things, and considered how to re-use `createTestParatextProject()` from editor-tab-add-resource-dialog.component.spec.ts. In the end I chose to duplicate it into editor-tab-add-resource-dialog.stories.ts, with a code comment referencing the other location. I can pursue an alternate approach if desired. 
Here is a screenshot from Storybook of the dialog on a small phone. The "Select a Paratext project or DBL resource." text was adjusted slightly and moved out of the placeholder area to be shown above the …
> SF-2818 Move instructions out of placeholder for open resource tab

- .vscode/launch.json
This restores VSCode's behaviour of showing the source mapped .ts
files when attached to a running Chromium.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2813)
> dev: fix frontend debug vscode source mapping

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
The attach audio feature is in multiple places. This PR creates an attach audio component that can be reused for recording questions, answers and the coming-soon audio comment feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2795)
> SF-3036 Add attach audio component

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
Project changes can be adding books, for example. It now listens to the activated project to retrieve its project id, where beforehand it was waiting for the components to supply this.
Similarly, the initialize() call now can happen even when the project hasn't been switched (but it's private now). This accounts for the addition of books. It is on a 1s throttle, like the calculate() call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2810)
> SF-3038 Listen to project changes for ProgressService

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
A user may not recognize that to start a recording, they need to click the button. The tooltip partially fixed the problem, but not for users on mobile devices. This was suggested by the test team.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2777)
> Add message to tap button in audio recorder dialog

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
This PR changes the behaviour of highlighting so that when a verse is selected in a target text, the entire verse of the source text is also highlighted. See the Jira issue for the discussion on this change.
Also remove the highlight on the final segment of a verse when it is blank (i.e. the blank segment at the start of the next paragraph).
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2814)
> SF-2968 Highlight all meaningful segments of a verse when selected

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.types.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Please reference the [balsamiq](https://balsamiq.cloud/sghq53/pejrlz8/r49DC) for the mock up of this change.
This PR add a way to hide the info for unusable translate and training books on the draft generation stepper.
Collapsed:
Expanded:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2817)
> SF-3048 Hide unusable books details on draft generation stepper

- src/RealtimeServer/scriptureforge/models/sync.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Models/Sync.cs
- src/SIL.XForge.Scripture/Models/SyncErrorCodes.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
In the event a sync fails due to a user who no longer has permission to sync a project we want to inform the user to contact the project administrator. This change passes an error code that can be read by the front-end when the notification of the sync completes. It will display a different sync error message and dialog message than the default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2794)
> SF-2991 Display informative error message when sync fails due to permissions issue

- src/SIL.XForge.Scripture/ClientApp/src/index.html
Chrome 108 (Nov '22) added support for this new tag, which resizes the visual viewport to the visible space. It does not appear after brief investigation that Safari supports this, and Firefox has been documented to resize with or without this setting.
Note that if we choose to hide the bottom bar in the future (which is currently the case), it may not be quite necessary to use "resizes-content" as compared to the other accepted values. It may be that, given that bar will go away, the value "overlays-content" may also suffice. However, the default (resizes-visual for Chrome) likely would cause buggy behavior, given that it currently hides the top bar.
- - - …
> SF-3052 Add interactive-widget setting to viewport meta tag

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This PR checks that a user is still on a back translation project before continuing the Sync process. If the user is no longer found on the project an error will be thrown and dialog message displayed to the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2822)
> SF-3049 Fix sync error when user no longer on back translation

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
This PR fixes the audio dialog not always displaying the audio visualization bar. I have been able to reproduce this on Firefox and Safari for iOS (QA BrowserStack) but not on Chrome. This change loads the canvas element countdown/tap to record to ensure the context can be initialized when the recording starts. When the recording is stopped, the `canvasContext` is reset to a default state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2821)
> SF-3050 Fix audio visualization not displaying

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.stories.ts
A snapshot that is not consistently reproducible has almost no value, so we're not losing much by turning these off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2834)
> Disable Chromatic snapshots that produce inconsistent results

- scripts/db_tools/parse-version.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
- src/SIL.XForge.Scripture/Models/FeatureFlags.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/appsettings.json
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR adds support for the updated learning rate for Serval.
I have placed this behind a feature flag so we may disable it when Serval implements this rate as the default, or if the new rate proves problematic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2829)
> SF-3063 Specify updated learning rate for Serval

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
This PR fixes the offline indicator that stopped displaying after merging the Angular 18 update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2835)
> SF-3067 Fix offline indicator not displaying

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
This PR updates the logic to only filter the last blank segment when it is a segment that begins on a new line and is blank. Previously, the final blank segment was not being highlighted when creating a question in the question dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2833)
> SF-3061 Include last blank segment when previewing question verses

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
When viewing a tab with the source text, while navigated to a text
location that is not in the source, it was showing "Loading...".
This re-works how and when we decide on placeholder messages, with the
result that the source text will say "book not found" rather than
"Loading..." in the situation above.
The TextComponent Input placeholder is now being used to allow
overriding the message shown when there is no content to show.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2828)
> SF-3042 Show no-book message for source

- src/RealtimeServer/scriptureforge/models/translate-config.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
This PR adds a missing project type "Transliteration" to the validation schema, which I discovered in our Mongo database after running `validate-data.ts`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2846)
> Add missing project type Transliteration

- .github/workflows/release.yml
- scripts/build-and-ship
- src/SIL.XForge.Scripture/Controllers/HealthController.cs
- src/SIL.XForge.Scripture/Models/HealthCheckResponse.cs
- src/SIL.XForge/Configuration/AuthOptions.cs
- test/SIL.XForge.Scripture.Tests/Controllers/HealthCheckControllerTests.cs
This PR adds support for an API key to the health check endpoint.
Before running this locally, add a test key to your user secrets:
```sh
dotnet user-secrets set "Auth:HealthCheckApiKey" "test_key"
```
After starting Scripture Forge, you can test the endpoint via Swagger (http://localhost:5000/swagger/index.html) or curl:
```sh
curl -X 'POST' 'http://localhost:5000/health-check' -H 'X-Api-Key: test_key' -d ''
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2847)
> Add API key to health check endpoint

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Here's what this branch looks like. Not amazing, but way better than staring at a page that hasn't loaded and shows no sign of life.
As an example of how bad it is on live, I had this page for 1 minute 50 seconds before the books loaded:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2843)
> SF-3072 Fix list of books not loading on draft page

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
This PR fixes the `Cannot read properties of undefined (reading 'percentage')` error in the generate draft wizard that can occur when the connection is interrupted while loading the progress of the texts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2845)
> SF-3051 Fix error in drafting wizard when texts have not yet loaded

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/subscription-disposable.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2788)
> Deprecate SubscriptionDisposable

- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-create-settings.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- src/SIL.XForge.Scripture/Models/SFProjectCreateSettings.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This change removes the translation suggestions option from the connect project page. This also includes changes to remove the "login" state from the connect project page which is no longer relevant. A user not logged into Paratext is not able to access this page. If it was typed into the browser manually, the user would be redirected to the my projects page.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2854)
> SF-3080 Remove enable translation suggestions from connect settings

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
There is a small delay between when a draft is started and when we get the draft job from the draft generation service that indicates that the build was queued. The small delay after the build is started will look like nothing happened when the user initiates a draft build and can be confusing. This PR delays closing the draft generation stepper until a queued job is retrieved from serval. A spinner progress is displayed as the user waits for the queued job.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2853)
> SF-3081 Show draft queued immediately when job started

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change adds form validation to the note dialog form when adding or editing notes. If a user tries to save an empty note, they will be prompted to enter text rather than having the dialog close without any action.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2851)
> SF-3054 Warn user when saving a note without content

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
When generating a draft for the first time for a Back translation project, it is possible that while the draft is queued the spinning gears animation will not show if a user navigates away and back to the page because the preTranslate flag has not been set on the project in `MachineProjectService.StartBuildAsync`. This change moves setting the preTranslate flag just before the project is synced in `MachineApiService.StartPreTranslationBuildAsync`.
I marked this as testing not required since a developer will be able to confirm these steps acceptance steps easily.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2859)
> SF-3085 Fix back translation draft not showing progress

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
This PR removes app notices from the Drafting page when projects are not setup for drafting. New tests were added to the `draft-gerenation.component.spec.ts` to verify notices either appear or do not appear depending on if project `isPreTranslationApproved`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2864)
> SF-3092 Fix draft notices displaying when drafting is not enabled.

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This PR updates the behaviour so that when a question is archived from the Community Checking page by an admin, the current question is moved to the next question instead of moving back a question.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2877)
> SF-3100 Move to next question when previous question is archived

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge/SIL.XForge.csproj
- test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
- test/SIL.XForge.Scripture.Tests/Services/FileSystemServiceTests.cs
- test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
This PR updates some package dependencies that contain known vulnerabilities:
_I have updated these to the minimum fix versions to reduce incompatibilities._
- NPOI 2.7.1 to 2.7.2
- MailKit 4.7.0 to 4.8.0
- Update dependencies of dependencies that dotnet reports as vulnerable:
- Microsoft.Windows.Compatibility from 6.0.0 to 6.0.6
- System.Data.SqlClient from 4.8.3 to 4.8.6
- System.IO.Packaging 6.0.0 to 6.0.1
- System.Text.Json 7.0.3 to 8.0.5
- System.Text.RegularExpressions 4.3.0 to 4.3.1
- Move FileSystemServiceTests to SIL.XForge.Scripture .Tests so that ParatextData is no longer a dependency of SIL.XForge.Tests.
Not Fixed:
- BugSnag. BugSnag plan to update this in Q1 2025 (see https://github.com/bugsnag/bugsnag-dotnet/issues/170).
- The only other alternative would have been to …
> Dependency Security Updates

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
This PR fixes support for Scripture Forge running on ARM64 on Windows (i.e. on new Surface tablets).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2885)
> Fix support for Windows on ARM64

- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.html
This PR fixes how the sync progress is displayed in the tab resource dialog to prevent overlapping of text. Rather than optionally hiding the new sync info, this moves the sync progress into the space where the "Loading..." message previously appeared during the sync progress. This allows users to have the same visual insight into the status of thy sync across the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2873)
> SF-3095 Fix sync progress display when loading a resource.

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
When using a project plan, it is possible that a user can have permission on all books and automatic permissions on some books. When that happens, SF incorrectly calculates book level permissions. This change updates our permissions calculations to correctly give permission when automatic book permissions are set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2865)
> SF-3093 Allow adding draft to a book when project plans are used

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
This is the code that was just temporarily on live for including the timezone in a date.
The tests however are new.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2887)
> Add support for showing timezone in date format

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
This is based off the recent downtime notice that was pushed as a hotfix to live.
This branch:
- Adds a component that shows up globally and can list notices
- Adds a single notice about upcoming downtime (but keeps it hidden)
This is mainly about creating a slot in the UI for showing notices. There are a lot of options for how we might be able to load these notices in the future.
One important aspect of this change is that it adds localization strings for an "upcoming maintenance" notice. By getting this into the project, we can hopefully have it localized before downtime is going to occur, and reuse it as many times as needed.
- - - …
> Add global notices component with upcoming downtime message

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
These were found by temporarily adding `"noUnusedLocals": true` to `src/SIL.XForge.Scripture/ClientApp/tsconfig.json`.
I did not persist the config change because the FeatureFlagService has private properties that are accessed via `Object.values(this)`, but appear to not be used when only statically analyzed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2890)
> Remove unused private members from TypeScript files

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
This PR fixes front end unit tests that are not behaving correctly:
* Time zone in date unit test fails in New Zealand and time zones that are not whole hours (i.e. India)
* Error in `AppComponent`:
```
ERROR: 'NG0304: 'app-global-notices' is not a known element (used in the 'AppComponent' component template):
1. If 'app-global-notices' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
2. If 'app-global-notices' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.', [[[...]]]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2891)
> Fix broken unit tests

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
The draft wizard cannot be opened offline, but if the user goes offline while the draft wizard is open, then the user can proceed and generate a draft that will fail. This PR prevents the user from advancing steps if the internet connection drops and shows a message to the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2893)
> SF-3108 Do not allow generating drafts in draft wizard when offline

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts
There are a lot of ways to misinterpret the configured draft sources, and the model may change in the future. Read the doc comment for rationale.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2906)
> Make projectToDraftSources from ConfirmSourcesComponent a util function

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR fixes an issue where deleting a project that was referenced in a resource tab for a different project was throwing an exception when loading the tab.  Now, the deleted project tab is excluded when loading editor tabs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2898)
> SF-3082 Remove persisted resource tabs from deleted projects

- .github/workflows/zizmor.yml
- .vscode/settings.json
zizmor does static analysis of GitHub actions. To see what it produces for SF, run `pip install zizmor` and then `zizmor .` in the repo dir. To see only higher severity findings, run `zizmor --min-severity high .`
My review of the results leads me to believe that none of the findings are exploitable, but we have opportunities to reduce the attack surface.
This is copied almost verbatm from the recommended workflow at https://woodruffw.github.io/zizmor/usage/#use-in-github-actions
You can see the results generated by this action run here: https://github.com/sillsdev/web-xforge/security/code-scanning?query=pr%3A2907+tool%3Azizmor+is%3Aopen
- - - …
> Add workflow to scan workflows with zizmor

- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2910)
> Link to localized sharing help when it is available

- src/RealtimeServer/common/migration.ts
- src/RealtimeServer/common/services/user-migrations.ts
- src/RealtimeServer/scriptureforge/services/biblical-term-migrations.ts
- src/RealtimeServer/scriptureforge/services/note-thread-migrations.ts
- src/RealtimeServer/scriptureforge/services/question-migrations.ts
- src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
- src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
- src/RealtimeServer/scriptureforge/services/text-audio-migrations.ts
- src/RealtimeServer/scriptureforge/services/text-migrations.ts
- src/RealtimeServer/scriptureforge/services/training-data-migrations.ts
I'm fairly certain there's a way to do this at compile time with the type system, but doing a runtime check is much easier to implement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2916)
> Verify migrations have monotonically increasing version numbers

- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2919)
> SF-3122 Use lambda in all throwError calls

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This fixes an issue where "hide text" projects couldn't navigate questions on mobile, since the bottom bar is now being hidden.
So now, we don't hide the bottom bar if "hide text" is enabled. We will instead only hide the bar if the "hide text" is disabled and the chapter audio is shown. Effectively, this is when "the user opens the chapter audio."
The second case where we hide the bar remains. I did a slight refactoring to make all this clear and readable.
The original reason for the hiding behavior is still intact, that being to free up space on mobile and keep users focused on their intended task.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2905)
> SF-3114 Make chapter audio only hide bottom bar if scripture text is shown

- src/RealtimeServer/scriptureforge/models/translate-config.ts
- src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
- src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR adds the ability to mix in training data from multiple sources. See the [balsamiq](https://balsamiq.cloud/sghq53/pejrlz8/r5325) for the original design.
No training books selected
Training books selected
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2875)
> SF-3077 Add UI for mixed training sources

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
By default, Chrome on Windows defaults to standard English formatting for Nepali dates, whereas Chrome on Android uses Nepali script and formatting (to an extent). This change supplies a custom date format that all platforms will use. It gets as close to the appropriate date/time format as possible with what's built into the standard API.
The one difference/shortcoming of which I'm aware is that Nepal uses the Vikram Samvat calendar, which is not supported with the 'calendar' option. We could use the 'indian' calendar, but given that Android defaults to Nepali script and Gregorian calendar, it should be acceptable to do so here, as well.
- - - …
> SF-3026 Force consistent date format for Nepali across platforms

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/retrying-request.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/testing-retrying-request.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2918)
> SF-3120 Replace toPromise with lastValueFrom

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This fixes a bug where the selected verse would be doubly toggled in some cases, especially after a history restore. The selected verse is tracked via state in the editor with a simple field, and it can become wrong. With the design in place, it is tricky to keep this field in sync.
The core of this comes down to the difficulty in distinguishing between different types of local changes, some coming from the editor and some from elsewhere. Local changes from elsewhere, like a history restore, will overwrite the text doc completely, including clearing its selected verse. To fix the bug, we check if the selection has been cleared and the editor thinks it hasn't, then refresh the editor.
I'm not sure about a unit test here. This is a really niche use case.
- - - …
> SF-3070 Refresh the selected verse if the states are wrong

- src/Migrations/BackoutCommits/BackoutCommits.csproj
- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/NotesFormatter.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- tools/CommentGenerator/CommentGenerator.csproj
- tools/RepoInfo/RepoInfo.csproj
This PR:
* Updates ParatextData to 9.5.0.8
* Marks a sync as failed when ParatextData refuses to send/receive because the project requires a version of Paratext greater than the version Scripture Forge users.
* Adds support for projects that utilize whitespace and invisible characters (a new feature in Paratext 9.5).
* These whitespace characters can be added to a chapter in Paratext, and are viewable in Scripture Forge. They can be removed or replaced in the Scripture Forge Quill editor.
Known bugs:
* You cannot paste the special whitespace characters into Quill. This is fixed in Quill 2.0.
Known behavior change:
* After syncing a project after this update, the file ParatextVersionForUsers.xml will be created with this contents:
```xml
<?xml version="1.0" encoding="utf-8"?> …
```
> SF-3123 Update ParatextData to 9.5.0.8

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
This may be the most insignificant bug I've ever fixed, but it's a bug nonetheless.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2926)
> Fix shadow on question count card

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
This PR fixes the resource books selected for training not persisting between steps. It adds a variable to store the books that will be used for training.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2927)
> SF-3141 Fix selected reference books persisting between steps

- src/SIL.XForge.Scripture/Services/ParatextService.cs
(cherry picked from commit ed33d050129e6622fe601927d943a1fcfaaa2f39)
This was originally a hotfix on live, which is now being merged to master.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2932)
> Add logging for note sync failure

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
- src/SIL.XForge.Scripture/Models/FeatureFlags.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/appsettings.json
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
As the 60 days have passed and Serval automatically sets this rate for us, this PR reverts the following PRs:
* #2829
* #2832
* #2902
The feature flag is retained so an version numbers with the feature flag will be parsed correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2933)
> Remove learning rate adjustment and notice

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
To do this, we check the queue count in the project doc and display that message if the build job state is queued. Once the sync count is zero, we display the regular queue message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2923)
> SF-3124 Add sync message before draft queued message

- src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs
This PR adds an index to `projectRef` in the `sync_metrics` collection, as follows:
This should speed up querying of sync_metrics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2934)
> Add projectRef index to sync_metrics collection

- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- src/SIL.XForge.Scripture/Models/MachineApi.cs
- src/SIL.XForge.Scripture/Services/IMachineApiService.cs
- src/SIL.XForge.Scripture/Services/IParatextService.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR adds support for a USX endpoint for downloading drafts, in the format: http://localhost:5000/machine-api/v3/translation/engines/project:6759d685b919b5bce800eb16/actions/preTranslate/40_0/usx
This endpoint can be tested via Swagger (http://localhost:5000/swagger/index.html).
As this has no user facing interface, I have marked this as testing not required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2936)
> SF-3131 Add support for retrieving drafts as USX

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
This allows navigation to My Projects when clicking the menu drawer on phones. It's a little confusing that the logo is present on desktop but not mobile. Users with both will be wondering where to go. This solution maintains the original intent of minimizing onscreen clutter for mobile.
(We don't have enough space to show the project name, but this is okay.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2915)
> SF-3144 Show logo and project abbreviation on mobile

- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR addresses the confusion of the offline message that is shown for BT that was found during regression testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2935)
> SF-3068 Update BT offline message

- mongodb/SyncMetrics/QueueAndRunTimePercentiles.mongodb
The output of this query can be seen in the metrics folder of the team drive. #2938 is likely to improve sync speed, and this query gives us a way to measure it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2939)
> Add query to find sync queue and run times

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This PR checks if the "Add Answer" button is present and accounts for its height when resizing the Question and Answers splitter area.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2943)
> SF-3154 Fix splitter area shifting when manage audio dialog is closed

- src/SIL.XForge.Scripture/wwwroot/scss/_home.scss
This fixes an issue where the background is shown just above/behind this element at some resolutions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2947)
> SF-3127 Fix horizontal line appearing on home page

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.html
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Changes:
- No longer state CSV, since supported file formats are `.csv,.tsv,.txt,.xls,.xlsx`
- Make the button appear like our other buttons
It would be preferable to add text explaining what formats are acceptable, but for this PR I'm only focused on removing anything that's actively misleading. Our help site [currently says](https://help.scriptureforge.org/generating-a-draft) "These need to be in .csv format" (which is false), but was a completely reasonable conclusion based on the current UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2949)
> Fix wording around uploading training data to not imply CSV only

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
The serval admin page needs to be updated to account for the additional training source. This adds the additional training source as an entry that can be downloaded and correctly shows the training sources and selected book configuration for a draft build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2950)
> Update serval admin page with additional training source info

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR fixes build failures that occur when changing to a source from a different language by:
* Clearing the ProjectSecret fields when a Serval project is removed
* Correctly handling missing corpora and parallel corpora by ignoring deletion "not found" failures, and creating corpora and parallel corpora when they are missing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2945)
> SF-3151 Fix Serval build failures when changing source languages

- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This PR speeds up synchronizing of popular resources on live by:
- Only updating the permissions for users in the target project when a resource is a source to a project.
- Updating all permissions on a resource when the DBL has flagged that the resource has been updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2938)
> SF-3149 Only update resource permissions when necessary

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
When a book is essentially blank on the project selected to apply a draft to, our mongoDB only has the first chapter for text documents. One option is to create the additional text documents and then apply the drafts, but this appears to go against our normal approach to have users format and create books in Paratext.
This PR gives the user a warning if they are attempting to add a draft to a book where chapters from the draft are not all present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2903)
> SF-3103 Warn user when project does not contain all draft chapters

- src/SIL.XForge.Scripture/Controllers/HealthController.cs
- src/SIL.XForge.Scripture/Models/HealthCheckResponse.cs
- test/SIL.XForge.Scripture.Tests/Controllers/HealthCheckControllerTests.cs
This PR removes the Serval check from the health check API, and adds a status summary that will be one of two strings:
* All systems are healthy.
* Some systems are down.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2951)
> Remove Serval status and add status summary to Health Check

- .github/workflows/ci-lint-prettier.yml
When looking at a list of jobs for branch protection rules, this job in particular has a confusingly meaningless name:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2961)
> Rename lint job in workflow file

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
This PR calls the Auth0 login API with the additional useBranding and logo parameters that will configure Auth0 to hide the SF name and SIL logo when using a site other than localhost or scriptureforge.org.
I marked this as testing not required since it won't be testable until the non-branded site is live. A developer can test this by setting useBranding to false.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2937)
> SF-3117 Add logo option to remove branding on auth0 page

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
When you run the Angular frontend unit tests, the following warning will be logged in the console multiple times:
```
WARN: 'NG0955: The provided track expression resulted in duplicated keys for a given collection. Adjust the tracking expression such that it uniquely identifies all the items in the collection. Duplicated keys were:
key "" at index "0" and "1". Find more at https://angular.dev/errors/NG0955', [[[...]]]
```
This PR fixes this warning, and fixes a couple of minor typos in a related `.spec.ts` files I noticed.
As this PR only affects unit tests, testing is not required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2968)
> Fix NG0955 warnings in unit tests

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
Before | After
-------|------
This makes it more consistent with the rest of the application, where we use the simple x for cancel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2970)
> Change draft cancel icon to simple x icon

- src/SIL.XForge.Scripture/Models/TextData.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/SFScrTextCollection.cs
- src/SIL.XForge/DataAccess/MemoryRepository.cs
- src/SIL.XForge/Realtime/MemoryConnection.cs
- src/SIL.XForge/Realtime/MemoryRealtimeService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MockHg.cs
- test/SIL.XForge.Scripture.Tests/Services/MockHgRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
When a user is retrieving the history for a chapter, and the project is being updated on disk by Paratext sync in another thread, the  get history request can fail with the following error:
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
```
This PR fixes that issue, which was recreated via a unit test. I also took the opportunity to unit test the get snapshot and get revisions code that interacts with the Paratext project on disk via Mercurial.
I have marked this as not requiring testing, as this crash is really difficult to recreate, and since the unit test recreates the environment of the crash, …
> SF-3166 Fix crash while retrieving history during sync

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
On the overview page, the user was wrongly being shown that questions were loading when they were offline. This is because the questionQuery.ready property never returns true if offline. However, the query results will still load the offline docs. This change adds checking for the online status and only shows the loading message if the user is online.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2959)
> SF-3084 Fix checking overview page not showing questions correctly

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
I opted for a minimalistic solution here, because this seems to be a rare use case, based on a conversation with Nathaniel. We need to support it, but most target languages won't be in the NLLB. We can certainly do more with the UI -- on the Summary and Training pages -- but apparently it's not necessary to guide them down this path too forcefully.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2971)
> SF-3170 Show a summary message when no training books are selected

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2957)
> SF-3101 Highlight range of source segments

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR makes it so that editing a resolved note will un-resolve that note thread.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2964)
> SF-3083 Resolve icon should change when editing resolved note

- src/RealtimeServer/common/diagnostics.ts
This PR adds support for generating heap snapshots of the Realtime Server. This will be useful to diagnose why the Out of Memory errors are occurring every 1-3 days, which result in the Realtime Server restarting.
**To Use:**
1. Get the process id of node: `ps aux | grep node`
2. Send the USR2 signal to the node process: `kill -USR2 {process_id_here}`
If developing, the console output will tell you where it was written, for example:
```
Heap snapshot written to /home/peter/src/web-xforge/src/SIL.XForge.Scripture/bin/Debug/net8.0/scriptureforge.heapsnapshot
```
If on QA or Production, look in the journal to see where the file was written.
**Note:** As we are already using USR2, I was unable to use the Node command line argument [--heapsnapshot-signalsignal](https://nodejs.org/api/cli.html#- …
> Add heap snapshot generation to the realtime server

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
The user should see warnings on the training step for two scenarios:
- The user's training source does not contain all of the translated books (books with more than 10 translated segments). This can indicate the user is using a source other than the one they are actually translating from.
- The user selected translated books to use for training, but did not select matching books an any of the reference projects.
Warnings will appear for the user, but they can still proceed to generate a draft.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2956)
> SF-3156 Warn user when mismatch in translated and training books

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
This PR fixes the incorrect language codes for resources created in Paratext 8 by retrieving the language code from the Settings XML (in this case an SSF file) instead of from the LDML file which will usually default to English in these cases.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2963)
> SF-3155 Fix incorrect draft source language codes

- src/SIL.XForge.Scripture/Controllers/HealthController.cs
- src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
- src/SIL.XForge.Scripture/Pages/Status/Error.cshtml.cs
- test/SIL.XForge.Scripture.Tests/Controllers/HealthCheckControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
This PR fixes our error page so that when errors that occur on a POST call this page, a 400 error is no longer thrown instead of the actual error code.
This not only allows us to use `Forbid()` in `[HttpPost]` actions, but it also means that if .NET throws a 500 error during a POST, it won't be rethrown as a 400 error.
I also took the opportunity to clean up some of the related tests to better reflect the type returned by their respective Controller action.
As this only affects API endpoints on error, this only requires developer testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2979)
> SF-3174 Fix 400 errors on Forbid() or with .NET 500 errors

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
When translated books are selected on the training page, they are automatically selected in the reference texts. Books should also be automatically deselected when the translated book is removed from training.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2969)
> SF-3167 Fix training books not correctly listed on summary page

- src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This includes:
- Delaying the creation of the project-select component until the projects list has loaded. This follows the basic pattern outlined by other usages of this component, and of course enables us to set the project on dialog creation. Setting the value programmatically after creation proved to be quite tricky, which explains why pages like Settings avoided it.
- Replaced dependence on targetProject$ in the template with the form control. Since the former was being changed in the event handler in the apply dialog, starting with a value (e.g. the current project) was causing the handler to be called immediately on dialog startup, which in turn triggered "changed after checked" exceptions. Apparently, depending on a different but equivalent property fixes this, as it likely isn't …
> SF-3126 Combine Add Draft dialogs

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
When the books selected for training do not have selection in both the translated books and reference texts the user will be shown an error directing them to fix the mistake. This change forces the user to fix the mistake before generating the draft.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2980)
> SF-3173 Show error when matching training pairs not selected

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/string-util.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/string-util.ts
I used the HTML parser instead of the XML parser as it is more lenient.  For example, the XML `DOMParser` will have parsing errors if there is no root tag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2974)
> SF-3172 Improve editor xml tag stripping

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
An issue appeared when a training book is selected, but then the user goes back and selects the book as a translation book. Even though the book is no longer a selectable training book, it still appears as a selected training book. This fixes the problem by ensuring that the list of selectable and selected training books are current when a user selects translation books.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2986)
> SF-3182 Fix warning message when training book no longer selectable

- scripts/check_external_urls.mts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url-class.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
The ExternalUrlService provides links to things outside the application. Essentially it represents the state of some of "the world" outside the app.
- We have basic unit tests of logic, but they don't verify the state of the world
- The state of the world outside the app changes even without changes to the app itself
A script has been added that enumerates all the URLs that could possibly be linked to by the ExternalUrlService. It then:
- Checks that they return a 200 status
- If the link is to a specific ID on the page, it verifies that that ID exists on that page
It can also be run against a different copy of the help site, in order to test changes before they go live.
- - - …
> Add script to check if all external links are valid

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR fixes a bug where some older resources which have invalid language codes, like "English-KJV", were not having their correct language code written to the project settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2990)
> SF-3187 Store the correct language code when migrating resources

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
A good portion of this was restored from its last working state (last year), before we removed it, and updated. The file processing comes solely from the existence of the uploadAudioFile property. I also restored the old Firefox .ogg file workaround, though I didn't test that it's still required (yet).
The upload button must be enabled to be visible. This is controlled by a boolean Input on the control, and it's false for its usage within the answers.
Also accounting for the 'uploaded' state in text-and-audio, since beforehand it was only looking for the recorded 'processed' state.
The aesthetics come from [what was selected in Balsamiq](https://balsamiq.cloud/sghq53/pejrlz8/rADE4), but we can certainly adjust it, based on what the result actually looks like.
- - - …
> SF-3176 Add Upload Audio to Questions

- src/RealtimeServer/common/index.ts
- src/RealtimeServer/package-lock.json
- src/RealtimeServer/package.json
- src/RealtimeServer/typings/json0-ot-diff.d.ts
- src/SIL.XForge/Models/QueuedAction.cs
- src/SIL.XForge/Realtime/Connection.cs
- src/SIL.XForge/Realtime/Document.cs
- src/SIL.XForge/Realtime/IConnection.cs
- src/SIL.XForge/Realtime/IDocument.cs
- src/SIL.XForge/Realtime/IRealtimeServer.cs
- src/SIL.XForge/Realtime/MemoryConnection.cs
- src/SIL.XForge/Realtime/MemoryDocument.cs
- src/SIL.XForge/Realtime/RealtimeServer.cs
- test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
- test/SIL.XForge.Tests/Realtime/DocumentTests.cs
- test/SIL.XForge.Tests/Realtime/RealtimeServerTests.cs
This PR adds support for replacing a document in the real time server, and having the real time server calculate the ops for you to replace the document.
This will be useful for updating JSON0 documents, which are complex and deeply nested.
This PR has been split off [feature/SF-3133](https://github.com/sillsdev/web-xforge/compare/feature/SF-3133) as it is a discrete piece of work, in the hope it will make code review easier, instead of one very large PR for [SF-3133](https://jira.sil.org/browse/SF-3133).
I also took the opportunity to add missing unit tests for classes I modified for this PR to help improve test coverage.
This PR doesn't have any acceptance criteria as the function is not yet in use (it is foundational work for [SF-3133](https://jira.sil.org/browse/SF-3133)).
- - -
This …
> SF-3185 Add replaceDoc support to realtime server

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
As we want users to have up-to-date documentation to assist with FAQ's and newer app features we should remove the RoboHelp Manaul from the Help Menu dropdown as it is not currently maintained/updated as frequently as the Help site.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2995)
> SF-3196 Remove Manual link from Help Menu

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
After the draft generation steps component was converted to not subclass the subscription disposable class, the `subscribe` method needed to be explicitly called in order for the logic to enable additional training data to be run. I have also added a test which will catch future regressions showing the additional training data option.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2994)
> SF-3193 Fix additional training data option not visible

- .vscode/settings.json
The C# extension (v2.63.x) updated to Roslyn v4.14.0-1.25074.7, this change renamed the vscode setting for [organizing imports on format](https://github.com/dotnet/roslyn/pull/76806). This PR updates our settings.json to keep our preferred defaults with the latest version of the extension.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2997)
> Update vscode settings for C# extension changes v2.63.x

- src/SIL.XForge.Scripture/fonts.json
This was done by running update_font_list.mts
This is a recently released font: https://software.sil.org/busra/release-9-000/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3000)
> Add Busra font

- src/SIL.XForge.Scripture/Controllers/ParatextController.cs
- src/SIL.XForge/Services/IProjectService.cs
- src/SIL.XForge/Services/ProjectService.cs
- test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR exposes the AddUser JSON-RPC API endpoint to the Paratext API so that the Paratext Extension can join users to projects that have already connected to Scripture Forge.
I also took the opportunity to remove some unnecessary unit tests which check whether Administrators or Translations can sync resources or cancel resource syncs. (Resources can only have PT Observers).
I have marked this PR as testing not required, as it is an API endpoint and should be tested by a developer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3003)
> SF-3203 Add an API endpoint to join an existing project

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
This PR fixes an error in some resources since upgrading to Quill v2: `[Parchment] Unable to create link blot`.
Quill v1 didn't render the links at all.  These "jump links" seem to be intending to link to a project/book/chapter/verse.  The quick fix is to render the link contents in a span.  In the future, we may try to support these links.
Here is an example value being sent to a 'link' blot:
```json
{
"style": "jmp",
"link-href": "prj:TNN.XXB.1.0",
"contents": {
"ops": [
{
"insert": "Guidelines for Using the Translator's Notes Series"
}
]
}
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2999)
> SF-3201 Fix broken editor jump links

- src/SIL.XForge.Scripture/Services/TransceleratorService.cs
- test/SIL.XForge.Scripture.Tests/Services/TransceleratorServiceTests.cs
A project had a file named `._Translated Checking Questions for 1SA.xml` which appeared to have binary garbage in it. This improves the filtering to more carefully match only the correct Trascelerator files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3007)
> Fix filtering of Transcelerator files

- .github/workflows/build-and-test.yml
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.spec.ts
We frequently end up merging tests that pass but cause warnings to be printed. This updates the workflow to try to stop this. Initially, this branch will fail *on purpose* to prove the change works. Then it will be updated to fix the warnings.
Actually, not sure if that strategy will work, because maybe it will run the workflow as it already exists on master.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3008)
> Prevent front-end tests from passing when warnings are printed

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
I put this test in a loop and ran it 100 times. With an 1100ms delay, it failed 56 times. With a 1200ms delay, it didn't fail once. I don't think in practice this means this test will completely stop failing, but it should be a lot less frequent.
Note that if the delay is set to 1500ms, it starts failing with another error. This is a very short audio file, and we're trying to pause it after 1s and before it finishes playing, so we can see a paused state. If I log the duration, it's `1.296`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3019)
> Fix common audio test failure

- mongodb/Projects/LatestSyncInfo.mongodb
- mongodb/Projects/SyncFailureCause.mongodb
This is useful for when you have several projects complaining of problems, you can add them to this query, run it, and see the error (or success) each one has.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3010)
> Add Mongo query to find latest sync results for group of projects

- mongodb/Texts/CorruptedTexts.mongodb
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
This will ensure chapters corrupted in this way can not continue to be edited.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3022)
> Update definition of corrupted chapter to include insert.link bug

- .github/workflows/chromatic.yml
As storybook tests require the `storybookUrl` value from Chromatic, this PR forces Chromatic to rebuild, even if it thinks there are no changes.
For the reason behind this change, please see the "Publish to Chromatic" and "Run Storybook tests" sections of https://github.com/sillsdev/web-xforge/actions/runs/7277973553/job/19836485161
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2255)
> Force Chromatic Rebuild for Storybook

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss
This focuses on both checkers and admin's, with checkers being the primary target.
- Slightly narrowed the book-chapter chooser. I'm aware there's an existing refactor to this, so hopefully it will make this less necessary
- Moved chapter audio next to the book-chapter chooser. This makes a little more sense for checkers, since the chapter audio is near the chapter selection
- Removed circle outline from chapter audio icon
- Moved Add Question button to question nav panel. This is still a logical place for it to live, and it fixes a run-off issue for admin's
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2993)
> SF-2864 Fix icon run-off on smaller mobile devices

- src/SIL.XForge.Scripture/Models/ParatextProject.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR adds an additional property to the /paratext-api/projects endpoint to express whether a project has drafting enabled or not.
This will make it easier for the Paratext Extension to determine what projects can be connected to that already have pre-translation drafting enabled.
This PR is marked as testing not required, as it is an API endpoint change, and so can be tested by a developer as it does not change user experience.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3002)
> SF-3202 Add IsDraftingEnabled flag to Projects API

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.service.ts
This fixes a bug where the cached projects state variable was wrong. The projects list can change, but it was never updated. Now we listen to the projectDocs$ observable and refresh the paratext projects list if the former changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2998)
> SF-3138 Update projects list dynamically in Add Resource dialog

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
This PR updates the existing Cancel Draft dialog to always display when a user selects to cancel a draft. This is intended to reduce incidental cancelation of drafts because of different draft build states allowing cancellation without displaying the prompt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3021)
> SF-3206 Display Cancel Draft dialog regardless of build state

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
We've had some recent problems with error reports that don't describe the actual problem. Having an error ID is useful when it's found in Bugsnag, but not all errors get reported there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3029)
> Add error message to error report email

- .github/workflows/build-and-test.yml
- .github/workflows/chromatic.yml
- .github/workflows/ci-lint-prettier.yml
- .github/workflows/ci-production-build.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
- src/SIL.Converters.Usj/SIL.Converters.Usj.csproj
- src/SIL.Converters.Usj/packages.lock.json
- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/packages.lock.json
- src/SIL.XForge/SIL.XForge.csproj
- src/SIL.XForge/packages.lock.json
This change introduces dependency caching for the build workflows for both the dotnet application and the Client application. The dotnet application needed to have dependency locking switched on which introduced the `package.lock.json` files in the `SIL.XForge` and `SIL.XForge.Scripture` directories.
If you open the Build / build and test and the Build / Production build and test github checks, you'll see that the cache was hit, meaning that dependencies were used from the cache rather than downloaded through the network.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3028)
> SF-3217 Cache build dependencies

- .github/workflows/codeql.yml
This PR fixes the CodeQL crashes by ensuring that the dotnet and node dependencies are all set up before starting the C# CodeQL action.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3041)
> SF-3220 Fix CodeQL crashes

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.html
This PR fixes a problem where the training data files available are not updated correctly when files are uploaded or deleted.
Additionally, the training data multi select had a warning tracking the files in the for loop. I updated the track parameter to track the training data file's dataId
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3030)
> SF-3222 Fix training data files not updated after file uploaded

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR adds a message when the previous version of a text was successfully restored and warns the user if the restoring a previous version failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3033)
> SF-2799 Notify user when previous version is restored

- .github/workflows/release-live.yml
- .github/workflows/release-qa.yml
release-qa.yml job deploy can't access secrets without an
`environment`. But it can't use an `environment` without a `runs-on`.
But if it has a `runs-on` it can't have a `uses`.
In investigating solutions for this, I observe that release.yml job
deploy should be able to access secrets anyway from its specified
environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3045)
> ci: rely on called workflow environment secrets

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.stories.ts
This PR updates the language code confirmation component to get its drafting sources configuration from the parent component. This is preferred since the new draft configurations architecture will come from a temporary config rather than saved to the project. Most of these changes were first introduced in code review from SF-3162.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3042)
> SF-3230 Get draft configuration for language code confirmation from parent

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-clipboard.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-clipboard.ts
This PR fixes an issue where, when pasting text into the editor with multiple newlines that aren't consecutive, only the first newline gets replaced with a space.  Also added replacement of tabs with space.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3039)
> SF-3228 Replace multiple newlines and tabs with space on editor paste

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab/tab.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
This PR fixes NG0955 warnings due to loop track expression targeting `tab.type`, since there can be multiple tabs of the same type, such as multiple resource tabs.  You can reproduce this warning by adding multiple resource tabs.
Added an `id` prop to `TabInfo` for angular to track instead.  The `id` prop is assigned a UUID upon tab creation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3047)
> Fix editor NG0955 warning

- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/paratext-project.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
- src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
- src/SIL.XForge.Scripture/Models/ParatextProject.cs
- src/SIL.XForge.Scripture/Services/ISFProjectService.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR addresses the issue where users roles have been updated in Paratext but not reflected in Scripture Forge. Primarily when a user is changed to an Paratext Administrator they do not have administrator access in SF until another admin runs a sync.
My Projects page UI change:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3012)
> SF-2829 Allow paratext roles that have changed to be updated

- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts
This PR:
- Changes the draft sources UI from `projects/:projectId/draft-sources` to `projects/:projectId/draft-generation/sources`
- Updates the navigation component to ensure the draft generation nav item is highlighted when on this page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3053)
> Highlight generate draft nav item when editing draft sources

- src/RealtimeServer/common/realtime-server.ts
- src/RealtimeServer/package-lock.json
- src/RealtimeServer/package.json
- src/RealtimeServer/typings/sharedb/index.d.ts
This PR upgrades sharedb to version 5.1.1 on the realtime server. This may be a safer way of upgrading because we can have confidence that having sharedb at version 5.1.1 is still compatible with clients on the previous sharedb 1.9.2. Then we can upgrade sharedb on the client app.
From running the realtime server tests, I found some deprecated messages that needed to be addressed
- updated realtime server constructor initializes ShareDB with `doNotForwardSendPresenceErrorsToClient`
- updated to mongodb 4.17.2 to satisfy the punycode deprecation warning (but it seems we should upgrade to further to 6.x)
Things I checked:
- the breaking changes from shareDB 1.x to 5.1.1 do not affect us (most breaking changes are dropping support for older versions of node).
- our sharedb extended classes …
> SF-3188 Upgrade to ShareDB 5.1.1 on server side

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
This PR addresses the source panel not being displayed at times. If the project has a selected source and the user is a Paratext user we want to always display the source side panel (except on small screens where the source and target are both tabs). Cases where the source panel would automatically hide were if there was a permissions issue for the user on the source or no book found in the source. We now keep the source panel open and display a message to the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3051)
> SF-3211 Show source panel in editor if project has source selected

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This PR fixes crashes that occur viewing or applying a draft, when a source book's book id is the wrong case, and the draft was generated from that source.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3062)
> SF-3240 Fix crashes when a draft book has an invalid book id

- src/SIL.XForge.Scripture/ClientApp/src/_text.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-blots.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-blots.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-registrations.ts
This PR creates a custom `ScrollBlot` to override Quill's scroll blot and an `UnknownBlot` to render when an unknown blot type is attempted.
If an unknown blot type creation is attempted, the custom `ScrollBlot` catches the error and creates the `UnknownBlot`.  After the editor renders (via `setTimeout()`), an error is thrown displaying the name of the failed attempted blot.
`UnknownBlot` uses `tagName = 'sf-unknown'`, ('span' was causing it to be incorrectly matched from a quill registry query and throw an `after.appendChild not a function` error).
You can test this blot by adding TNN as a resource.
Example:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3052)
> SF-3212 Create 'unknown' blot as fallback blot

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
This change shows the add to different project option for translator users. Originally only admins could do that, but now we want to open the feature up to all admins and translators on a project.
The user must still choose projects they have permission to edit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3065)
> SF-3242 Show option to add draft to a different project to translators

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
This addresses the querySelector made for querying the source quill editor placeholder text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3067)
> Fix selector in editor component test

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
This change moves the code to use the projectToDraftSources utility function rather than accessing draft sources from the project document. Testing is not required since it is a refactoring and most changes are on the serval admin area.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3068)
> Add support for arbitrary number of sources in Serval admin components

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
If the draft generation page hasn't been refreshed recently, the user may not know when another draft job has been queued. If he then attempts to configure and start a new job, the request will silently fail. This code changes the "startBuild" method to check if an existing build is present for the project, and if it is, it instead will show a notice, update the page with the running job, and send them back to the landing page.
We opted for this design, as opposed to a more elegant one, since the user really shouldn't be in this state. This was chosen for expediency over something like setting up cross-client notifications with project-notification.service.
- - - …
> SF-3205 Handle start draft requests when a job is already running

- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
I toyed with the wording a bit here, but I believe what's there is a good improvement and addresses JoEllen's concern
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3076)
> SF-3226 Clarify wording for canceling draft

- mongodb/Users/CountFirstRolesOverTime.mongodb
I wanted to figure out how roles on SF have trended over time, and especially how many new users have joined with each role. Of course, a user can have multiple roles, but in this case I went with the role of the user on the first project in the user's list of projects. The results are in the metrics folder in the team drive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3070)
> Add query to count users by first role over time

- .grit/patterns/remove_non_null_assertion.md
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-input-form/checking-input-form.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-history.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
I applied the Grit pattern, then checked out all files that had build failures. That means there are *lots* of unneeded non-null assertions in files that also have non-null assertions that _are_ needed, and can't be automatically removed as easily.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3077)
> Remove a number of unneeded non-null assertions

- src/RealtimeServer/common/services/doc-service.ts
To stop doc creation conflicts, MongoDB adds a `_create` property to the `_m` metadata in MongoDB.
This PR updates our validation schema to check for this object. It is not required as pre-5.1.1 documents will not have this object.
The code in ShareDB that writes this object is here: https://github.com/share/sharedb/blob/master/lib/submit-request.js#L213
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3086)
> Update validation schema to support ShareDB 5.1.1

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
**NOTE:** This PR is against an un-merged branch, not against master.
Prior to this change, if the user changed the selected sources, the language code confirmation checkbox didn't get reset.
The meat of this change is in `language-codes-confirmation.component.ts`, where I made the value be able to be set and also have the value emitted.
This allowed the use of [the banana-in-a-box syntax](https://v18.angular.dev/guide/templates/two-way-binding) for two-way data binding:
```html
[(languageCodesConfirmed)]="languageCodesConfirmed"
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3089)
> Fix language code confirmation in draft sources component

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
Note: This PR is against the feature branch `task/sf-3238`
This PR will hide the button to configure draft sources if the user is not an admin or if the user is offline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3092)
> Only show configure drafting button to admins

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
This has been bugging me for a long time. The button has always been red on hover, but until this change wasn't red before hover.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3093)
> Fix appearance of draft generation error button

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
**NOTE:** This is a PR against `task/sf-3238`, not `master`
To test this, try saving both as an admin (which does have permission), and as a translator (which does not have permission).
Stopping translators from getting to this page will be a separate task.
The implementation here feels quite bad to me, and it doesn't feel like we're handling all the save/sync states completely properly, but it seems to work for the scenarios I'm testing. We will likely need to revisit this later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3091)
> Show error state when failing to save draft sources config

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
See Chromatic/Storybook for the visual change
- Add open/close indicators to accordion headers
- Remove arrows from next/back buttons since they point horizontally and the actual direction they go is vertical
- Change the text on the back button to previous
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3094)
> Improve draft sources accordion UI

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
When a project without a source starts a pretranslation build, the build never starts because there is a silent error. This change reports the error and shows the draft as failed.
I have marked this as testing not required since developer testing should be sufficient.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3098)
> SF-3260 Show error when draft fails because source is not specified

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
The updateOfflineData method in project-data-doc.ts makes a call to updateFileCache which means that we do not need to call that in the subclasses like question-doc.ts. Additionally, there was an extra call when saving an answer which was unnecessary because the savedCallback property was already assigned to update the audio cache when saving an answer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3082)
> SF-3218 Update audio cache for questions when needed

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
This updates sharedb on the client side to version 5.1.1. The server side version is already up to date at 5.1.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3064)
> SF-3188b Upgrade to sharedb 5.1.1 on client app

- src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html
Angular prints this warning due to this component's track expression:
> NG0956: The configured tracking expression (track by identity) caused re-creation of the entire collection of size 25. This is an expensive operation requiring destruction and subsequent creation of DOM nodes, directives, components etc. Please review the "track expression" and make sure that it uniquely identifies items in a collection. Find more at https://angular.dev/errors/NG0956
This change addresses that warning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3103)
> Fix project select track expression

- src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR removes the requirement for source project to be set for NMT drafting. However, a training source or alternate source must be set for a build to start successfully.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3100)
> SF-3214 Allow project to start a draft when alternate training or drafting source is set

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
- Show error instead of warnings when source-side languages are not all the same
- Show distinct error message if the user tries to save when languages are not all the same
- Remove language code confirmation from the first drafting step
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3101)
> SF-3273 Require all source-side languages to be the same

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR adds a notice to direct users to ask an admin to configure draft sources for translators since translators have no way to configure sources on a project that has no sources.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3102)
> SF-3267 Show notice to translator when draft sources not set

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
This PR addresses two bugs related to the same issue of overflow within the editor container. The quill editor overflowed below the text container causing the last few lines to be hidden in cases the target chapter had a lot of text. This also created an issue where if the user scrolled down and selected a verse at the bottom when refreshing or navigating back to the editor it would hide any app notices above the text container.
This change updates the notice to remain at the top of the editor and only scroll the quill editor. One test needed updated as the width of the editor was set extremely narrow (beyond real-world cases) and failed with this change. By setting the width and heigh to a more reasonable size the testing performs as expected. Updating the app notices to …
> SF-3245 Fix quill editor scroll and hidden app notice

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
When backend cannot update user from Auth0 profile, user is sent into a endless redirect loop.
This PR adds a dialog to pause the retry loop.  Error details will be sent to Bugsnag and logged to the console.  The dialog, itself, currently doesn't contain error details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3107)
> SF-3280 Fix login redirect loop

- .grit/patterns/import_from_lodash_es.md
- .grit/patterns/missed_nullish_assignment_opportunity.md
- .grit/patterns/xforge_common_absolute_only.md
- scripts/update_font_list.mts
- src/RealtimeServer/common/metadata-db.ts
- src/RealtimeServer/common/realtime-server.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-history.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
- Migrated `if ($expression == null) { $expression = $value; }` => `$expression ??= $value;`
- Updated all Grit lint rules to error when they fail (I recently created a PR that broke one of the rules, and couldn't see it without deliberately going to the checks tab of the pull request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3112)
> Use nullish coalescing assignment when possible

- src/RealtimeServer/common/models/user.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- src/SIL.XForge/Services/AuthService.cs
- src/SIL.XForge/Services/IAuthService.cs
- src/SIL.XForge/Services/UserService.cs
- test/SIL.XForge.Tests/Services/UserServiceTests.cs
As we no longer support login with SMS, this PR removes the logic and references to that feature from the code.
This issue requires a change to Auth0 that I do not have access to - [see comments](https://jira.sil.org/browse/SF-3279).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3108)
> SF-3285 Remove SMS login logic from app

- mongodb/EventMetrics/CountBooksDrafted.mongodb
The results of this query can be seen in the "Books drafted in Scripture Forge" file in the metrics folder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3110)
> Add query to count distinct books drafted

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/IMachineApiService.cs
- src/SIL.XForge.Scripture/Services/ISFProjectService.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/PreTranslationService.cs
- src/SIL.XForge.Scripture/packages.lock.json
- test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
- tools/ServalBuildReport/ServalBuildReport.csproj
- tools/ServalDownloader/ServalDownloader.csproj
This PR adds support for a new feature in Serval 1.9 to update translation engines rather than delete and recreate.
I also took the opportunity to improve logging of build cancellations, settings updates (i.e. when the build sources are configured), and when the webhook is run.
I have marked this as not requiring testing, as the changes are reflected in Mongo, not necessarily in the frontend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3104)
> SF-3274 Update the translation engine instead of recreating on language change

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Angular 18 uses ES2022 syntax that older browsers (like Safari 15) don't support. When I say don't support, I mean the user gets stuck on a "Loading..." screen. (i.e. really doesn't support!)
This is done by code in the polyfills, so we could potentially reduce the version of generated code to an earlier version of ES, or create a browserlistrc file to generate code for older browsers.
That said, although this dialog will not be shown on these older devices, I think it is helpful to document our supported versions here, so that we know what browsers will run Scripture Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3118)
> Update supported versions list

- src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
- test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
This PR fixes a regression where a project will fail to sync when there are missing chapters in a text. The sync will fail due to a problem where the DeltaUsxMapper toUsx() algorithm assumes that the first chapter is chapter 1, but if chapter 1 does not exist in the usx document, it will skip over all chapters, then it will attempt to append chapters to the end of the usx doc. Thankfully the scrText does not allow creating duplicate chapters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3116)
> SF-3286 Fix sync failed when chapters missing

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
When a project or DBL resource has a copyright, we want the copyright notice to be displayed in the editor. Currently we show it only on the Source tab but not if it's loaded in the Resource tab.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3088)
> SF-3259 Fix resources not showing copyright notices

- src/SIL.Converters.Usj/UsxToUsj.cs
- test/SIL.Converters.Usj.Tests/TestData.cs
- test/SIL.Converters.Usj.Tests/UsxToUsjTests.cs
- tools/Roundtrip/ConsoleExceptionHandler.cs
- tools/Roundtrip/Program.cs
- tools/Roundtrip/Roundtrip.csproj
- tools/Roundtrip/Roundtrip.sln
- tools/Roundtrip/RoundtripMethod.cs
- tools/Roundtrip/SequentialGuidService.cs
- tools/Roundtrip/usfm.sty
- tools/Roundtrip/usx-sf.xsd
This PR adds a tool that lets you test roundtripping of USFM to and from Deltas, and to and from USJ. This tool can be run against a directory that either contains SFM files (for example /var/lib/scriptureforge/sync/), or a directory containing zip files containing SFM files.
I ran this tool against the open.bible corpus (https://github.com/pmachapman/open.bible), and found 3 issues with the roundtripping:
* A bug with USJ conversion for USFM files with footnotes that contain a space between the footnote category and footnote reference, i.e. `\v 1 In the\f + \cat dup\cat* \fr 1.1`
* A bug with Delta conversion for USFM files containing only some chapters: https://jira.sil.org/browse/SF-3286
* A bug with Delta converison for USFM files containing alternate chapter numbers and a footnote …
> Add a USJ and Delta roundtrip tool

- src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
- test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
This PR fixes a bug where footnotes that are at the chapter level (i.e. were for a chapter number) were being subsumed into the para below.
I have run this fix against the [open.bible corpus](https://github.com/pmachapman/open.bible) using #3115, and no regressions were detected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3119)
> SF-3232 Allow chapter numbers to have footnotes

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
This PR changes the snackbar message to a dialog when a draft request is already queued. Developer tester is sufficient to merge this since it is a simple change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3128)
> SF-3269 Show a warning dialog when draft request is already queued

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
- src/SIL.XForge.Scripture/packages.lock.json
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
The little remaining work is blocked until ParatextData updates their code to remove DotNetZip, as well
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2967)
> SF-3159 Upgrade to SharpZipLib

- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/paratext-project.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Certain projects, including back translations, don't have known language codes until after they are connected (because the Paratext registry API does not provide it)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3126)
> SF-3288 Handle draft source projects that lack language codes

- src/SIL.XForge.Scripture/Controllers/ParatextController.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR grants the ability for serval administrators and system administrators to download DBL resources.
I have marked as testing not required, as this is a straightforward admin change, and not facing most users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3123)
> SF-3195 Allow resources from DBL to be downloaded by Serval Admins

- scripts/db_tools/package-lock.json
- src/RealtimeServer/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package-lock.json
This PR fixes the following issues raised via `npm audit`:
```
@babel/helpers  <7.26.10
Severity: moderate
Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
fix available via `npm audit fix`
node_modules/@babel/helpers
@babel/runtime  <7.26.10
Severity: moderate
Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups - https://github.com/advisories/GHSA-968p-4wvh-cqc8
fix available via `npm audit fix`
node_modules/@babel/runtime
@angular-devkit/build-angular  0.1000.0-next.0 - 19.2.2 || 20.0.0-next.0
Depends on vulnerable versions of @angular/build
Depends on vulnerable versions of @babel/runtime
Depends on vulnerable …
```
> Update node dependencies

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/packages.lock.json
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- tools/ServalBuildReport/ServalBuildReport.csproj
- tools/ServalDownloader/ServalDownloader.csproj
This PR updates to Serval.Client 1.9.1 (the version currently on QA), and updates the cancel build logic to use the new features of this release.
I am marking as testing not required, as testing can be completed by a developer due to the under-the-hood nature of this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3134)
> SF-3300 Retrieve the build id from the cancel build action on Serval

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Serval on QA has updated to version 1.9 which changes how special text markers are used. We need to advertise this to the user via a notice.
I have marked this as testing not required, as developer testing will be sufficient given the straightforward nature of this notice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3099)
> SF-3219 Add a message to drafting advertising the Serval USFM changes

- src/SIL.Converters.Usj/SIL.Converters.Usj.csproj
This PR fixes the following warning that is displayed when running `dotnet watch`:
```
dotnet watch ⚠ msbuild: [Warning] Found project reference without a matching metadata reference: D:\Source\Repos\web-xforge\src\SIL.Converters.Usj\SIL.Converters.Usj.csproj
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3136)
> Fix project reference without a matching metadata reference warning

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
This PR fixes a problem where the select for a share role has text that overflows on different languages. I looked at decreasing the size of the text, but in the end it looked a lot better configuring the select to grow with the text.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3138)
> SF-3294 Fix text overflow on share project role select

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
This PR fixes a bug where a Serval Administrator can receive "this project has been deleted" popup when viewing the event log in the Serval Administration area.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3122)
> SF-3204 Do not show project deleted for Serval Admin viewing Event Log

- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/paratext-project.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/utils.spec.ts
Clearing the first training source would incorrectly set it to the
source project.
The bug fix is in draft-sources.component.ts where we now pass
`definedReferences` and `definedSources` instead of
`this.trainingSources` and `this.draftingSources`.
draft-sources.component.html:
- I didn't see that the `loading ? undefined : ..` was working as
intended and removed it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3133)
> SF-3268 Fix clearing first training source

- src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
This PR fixes an issue where the project deleted or user no longer has access dialog appears multiple times when a user is removed from a project. This is because both the project component and app component had logic to show the dialog when the project doc is updated. This PR removes the logic from the project component so that the app component can handle showing the dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3124)
> SF-3189 Fix project deleted dialog appearing more than necessary

- src/SIL.XForge.Scripture/locales.json
Indonesian has been published to the Help Site and this PR updates the help links to navigate to `https://help.scriptureforge.org/id`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3144)
> Add url links for Indonesian on Help Site

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
The chapter number got dropped at some point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3142)
> Show chapter number when archiving questions in chapter

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR detects when a user has no translated books available for training and warns the user. This can occur if the user only has 1 books on the project or all of the books were selected on the previous step. This also cleans up some dead code in the spec file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3125)
> SF-3216 Warn user when no training books are available

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
If the app goes offline while configuring draft sources clicking the "Save & Sync" button will error out as internet connection is required. Following the behavior of adding a resource tab to the editor the "Save & Sync" button will be disabled and a message displayed letting the user know to connect to the internet to save the draft source configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3148)
> SF-3271 Prevent Save & Sync of draft sources when offline

- src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
- src/SIL.XForge.Scripture/Services/ParatextZippedResourcePasswordProvider.cs
- src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
- test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextZippedResourcePasswordProviderTests.cs
- tools/Roundtrip/Program.cs
- tools/Roundtrip/README.md
- tools/Roundtrip/Roundtrip.csproj
This PR adds support for roundtripping DBL resources to the round trip tool. I also took the opportunity to add unit test to the zipped resource password provider, as this class was needed by the round trip tool.
Running the tool on the `_Resources` directory on resulted in three resources that have roundtrip issues, which I have included a fix for. I then ran these fixes against the open.bible dataset, and the DBL resources on SF live.
I have marked this as not requiring testing, as it doesn't change the behvaiour of the SF internal logic, only exposes the `ParatextZippedResourcePasswordProvider` as a `public` class instead of a `private` class.
If you wish to test this, run against your Paratext projects directory (`/var/lib/scriptureforge/sync/` or `C:\My Paratext 9 Projects\`), and …
> Add DBL resource support to the roundtrip tool

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
This PR removes (by making private) some feature flags that have been permanently enabled for some time now.
As these feature flags refer to drafting, only basic testing of drafting functionality is required by a developer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3152)
> Remove permanently enabled feature flags

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/_checking-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/_checking-answers-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/_checking-comments-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/_checking-questions-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
This touches most community checking related components where needed.
It does **not** update include any updates to the Quill editor.
There are some colors left which need to be addressed separately i.e. the blue color of the like icon. There is also a mixin for icon size which needs to be refactored in a different way.
Dark mode improvements have been made.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3153)
> Improve theme support for community checking

- mongodb/Projects/FindReferencesToMissingUsers.mongodb
This PR adds a MongoDB script that finds the references to missing users in projects. These references will stop projects from syncing.
I have run this script on QA and live, and remove the relevant references (only 1 project on QA and 1 project on live were affected). Both of these occurred at the end of October last year, so I believe these were a temporary issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3165)
> Add MongoDB query to find references to missing users

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
- src/SIL.XForge.Scripture/appsettings.json
This PR is from a suggestion from @Nateowami to combine the subsume the allow fast training and use echo for pre-translation feature flags into the developer tools feature flag.
With this PR, enabling developer tools will cause the fast training and echo checkboxes to appear in the draft generation wizard.
I also took the opportunity to clean up the casing of dark mode, re-enable a disabled unit test, and clean up the feature flag server-side config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3162)
> Combine the fast training and echo feature flags into developer tools

- src/SIL.XForge.Scripture/ClientApp/package-lock.json
This PR fixes the following dependabot alerts:
* https://github.com/sillsdev/web-xforge/security/dependabot/202
* https://github.com/sillsdev/web-xforge/security/dependabot/203
* https://github.com/sillsdev/web-xforge/security/dependabot/204
I also took the opportunity to run a `npm dedupe`.
As these dependencies are dev dependencies, no testing is required beyond successfully PR build and test GHA execution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3166)
> Update build-angular to fix vite dependabot alerts

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
This PR changes the draft generation steps to use the `TranslationScriptureRanges` collection instead of the `TranslationScriptureRange` string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3151)
> SF-3315 Use TranslationScriptureRanges for draft generation

- src/SIL.XForge.Scripture/Services/IMachineApiService.cs
- src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
- src/SIL.XForge.Scripture/Services/IParatextSyncRunner.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs
- src/SIL.XForge.Scripture/Services/SyncService.cs
- src/SIL.XForge.Scripture/Startup.cs
- src/SIL.XForge.Scripture/packages.lock.json
- src/SIL.XForge/Realtime/IRealtimeService.cs
- src/SIL.XForge/Realtime/MemoryRealtimeService.cs
- src/SIL.XForge/Realtime/RealtimeService.cs
- src/SIL.XForge/SIL.XForge.csproj
- src/SIL.XForge/packages.lock.json
This PR fixes a memory leak when the Realtime Service checks if the Realtime Server is running.
Also, following the guidance on https://docs.hangfire.io/en/latest/background-methods/using-ioc-containers.html, I have updated the background job logic to execute jobs by their interface, and have included Hangfire.Autofac so that Hangfire uses a tagged lifetime scope, meaning the objects are correctly disposed within the object lifecycle.
This PR is marked testing not required, as a debugger with breakpoint is required to run the acceptance test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3147)
> SF-3198 Fix memory leak in RealtimeService from CheckIfRunning()

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
These two lines used to be here and were mistakenly removed in a previous PR. See the conversation about them here:
https://github.com/sillsdev/web-xforge/pull/3133#discussion_r2035736105
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3155)
> SF-3318 Skip prompt when no changes made on draft source page

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3170)
> Use alternate logo when web host is not Scripture Forge

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
See Chromatic for the before/after.
For a while I was confused why this mat-card didn't have the border radius applied properly, but the other cards on the page did, and there didn't appear to be any CSS difference. Eventually I concluded:
- If you set a background on an element, and a border-radius, that background follows the border radius
- If you have an element with a border radius, and inside another element with a background (but no border radius), you need to set `overflow: hidden` for the parent to constrain the background of the child elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3169)
> Fix border radius on draft sources stepper

- .github/workflows/codeql.yml
This may or may not fix the issue. See comment. It's probably worth running the C# action on this PR a number of times to see if it breaks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3171)
> Install NPM dependencies ahead of C# CodeQL autobuild

- .dockerignore
- src/SIL.XForge.Scripture/Dockerfile
This PR fixes building of the docker image, and moves the .dockerignore file to the correct location, modifying it to work correctly.
The best way to test this PR would be to merge it, then run the "Build Docker development images" GHA manually via https://github.com/sillsdev/web-xforge/actions/workflows/docker-dev.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3176)
> Fix docker compose build and correct the .dockerignore location

- src/SIL.XForge.Scripture/Services/IParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This PR improves performance of the configure sources API call by only retrieving the list of resources from the DBL once per backend API call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3175)
> SF-3333 Reduce calls to the DBL when configuring sources

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.stories.ts
This stemmed from a user workshop, where it was confusing that some workflows for recording audio didn't save the audio even after clicking the (first) save button. This fixes those workflows, such that users only have to click Save once, for each workflow. The dialog defaults to not requiring a manual save.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3159)
> SF-3298 Save recording automatically (except for inline recording)

- .github/copilot-instructions.md
The instructions give context to Copilot to help it do a better job.
There is some duplication. And it's not super elegant. And some
instructions are not exactly verified. But so far it has been useful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3172)
> dev: add copilot-instructions.md

- src/SIL.XForge.Scripture/ClientApp/src/_text.scss
- src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
- src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/_sf-tab-group-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/_biblical-terms-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/_editor-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/_editor-draft-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/_note-dialog-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
- src/SIL.XForge.Scripture/ClientApp/src/themes/_default.scss
This PR improves theme support for a number of components used in the translation editor part of SF.
A number of colors in Quill have also been updated but not everything. Some colors will not be related to the main theme palette but do need attention to better support dark themes. This work could be done at a similar time as working on the notice component which also needs better support for dark mode.
One area in dark mode I didn't complete is the background color of Quill when not in read only mode. Currently it is still the same as light mode. This could be changed to a lighter neutral tone but that will also require changing other elements to better suit the new background - I made an initial start on supporting different colors in Quill based on read only mode.
- - -
This change …
> Improve theme support for translate editing

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts
This change introduces a confirmation when a user tries to navigate away from the draft sources page when there are unsaved changes. It uses the window.confirm api to show the prompt. This shows the prompt when a user clicks back/forward on the browser or selects a page to navigate to so that the user will not mistakenly leave the page without saving their changes.j
Unfortunately this does not behave the same way if a user edits the url or refreshes the page, but since that is not as likely I think this is sufficient for the task.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3184)
> SF-3349 Prompt user when leaving draft sources with unsaved changes

- src/RealtimeServer/common/models/user.ts
- src/RealtimeServer/common/services/doc-service.ts
- src/RealtimeServer/scriptureforge/models/sf-project.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
This PR adds missing indexes to MongoDB to stop specific functions from running a COLLSCAN (i.e. reading every document in the collection). These functions are documented in the comment above each new index.
When SF is rebuilt and run, these indexes will be created automatically by the real time server.
I also added a feature to specify index options, as I needed to specify that the indexes for `SFProjectService.IsSourceProject()` were sparse, meaning that the properties were only indexed if they had a value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3189)
> Add missing indexes to MongoDB

- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- src/SIL.XForge/Services/ProjectService.cs
This PR:
* Improves real time server connection reuse when updating settings
* Reduces the calls made to ParatextData (for Projects) or the DBL (for Resources) for scenarios when:
* More than one user is on a project or resource
* A resource or project is used for both the training and translation sources.
Testing Notes:
* Retesting the SF-3333 (#3175) acceptance test will be sufficient. This can be done by a developer.
* I have re-run the SF-3208 (#3013) acceptance test for regressions (it passed)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3187)
> SF-3333b Reduce calls to the DBL, PT, and RTS when configuring sources

- mongodb/Projects/SyncFailureCause.mongodb
Previously this query found all sync errors a project has encountered. In practice, usually we want to investigate the most recent error or errors. I've updated the query so we can easily filter for only errors that have occurred within the past n days.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3194)
> Update query to find a project's most recent sync failures

- src/SIL.XForge.Scripture/Services/ParatextService.cs
Although SF-3166 (#2965) greatly reduced the occurrence of the following error:
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
```
I notice that these still happen on bugsnag (https://app.bugsnag.com/sil-international/scripture-forge-v2-plus/errors/681c30c6d383ca457857e620). As I just had this error occur to me on dev, I was able to investigate the program state when this crash has occurred, and have determined it was caused by an internal non-thread safe cache that ParatextData's `HgRevisionCollection` uses.
As our code does not use the cache (due to only reading each revision summary once), I have …
> SF-3166b Avoid using cache when generating revision summaries

- src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
Our h1's are currently using the default Material typography fairly pretty consistently. I removed one place, in draft sources, that differed, and I cleaned up a number of old/dangling rules and classes. For example, mat-headline-4 is not used in our current version of Angular that I can tell, it's been replaced with mat-headline-large.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3193)
> SF-3027 Consistent Page Title Styling

- src/RealtimeServer/scriptureforge/realtime-server.ts
This PR fixes a crash that occurs when a query specifies an invalid project id. This crash results in the entire real time server stopping until it is restarted by Hangfire.
You can recreate the crash and verify the fix by running the following code on the frontend, in a component that references the RealtimeService:
```ts
const parameters: QueryParameters = {
[obj<NoteThread>().pathStr(t => t.projectRef)]: { $ne: null }
};
await this.realtimeService.subscribeQuery(NoteThreadDoc.COLLECTION, parameters, this.destroyRef);
```
As this PR is very straightforward (adding a `.catch()` to the `.then()`), no testing is necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xfor …
> Fix realtime server crash when querying for notes for an invalid project

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
This change undoes a part of #2780, which introduced a bug causing checking-question to not update correctly when chapter audio is uploaded. The core of that fix, refreshing audio when the question doc changes, is still intact.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3192)
> SF-3334 Fix bug with updating scripture audio

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
This is a follow-up PR for SF-3349. If the user has saved their changes, then they will be able to navigate away from the configure sources page without the prompt about unsaved changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3191)
> SF-3349b Only prompt user about unsaved source changes

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
`FlatTreeControl`, `MatTreeFlatDataSource`, and `MatTreeFlattener` were deprecated.  This PR refactors the code to use the suggested `childrenAccessor` on MatTree instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3206)
> Rework deprecated mat tree classes

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.ts
This PR improves the processing of lynx diagnostics before emitting as `rawInsightSource$`, particularly adding a debounce to avoid emitting after each event URI (text doc id) when loading a new project.
You can test the loading speed by opening a DBL resource like 'NTV' with lynx enabled in QA vs this branch.
The problems panel still is slow to switch with many insights, but that will be improved in a separate PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3207)
> SF-3370 Improve lynx processing time when opening large projects

- mongodb/EventMetrics/CountBooksDrafted.mongodb
Before this change this query was producing results that were clearly incorrect (I would run the query weeks later, and numbers were going down instead of up, even though it was querying a collection that only has documents added to it).
I don't know what was wrong with it. Probably reading a bunch of Mongo documentation and carefully looking at it would reveal the problem, or I can just rewrite it to be short and simple, which is the approach I took.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3211)
> Fix CountBooksDrafted Mongo query

- src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts
QA is supposed to be a simulation of live, with the proposed changes to be shipped to live being the only variable we are testing (to the degree that it's possible/practical to do so).
The staging URL became unavailable, and this resulted in a test failure during the test team's full regression run.
(See https://jira.sil.org/browse/SF-3383. I didn't mark this as fixing that issue because really there isn't an issue, other than QA using the development help site when it shouldn't, and that incorrectly failing tests).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3212)
> Fix QA site mistakenly linking to wrong help site

- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- tools/CommitGenerator/CommitGenerator.csproj
- tools/CommitGenerator/CommitGenerator.sln
- tools/CommitGenerator/Program.cs
This PR fixes the 524 (HTTP timeout) errors thrown by Cloudflare, by removing the logic that checks if a revision had a change in a specific chapter. The reasons on why this logic should not be used are given in the code comment.
I've also included the tool I used to create the lots of revisions in a project, which I used to recreate the same environment as the projects on live that were encountering this issue.
I have marked this as testing not required, as the only real testing required is opening a history tab on the frontend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3216)
> SF-3388 Fix 524 errors when viewing chapter history

- src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.spec.ts
Beforehand, network changes would change the parent form's editability. What wasn't obvious was that changes to the parent's editability was overwriting the values of the child controls. So those need to be refreshed after the parent form is updated.
I also brought up the online subscription to our current best practices.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3217)
> SF-3384 Refresh Roles and Permissions form when network connection changes

- .github/workflows/build-and-test.yml
- .github/workflows/chromatic.yml
- .github/workflows/ci-lint-prettier.yml
- .github/workflows/ci-production-build.yml
- .github/workflows/codeql.yml
- .github/workflows/grit.yml
- .github/workflows/zizmor.yml
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions:
> If your repository uses GitHub Actions to perform required checks on pull requests in your repository, you need to update the workflows to include the merge_group event as an additional trigger. Otherwise, status checks will not be triggered when you add a pull request to a merge queue. The merge will fail as the required status check will not be reported. The merge_group event is separate from the pull_request and push events.
- I've updated every workflow that runs on PRs to run on merge queues
- I've also updated all pull request workflows to run on all PRs, since I can't think of a …
> Update workflows to support merge queues

- .vscode/extensions.json
The previous sass compiler (ritwickdey.live-sass) is deprecated. This is the recommended replacement. I've updated the [wiki page](https://github.com/sillsdev/web-xforge/wiki/Components-and-layout) that describes how this is used for our static page scss.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3226)
> dev: add updated live sass compiler recommendation

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This PR fixes the following crash detected on QA: https://app.bugsnag.com/sil-international/scripture-forge-v2-plus/errors/6836ea5f71e48b17c509d085
As this is a simple null check, I don't think testing is required, but if you do think it should be tested, I have written the acceptance test documenting what I did to recreate this issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3233)
> SF-3411 Fix crash when a scripture range is missing

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
This PR:
* Updates the frontend to show the draft revisions in descending order
* Updates the backend to return the draft revisions in descending order
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3229)
> SF-3400 Show draft history in descending order

- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
This PR displays the book names on the new draft history interface in a summarized format, i.e. Genesis - Exodus.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3248)
> SF-3390 Show book names in summarized format in draft history

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This PR allows users on the community checking app to select the book and chapter they want to navigate to without requiring the user to be on the "all books" scope. If the user does select a chapter or book with the select, the scope is automatically reset to all books and they will need to set the filter again to their preference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3223)
> SF-3322 Allow selecting book and chapter in community checking

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
An error appears when a user attempts to refresh the page on the configure sources page while offline. This fix updates the behaviour on the page so that it only makes network requests while online. Additionally, if we get offline errors on this page, the errors are suppressed. If the error is not network related, they get silently reported.
This error is hard to reproduce locally. The best way to test this is by merging it to master and testing on QA.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3266)
> SF-3343 Fix error when use refreshes configure source page while offline

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change fixes an issue where selecting the all books scope when there are no actively selected questions causes an error. The component can be in a state where there are no actively selected questions now that we can navigate to any book and chapter from any question scope. This was introduced in PR #3223
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3268)
> SF-3428 Fix error when selecting all books scope when no question selected

- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/Startup.cs
- src/SIL.XForge.Scripture/packages.lock.json
This PR enables `/swagger/` on QA, so that developers of extensions or modules that connect to Scripture Forge can have access to up-to-date API documentation.
I have also updated Swagger to the latest version (there were no real changes in this update that will affect us - see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3276)
> Enable Swagger on QA

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/_draft-history-entry-theme.scss
Before | After
-------|------
This brings the contrast ratio up to the AA standard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3278)
> Improve contrast of draft history cancelled indicator

- src/RealtimeServer/scriptureforge/models/question.ts
In my code review of #3262, I noticed that there were no indexes for the queries in the CheckingQuestionsService.
This PR adds a query that is used by `CheckingQuestionsService.queryQuestions()` and `CheckingQuestionsService.queryAdjacentQuestions()`.
The index when created looks like:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3275)
> Add index to improve question querying performance

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR adds valid USFM for chapter to the conditions for showing lynx insights.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3280)
> SF-3385 Hide lynx when chapter usfm is invalid

- .github/workflows/e2e-tests.yml
- src/SIL.XForge.Scripture/ClientApp/e2e/e2e-utils.ts
- src/SIL.XForge.Scripture/ClientApp/e2e/e2e.mts
- src/SIL.XForge.Scripture/ClientApp/e2e/record-mobile-checking-videos.mts
- src/SIL.XForge.Scripture/ClientApp/e2e/test-definitions.ts
- src/SIL.XForge.Scripture/ClientApp/e2e/test_characterization.json
- src/SIL.XForge.Scripture/ClientApp/e2e/user-emulator.mts
- src/SIL.XForge.Scripture/ClientApp/e2e/workflows/edit-translation.ts
- src/SIL.XForge.Scripture/ClientApp/e2e/workflows/generate-draft.ts
- src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3259)
> Add e2e test for editor and improve other e2e tests

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
This brings the display of the projects more inline with how we show projects elsewhere in the application.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3285)
> Add short name to confirm sources component

- mongodb/EventMetrics/CountBooksDrafted.mongodb
This query broke because the shape of the data we're processing changed, going from TranslationScriptureRange to TranslationScriptureRanges. This updates the script to handle both payload types, and outputs the data by book, and by project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3291)
> Update count books drafted query to support new event metrics format

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.ts
This PR fixes the issue where editor edits were causing "Loading..." to show for expanded nodes in the lynx problems panel.
Two issue were the cause of this:
-  In `LynxWorkspaceService`, `DiagnosticsChanged` event is firing multiple times for the same URI (once for each diagnostic source), causing insight ids to change for unchanged insights.
- In `LynxInsightsPanelComponent`, the processing of child nodes was only being triggered on expansion of the parent node, so if the parent node was already expanded when the edit was made, the child node would be stuck at 'loading'.
The first issue was fixed by grouping diagnostics in the `DiagnosticsChanged` event by source to prevent insight tracking for a different diagnostic source from being cleared when processing.
The second issue was fixed …
> SF-3430 Fix insight loading on editor edit

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay.service.ts
This PR fixes a timing issue that caused a null reference error due to the 'setTimeout' used when calling `ensureOverlayWithinEditorBounds()`.
- Changed `ensureOverlayWithinEditorBounds()` to use the instance variable `openRef` instead of passing in overlay ref.
- Added null check for `overlayElement` inside `ensureOverlayWithinEditorBounds()` method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3290)
> SF-3444 Prevent error when rapidly clicking Lynx panel insights

- src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
When a user wants to edit the project in a project select, they have to manually highlight and delete the currently selected project. This change updates the project select so that when a user clicks in the input, the currently selected project text is highlighted and the user can begin typing to clear the previously selected project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3261)
> SF-3276 Highlight text in project select when user clicks the input

- src/SIL.XForge.Scripture/Models/SyncMetrics.cs
- src/SIL.XForge.Scripture/Services/IParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- src/SIL.XForge.Scripture/Services/SharingLogicWrapper.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
- test/SIL.XForge.Scripture.Tests/Services/SharingLogicWrapperTests.cs
This PR resolves SF-3422 (a bug introduced by SF-3241 / #3061) by allowing Observers to sync projects if there are no outgoing changes to Paratext.
This scenario occurs if a project only has users who are observers in Scripture Forge, and this project is a source project for translation suggestions or drafting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3277)
> SF-3422 Allow source projects with observer permission to sync

- src/SIL.XForge.Scripture/ClientApp/src/app/permissions-viewer/_permissions-viewer-theme.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/permissions-viewer/permissions-viewer.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
Super minor, but nice to have. (GitHub Copilot did most of the work)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3309)
> Add dark theme support to permissions viewer

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/base-services/tab-factory.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.stories.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
This change enables the localizations for labels in the editor tabs and the add tab menu to update dynamically when the user updates the locale. To do this, I needed to update the type for the tab header text to be an observable rather than a defined string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3303)
> SF-3043 Update tab header localizations when locale updated

- src/RealtimeServer/scriptureforge/rightsByRole.json
- src/RealtimeServer/scriptureforge/services/training-data-service.spec.ts
- src/SIL.XForge.Scripture/Models/MachineApi.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- src/SIL.XForge.Scripture/Services/TrainingDataService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
- test/SIL.XForge.Scripture.Tests/Services/TrainingDataServiceTests.cs
This PR updates the machine-api backend to use the `rightsByRole.json` permissions rather than hardcoding an "is administrator or translator" check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3312)
> SF-3470 Use the rights by role permissions for the machine API backend

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This PR fixed the remaining issues with the new draft user interface. I have fixed each bug in a separate commit.
@Nateowami I am marking as a draft so you see if this fixes the issues you have been encountering, and if there are any additional bugs you are aware of to add to the  the ticket (https://jira.sil.org/browse/SF-3454)
Also, here is the interface for showing error details in a history item (the items will expand as data is available - this crash occurred before the build reached Serval):
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3297)
> SF-3454 Fix remaining issues with the new draft user interface

- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
This PR passes a tag to Serval, based on the Scripture Forge environment, so that the jobs in ClearML are tagged. These tags are only visible in ClearML.
See also: https://github.com/sillsdev/machine.py/pull/208
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3316)
> Add tags to Serval jobs based on the Scripture Forge environment

- src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
Recent changes to the configure sources page made the last step significantly taller, which resulted in some screenshots getting cut off. This increases the page size before taking those screenshots, then resets the size so full page screenshots won't be excessively tall.
The screenshots this outputs are already live at https://help.scriptureforge.org/preparing-for-ai-drafting#confirming-the-languages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3321)
> Update e2e screenshot sizes to fit new draft sources page

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/Services/SFProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
When a source project has failed its most recent sync attempt, it shows on the configure sources page as having failed to sync when the user saves their changes. This was not completely accurate because the page only reports the last sync state without actually attempting to synchronize the project.
This change updates the backend logic so that when a source project's most recent sync attempt has failed, saving the project as a source on the configure sources page will kick off a sync of the source project.
The steps to reproduce the issue require manually updating the DB. Developer testing should be sufficient to reproduce the issue and confirm this change works.
- - - …
> SF-3397 Synchronize drafting sources if needed when configured

- src/SIL.XForge.Scripture/ClientApp/src/styles.scss
A horizontal scroll bar appears when the UI is changed to RTL. I think this occurred when we updated to implement material theme, but I did not go back to confirm. This change removes the unnecessary horizontal scroll bar.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3263)
> Remove unnecessary horizontal scroll in RTL UI

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-util.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/string-util.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/string-util.ts
This PR removes the quotes from the sample text in the lynx problems panel.  Also, the sample text is split into pre-insight/insight/post-insight parts so that they can be styled differently.  Accordingly, the insight portion of the sample text is styled with background and text decoration like the editor insights.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3311)
> SF-3419 Remove Lynx problems panel quotes and improve styling

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR fixes the issue where "training files" was not being localized.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3325)
> Localize training files label in draft generation stepper

- src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
The updated screenshots are already published on these pages:
- https://help.scriptureforge.org/enable-community-checking/
- https://help.scriptureforge.org/managing-checkers/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3327)
> Add community checking screenshots to e2e tests

- src/RealtimeServer/scriptureforge/models/translate-config.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/Models/DraftConfig.cs
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This PR stores the developer only settings of fast training and echo translation engine on a project. The result of this is that future pretranslation builds will automatically have the fast training and echo translation checkboxes selected if the most recent build used those features.
However, if a user does not have the developer tools feature flag enabled, these settings will not be used on the build and will be reset to false on the project. It may be possible to avoid updating the settings when the feature flag is not enabled, but it seems more intuitive to keep the state of the draft config consistent with what was used on the most recent pretranslation build.
- - - …
> SF-3435 Save fast training and echo settings across draft builds

- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
The issue is minor, but the solution is pretty trivial. See https://v18.material.angular.dev/components/list/overview#action-lists
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3324)
> SF-1007 Allow selecting questions with keyboard

- .vscode/settings.json
- src/SIL.XForge.Scripture/ClientApp/angular.json
- src/SIL.XForge.Scripture/ClientApp/package-lock.json
- src/SIL.XForge.Scripture/ClientApp/package.json
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/insight-formatting-utils.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/insight-formatting-utils.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/insight-formatting.worker.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/quill-insight-render.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/tsconfig.spec.json
- src/SIL.XForge.Scripture/ClientApp/tsconfig.worker.json
- src/SIL.XForge.Scripture/Startup.cs
This PR drastically improves loading speed and UI responsiveness for projects with very large numbers of insights (> 1000).
- Added web worker to offload delta formatting operations from the main thread, improving performance and responsiveness.
- Added npm package `Comlink` library to improve working with web workers.
- Added worker named-chunk pattern to SPA routes.
- Included fallback to main thread processing if worker creation fails.
- Additionally, when adding the blot attributes to the editor delta, optimized by detecting the overlapping insight ranges and only calling the expensive `delta.compose()` after those cases and not after every insight (`delta.compose()` handles the case where insights have the same severity and overlapping ranges).
- - - …
> SF-3370 Add web worker and improve blot formats delta creation

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.directive.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts
Prototype bubble splash effect to add to various buttons as an angular directive.  Part of gamification initiative to add visual rewards for app actions.  The directive can be added to angular material buttons.  Currently, the angular directive is only in Storybook for preview and feedback.
```html
<button mat-flat-button sfBubbleButton color="primary">Mat flat button</button>
```
Sample buttons can be seen in Storybook under 'Misc/Bubble Button'.
**Note:**
- Added npm packages `sass-loader`, `css-loader`, and `style-loader` to be able to load the directive stylesheet in its story.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2013)
> SF-2193 Add bubble splash effect that can be added to various buttons

- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts
The avatar component switches to a different mode when the avatar fails to load. Up until now the tests had tried to load an avatar that doesn't exist from example.com, and then demonstrate the behavior when it fails. However, since the network request can take some time to fail, the screenshots could get taken before the avatar component changes modes. This commit switches to using localhost for the nonexistent avatar.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3351)
> Attempt to fix Storybook avatar tests

- src/SIL.XForge.Scripture/locales.json
Various systems are picky about the exact format of locale codes (e.g. Docusaurus and Crowdin might not expect the same format). I *think* Docusaurus is less picky than it used to be.
There isn't a real user-facing problem at the moment, and the server for the help site appears to be case-insensitive, but locally the capitalization sometimes becomes an issue when running the development server, which is case-sensitive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3352)
> Update capitalization of pt-BR help URL to match Docusaurus

- src/RealtimeServer/scriptureforge/models/sf-project.ts
- src/RealtimeServer/scriptureforge/services/sf-project-service.ts
- src/SIL.XForge.Scripture/Models/ParatextSettings.cs
- src/SIL.XForge.Scripture/Models/SFProject.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
- test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This PR adds a "Visibility" property to `sf_project` that will be set on the next sync of the project.
This should be tested by a developer, as this property is not yet displayed on the frontend in any way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3346)
> SF-2904 Store Paratext project visibility in the project document

- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Every time I look at this statement it feels disjointed from what follows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3353)
> Improve draft history configuration heading

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-filter.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-filter.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
This PR fixes both:
- SF-3443 Error when lynx nav to unsupported USFM chapter
- SF-3494 Lynx problems panel shows insights with no chapter permissions
Both issues are fixed by filtering out lynx insights for chapters that cannot be edited (no permission or invalid USFM).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3355)
> SF-3443 SF-3494 Filter out Lynx insights for chapters that cannot be edited

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
This PR updates the behaviour when opening a draft tab. If draft history is enabled, previous drafts will be shown on books and the menu to select historical drafts will be visible. If the draft history is not enabled, the previous behaviour is expected and the page will say that no draft exist for the book.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3343)
> SF-3479 Show previous completed drafts when opening draft tab

- src/Help/UpdateHelp/UpdateHelp.csproj
- src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- src/SIL.XForge.Scripture/packages.lock.json
- src/SIL.XForge/SIL.XForge.csproj
- src/SIL.XForge/packages.lock.json
- test/SIL.Converters.Usj.Tests/SIL.Converters.Usj.Tests.csproj
- test/SIL.Converters.Usj.Tests/UsxToUsjTests.cs
- test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
- test/SIL.XForge.Tests/DataAccess/BsonValueConverterTests.cs
- test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
- tools/CommentGenerator/CommentGenerator.csproj
- tools/CommitGenerator/CommitGenerator.csproj
- tools/RepoInfo/RepoInfo.csproj
- tools/ServalBuildReport/ServalBuildReport.csproj
This PR updates dotnet dependencies to latest versions, including ParatextData. These were all minor version changes.
The Nunit update highlighted a test that was incorrectly passing due to a bug in the version Nunit we were using.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3365)
> Update dotnet dependencies

- src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
This makes the text color on this page slightly darker from a contrast ratio of 2.67 to 5.74 (4.5 is the minimum for AA accessibility standards). However, since it's no longer transparent, it's also _lighter_ than before in dark mode, which was the impetus for working on this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3369)
> Adjust color of text on checking overview page

- src/SIL.XForge.Scripture/ClientApp/e2e/e2e-utils.ts
- src/SIL.XForge.Scripture/ClientApp/e2e/workflows/community-checking.ts
- src/SIL.XForge.Scripture/ClientApp/e2e/workflows/edit-translation.ts
I'm not clear exactly why, but when running on the Angular 19 upgrade branch, some of the Playwright locators find elements behind the dialog, leading a locator to match multiple elements. This updates the locators to be more precise, and continue to work post upgrade.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3380)
> Update e2e tests to work with Angular 19

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.ts
This PR adds styling fixes to better display the lynx dialog overlay (viewed by clicking a lynx warning lightbulb or error icon in the editor) in RTL direction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3367)
> SF-3451 Fix Lynx overlay RTL styles

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/base-services/insight-render.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/quill-insight-render.service.ts
This PR fixes an issue where the lynx overlay would not display when using the lynx problems panel to navigate to (and display the overlay for) an insight from a different chapter.
The fix involved waiting for the insights for the chapter to render before making the call to render the overlay.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3374)
> SF-3497 Fix no Lynx overlay when Lynx problems panel nav to another chapter

- src/SIL.XForge.Scripture/ClientApp/e2e/presets.ts
I designed the e2e tests to interact at similar speed as a user, to be able to actually watch what is going on, and optionally record them for debugging purposes. However, going slow doesn't need to be the default, and makes running them locally take longer unless you explicitly choose to use the fast option.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3387)
> Increase interaction speed of default e2e preset

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pseudo-localization.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pseudo-localization.ts
Also updated pseudolocalization to show word wrap problems better
Pseudolocalization shows no problem, because there's no space in the status text for English. However, some translated strings will show a word wrap problem, because they contain spaces.
I updated the logic to add a space in the middle of any strings that consist of a single word. This allows pseudolocalization to show white space problems before any translations have been completed.
White space issue is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3386)
> Fix word wrap of status text in draft history

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress-dialog/draft-apply-progress-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress-dialog/draft-apply-progress-dialog.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress-dialog/draft-apply-progress-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress-dialog/draft-apply-progress-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change adds an errorMessages property to the draft apply progress. We attempt to infer some information from any failures, based on where they occurred, and report that to the users via the new property. Sometimes exceptions can include an error code, but the error codes don't seem to be very valuable to the user.
Obviously we'll need to refine the error text content I used here.
This also, notably, makes the app no longer prevent applying when the target chapter has invalid/unsupported USFM. We now check whether the target is editable, less when it's invalid/unsupported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3357)
> SF-3476 Add error reporting when applying draft fails

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR prevents unpaired parentheses from being written to the database for Biblical Term Renderings. If not stopped, these will cause ParatextData to throw an exception and the sync will fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3378)
> SF-3512 Do not allow unpaired parentheses in BT renderings

- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
This PR excludes the id segment from the translated segment count, as this is a segment that is not translated, and will usually have text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3384)
> SF-3518 Exclude id segment from segment counts

- src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.ts
There is a linked issue, but most of the changes do not actually pertain to it.
Main changes:
- Clicking on the "Draft jobs" button on the Serval projects page now properly opens the jobs list filtered to just that project (That's what the linked issue is about).
- The jobs list isn't loaded until the tab is active, which means it doesn't load if the user is just looking at the projects tab
- We only fetch relevant events in the Drafting category (my testing shows about a 90% reduction in the number of events that end up loaded)
- Logic for correlating events is greatly improved. I used data from live in local testing to make sure it was working correctly.
- Projects used for training/translating data are now listed, along with which books are used
Given the current component on live is …
> SF-3526 Fix up Serval draft jobs component

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
- src/SIL.XForge.Scripture/Services/MachineProjectService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
I also added an optional parameter to the dialog service to disallow closing by clicking outside the dialog, since for this case, we want them to explicitly click the button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3381)
> SF-3488 Force refresh when draft config changes remotely

- src/SIL.XForge.Scripture/Services/TrainingDataService.cs
- test/SIL.XForge.Scripture.Tests/Services/TrainingDataServiceTests.cs
This PR allows CSV and TSV files that contain unmatched quote marks to be correctly processed as training data for Serval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3404)
> SF-3531 Allow CSV files containing unmatching quotes

- src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
The mistake in this file became evident when I ran `./update-help-site-screenshots.sh` and the screenshots in the help didn't match their context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3411)
> Fix screenshot name in localized_screenshots e2e test

- src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.spec.ts
The github-action-preview subdomain is not consistently updated, and expires after something like 30 or 90 days from its most recent deploy. There isn't a compelling reason to link localhost to it, and if for some reason that's helpful for testing, a developer can easily edit the environment file locally to make sure links work. Also, `./scripts/check_external_urls.mts` is our main way of making sure the app and new help site don't have broken links.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3410)
> Use production help URL in development environment

- src/RealtimeServer/.eslintrc.json
- src/RealtimeServer/scriptureforge/migrator.ts
- src/RealtimeServer/scriptureforge/services/note-thread-service.ts
- src/RealtimeServer/scriptureforge/services/question-service.ts
The change to the lint rule is copied from #3391. I then fixed the lint issues, and made them be considered errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3414)
> Enable promise linting in RealtimeServer

- src/SIL.XForge.Scripture/Services/ParatextService.cs
This reverts commit 254f660436dc0f3b98ac704a7cb8dd3670c38898.
This will revert Scripture Forge to use the same URL for the DBL as Paratext.
Users are encountering issues where resources they see in Paratext (i.e. the NIV84) are no longer visible in Scripture Forge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3421)
> Hotfix: Revert "Switch to new DBL server in prod environment (#3385)"

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR fixes a bug where notes cannot be reopened after editing when they are in `s_` section heading segments. This bug occurs because the editor will sometimes break the segment into two in the view (the data model is unaffected as ShareDB will recombine these segments into the same Delta).
While investigating, I also noticed a bug where the tooltip showed the wrong note count when a note thread contained deleted notes, which I have included a fix for.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3413)
> SF-3524 Fix bug where notes in headings cannot be reopened after editing

- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This PR adds support for rethrowing errors that occur in communication with Serval, which will cause the Hangfire job which is scheduled by the webhook to rerun up to a maximum of 10 times (the Hangfire retry default).
This should reduce some of the problems we have been seeing from the webhook appearing to have not run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3416)
> SF-3543 Rethrow webhook errors caused by Serval communication issues

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
Avoid a potential race in what menu items test 'navigate to last
project' finds by specifying NmtDraftAuthGuard.allowTransition.
As such, expect a 10th menu item of "Generate draft".
This test also slightly increases the coupling of the named menu items
in the comment with the count of menu items expected, as well as
changing from "Manage questions" to "My progress".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3445)
> Be specific about draft ability in app.component.spec

- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
This PR fixes a bug where community checking users could not view all texts in a project offline because they did not have a chapter permission record.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3436)
> SF-3563 Fix offline support for community checking users

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
This PR fixes a bug where books with many missing verse numbers showed incorrect progress. This is fixed by using the known number of verses in a book when that book has less than two third of the known verse segments present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3437)
> SF-3557 Improve book progress accuracy for incomplete books

- src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
This increases the number of lint warnings from 17 to 247.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3444)
> Enable no-floating-promises lint rule in ClientApp

- src/RealtimeServer/common/diagnostics.ts
- src/RealtimeServer/common/resource-monitor.spec.ts
- src/RealtimeServer/common/resource-monitor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3390)
> Store resource usage report in more persistent location

- src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
- src/SIL.XForge.Scripture/Services/ParatextService.cs
- test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
This PR fixes a bug where notes were incorrectly positioned in introductory paragraphs. This issues occured because the USFM segments in the introductory material were not being as paragraphs, and so the notes were being offset by the number of preceding introductory paragraphs, headings, identificatory tags, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3438)
> SF-3549 Position notes correctly in introductory paragraphs

- .github/workflows/build-and-test.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/release.yml
This line has started failing because while `dotnet --version` finds .NET, `dpkg` can't find .NET installed as a package (likely the image installs it via a different method).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3465)
> Fix GHA failures caused dpkg finding no .NET packages installed

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This PR adds guidance to the user to select formatting options for their draft from the generated draft tab. The "apply to project" button will be disabled as long as the user has not selected formatting options for their project. Once options have been selected, they can add drafts to their project from the generated drafts tab.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3447)
> SF-3566 Guide user to formatting options on draft tab

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.ts
This PR adds a null check to the `LynxWorkspaceService` to handle cases where a book/chapter may not have a defined chapter, which can happen when navigating to a book with no first chapter.
Also added a test case to for the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3457)
> SF-3561 Fix lynx autocomplete error when nav to book with no first chapter

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This PR fixes an issue where changing a user role to observer was not disabling lynx in the editor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3453)
> SF-3560 Fix permissions check for lynx to include role

- src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
Our segment count logic counts poetry break verse tag /b and chapter intro tag /ie as untranslated segments, which messes up the count on the Translate Overview. This should fix the issue for those tags, but there may be other tags that need to be ignored, too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3451)
> SF-3573 Exclude blank line tags from segment count

- src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-editor.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.ts
This PR fixes an issue where note embeds were causing lynx lib position calculations to be incorrect, as lynx lib uses the delta from the DB doc, not the editor delta which may contain note embeds.
The fix involves adjusting the offset used by lynx lib, subtracting the number of preceding note embeds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3470)
> SF-3579 Fix lynx autocorrect not working after note embed

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
- src/SIL.XForge.Scripture/Services/MachineApiService.cs
- test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
This PR updates the revision system. TextDocuments are saved that correspond to the most recent version of a draft. However, anytime a new format is introduced, a new version of the document is saved. So we cannot depend on the timestamp to help get the correct version. I introduced logic to use the most recent version of a document that comes before the next build. That ensures we get the right version of the document for an earlier draft.
There is still some clean up (like chapter number not being used). There are probably more tests that can be written too. But it is ready for review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3479)
> SF-3556 Wait for finishing build to complete before showing draft

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translator-settings-dialog.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translator-settings-dialog.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translator-settings-dialog.component.ts
This PR fixes an issue where the user lynx settings in the translator dialog weren't reacting to project settings changes.  The component in general was reworked to no longer reference getters and setters in the component template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3486)
> SF-3588 Fix translator dialog lynx master switch reactivity to project changes

- src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/data-loading-component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/paginator/paginator.component.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/subscription-disposable.ts
- src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.ts
This was done by running `npm run lint -- --fix`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3488)
> Remove unused lint directives

- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.spec.ts
- src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/3474)
> SF-3558 Update draft generation UI on language change
