src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.spec.ts

- Depending on the timezone of the machine running the tests the actual result my difer from the expected result. Have switched to use a regular expression to cover both options
I realize probably only affects me in NZ but it reports an error everytime I run my tests which is distracting :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2)

User Entry Unit Test Fix

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

- Questions pane no longer appears on top of the main navigation drawer on smaller viewports
- Progress circle now updates correctly if answers have been added to questions
- When the chapter changes the menu selector now auto focuses on the selected chapter when opened
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/50)

Checking App Bug Fixes (SF-313, SF-321, SF-323)

---

.vscode/extensions.json

* The eg2.tslint extension by Erich Gamma has been deprecated in favor of the ms-vscode.vscode-typescript-tslint-plugin extension maintained by the official Microsoft VS Code team.
* Add Angular Language Service - checks TS in HTML files, can Ctrl + click on methods, etc, in HMTL files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/53)

Update VSCode Extensions

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sfproject-roles.ts

- Admins can now only delete other users answers and comments
- Admins can no longer answer their own questions
- Admins will always see answers without needing their own answer
- Heading for answers changed for users when they don't have access to view all user answers
- Only admins will see unread answers/comment notification in the questions panel
- Users can now only see their answers when project settings are set to not allow answers visible to everyone
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/58)

Ensure use roles see relevant buttons (SF-279)

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html

added some selectors to allow HelpHero to find some elements that were otherwise not reliably selectable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/54)

Help hero additions

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts

For the validation error messages to appear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/84)

SF-341 Mark control as touched+dirty after chooser, to show messages

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts

* when logging in with Paratext, if the authorize app page is cancelled it now returns to the login
* also fixed error page still showing the loading bar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/90)

SF-64 Fix PT login auth access cancel

---

src/SIL.XForge/Realtime/package-lock.json
src/SIL.XForge/Realtime/package.json
src/SIL.XForge/Realtime/realtime-server.js

* ws dependency upgrade to fix security vulnerability
* update dependencies that already satisfy latest
* remove jsonwebtoken (now dependency of jwks-rsa)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/112)

Fix realtime server after dependency upgrade

---

src/SIL.XForge/Realtime/package-lock.json
src/SIL.XForge/Realtime/package.json

* added lodash dependency only to fix vulnerability of jwks-rsa and sharedb-access.
* reported in GitHub but not in `npm audit`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/114)

Security: update lodash

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- Add HelpHeroService to AppComponent to allow tours to auto-start on any page
- Resolves the following wrong-order warnings:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/120)

Resolve HelpHero warnings and enable auto-start on every page

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

This PR addresses the following error message:
Since HelpHero added a "skip" funnel feature, we don't need all of this manual flow-control, and so I deleted it. It seems like manually triggering tours causes this error, so I am switching to have HelpHero auto-start tours.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/121)

Fix SF-381 (Clean up tour triggers)

---

src/SIL.XForge/AssemblyInfo.cs
src/SIL.XForge/Controllers/ProjectsRpcController.cs
src/SIL.XForge/Models/ProjectEntity.cs
src/SIL.XForge/Utils/ISecurityUtils.cs
src/SIL.XForge/Utils/SecurityUtils.cs
test/SIL.XForge.Tests/Controllers/ProjectsRpcControllerTests.cs
test/SIL.XForge.Tests/Utils/SecurityTests.cs

The GenerateKey implementation was duplicated from a prior Security class in this repo's history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/117)

SF-345 Implement specific person sharing

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- Fix: Zoom in/out not working on Firefox
- Fix: Zoom in/out buttons are always available to click even if the toggle button wasn't clicked
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/144)

Firefox fixes (SF-388 & SF-374)

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar-testing.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar-testing.module.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/mock-avatar.module.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.spec.ts

* remove NO_ERRORS_SCHEMA
* remove CUSTOM_ELEMENTS_SCHEMA
* remove XForgeCommonModule
Note: NO_ERRORS_SCHEMA and CUSTOM_ELEMENTS_SCHEMA should not be used in tests because it might mask real errors. `XForgeCommonModule` should never be used in tests because it includes the `AvatarComponent` which accesses the internet. Use the `AvatarTestingModule` if needed instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/146)

Refactor Unit Tests

---

src/SIL.XForge.Scripture/wwwroot/css/sf.css

My Paratext account isn't confirmed yet, so I've just been looking for low-hanging fruit on the pages I have access to. The screenshots were taken in responsive design mode to keep them small, but there's no substantial difference in appearance between this and a large screen.
Before | After
-----|-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/174)

Improve styling of home page footer

---

README.md

Cloning a repo that ends with `.git` results in a directory without `.git` on the end. The instructions for the Vagrant install try to `cd` to `web-xforge.git`, but they should `cd` to `web-xforge`.
I ran into this because I started to try the Vagrant install before I realized bionic was now supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/173)

Fix README instructions for clone before Vagrant install

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.ts
src/SIL.XForge/Models/User.cs
src/SIL.XForge/Realtime/Server/src/realtime-server.ts
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

* use "displayName" instead of "name"
* populate "displayName" from "name" or "nickname" only on create. Nickname already contains the correct value from Auth0
The "name" field is overwritten from Auth0 on login so we store our own value that can be modified in "displayName".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/185)

SF-433 Use "displayName" for user

---

src/RealtimeServer/scriptureforge/models/verse-ref-data.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/scripture-utils/verse-ref-data-converters.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- Question icon now appears next to verse in Quill editor
- Verse range is underlined in Quill editor relating to questions
- Clicking a question in the Quill editor will now select the question to answer
- Active question will now highlight a question in the Quill editor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/184)

Show relevant question icons within the scripture text panel (SF-154)

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts

The "Update your name" dialog now requires that the name not be blank, and not consist merely of white space. No errors are shown until the user tries to save it or leaves the textbox.
@irahopkinson On the card you mentioned that "There is already code for checking the validity of this elsewhere." I looked high and low and couldn't find any validation of the name, on either the front end or the back end. That comment was about a month ago, so perhaps it changed between now and then?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/189)

Disallow blank names, fixes SF-390

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts

This is the second part of a fix for SF-421. The first part is #199. Both are related to audio not pausing, but I've kept them separate due to being fundamentally unrelated.
When switching books, the list of questions and the text are updated, but until now the question itself has not been updated. For that reason the audio didn't pause when switching books. It didn't have anything to do directly with audio though.
I also modified the edit-name-dialog test to close the dialog at the end of the test.
Integration tests are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/200)

Switch question when switching books

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts

Previously, when using the dialog box to select a reference, the reference input field was shown with a red border. This is because it's gained and lost focus without a valid input. The solution I'm using is to mark it as untouched if the dialog is opened while the input is empty. This may seem a little hacky, but I think it correctly reflects the semantics of the situation. The input field *has* lost focus, but it's lost focus to an element that is used to fill the field. The user is still interacting with it, so in a more useful sense it still has the focus.
Fixes SF-340.
Old behavior:
Integration tests are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/202 …

Don't show reference field as invalid when reference dialog is open

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/autofocus.directive.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

Answer and comment fields are focused using a new appAutofocus directive.
The email input in the share dialog is focused by removing the "default" attribute from the dialog's submit button, so it wouldn't steal focus from the input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/208)

Autofocus text fields

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts

A short while ago I added validators to `edit-name-dialog.component.ts`. It turns out we already have the same validator in XFValidators. This PR just changes it to use that canonical validator instead of a custom regex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/209)

Use XFValidators in EditNameDialogComponent

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

If an invalid reference is supplied and then the scripture chooser dialog is used, the end reference input should be enabled again. Previously it would remain disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/224)

SF-365 End reference disabled after using scripture chooser dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html

This just changes the order of the help menu entries, putting the version at the end. It's an absolutely trivial change to something that just struck me as a bit off.
Before | After
-----|-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/225)

Reorder items on help menu

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss

This restores the previous CSS that was applied to the `app-checking-text` element before the disabling of CSS view encapsulation for this component in d2aa29639912fbce452070239f3b4eca2b9e17f8.  The `:host` selector didn't get updated to `app-checking-text`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/227)

Fix layout of checking-text component during loading

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
src/SIL.XForge.Scripture/ClientApp/src/typings/recordrtc.d.ts

- Updating definition file for RecordRTC
- Changed recorderType to use StereoAudioRecorder for wider device/browser support
An issue was found on Safari on Mac as, in its current version, doesn't support the Media Streaming API - currently an experiemential feature only. This also applies to iOS. I've changed the recorder type over to `StereoAudioRecorder` which is supported across all. Have tested the following and the all record and playback fine.
Windows
- Chrome
- Firefox
- Edge on Chromium
Mac
- Chrome
- Safari
- Firefox
I've not fully tested Linux other than using vagrant box (on a Mac).
It is worth noting that on mac you can't install ffmpeg to `/usr/bin/` as it is locked off as an OS level - not even root users can touch it. It can only be installed to `/usr/local/bin/`. As a work …

Fix: Audio player on Firefox (SF-399)

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts

- Check for an exact match for clicking on a verse/question icon
- Have a fallback for a best match for a verse in the middle of a question
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/235)

Question icon does not navigate to an appropriate question and answer (SF-452)

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss

This was broken by me in 73f2e2466129270b2b00538553700c508c3288d7.
As far as I can tell, there are only two places this component is used, and both of them are now rendered correctly in both Firefox and Chromium.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/237)

Fix layout of app-checking-text in question dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

Fixes SF-460, where the menu for setting the text size was clipped when sharing was disabled. 
I thought the CSS I was removing might be used for something else, but after asking @nigel-wells about it, it appears it is no longer needed. As far as I can tell everything still looks correct in mobile and desktop view, for Chrome and Firefox.
Before | After
-----|-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/238)

SF-460: Fix clipping of text size menu when sharing is disabled

---

src/SIL.XForge.Scripture/ClientApp/src/app/app-routing.module.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-offline-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts

This PR addresses SF-408, an error in Firefox private browsing due to IndexedDB being unavailable (`window.indexedDB` is defined, but attempting to use it throws an error). While ideally we wouldn't depend so heavily on IndexedDB that everything breaks when it's unavailable, for now the best approach is to inform users that they need to use another browser or exit private browsing mode.
The best way I could think of to handle this is to deal with the error in the exception handling service and change the message to something more helpful if the problem is IndexedDB in Firefox. I'm not sure it's an ideal solution, but I don't think there's a way to detect this until the exception is actually thrown (Actually, it starts as a promise rejection. I'm unsure whether it's thrown at any point, …

Convert error component to dialog and address SF-408

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts

Hitherto the filter input on the admin page has filtered on name and email, but not displayName.
Unfortunately the searching feature relies on Mongo's `$regex` operator, rather than looking for an exact string match. I don't know a good solution to this. The email addresses I use locally are in the form of `a+b@example.com`. The `.` will match any character, and the `+` is interpreted as an operator, so even exact search terms sometimes don't match. This isn't a huge deal since it's on the system admin page, but it definitely feels wrong.
I looked into adding tests for this, but the way we mock the search feature of the user service, it doesn't even consider the query, so without major changes, the test would just be testing itself.
--- …

Filter by displayName on system administration users page

---

src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge/Services/IProjectService.cs
src/SIL.XForge/Services/ProjectService.cs
test/SIL.XForge.Tests/Services/ProjectServiceTests.cs

Remove unneeded system role argument.
---
In discussion, the system admin user listing area will not show invitees. This begins to address that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/248)

SF-359 Don't provide specific sysadmin access for invitee listing

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/255)

SF-468: Target editor does not display full width when no source

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts

Previously the error dialog would offer to "Show more" regardless of whether it actually had a stack trace to show. In some cases (e.g. network errors) there is no stack trace that can be shown, so this is unhelpful and makes the error dialog appear to be broken, in addition to whatever error just happened.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/259)

Only offer to show more in error handler when stack exists

---

src/SIL.XForge.Scripture/ClientApp/angular.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.defaults.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

Implements basic error reporting to Bugsnag from the front end.
- I have a ton of list items here, so checkboxes are for keeping track of which things are resolved. Some things should probably be put off until after merging, though we'll have to decide which ones.
- We now have a coresponding project on Bugsnag. I've sent a few errors in order to test it out and verify what will show up on Bugsnag.
- I've generated an "error id" for each event we send to Bugsnag. If the user clicks the mailto link to send an email, the error id is included so we can cross-reference issue reports with Bugsnag events.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/243)

Add Bugsnag error reporting to error handling service

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

Most of the work to fix the HelpHero tour was in the HelpHero editor itself. The one thing that needed to change in our code was that we need set a user property that indicates whether the user's name has been confirmed. When the tour runs we use this to determine whether the name confirmation dialog will open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/268)

SF-471: Handle name confirm dialog in HelpHero tour

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

The way I tested this was by killing the server. I assume this is similar to network errors where the server is unavailable for other reasons (e.g. the user's internet being down). It doesn't appear that there is a robust way to determine whether an error was caused by network issues.
Note that this will have merge conflicts with #272 (i.e., neither has merge conflicts with master right now, but once one is merged, the other will have conflicts with master). Since that is a very high priority PR, it's probably best to let that one be merged before this one. The merge conflicts won't be great; I just don't want the other PR to be slowed down at all. In the meantime this can be reviewed.
--- …

Notify user of network errors via snackbar rather than dialog

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Services/ProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

* Users specifically invited to a project but joins by an
* alternative method will have their share key removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/273)

SF-500 Remove share key when user connects to a project

---

src/SIL.XForge.Scripture/ClientApp/angular.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

- Launching of the error reporting component is now wrapped in a call to `ngZone.run`, so `ngZone.run` no longer has to be called inside the error component itself.
- Source maps are enabled in staging so Bugsnag can use them to show where an error occurred.
- Errors are reported to Bugsnag before logging them in the console. This is to prevent the logging from showing up as breadcrumbs in Bugsnag, where it is just noise. I've also wrapped this with try/finally so that the error dialog, reporting to Bugsnag, and logging to the console all happen independently of each other (one can throw an exception and the other two will still run).
--- …

Miscellaneous error reporting changes

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

A Bugsnag report shows Bugsnag threw an error because `notify()` was called with a non-error object. In general, if a promise rejection is unhandled and the rejection is an error, we want to report the rejection. But if it's rejected with a non-error object, then we want to report the error that is reporting the rejection (the "Possibly unhandled rejection" error).
There are multiple reasons for this, but the main one is that we want to see the stack trace associated with the original error that the promise was rejected with--not some stack trace to the deepest recesses of the promise implementation we are using.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/281)

Fix reporting of non-error promise rejections

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting.service.ts

When Bugsnag reports the breadcrumbs that lead up to an event, it includes the redirect from `/projects#access_token=some_token`. Access tokens shouldn't be ending up in our error reports, especially since errors could become issues in Jira, where they would be public.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/300)

Redact Auth0 access token from error reports

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss

* There isn't a perfect icon for this, but I think post_add is better.
* Part of the problem seems to be that the icon, without its label, is
too small. So increasing the size of the icon when it doesn't have a
label in xs.
* Editing the instruction to make it more clear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/299)

SF-551 Adjust icon, wording, to clarify Adding question on xs

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/project-deleted-dialog/project-deleted-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html

* Hitting the enter key while editing a form field can lead to unexpected results.
* Adding a type attribute to each button will explicitly allow a user to simulate submitting a form
* or prevent a click event from firing unexpectedly on the first button of the page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/304)

SF-554 and SF-555 Add type attribute to buttons

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts

* call updateScriptureEndEnabled during ngOnInit
to set the proper enabled state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/298)

Disable end reference on question dialog init (SF-556)

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* Use the currentUserId from the userService instead
of making a call to the backend to get a user
* Take a user as @Input from the parent component for
use in the calls that need a real user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/311)

Remove userService.getCurrentUser() request (Fix SF-563)

---

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html

It was going slightly too far to the right.
---
Tested in Firefox and Chromium, in 320px wide and really wide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/323)

SF-570 Restrict flexbox into narrow viewport

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

Previously, if users started editing their answer and then canceled the edit, the other answers could be shown as unread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/333)

SF-581 Answers should not be shown unread after canceling answer edit

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

While trying to troubleshot an unrelated issue I came across this code that seemed redundant:
``` js
if (questionDoc.verseRef.bookNum !== this.book) {
this.book = questionDoc.verseRef.bookNum;
}
if (this.questionsPanel.activeQuestionChapter !== this.chapter) {
this.chapter = this.questionsPanel.activeQuestionChapter;
}
```
Generally you shouldn't have to check that `a != b` before setting `a = b`, since the operation should be idempotent. Checking the setter for `this.chapter`, it is idempotent, so we can safely set `this.chapter` without first checking its value. The setter for `this.book` isn't idempotent, but I think it can be, and that's the change I made. I could be wrong about that though, in which case my change may have actually modified the behavior by making it return …

Make setter function in checking.component.ts idempotent

---

src/SIL.XForge.Scripture/Startup.cs

By default ASP.NET Core sets the `ETag` and `Last-Modified` headers when serving static files. When these headers exist, a browser should send a request to the server with the `If-None-Match` or `If-Modified-Since` headers set. The server can use these headers to determine if the file has changed and then send a `200` and the content if the file has changed or a `304` if the file has not. Unexpectedly, Chrome does not send a request with `If-None-Match` or `If-Modified-Since` headers set and just gets the file from the disk cache. You can find out more about the behavior of Chrome [here](https://gertjans.home.xs4all.nl/javascript/cache-control.html).
I believe that updating the server to set the `Cache-Control` header to `must-revalidate` should fix the problem. This should cause Chrome …

Set "Cache-Control" to "must-revalidate" for static files

---

README.md
deploy/vagrant_xenial_gui/Vagrantfile

---
I was in the neighborhood and so did some updates to the vagrant instructions and provisioning. 
I didn't look into why `dotnet clean` left a dotnet process around with no parent other than to observe that it only happened when run from the provisioning script, not when run by hand in a terminal. I don't consider the `pkill` and `rm` steps to be very elegant but they result in a working system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/331)

Update vagrant instructions and provisioning

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

So we don't continue to say there's no audio if there is audio.
I would have liked to stop recording using the Stop Recording button
but had trouble getting it to show up in the DOM when running tests.
-------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/348)

SF-579 Update validation in response to audio changes

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss

* rtl languages will be detected in the browser dependent on content
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/356)

SF-615 Support right to left languages in quill editor

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/Services/DeltaUsxExtensions.cs
src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

- normalize all data from PT API data to NFC
- insert blanks at the beginning of all paras
- insert blanks at the beginning of all cells
- remove type attribute from blanks
- determine size of blank from segment ref
- handle blank line style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/359)

Fix text corruption when USX is NFD

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts

* Telling the browser what language a text is may help with
hyphenation, etc.
* The language code is fetched from the project writing system tag. It
needs to be a BCP 47 language tag.
* Because of challenges in making a text.component.spec.ts, the test
was put in checking.component.spec.ts, which doesn't necessarily cover
usage from other areas like editor.component.ts.
----
Here is a screenshot of `lang` having been added to the translate component.
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/358)

Set HTML lang attribute for Scripture text area

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts

The latest build of QA has the following errors:
```
TypeError: Cannot read property 'canActivate' of undefined
TypeError: Cannot read property 'allowTransition' of undefined
```
These errors were introduced in e8fe19cf0e94a92603b5790a068a90f37e7ab755 (#354).
The way I used dependency injection worked in development builds, but broke in production builds, likely due to the AOT compiler. It appears the classes were constructed with undefined arguments.
To test this you'll need to run `ng serve --prod`. This often results in a `JavaScript heap out of memory` error. You can increase the memory limit by running it as `node --max-old-space-size=4096 ~/bin/ng serve --prod`. It's a pretty slow build.
In order to get things working with the production build, you'll need to edit …

Fix production build router guard dependency injection errors

---

lgtm.yml

Currently lgtm has not been analyzing C# due to an error when it tries to build it. This leaves us with several options:
1. Leave as-is, with no C# analysis.
2. Install the `node` and `npm` packages so it can build the C# (the reason it needs these is that `SIL.XForge.Scripture.csproj` specifies that `npm run build` and similar commands have to be run before buildilng). Installing the versions of the `node` and `npm` packages that are available in the repos resulted in `Maximum call stack size exceeded` (for unknown reasons), and would add additional time to the build.
3. Modify the offending `.csproj` file, or add another , so that lgtm builds without having to run node and npm.
4. Have lgtm skip the offending project file.
5. Have lgtm analyze C# files without building them. According …

Configure lgtm to analyze C# without building the project

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts

- in AppComponent, navigate to start when currently selected project has
already been deleted
- in SettingsComponent, navigate to start when project deleted by user
- in ProjectComponent, navigate to overview when no texts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/371)

SF-629: Infinite loop when deleting project

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

* When adding a question in the checking.component (not checking-
overview), select that question after adding it. This may result in
switching to another book or chapter.
* Tested on laptop and phone sizes. Tested from All Questions area and
from one book to another.
----
Screenshot showing that the Mat 1:2 question was jumped to, when I added it while looking at Genesis 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/368)

SF-614 Jump to newly added question

---

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

- properly handle a char element as the last node in a note element
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/377)

SF-634: Notes not properly round-tripped during sync

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts

After further discussion it was decided not to auto-fill the email address or figure out if the user already has an account. Instead, all share links will go to the signup page if the user isn't logged in already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/379)

SF-406 Send users to the signup page when they use a share link

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-styles.scss

- Added functions to text component to determine if the browser has applied LTR or RTL for quill
- Adjusted margins set for USX styles to take in to account LTR or RTL
- Highlighting question segments now also highlights similar verses i.e. verse_1_2/q1 and ignores segments that are blank
A discussion needs to be had around indenting and margins as, at least ont he project I've tested on, they look a little out of control and get worse the smaller the viewport. Might need to make use of vw and other @media queries
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/376)

SF-616 Incorrect styling of rtl languages

---

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

- remove all nodes except book elements from old USX
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/382)

Fix data corruption when USX contains no paras

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

* do not allow space breaks in chapter selection menu
* limit text component size to parent width
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/393)

SF-625 Flexible display for number in chapter select

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* When a user views a question, record the IDs of each current answer
in a list of answers to show.
* If the user has not yet answered the question, then add any newly-
received answers to the list, so that when the user answers the
question, all answers will be displayed.
* After the user answers the question, buffer any newly-received
answers from other users, and don't display them until the user clicks
a link to reveal them.
* The show-answers link is currently at the top of the question list
but needs moved out.
----
I struggled to find just the right terminology, or to apply it in consistent ways that were helpful. This patch isn't really "buffering" answers, so much as "holding them back" or not letting them in yet. I will welcome improved terminology suggestions :)
Followup PRs …

SF-617 Buffer new unread answers

---

src/SIL.XForge.Scripture/Resources/SharedResource.en.resx
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/SharedResource.cs
src/SIL.XForge.Scripture/Startup.cs
src/SIL.XForge.Scripture/appsettings.json
test/SIL.XForge.Scripture.Tests/I18N/SharedResourceTests.cs
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

* Add support to localize strings used in controllers
and services
* Internationalize SFProjectService.cs
* Add unit test to prove that all
the Keys appear in the english .resx file.
Note: I will follow this up with more i18n work if this PR is approved
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/397)

SF-667: Backend i18n

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

Replaces the start verse and end verse scripture selection method in the answers component with a dialog that allows selecting text with the mouse.
---
The layout looks pretty bad to me (the buttons in particular). I'm hoping it can be improved.
---
---
The gray selection color is due to the dialog losing focus when I took the screenshot, and is my system default, not a style set in CSS. Notice that the selection is expanded to word boundaries.
---
---
Again, this doesn't look like a very nice layout to me.
This is a draft pull request because two tests are failing, and I don't know how to fix them. It's caused by this change in `text.component.ts`:
``` diff
-    Promise.resolve().then(() => this.adjustSelection());
+    if (!this.isReadOnly) {
+      Promise.resolve().then(() => …
```

SF-621 Add scripture text selection dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss

Before | After
-------|------
Note: The excessive scroll bars only exist in responsive design mode on desktop. On Firefox mobile they do not show up.
This accidentally slipped through in #396. I'm not sure exactly how, but I know it wasn't originally broken, so my guess is that it happened in a rebase. I did see this issue pop up after a rebase and fixed it, but I didn't check the responsive design mode, where my fix apparently did not apply.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/408)

Fix text selection dialog layout on mobile

---

src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

Removed:
- `@angular/platform-server`
- `file-saver`
- `zxcvbn`
And the associated types:
- `@types/file-saver`
- `@types/zxcvbn`
And from RealtimeServer:
- `lodash`
- `@types/lodash`
Both `core-js` and `@angular/pwa` appear to be currently unused, but I left them because I thought we are likely to use them in the future.
Perhaps some of these packages need to remain, however, I couldn't find that they are actually used. Everything builds fine (including a production build), the tests pass, and the app seems to work fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/409)

Remove unused npm dependencies

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
src/SIL.XForge/Configuration/AudioOptions.cs

- Fixes two lgtm alerts (unused imports)
- Makes imports that start with `src/` relative (`../`). I'm not sure this is important, but we've been standardizing on it. If it is important, I have a very simple lgtm query that can catch this. I just don't know if it's actually important or not.
- Also fixes spelling in order to fix a C# doc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/410)

Fix lgtm alerts and non-relative imports

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

* Restructuring layout.
- Adding more divs to checking-answers html, to separate the banner
from a now-scrollable area, both in a flexbox column.
- The scrollable area changed from being an as-split-area to being
.answers-component-scrollable-content.
- answer-panel needed height 100% as part of making the rearranged
layout work.
* Adjust checking.component calculateScriptureSliderPosition() to give
a desirable amount of height to the answer panel when the question is
navigated to or after the user shrinks the panel.
- There is a minimum height that will show (1) just the question, the
answer count and the show-more-answers banner if present, or (2) just
the question and the add-answer button.
- Clicking the same question in the list a second time will display
the answer panel at a height …

SF-617 Pin show-unread banner to bottom of answers area

---

.lgtm/javascript-queries/import-relative-to-project-root.ql

Finds imports that start with `src/`.
This has been tested. To see the kinds of alerts it would produce, see https://lgtm.com/projects/g/Nateowami/web-xforge-test/rev/pr-3ed316089d950f77aeb60176c42872419ef2ad96
I'm pretty sure this won't take effect immediately upon being merged, but after a day or two.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/414)

Add lgtm query for js imports relative to project root

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- add trainSelectedSegment() to SFProjectService
- preserve current segment when switching books or chapters
- ensure that the correct source segment is selected when focus returned
to selected target segment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/423)

Train saved segment before updating last user location

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* So that back at the 'Add answer' screen, there is not also a 'Show
unreads' banner.
* Add unit tests regarding the 'Show unreads' banner and
buffering remote answers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/420)

SF-617 Release pending answers from buffer if user deletes own

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* The project admin was seeing new answers right away without them
being held back with a show-more banner. This is because a project
admin isn't shown the 'Add answer' screen even if
currentUserTotalAnswers === 0. They are just shown the screen with a
list of answers.
* Check if the current user is even able to add an answer when
deciding whether to buffer. If they can't then buffer.
* Then it successfully buffers for a project admin.
===
See attached 1-minute animation where incoming answers are buffered for a project admin (on the right) even tho the project admin owns no answers. This is demo'd with only a couple answers, but will no doubt more clearly be useful when there are 20 answers.
--- …

SF-617 Buffer answers if can't add answer

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

There turned out to be two problems here:
1. The main component (`#text-panel`), being a child in a flex layout, automatically has a `min-width` of `auto` (content size). This allowed its content to overflow the parent.
2. Some of the tabs were hidden, and this appears to mess up the automatic scrolling functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/431)

SF-663 Fix answer tab overflow

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* Splitting up the h3 conditionally, and adding spans, to make testing
the DOM simple.
* Adding similar assertions for 'Show unreads' banner answer count
from DOM.
* Styling .answers-component-footer button was needed to maintain
spacing in the 'Show more' button around the unshown answer count.
==
See animation where answers header includes the count of buffered/unshown answers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/429)
Update: Testing the change to use "ngIf else" shows that it correctly works with respect to "See other's answers and comments" and still shows the correct count in the header when it shows a count.

SF-617 Include buffered answers in total answer heading count

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* ..., including buffered answers.
* Otherwise, a project admin can be looking at a screen with no
answers, no answer header, and a banner saying 'Show 1 more unread
answers'. Now the project admin will also see a header saying '1
Answers'.
===
A key change here was changing from using `answers.length` to using `this.totalAnswers`.
See animation below, where the project admin on the right-hand screen sees a total answer count even if all answers are buffered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/434)

SF-617 Show total answer count header if there are any answers

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

===
See animation below
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/435)

SF-617 Do not show 'show more answers' banner if editing an answer.

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* If the project disallows users seeing each other's answers, don't
show a show-more-answers banner to users.
* But show it to project admins still since they can see all the
answers.
* 'Your answer' should continue to show to users if they have an
answer on a not-see-others-answers project.
===
See 1:20 animation showing the behaviour of the dont-show-others-answers setting on whether the show-more-unreads banner displays for checkers and admins (the admin is on the right), whether checkers see 'Your answer' or 'n Answers' in the answer list header, and that an admin sees 'n Answers'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/436)

SF-617 Don't show show-more  banner to users if can not see others ans

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/browser-globals.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts

A number of tests produce a significant amount of logging in the console, resulting in a noisy output. This is especially bad in the exception handling service, which logs errors complete with stack traces. I've mocked the console object to suppress messages that are expected.
There are also some places where the tests overwrite a global variable in order to mock it. This works, but is rather hackish. In the places I'm aware of that have this issue, the global value (e.g. document, console, navigator) is now injected so it can be mocked in the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/433)

Inject browser globals and mock them in tests

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

Before | After
-------|------
I know it's trivial. It's been bugging me for a while. :smile: If you can't see a difference try looking at your screen from a different angle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/437)

Fix padding and margin on next question button

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

Previously the logic for finding the nearest word boundary was to search for word boundaries with `\b` in a regex. Unfortunately, this doesn't work for non-Roman scripts.
Instead we are now searching for white space, zero-width space, or word boundary. I've added a test for Arabic that fails before making this change and now passes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/438)

SF-685 Fix exception selecting text with non-Roman script

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts

When suggestions are disabled the slider wasn't getting set to its value when the dialog opens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/440)

SF-681 Fix suggestions threshold slider

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

Currently users can choose to ignore the dialog that tells them their browser is unsupported. When an error occurs it's a good time to remind them it may be due to their unsupported browser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/444)

Remind users their browser is unsupported when an error occurs

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

- Hide locales on qa if they would be hidden on live
- Only show the language picker if there are two or more locales
Contrary to what I had thought, the non-production locales would not have been shown on live had we deployed the current master to live. I mis-read the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/445)

Hide non-production locales on qa

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az_AZ.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az_AZ.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

All internationalized strings have been translated, but not all strings in our app have been internationalized, and the translations have not been verified (not sure how that process works). For that reason it will not be shown in production yet. Once we are happy with it all we need to do is flip the switch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/446)

Add Azerbaijani to the front end

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-global-vars.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

- If user adds an answer, or edits an answer, draw attention to what
they just added/changed, rather than to other answers.
- If user starts to edit their answer, but cancels, don't draw
attention to their unchanged answer.
- Continue drawing attention to unread answers, but only if the user
had not just added/changed an answer.
- Reusing 'answer-unread' style as 'attention'.
--
See animation demonstrating what is highlighted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/451)

SF-675 Draw attention to own answer if just added/edited

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* show unread icon to admins when see others answer is on
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/455)

SF-624 Hide unread answers icon from non-admin users

---

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts

* If the current admin had their access removed while on the users
page (collaborators component), the behaviour was that they would see
a permission error from calling onlineInvitedUsers(), then told that
the project is no longer accessible, and sent to another page.
* Now if it happens, a snackbar message shows saying there was a
problem loading the list of invited users, they are told that the
project is no longer accessible, and sent to /projects.
* The order of when Promise.all(tasks) is called was changed slightly
to not unnecessarily include it in the try.
* The error is thrown from command.service.ts onlineInvoke().
---
See animation where the admin on the removes the admin on the right from the project.
--- …

SF-673 Gracefully handle failed onlineInviteUsers() at collaborators

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* The subscription to remote changes in a question doc appears to queue up values,
* and emits them once subscribed to, one at a time. This would mark a third comment read,
* and then the fourth comment would appear and hide both, leaving the third read even though the
* user could not have been quick enough to read it.
* Also remove unused property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/461)

SF-624 Delay marking remotely added comments as read

---

src/RealtimeServer/scriptureforge/models/answer.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

When only part of a verse is selected ellipses are now shown when needed. They should be shown everywhere the selected text will be shown. Here's what it looks like in the initial text selection dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/459)

SF-708 Add ellipses to selected text when needed

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

- Added because it's the only language that has all strings translated (including strings that were merged into master only yesterday!)
- I got the localized name for Indonesian ("Bahasa Indonesia") from the Wikipedia language selector, which proved to be more reliable than other sources when it came to Azerbaijani.
- I've set `production: false` so it will only appear locally. When we're happy with the translation, the date format, and everything is ready, then we can flip the switch and it will appear on qa and live.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/465)

Add Indonesian front end strings

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

* Also fix terser-webpack-plugin vulnerability
Bumps [npm](https://github.com/npm/cli) from 6.13.0 to 6.13.4.
- [Release notes](https://github.com/npm/cli/releases)
- [Changelog](https://github.com/npm/cli/blob/latest/CHANGELOG.md)
- [Commits](https://github.com/npm/cli/compare/v6.13.0...v6.13.4)
Signed-off-by: dependabot[bot] <support@github.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/468)

Bump npm from 6.13.0 to 6.13.4

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

- Move locale cookie logic to i18n service
- Also gets rid of `localeCode` property in favor of `canonicalTag`, which corresponds to the first element of the `tags` array.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/470)

Move locale cookie logic to i18n service

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

- The az format was not working in Chrome
- Change en-GB format from 24 hour format to 12 hour format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/472)

Fix en-GB and az date formats

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

This code (actually a slightly different version) is already on qa and was used to diagnose the 401 error we were receiving from the Paratext registry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/477)

SF-719 Add logging to ParatextService to debug RefreshAccessTokenAsync

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

- Set expiration to one year, consistent with what happens on the home
page, rather than letting it default to session
- Set the cookie's path to '/'. Previously there appeared to be an issue
where it was set to the current url, leading to multiple conflicting
cookies. After deleting those cookies it wasn't reproducable again.
However, there's no cost to specifying the path to prevent the
possiblity of issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/476)

Fix locale cookie expiration date

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
src/SIL.XForge.Scripture/Pages/Shared/_SelectLanguagePartial.cshtml
src/SIL.XForge.Scripture/SharedResource.cs
src/SIL.XForge/Models/InterfaceLanguage.cs
src/SIL.XForge/Models/LanguageDirection.cs

* Add en-GB to Razor pages
* asterisk next to unapproved languages
* revert lowercase tag for Auth0 (not necessary)
* prefer UIC to C for ASP in utils
This moves us closer to having a single source for languages (e.g. JSON file) and more importantly means we could ship to live when everything else is ready.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/478)

SF-666d only approved languages on production

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

A recent PR added the concept of non-production-ready locales to the back end. Here's how the selector on the main page now looks:
Asterisks indicate the locales that will not be shown on qa or live. For consistency, this PR changes how locales are listed in the Angular app:
Before | After
-------|------
As you can see, I removed the lighter color and strikethrough. I think consistency in how we indicate this will be less confusing for developers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/479)

Use asterisk to show non-production locales in menu

---

src/SIL.XForge.Scripture/Resources/Pages.Index.id.resx
src/SIL.XForge.Scripture/Resources/Pages.RegisterSuccess.id.resx
src/SIL.XForge.Scripture/Resources/SharedResource.id.resx
src/SIL.XForge.Scripture/SharedResource.cs

Front-end strings are already up to date
My goal is to get the back end caught up to the front end in terms of supported locales, so that we can merge the list of locales into a single file that can be used by both the front end and the back end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/483)

Add Indonesian to back end

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

How it looks now:
Development | Production (including QA)
------------|--------------------------
The locale codes may be useful for developers, but they're more likely to confuse users. The `en-GB` locale is production ready since the only thing it affects is date format. It makes for an easy way to test our locale selection and persistence system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/482)

Enable en-GB for production and remove locale code from menu

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
src/SIL.XForge.Scripture/SharedResource.cs
src/SIL.XForge.Scripture/Startup.cs
src/SIL.XForge.Scripture/locales.json
src/SIL.XForge/Models/InterfaceLanguage.cs

Back end and front end now both read locales from the same place
Note: This PR also enables en-GB as a production-ready locale. Among other things #482 does that, but the file where it's specified is moved in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/487)

Move list of locales to separate JSON file

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

* Answers were not being marked as read when a user clicked on
* show unread answers
* Also do not mark the answer read if the user clicks the answer badge
* Also wait to show questions until question query is ready
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/490)

SF-720 Mark remotely added answers as read when shown

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

- Debounce selection change event
- Set selection preview element to a constant height to prevent the text
that is being selected from moving as a result of the selection
(Note that debouncing the selection change event wasn't really necessary in order to fix this).
An alternative solution I considered was to wait until after the user is finished making a selection. However, there is no event for this, so the only way to detect it would be based on mouse and keyboard events, which wouldn't be a very reliable method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/500)

SF-738 Fix jerkyness when selecting text for an answer

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

Selecting text that is not in verses (e.g. text in the introduction) is not supported. If a user selected it and clicked "save", the error message was "Select text to attach to your answer." That message may not be the most useful in that case, so it has been changed to "Select verses to attach to your answer" to be slightly clearer.
Once this is merged the updated translation file should be sent to Crowdin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/505)

SF-745 Change text selection dialog error message

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

- The logic for whether ellipses should be shown before and/or after the selected text was incorrect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/503)

Fix bugs in text chooser dialog and add detailed comments

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.scss

Previously the far right side of the chapter selection menu in the translate app was not clickable.
This was introduced in  #432 when fixing a related issue.
Before | After
-------|------
These screenshots are from Firefox's element picker. The purple area shows padding, which in this case corresponded to an unclickable region of the chapter selection menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/507)

Fix clickability of part of chapter select menu in translate app

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts

- Created localDelete() in sf-project.service.ts to remove the project from indexdb
- If sharing fails then the local data of the project is removed
- If a user is removed from the project then the local data of the project is removed
The bug occurs when IndexDB has stored that sharing is disabled. When sharing is enabled again and the link shared 2 remote changes get triggered. The first tells IndexDB that sharing is now enabled. At this point the user roles on the project is yet to have its remote changes brought through so the app thinks they don't have permission. Straight after that the second remote change triggers which gives the user role permission to the project. By this point it is too late as the dialog is already appeared.
The solution I suggest is to ensure any local data in …

SF-740 The project has been deleted

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

I was able to see this happen when my screen was 700 x 650 and the content of comments was more than the height of the page.
Specifying height=auto seemed to fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/519)

SF-754 Fix split container y-axis scrolling on Firefox

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

Set `dir="auto"` on each paragraph, rather than just the editor as a whole.
This isn't a perfect solution (it doesn't support bi-directional text within a paragraph), but it should greatly improve the situation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/494)

SF-610 Improve rtl support in Quill editor

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss

This fixes a bug when dragging and dropping text into segments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/522)

Remove right and left padding on segments

---

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts

The problem only appears when the language has changed after the page loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/525)

SF-763 Fix internationalization on users and settings page

---

src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts

The snackbar wasn't being shown when the network error came from a promise rejection (which is how all or almost all network errors reach the exception handler).
How it looks now:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/527)

Fix showing of snackbar when a network error occurs

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

Using the element ref for the quill-editor rather than querying the document will ensure that only this instance of the quill-editor will be affected and other quill editors in the document do not get accidentally changed.
The text direction class in quill-editor is not being used anymore, so this is removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/528)

SF-610c Use template query to inject quill element ref

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

This was broken in #528 (8d72a6399084c5c7b5c8ade093885023d99730f1) with the removal of the `rtl` and `ltr` classes from the Quill editor element.
Here's how it looks when there is a question that's not in a `usx-para`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/530)

Fix styling of question count icon

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/supported-browsers-dialog/supported-browsers-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/supported-browsers-dialog/supported-browsers-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

The translation strings from the error component for "Chrome" and "Firefox" are now used in both the error component and the unsupported browser component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/532)

Internationalize browser unsupported dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html

Just a small bit of text that got missed. I opted to re-use the string from the checking component, since it's identical and used in approximately the same context. Also, since there's only one string, and the prefix isn't the same as the component name, I just used the pipe instead of the structural directive.
Put another way, I didn't want to write `<ng-container *transloco="let t; read: 'checking'">` in a file named `checking-questions.component.html`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/533)

Internationalize checking-questions component

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

This was broken in 293b9219411e9dbc29e77a1c01b4fa40e9d2732b:
SF-752: Await local query updates when a doc is updated #516
This was due to a clash with an earlier fix that didn't get to the root of the problem:
09f000ef4866f07b3c4075c137a312e120fba15a
SF-663 Show newly added questions without full refresh #430
---
In terms of reviewing this, I suggest looking at #430 (the first fix) and #516 (the second fix, which conflicted with the first).
To fix the tests I had to change from using `env.realtimeService.create` to `env.addQuestion`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/535)

SF-777 Fix duplicate question on checking overview

---

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts

The problem is caused by the language not always being set yet when the dialog was opened. This resulted in odd, partially-translated dialogs such as this:
The reason for this is that the message is calculated before the dialog is opened, whereas the dismiss button is translated using Transloco's structural directive. Remarkably, it appears that the message dialog is used in only this one place. There were two main ways to go about fixing this that I considered:
- Fix the race condition. This would most likely be done by creating some promise that resolves after the language has been set, and then awaiting it. This wouldn't necessarily be very straightforward, since the language is only set from Auth0 upon login, and after that is retrieved from a cookie, so the logic would differ based …

SF-780 Fix internationalization of project link invalid dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/typings.d.ts

- change source of segment update delta to "api", which causes the
history module to not add the change to the undo stack
- fix selection location after undo
- remove "higlight-segment" format from verse embeds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/539)

SF-760: Fix data corruption on undo

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json

SF-778 and SF-770 are held up in "testing blocked" because they need translations from Crowdin for the "Report an issue" email, and connect to Paratext component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/546)

Update all translation files from Crowdin

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

Before "SF-783 Localize user roles (#542)" was merged @irahopkinson pointed out that localization functions in the i18n service may be confusing if they start with "translate" instead of "localize", since we have a translate app, and it may appear to be related to the translate app, rather than localization.
This was done by a project-wide find-and-replace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/548)

Rename localization functions in i18n service to reduce ambiguity

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* Add tests for existing functionality.
* Extend test environment to help test situations with missing
chapters text docs.
- Change from specifying chapter counts to specifying the
highest chapter. So a book with chapters 1 and 3 would only
have two chapters, but a highest-chapter of 3. This assists with
specifying books with missing chapters.
- Make special provision for including Source books in Paratext
even if they have no chapters, as long as the Target also has
no chapters, to help construct situations of chapterless books.
- Change AddPTBook() to better mimic situations of Paratext missing
chapters.
* Expose `FetchTextDocsAsync()`, `InitAsync()` and `CloseConnection()`
to tests.
--- …

SF-743 Add sync tests

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* Passing on a set of chapter docs that contains items that are not
actually in the SF DB causes problems later when SyncBookUsxAsync()
might try to delete docs from the DB, or when diffing the doc's null
Data.
* Add tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/544)

SF-743 Omit nonexistent chapter docs from FetchTextDocsAsync

---

src/SIL.XForge.Scripture/Models/Chapter.cs
src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge/Realtime/MemoryDocument.cs
src/SIL.XForge/Realtime/RichText/Delta.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Tests/Realtime/RichText/DeltaTests.cs

* Explicitly crash on Delta.Diff(null).
* SF-743 Assert state of data
- There might be a problem where incoming chapter deltas have a null
Delta from DeltaUsxMapper.ToChapterDeltas(). If so, crash early and
with some explanation.
* Crash in MemoryDocument.DeleteAsync() to mimic production
- To help unit tests identify problems.
* Refactor in ParatextSyncRunner
- Break up SyncBookUsxAsync() into some smaller methods, to help
understandability and testing.
- Rename variables to make it more clear what data sources we are
working with and what the variables are. (eg PT Data Access, SF
database, chapters)
- Add comments.
- This is not intended to have any behavioural changes.
* SF-743 Add sync test
- Add test for ChangeDbToNewSnapshotAsync() now that it exists after
refactor.
- This could …

SF-743 Followup refactor, test, edit

---

src/SIL.XForge.Scripture/Pages/Index.cshtml.cs
src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml

Our Bugsnag config has gotten a little redundant. This PR fetches the Bugsnag config from the config file, rather than placing it in the view file directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/554)

Base static page Bugsnag config on config file

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

On Bugsnag we've been getting:
```
Bugsnag usage error. notify() expected error/opts parameters, got unsupported object
```
This PR should fix this error. It happened when we got a promise rejection that was a plain object, rather than an error object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/557)

Fix Bugsnag "unsupported object" error

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

* Cookie language was clobbering Auth0 updates
* Flow: Cookie (homepage) > Auth0 user (Login) > user doc (frontend)
* This flow doesn't need `trySetLocale` to update userdoc or Auth0 user
* But frontend change of language should update all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/556)

SF-792 Fix login language selection

---

src/RealtimeServer/common/models/user.ts
src/SIL.XForge.Scripture/Resources/SharedResource.resx
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/SharedResource.cs

* AuthType is Facebook aware (the only use of this doesn't require this change)
* Invite email includes localized Facebook option
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/558)

SF-809 provide for Facebook login

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

The operative part is the change in `isVerseSegment` (previously named `isSegment`) from:
``` ts
return node.nodeType === node.ELEMENT_NODE && (node as Element).tagName.toLowerCase() === 'usx-segment'; 
```
to:
``` ts
return Array.from((this.scriptureText.nativeElement as HTMLElement).querySelectorAll(this.verseSegmentSelector)); 
```
where `this.verseSegmentSelector` is `'usx-segment[data-segment^=verse_]'`. The problem was an assumption that all usx-segments are inside verses, which is not necessarily the case. Instead we have to check that not only is it a usx-segment, but that it has a `data-segment` attribute that starts with `verse_`.
--- …

SF-795 Fix text selection that starts outside any verses

---

src/SIL.XForge.Scripture/ClientApp/src/app/app-routing.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-routing.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/users-routing.module.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts

- Moved import of AppRoutingModule to after import of other routing modules, as suggested by Angular docs (https://angular.io/guide/router#module-import-order-matters):
> "Each routing module augments the route configuration in the order of import. If you list AppRoutingModule first, the wildcard route will be registered before the hero routes. The wildcard route-which matches every URL-will intercept the attempt to navigate to a hero route."
- Changed a number of instances of forRoot to forChild, in the non-root modules, as instructed by Angular docs (https://angular.io/guide/router#hero-feature-routing-requirements):
> "Only call RouterModule.forRoot() in the root AppRoutingModule (or the AppModule if that's where you register top level application routes). In any other module, you must …

SF-811 Create 404 page in Angular app

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts

Here's how it looks when activating a question. Notice that (due to lots of front matter) the text doc is scrolled a large amount to verse 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/564)

SF-815 Scroll to question when it is activated

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts

In "Fix Bugsnag 'unsupported object' error (#557)" I changed the tests in a way that resulted in unnecessary excessive logging that makes it harder to understand the output, especially when there are actual errors.
Before this commit:
```
$ ng test
13% building 25/26 modules 1 active ..._modules/postcss-loader/src/index.js??embedded!/home/nate/src/web-xforge/src/SIL.XForge.Scripture/ClientApp/node_modules/sass-loader/lib/loader.js??ref--15-3!/home/nate/src/web-xforge/src/SIL.XForge.Scripture/ClientApp/src/styles.scss24 02 2020 16:16:26.312:WARN [karma]: No captured browser, open http://localhost:9876/
24 02 2020 16:16:26.330:INFO [karma-server]: Karma v4.2.0 server started at http://0.0.0.0:9876/
24 02 2020 16:16:26.330:INFO [launcher]: Launching browsers xForgeChrome with concurrency …
```

Fix mistaken logging of test exceptions when running tests

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

The CheckingComponent class extends DataLoadingComponent, which in turn extends SubscriptionDisposable. SubscriptionDisposable disposes subscriptions when ngOnDestroy is called. The DataLoadingComponent calls `super.ngOnDestroy()` within ngOnDestroy. I think without this change, DataLoadingComponent and SubscriptionDisposable do not have their respective implementations of ngOnDestroy called.
I searched our project for `ngOnDestroy`, and in each instance where we implement it, it either calls `super.ngOnDestroy()`, or it's in a class that directly implements `OnDestroy`, rather than extending a class that implements it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/5 …

Fix disposing of subscriptions in checking component

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

This is a totally trivial thing, but I keep noticing that the add question button is larger on hover than the buttons beside it. This is because we have CSS specifically specifying a smaller size for those buttons, in `share.component.scss` and `font-size.component.scss`.
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/570)

Fix mismatched size of add question button in checking app

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss

This solution seems to work, but I am not at all certain that it is correct. I basically did two things:
1. I changed `.ltr .ql-editor > p .question-segment[data-question-count]` to `.ltr .ql-editor > .question-segment[data-question-count]`. I *think* the previous selector was just wrong. It wasn't consistent with the rtl selector. @nigel-wells Perhaps you could take a look at this selector?
2. Changed the part of the selector that selects `usx-para[dir='ltr']` to select that *and* `p[dir='ltr']` (likewise for the rtl selector). That's because sometimes we set `dir` on `usx-para` and sometimes we set it on `p`. I don't really understand why/when we use one or the other. Perhaps @nigel-wells or @ddaspit can provide insight on that as well.
&nbsp; | Chrome | Firefox …

SF-802 Fix layout of text doc question icons on rtl texts

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss

Notice that in the first column verse number 2 and 4 are at the end of the line, rather than sticking with the first word of the verse and wrapping to the next line.
Before | After
-------|------
There are some minor differences in appearance, but I don't think it's very significant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/568)

SF-813a Fix line break after verse number

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

- Expand question panel when activating question
- Cap expansion height at 75% of split area
This doesn't fix everything that's wrong with the split area, so more will be coming in another PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/572)

SF-817 Expand question panel when activating question

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts

- Causes split area to adjust when clicking currently active question
- Closes question list when tapping current question on mobile (previously tapping the active question on mobile had no effect, and the question list remained open)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/573)

SF-817b Activate question when clicking currently active question

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

- Remove excessive padding from the bottom of last answer
- Stop wrapping timestamp (only happened rarely)
- Remove unneeded padding from right side of answer area
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/574)

SF-817c Fix styling of answers area

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts

Currently it's very easy to accidentally close the question dialog by clicking outside the dialog. This could easily lead to losing some work, especially if a question isn't super short and/or has audio attached. It's still possible to close the dialog by clicking the cancel button at the bottom of the dialog, which is a lot less likely to happen by accident.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/576)

Disable closing of question dialog when clicking outside dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html

It turns out my previous fix (#578) was incomplete. I failed to account for expanding the tree. I also didn't leave it with quite enough padding.
Here's how it looks now with fairly large numbers:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/579)

SF-816b Second attempt to fix layout of answers count

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

Large screen | Smaller screen
-------------|---------------
Unfortunately, this change wasn't as clean as I was hoping. Also, the transition to the icon-only button occurs at a much larger size than I would have liked. This is because the right panel shrinks to a fairly small size before the navigation panel disappears. I spent some time trying to improve the dynamic layout of the components above the text document, but it turned out to be more complicated and take more time than I thought it was actually worth.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/583)

SF-837 Add text to Add Question button on checking page

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

Edits to the text doc caused some issues:
To fix this, I stopped it from subscribing to updates, as specified in the functional spec.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/584)

SF-827 Stop subscribing to updates to text doc in checking app

---

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

* change state.LastVerse from a string to a number and only update it if the number can be parsed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/588)

SF-858 fix invalid last verse on Sync

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts

This fixes a bug where adding or deleting an answer caused books to disappear from the navigation. This was due to the questions not having yet been loaded into IndexedDB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/590)

SF-779 Change question count queries to question queries

---

src/SIL.XForge.Scripture/locales.json

* include the Latin script name in the autonym for those who don't have the font, at least until we deliver the font or a part of the font for that name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/594)

Update W. Kayah Li name

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/scroll-into-view.ts

See where lgtm introduced the alert: https://lgtm.com/projects/g/sillsdev/web-xforge/rev/ea4b3bb2f963730342268d36aa78ec048ea1b0c6
This was introduced in #581, where lgtm found the new alert, but it appears the bot never commented on the PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/598)

Fix lgtm alert for unnecessary null check

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

* Make sure when writing and reading USX files that the removed non-data whitespace is preserved
* So that on Sync (as well as Clone) only data whitespace is compared for changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/600)

SF-864b USX save and read whitespace

---

src/RealtimeServer/common/exception-reporter.ts
src/RealtimeServer/common/index.ts
src/RealtimeServer/common/web-socket-stream-listener.ts
src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/RealtimeServer/typings/sharedb/index.d.ts
src/SIL.XForge/Realtime/RealtimeService.cs

This catches errors from three sources and reports them to Bugsnag:
- The ShareDB server
- The Express server that serves static files
- The Node HTTP server that passes HTTP connections on to ShareDB and Express (if I'm understanding our code correctly)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/597)

SF-776 Add exception reporting to Node backend

---

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

Also update failure text to be consistent with success text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/605)

SF-883 Show dialog on sync fail

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html

- Render audio component before audio data is loaded
- Fix resulting issue where currentTime and/or duration is NaN
- Fix issue (possibly resulting from this change) where duration and or
currentTime is briefly enormous
- Fix slider layout issue where slider thumb was positioned incorrectly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/610)

SF-863 Fix split area height problem caused by audio component

---

src/SIL.XForge.Scripture/Services/SFScriptureText.cs
src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs

* Treat missing doc ops as an empty ops.
* This fixes SF-701 where a `KeyNotFoundException: Element 'ops' not found.` exception can occur when syncing, if the SF DB has chapter texts with no ops.
* Add SFScriptureText tests, comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/612)

SF-701 Handle missing ops or doc in SFTextCorpusFactory

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

- Presently it's not obvious which locale is selected, since the bold isn't very bold.
- Angular MDC has a way of showing checkmarks for the selected item in a group, but it doesn't appear to integrate with our locale selection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/614)

Add checkmark to selected locale

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts

Previously pressing the back button after login sent the user back to a 404 page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/615)

SF-638 Fix 404 page when pressing back button after login

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

Shortening the translation was first ruled out as a possibility before increasing the area.
Reducing the icon's right margin from 32px to 30px would be sufficient on my machine, but it's possible with a slightly different font, layout engine, or scrollbar width, the text could take up a little more space, so I reduced it to 24px for good measure.
For what it's worth, I've only ever reproduced this as an administrator with lots of books in Chromium. Without a lot of books the scrollbar doesn't appear, and in Firefox on my machine, the scroll bar isn't wide enough to cause the issue.
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/617)

SF-831 Fix overflow of community checking label in Azerbaijani

---

src/SIL.XForge.Scripture/Services/SFScriptureText.cs
test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs

* add critical test back in to safeguard future changes
Note I was happy to ship the last PR for this since the change had been sitting for so long after all of Mark's hard work, and we value shipping code. However, I was not happy that I had to remove a test to do it and not just any test, the critical one for this issue. Even though the last fix just moved the check for missing ops back up into the parent call in `SFTextCorpusFactory`, I couldn't just move the test to the parent because that would require serious refactoring to make it testable (we'd probably need to get it to use a Delta doc instead of a BSON doc). The test is back now. This fix adds the check for missing ops into the constructor of the child (`SFScriptureText`) and throws so it can still be tested. This has the …

SF-701b Handle missing ops better

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts

- This is the fourth time we've worked on this issue in one way or another, with the previous fix being c12d511720b9d31f24228d639c4bb4f59e257f7a
- Also a couple miscellaneous changes
Previously `initTexts` was only called when the route changed (switching projects) or `projectDoc.remoteChanges$` or `questionsQuery.remoteChanges$` provides us new data. It would appear `remoteChanges$` means just that; remote changes. That doesn't really explain why it happens so much more often when using a production build though, and doesn't always happen with non-production builds. I do think `initTexts` is idempotent though, so I'm not really worried about it causing problems.
--- …

SF-663 Fix missing questions on overview page

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html

- Set `anchorMargin` for language menu on extra small screens
The margin 88 refers to keeping it flush with the content on the right edge of the screen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/624)

SF-920 - List of languages in mobile view

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts

- Moved audio recorder `recording` event to only emit after successfully getting rights to use the microphone
- Reset question dialog  validation if `denied` access to the microphone
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/623)

SF-892 - Empty question added without any text if audio permission is blocked in the browser

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss

Before | After
-------|------
The problem was that when there is no text, the paragraph has dir set to auto and doesn't properly align the question count icon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/625)

SF-923 Question count misaligned when segment blank

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts

- Active question returns undefined now if the text displayed is a different book from the active question
- Showing questions for a specific book now only lets you add questions to that book and not other books on the project
- Scripture dialog will automatically switch to chapter view if only a single book is available
- Added `localChanges$` as an observable for when `remoteChanges$` is not available
The Jira task I believe relates to a connection issue with the backend which then doesn't let  `remoteChanges$` emit an event. As changes are are added locally it means part of the interface is updated immediately but the area relying on `remoteChanges$` to fire (segments and question icon being added to the text component) never gets triggered. I added a new `localChanges$` so that we can …

SF-828 - The question icon does not appear after creating a question in the book

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts

When using Facebook as an auth provider, the user has the option of canceling. Unfortunately Auth0 then sends the user back to our app, rather than back to the login screen. 
Here the user can click "Not now":
Here the user can click "Cancel":
Error dialog:
Before | After
-------|------
Note that all login errors are handled this way (Assuming it's an error that is sent back to the app, rather than e.g. a incorrect password, which would be handled on the Auth0 login page).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/628)

SF-891 Provide helpful error dialog when login via auth provider fails

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts

- Always return true for checking online/offline status in pwa.service.ts for production
This will be removed when we are ready for the PWA to be made available in production
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/633)

SF-941 - Disable offline route on QA/Production

---

README.md
deploy/dependencies.yml
src/SIL.XForge.Scripture/Models/TextInfo.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/IScrTextCollection.cs
src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge/Services/FileSystemService.cs
src/SIL.XForge/Services/IFileSystemService.cs
test/SIL.XForge.Scripture.Tests/Services/LazyScrTextCollectionTests.cs
test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

In our production code, target and source Paratext projects were located in separate subfolders of a project in the sync folder. This change reintroduces that functionality so that projects that share the same source will have a unique clone of that source paratext project.
* require the text type when accessing paratext project data
* add test for failing pt send/receive
* specify custom mercurial required in README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/627)

Clone target and source as subfolders in the main sync project

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts

Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/637)

Stop autofocusing in scripture chooser dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss

Before | After
-------|------
This prevents a layout change when the error message is shown, which would throw off the split-area height when the error message is shown, causing the save and cancel buttons to be partially hidden.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/639)

SF-862 Fix layout of checking answers error message

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/offline/offline.component.ts

- Definite assignment assertion modifiers are sometimes necessary, but should be avoided when not needed. In this case a couple uses were not necessary.
- In a couple instances constructors incorrectly declared parameters as properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/638)

Remove unneeded definite assignment assertions and class properties

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

When a project admin disables the checking app, other users on the checking app were affected.
Previously, the app becomes unresponsive and the users get notified at the bottom.
Now users get notified with a message dialog, and the app navigates away from the checking app.
I chose to use a dialog over a snackbar message since it may happen when a user has stepped away from the computer, and would miss the snackbar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/629)

SF-861 Remote disable community checking shows message dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

- refactor setting direction using Delta formats
- include auto formatting in undo stack
- ensure that verse embeds do not get inserted inside of segments
- remove spurious segment highlighting on undo/redo
- refactor segment highlighting
- ignore embeds when determining selection location after undo/redo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/634)

SF-637 Fix redo in translate app

---

src/RealtimeServer/common/web-socket-stream-listener.ts

- Changed WebSockets to always establish a connection
- Moved verifyToken to take place on a successful connection and if this returns false the connection is immediately closed
The result of this means the Reconnecting WebSocket no longer triggers an error event which is what we use for connection issues and going "offline". Now the 401 response simply closes the WebSocket.
The underlaying issue is the browser does not pay attention to http headers so closing the socket instead allows us to pass additional information as to "why" it is closing.
WebSockets also appear to discourage the use of `verifyClient` which is what we were using: https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketserveroptions-callback so this feels like a good time to address this as well.
I have …

SF-942 - 401 error results in user being told they're offline

---

src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs

This was most likely broken in 2b1fc3c4f58853494aa6f3621e92870320eaa4a7 when JsonRpc.Router was upgraded to 4.0.4.
It appears JsonRpc.Router no longer supports default arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/642)

SF-943 Fix no methods matched request error

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

Perhaps I'm missing something, but I've never quite understood why we have the header shrink when scrolling down the page. I'm not sure I know of any other websites that do that, and I think it could be slightly confusing to users.
However, since I don't know why it was done this way in the first place, I am merely bringing this up as a proposal. Perhaps there is a valid reason; if so feel free to close.
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/626)

Stop shrinking header when scrolling down

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/ParatextService.cs

Send and receive with Paratext would not work correctly if there are multiple clones of the same project on the SF server. We allow multiple clones because a Paratext project and be a target project of a SF project and a source project for one or more SF projects. This allows Paratext Data to correctly identify the correct local repo to use to perform a send/receive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/648)

SF-924b Disable caching of VersionedText for send/receive with Paratext

---

deploy/dependencies.yml
deploy/files/InternetSettings.xml

* Node 10.9 was needed on develop branch to run the frontend.
* PTDataDll needs some settings specified to know how to use the
Internet.
* reportgenerator should be installed for the current user, not for
root.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/646)

Update ansible: node 10.9, connection settings for PTDataDll, etc

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html

Also stop autofocusing first element in menu drawer and questions panel
Situations where we make sure to scroll the question into view:
- On page/view load
- Switching questions with the next/previous buttons
- Opening the question list (on mobile)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/650)

SF-944 Scroll question into view when switching questions

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

Ellipsis shown when it should not be | Ellipsis not shown when it should be
-------------------------------------|-------------------------------------
Since the selection is expanded to include the entirety of partially selected words, the entire verse is selected in this example, despite the last letter of the last word not being included by the user. | All of the first word is selected (because the selection is expanded to include all of partially selected words), but the selection doesn't go to the end of the verse, so the ending ellipsis should be shown.
This turned out turned out to be a simple error in calculating how much of the verse is included in the final selection.
--- …

SF-952 Fix ending ellipsis in scripture selection dialog

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

This PR actually resolves a couple of race bugs when content is added offline and the page is reloaded/ navigated away/closed down and opened up again. These fixes will relate to all real time documents and it is something Damien has specifically helped with.
I have found one instance where a duplication can occur and that is with the use of live reload. With live reload enabled, and a comment is added offline (shut down the backend), when the backend is enabled (without manually refreshing the front end) the app may initially try to add the operation depending on the timing of the reconnecting websocket. If this process can start just before live reload refreshes the page then the offline data doesn't have a chance to update and it is then processed again after the refresh. This is just …

 SF-928 - Checkers can add a comment offline and have it synced when online

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- whitelist USX formats
- re-enable default Quill keyboard behavior
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/653)

SF-893: Disable default Quill formatting

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

The first time a project is synced after a question is added, the property syncUserRef is added to the question. Previously this caused the question to be marked as newly edited.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/659)

SF-950 Do not highlight question on first sync

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss

We've discussed making the add question button on the checking overview page more prominent but haven't come to any conclusions yet if I recall correctly. This is my suggested incremental improvement.
Desktop | Mobile
--------|-------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/660)

Make add question button on checking overview page more prominent

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts

- Changed the registration strategy for the service worker to `registerImmediately` to avoid conflicts with using the `ReconnectingWebsocket`
Angular's service worker by default has a registration strategy to `registerWhenStable` which is described as :
```
Register as soon as the application stabilizes (no pending micro-/macro-tasks).
```
As we are using `ReconnectingWebSocket` it creates a macro task timer which means the app is never consider stable therefore the service worker won't register. There must have been just enough  time between the web socket connecting originally compared to where I then moved it to which introduced the issue. Thankfully we can simply change the registration strategy to `registerImmediately` which does what it says and registers it straight away without …

Service Worker Registration

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts

Online | Offline
-------|--------
A few concerns here:
- In the top app bar we hide the language switching menu, and items in the menu on the right. That's inconsistent with the way we're merely marking items in the sidebar as unavailable offline.
- I'm not sure the positioning of the cloud is very good, or even the right solution.
I also marked pwaService as public in `avatar.component.ts`, since it is used in the template. Previously a warning was shown in the template regarding accessing a private menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/657)

SF-931 Indicate routes that are not available offline

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts

This reverts commit 79cd662667cb0628a541b09fa5b396314a241471.
* now that we no longer have the offline page redirect, this is unhelpful now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/670)

Revert "SF-941 Disable offline route on QA/Production (#633)"

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts

- Added subscribed state to RealtimeDoc
- Changed `isLoaded()` to also check if the doc has been subscribed to - this covers instances where a snapshot was ingested and not subscribed to yet
The issue encountered in this is sharedb docs are automatically unsubscribed as soon the connection state changes. As user docs are never subscribed to via a realtime query it meant the offline data would never be updated. This PR creates a new subscribed state so we can track if the document was subscribed to at some point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/669)

SF-938 - Ensure user config is saved offline and synced online

---

src/SIL.XForge/Services/EmailService.cs

* don't send from the beta subdomain. The main site has setup for avoiding SPAM, the subdomain doesn't.
This is cleanup onto `master` after the hotfix branch was applied to `sf-live`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/672)

Always send email from main site

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

With regards to training segments, it appears that naturally does not occur when offline. It seems to only try to train a segment when a suggestion is used, though the actual logic is difficult to decipher. In any case, I haven't been able to cause any errors when offline, other than the usual console errors caused by the websocket being unable to connect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/668)

SF-939 Disable suggestions in translate app when offline

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/i18n-locale.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

* gives us one source of truth in `locales.json`
* move locales to utils to prevent circular dependency between auth and i18n services
Review in conjunction with PR https://github.com/sillsdev/auth0-configs/pull/55.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/673)

SF-921 send language options to Auth0

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

- only apply box-decoration-break: slice on Firefox
- see Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1569107
- adjust box-shadow for selected paragraph so it looks better on Firefox
- added in `wbr` element for breaking the verse with the following segment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/661)

SF-813: Only use box-decoration-break: slice on Firefox

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts

- Removed reliance on `questionQuery` being `ready` before questions docs are returned
- Add methods to load and unload text docs per project required for the checking app
- Disposing of a realtime doc will now remove its offline storage and remove it from the available collection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/677)

SF-927 - Checkers can answer a question offline and have it synced when online

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts

Previously, when opening the dialog while offline, the toggle switch remained off even when it should be on, due to being disabled.
Before | After
-------|------
Also fixed the issue with the slider:
(This problem occurs when we go offline, the message is shown, causing the dialog to become wider, and messing up the layout of the slider).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/682)

SF-939b Fix translate suggestions dialog when going offline

---

src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs

* handle the case when a syncUser is missing, possibly due to a crashed sync (NewSyncUsers are only updated at the end of a successful sync)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/687)

hotfix: handle when syncUser is missing

---

src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs

If a Paratext user not belonging to a Paratext project works on the community checking app, the ParatextNotesMapper would assign comments to the Paratext user. Then the comment would get rejected when trying to send and receive because the user was not on the Paratext project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/688)

Assign comment to project admin user if checker not on PT project

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/local-settings.service.ts

Currently when one tab logs out, the others do nothing. That's because our code is looking for a change to the user_id stored in localStorage, but when we log out, localStorage is cleared all at once, and the event that is fired has the key set to null, rather than user_id.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/692)

SF-972 Log out all tabs when one tab logs out

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts

The problem was that in the past, if the access token wasn't in the URL, we would clear auth data out of local storage before attempting to verify that the user is authenticated. This caused the other tab to think the user had been logged out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/693)

SF-974 Stop redirecting first tab when opening a second SF tab

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts

This was broken in e7296f9460a169a6957853afc695d23a7f235c8e.
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/701)

SF-979 Fix highlighting of active item in navigation drawer

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts

This was broken in e7296f9460a169a6957853afc695d23a7f235c8e because the new router directive didn't support relative routes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/702)

SF-980 Fix broken link on translate overview page

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts

Stopping event propagation was unnecessary and prevented menus from closing
This was broken in e7296f9460a169a6957853afc695d23a7f235c8e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/706)

SF-991 Close menus when they lose focus to navigation item

---

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts

Previously, if a user had last visited the checking app, and then checking was disabled, clicking on the Scripture Forge icon or clicking on "Project home" in the menu sent the user to a mostly blank page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/707)

SF-990 Redirect to translate app if checking app is disabled

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

The problem before this fix: `ParatextService SendReceiveAsync()` gets
to Paratext `SharingLogic Share1Project()` where it calls
`sharedProject.Permissions.GetUser()`. If the result is null,
`Share1Project` returns early and changes are never locally committed
to the hg repo or pushed.
`PermissionManager GetUser()` gets to `GetUserInternal()`, which gets
`string.Empty` from `RegistrationInfo.UserName` via
`GetDefaultUser()`. In the end we don't commit locally.
This fix: `MultiUserPermissionManager` overrides `GetDefaultUser()` to
return a desired PT username. `ParatextService SendReceiveAsync()`
now sets a shared project's .Permissions to such a custom
`MultiUserPermissionManager` so text changes are committed to the
local hg repo. It is just re-using the one in the SharedProject's …

Set shared project Permissions to custom with PT username

---

src/SIL.XForge.Scripture/Pages/Index.cshtml

* the increase to 15 seconds meant the 2nd and 3rd slider didn't init until much later (enough time for the user to scroll to see it uninitialized)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/697)

SF-541d fix slider init

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts

RPC method names should be case insensitive, but due to a bug in JsonRpc.Router it's currently case sensitive for some method names and some locales. A fix has been submitted at https://github.com/edjCase/JsonRpc/pull/80, but it's likely to take some time  to have the fix merged. In the mean time, there's no real reason for the front end to have different capitalization than the back end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/719)

Capitalize RPC method names for consistency

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

- Including the name of the method that failed in the error message should help when it comes to interpreting Bugsnag events and support requests from users. Previously messages such as "Exception occurred from target method execution" and "No methods matched request" have been unhelpfully ambiguous.
- Also made the tests for the exception handling service slightly more robust.
Note:
BigInt was included in the tests because I was trying to cover all primitive types, and it's a new primitive in ECMAScript 2020. It's not really that important; it was added for good measure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/726)

Include method name in JsonRpc error message

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html

This should help us cross reference errors the testers report with events in Bugsnag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/729)

Include event ID in error dialog under details

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

This was broken in 6aed2d79acb503b601eea9d583dff0f7f3a9d5be and caused Azerbaijani text to be cut off due to space constraints.
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/733)

SF-1012 Fix padding of icons in navigation panel

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts

Here's how it looks now:
This should be shown when the audio is not stored offline, and the user is offline, and the audio data wasn't already loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/732)

SF-963 Inform user when audio is unavailable

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

This was broken in ba0b7dc50240f3d5ab02656f5f7824481d4be3e2.
#722 (original) | #733 (first fix) | fix/sf-1012b (this PR)
----------------|------------------|-----------------------
@irahopkinson I'd appreciate it if you'd double-check my work locally, given my apparent inability to notice UI changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/736)

SF-1012b Fix highlighting of icons in navigation panel

---

src/SIL.XForge/Services/SecurityService.cs

Original implementation had several issues:
- Why throw away a byte of random data at the start? We could use 16 bytes of random data, not 17. Since it's coming from RNGCryptoServiceProvider, it's drawing on a presumably-limited entropy pool such as /dev/random on Linux, so if this gets called too often there might be slowdowns as the entropy pool waits to gather enough entropy to return the requested bytes.
- Why limit oneself to non-zero bytes here? GetBytes() would produce 256 possible values (8 true bits of entropy per byte) as opposed to GetNonZeroBytes's 255 values (only 7.9944 bits of entropy per byte).
- Why limit oneself to 62 possible characters instead of 64? Yes, these IDs are going to be used in URLs from time to time so Base64 is unsafe as it would produce strings containing …

Improve key generation in SecurityService

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.scss

&nbsp; | Before | After
-------|--------|------
Small screen | ![](https://user-images.githubusercontent.com/6140710/88328630-bf327e80-ccf6-11ea-8db9-f7a4f328e2d6.png) | ![](https://user-images.githubusercontent.com/6140710/88328635-bfcb1500-ccf6-11ea-9744-3c9a52d6b371.png)
Large screen | ![](https://user-images.githubusercontent.com/6140710/88328738-dffad400-ccf6-11ea-86e0-c4c19bdc0eba.png) | ![](https://user-images.githubusercontent.com/6140710/88328740-e0936a80-ccf6-11ea-95fc-9d542a60934e.png)
Suggestings for abbreviating the text without obfuscating the message are welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/738)

SF-963b Fix audio not available message on mobile viewport

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/ExceptionLogging/ExceptionHandler.cs

The previous hotfix did not affect CallApiAsync, which is what needed more logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/742)

Expand error logging in CallApiAsync

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts

Previously the only thing under "show more" was the stack trace, so we didn't offer to show more when there was no stack trace. Now that the error id is also shown under "show more," we should no lnoger hide the button when there's no stack trace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/747)

Always show error id in error dialog

---

src/SIL.XForge.Scripture/ClientApp/ngsw-config.json

Navigating to
- `/terms`
- `/privacy`
- `/learn-more`
- `/language-api` (triggered by switching language on home page)
was being handled by the service worker, leading to a not found page.
There may be other paths, but I'm not sure what they are.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/752)

SF-1024 Stop service worker from handling server endpoints

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.scss
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

* Shortening the initial message displayed. Additional description is
shown when pointing to or clicking a question mark 'help' icon.
* Changed 'warning' icon to 'volume_off'. This doesn't seem like a
'warning' situation. 'volume_off' visually shows that there is audio
but it's not playing.
* html, scss
- Moved `isAudioAvailable` items into their own div, rather than
check for `isAudioAvailable` on each element.
- The play button is now hidden if audio is not available.
- Introduced CSS class `audio-area` to apply similar styling to the
audio-unavailable message as to the player controls area (such as
the border around it).
* styles.scss
- The tooltip default font size is a bit small on desktops but was
ok on mobile. Introduced `.mat-tooltip` style here, rather than
in the component scss, …

SF-1020 Shorten audio unavailable offline message

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

In the console, Firefox has the following warning:
> Cookie “.AspNetCore.Culture” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
Similar messages are displayed in Chromium.
For context, major browsers are rolling out a change to make the sameSite attribute default to "Lax" rather than "None". This makes the default more secure, but can break backwards compatibility for sites that relied on the default being "None".
Additionally, major browsers are going to start requiring that when sameSite is set to "None", the secure attribute is set to "true".
Right now some of our cookies are not …

SF-995 Set secure and sameSite attributes on locale cookie

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts

The reason I haven't added a test is because in order to trigger the issue, there has to be an error loading the audio. And while we can mock the PwaService to tell the component it is offline, we don't have a way to actually go offline in the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/758)

SF-1028 Load audio data after user comes back online

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts

- When `online` try and upload files and, failing that, resort to offline handling
- When `online` try and delete files and, failing that, resort to offline handling
- Added `try catch` around `JsonRpc` requests as these never caused errors when they should have. This provides additional information to Bugsnag as well in terms of what method failed
This PR resolves the 504 dialog (and sometimes network connection snackbar) when attempting to use `onlineInvoke` requests when not entirely online. Please note that the console will still display errors which is normal for offline mode.
This PR also resolves audio files - being left orphaned on the server when the attempted file creation/deletion failed.
It is also worth noting that I've only applied the `try catch` logic around the …

SF-1016 - The error appears when returning to online mode after adding some answers in offline mode

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

Previously the progress circle didn't update after a user answers a question. Now the progress circle updates immediately, reflecting the newly answered question.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/761)

SF-965 Update progress circle when answering a question

---

.vscode/launch.json
src/Migrations/PtdaSyncAll/Program.cs
src/Migrations/PtdaSyncAll/Startup.cs
src/Migrations/PtdaSyncAll/build-production

Program.cs
- Add call to RunAsync(). Using existing inspection method since it
has a useful structure for doing this, and in context of reporting on
what we are doing.
- Allow running in inspect mode or sync mode, depending on environment
variable.
- Give helpful message if program fails because SF is running.
- Add more information to error messages that can happen while
processing.
- Add fancy Log() method with time. It will be interesting to see how
long the program takes to run.
Startup.cs
- Add needed services.
- Using `AddTransient` since each usage of ParatextSyncRunner should
be a new instance. We don't want to use a singleton with data mixed in
from other sync runs.
build-production
- Add inspect vs sync mode setting instructions and to usage command.
launch.json
- Add mode …

Migrator: Make PtdaSyncAll sync all 

---

.vscode/launch.json
.vscode/tasks.json
src/Migrations/PTDDCloneAll/PTDDCloneAll.csproj
src/Migrations/PTDDCloneAll/Program.cs
src/Migrations/PTDDCloneAll/Startup.cs
src/Migrations/PTDDCloneAll/build-production
src/SIL.XForge.Scripture/Services/ParatextService.cs

Add the migration tool to the Migrations folder. This tool can be packaged and run on the QA or live server to clone the Paratext project data for all projects on the Scripture Forge server into the sync folder.
This is the final step in the two part migration process to use the Paratext Data dlls to synchronize SF projects with Paratext.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/757)

Add migration tool to clone projects using Paratext Data dll

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts

Decided to split #765 so that the lazy loading of the system administrator module can be included after the upgrade to Angular 9.
This PR covers:
- Always login with offline authentication if available
- Check ping and auth0 when the app is confirmed as being online
- Only set the web socket status if it has actually changed to avoid multiple events being submitted
Improving load time is really an ongoing task rather than a once off task so I see this PR as a first step.
The main impact this PR aids with is actually after the initial load in to memory (when you get past the `Loading...` message) and the app being usable. The app will now always initially load up using offline authentication if available and then check after the fact with auth0 if it is still valid. It also checks again …

SF-930 - Improve load time for PWA (latest)

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SfScrTextCollection.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/SfScrTextCollectionTests.cs

Up to this point our code has made use of Paratext Data without initializing Paratext Data. But this was causing problems if we needed to use ScrTextCollection.SettingsDirectory since it has not been initialized to a path. After discussing with the Paratext developers, we decided that it is essential for Paratext Data to have access to ScrTextCollection.SettingsDirectory. This provides a minimal implementation of ScrTextCollection, so Paratext Data has this requirement satisfied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/784)

Use minimal implementation of ScrTextCollection to initialize Paratext Data

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/usfm_mod.sty

- usfm_mod.sty was looked for when cloning a project with some front
and back matter.
- Including usfm_sb.sty so it's there when/if needed.
ParatextData was asking for usfm_mod.sty. I can't help but want to supply it. See email for context and explanations. I'm expecting that this PR will be argued against, but it's here if wanted. 
Using or not using the usfm_mod.sty sytlesheet didn't seem to have an impact on the files in the cloned project directory. And a brief look at some of the extra project books in SF did not quickly spot any visible differences.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/780)

Sync: Install usfm_mod stylesheet

---

src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs
src/Migrations/PTDDCloneAll/Program.cs

*Also report Paratext username of user used to clone projects.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/786)

Throw error if PTDDSyncRunner runs unsuccessfully

---

src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf.svg
src/SIL.XForge.Scripture/ClientApp/src/manifest.json

- Updated sf.svg to correctly report dimensions as 1024x1024
- Updated manifest.json to state which icon can be used as `maskable`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/783)

PWA Manifest

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

If the storage quota has been reached and uploading or storing an audio file fails, discard the question or answer if it is being created, or discard changes if being edited. Then show a dialog to free up space.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/763)

SF-964b Do not save questions and answers if audio could not be saved

---

deploy/dependencies.yml

- Ubuntu 20.04 had trouble installing mercurial from pip. Depending on
the version, it either didn't install, or later there were errors in
SF about changedChapter.py.
- Continue installing mercurial 4.8.2 in Ubuntu 16.04 and 18.04, but
install the mercurial system package in Ubuntu 20.04+.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/790)

Install mercurial 4.7+ from pip or system

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

- Ensure multiple websockets are not setup when `init` is run through the login process
Although the Jira task has a number of steps to go through the main steps to reproduce are:
**Checker**
1. Log in to project that has questions 
2. Select book with questions
3. Go offline using either using the browser or terminating `dotnet`
4. Go online
**Admin**
1. Log on to the same project
2. Add a new question
**Result**
* Checker will receive console errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/791)

SF-1054 - Console error appears for checker user when returning from offline mode

---

src/SIL.XForge.Scripture/Services/IInternetSharedRepositorySourceProvider.cs
src/SIL.XForge.Scripture/Services/InternetSharedRepositorySourceProvider.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Tests/Services/TokenHelper.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

Stopping the caching was easy. The unit tests were using the cache to set Sources and assert about them. This PR moves Source creation into a service that can be mocked. This allows the tests to remain mostly unmodified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/795)

LT-1062 Don't cache repo sources

---

src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs
src/Migrations/PTDDCloneAll/Program.cs

This allows us to run a silent clone of the projects, and then deletes the cloned repositories without persisting anything to the SF mongo database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/796)

Allow silent cloning mode for clone all migration tool

---

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

This is a draft since I want to do some local testing still.
The projects that triggered the problem were probably from a much older SF version than the current.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/797)

Sync: Return unmodified USX if no chapter deltas

---

src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs
src/Migrations/PtdaSyncAll/Startup.cs

Because it is not necessary to clone new books for the sync all migration step, books that cannot be cloned will be skipped over. These books will be safely added during the clone all migration step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/798)

Skip books during sync-all migration that cannot be cloned

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html

- This is already possible when the user answers a question for the first time, since the user is prompted with a dialog.
- There isn't really any reason it needed to be disabled in the first place. I think maybe at the time I thought editing the name would require immediately saving it via an API call, but the user object is part of the realtime system. This is just reverting a change that never needed to be made in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/803)

SF-1002 Allow users to edit display name offline

---

src/RealtimeServer/common/models/project.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/SyncService.cs
src/SIL.XForge/Models/Project.cs
src/SIL.XForge/Services/IProjectService.cs
src/SIL.XForge/Services/ProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
test/SIL.XForge.Tests/Services/ProjectServiceTests.cs

So, I don't really need to expose a backend API method of `GetSyncDisabled`, do I. But then, do I need `SetSyncDisabled`? I'm a bit foggy in remembering how this is supposed to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/804)

Sync: Allow projects to have their synchronization disabled

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts

- Retry `checkSession` for `auth0` when a timeout occurs
This issue relates to a timeout from `auth0` but I'm not entirely sure what and when this occurs. The only way I was able to consistently cause a timeout was to edit my hosts file and direct `sil-appbuilder.auth0.com` to my `localhost`. 
The timeout happens after 1 minute of running `checkSession()` in `auth.service.ts` which then runs `checkSession()` from `auth0`.
What I've currently done is a simple retry. This could be easily changed to retry multiple times but I think if it is failing multiple times then perhaps there is a larger issue going on.
I also think we don't need to check with `auth0` everytime the app loads. When we first authenticate `auth0` gives us the relevant tokens and states when it will expire. If we know the …

SF-1055 - An error occurred during login

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

Previously it was redacted from the url in breadcrumbs, but not from the current page url.
(We don't want the access token in the URL reported to Bugsnag because it's a credential).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/810)

Update Bugsnag and redact access token from error report

---

.vscode/launch.json
src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs

There are 2 projects that cannot be migrated due to inadequate book permissions, and users have not responded to our email. This change will allow us to synchronize any questions and answers, but will skip over changes to books. We can then retrospectively evaluate if the text changes were significant. An initial look at the text changes on these two projects reveal that they are not considerable changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/813)

Specify if sync all should skip synchronizing books

---

src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/SIL.XForge.Scripture/ClientApp/angular.json
src/SIL.XForge.Scripture/ClientApp/e2e/tsconfig.e2e.json
src/SIL.XForge.Scripture/ClientApp/ngcc.config.js
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/src/tsconfig.app.json

* allow ng analytics
* ignore deep import warnings, see https://github.com/angular/angular/pull/35683#issuecomment-592434035
* fix warning "xxx.ts is part of the TypeScript compilation but it's unused"
* upgrade Realtime prettier (also fixes all realtime-server dependencies in ClientApp)
This is likely needed before we can ship to QA and Live. I've tested with a production build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/815)

Fix dependencies after ng9 upgrade

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

When a device using Firefox is full, IndexedDB becomes unreliable. It used to show a message dialog about private browsing mode which was not the case. I've made the message to cover both cases where a user is incorrectly using private browsing in FF, or if their device is out of space.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/820)

I18n for Firefox private browsing and out of space errors

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-data-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts

- Added `updateAnswerFileCache` to the question doc so it can be called when required
- Cache answer audio on question activation
- Cache answer audio on remote changes to a question currently being viewed
- Cache answer audio when saving an answer
- Moved update file cache subscription to now take place when a realtime doc updates offline data
- Changed realtime doc for `updateOfflineData` to `protected` so that it can be expanded in child classes
- Updated realtime query to emit the specific document that has remotely changed
- Added `get` and `getAll` to file service
- Updated checking tests to reset `mockedFileService` for each test so that `verify` is valid per test rather than over all tests
- Created tests for ensuring answer audio is cached
There was a point on the Jira task when …

SF-978 - Cache audio on answers when played

---

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts

- `toBeDefined()` will always be true. Using `not.toBeNull()` will
test what we want.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/823)

Connect: Expect progress bar not to be null

---

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

- Disallow in backend.
- I didn't find a great preexisting exception to use and used
ArgumentOutOfRangeException.
- Report problem in front-end for the exceptional circumstance.
- command-service.ts would receive a response back from
this.http.post() that was not a thrown error but a response with an
error. Throwing that makes it be treated similarly.
- connect-project.component.ts:
- Catch errors from projectService.onlineCreate(). If the error
looks like the already-connected problem, inform the user to just
retry, or report if it keeps happening, and re-query the paratext
projects.
- Pass the error to errorHandler.handleError() to re-use its email
reporting capability, and to log this situation to bugsnag.
--- …

SF-1072 Connect: Do not connect PT project twice

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/Models/UserSecret.cs
test/SIL.XForge.Scripture.Tests/Services/MockLogger.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- Note that the PutNotes test change may look nice, but that test
isn't working right now anyway :-/. See SF-1089.
- Introduces class MockLogger<T>, since using NSubstitute with ILogger
is tricky.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/818)

Sync: Do not write PT username to server logs

---

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts

When a user's device is full, IndexedDB could abort a transaction with either a QuotaExceededError or a DataError. If this happens while uploading a file, we catch that an notify the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/824)

Show error message if a file could not be saved

---

src/SIL.XForge.Scripture/Services/IParatextDataHelper.cs
src/SIL.XForge.Scripture/Services/ParatextDataHelper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

An exception was caught in test each time VersioningManager was used to get a new VersionedText. The tests continued and passed anyway. This change pulls the commit part out of PutNotes so it can be mocked in the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/826)

Mock versioning manager functionality in ParatextService tests

---

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts

One user reported an error where the 'audio' object store has not been created. I'm not able to identify the exact cause, but this change will ensure that every user will have an up-to-date indexedDB database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/830)

SF-1102 Check each indexeddb object store exists on upgrade

---

src/SIL.XForge.Scripture/Models/SFParatextUser.cs
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/InternetSharedRepositorySourceProvider.cs
src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs
src/SIL.XForge.Scripture/Services/NotesFormatter.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/MockLazyScrTextCollection.cs
test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- Stop using now-removed MultiUserScrText.
- Satisfy new ParatextUser argument to ScrText ctor.
- Subclass ParatextUser as SFParatextUser, to have a 'valid' user.
- RegistryServer.Initialize() now wants a ParatextUser. We aren't
using it anyway. Stop trying to initializing it until we need it.
- Satisfy call to GetHgUri() without crashing because of a null
RegistrationCode.
---
So far so good in testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/831)

SF-1088 Sync: Upgrade to ParatextData 9.2.3-alpha

---

test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs

- ParatextServiceTests.cs PutNotes test fails when VersionedText.cs
VersionedText(ScrText) checks if ScrText Settings.Guid is empty, and
if so calculates a new guid for it. It tries to write the info to a
file but has trouble and crashes.
- I haven't fully compared the context of our MockScrText construction
and how ScrText objects get constructed. But I do see that setting
ScrText.Settings results in setting ScrText.CachedGuid to the value
of Settings.Guid.
- Set ScrText.Settings.Guid when we set up a MockScrText with a known
Guid so we don't crash in VersionedText.cs VersionedText(ScrText).
To clarify, this code was written to prevent the test from crashing rather than testing. It won't necessarily make the test pass.
--- …

Set MockScrText.Settings.Guid

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

- Increased minimum browser support of Safari to 11.1 desktop and 11.3 on mobile
After investigation and looking at browser version usage it was decided to simply not support Safari 10.x any longer.
Note that I've had some issues with testing on BrowserStack with `localhost` so it might need to wait until it reaches QA to test the dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/837)

SF-1080 - Quill box does not display in the Project after login to SF

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

- DebugElement query() appears to be returning type
`DebugElement | null`, and so checking if the return is
.toBeDefined() will always be true. So instead, check whether the
return is or isn't null.
- scripture-chooser-dialog.component.spec.ts: Methods were defined
as returning type `DebugElement | undefined`, which is probably not
true. Change that to the also incorrect(?), but matching the .d.ts
declarations, type `DebugElement`.
- app.component.spec.ts: A test here was using .toBeDefined, and
when that was changed, it revealed that the test wasn't really
working.
- Add more setup to test.
- mdc-list-item elements don't seem to keep an id, and so we
can't check for them by looking for an element with such an id. So
look for items in the menu list that have matching text, to check
for …

SF-1096 Fix DebugElement toBeDefined to not.toBeNull

---

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts

I couldn't find a very ideal way to implement this, so it isn't as clean a solution as I would have liked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/841)

Make email address clickable in sync disabled message

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- Removed previous logic that set RTL/LTR based on text contained in a paragraph
- Enforce direction based on project `isRightToLeft` setting from Paratext
- Improved USX formatting for RTL
Issues identified to be addressed were:
1. Arrow keys do not work at the end of a segment.
2. Unable to select the first position in a segment.
3. In a LTR segment, typing at the beginning of the segment adds to the end.
4. Unable to navigate to a blank segment.
5. In a LTR segment, unable to select the end of the segment.
6. Selection marker should appear on right side when document is RTL.
This PR does not look heavily at bidirectional text within segments but focuses on RTL scripts working correctly. Segments can contain LTR scripts but Chrome decides to handle things differently where it will jump …

SF-955 - Editing in a RTL text is inconsistent

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

A couple list items in the help menu were not fully clickable (some regions of the list item just closed the menu when clicked). Here's a visualization of the element structure created using Pesticide CSS:
Before | After
-------|------
I've made two changes:
1. The entire region of each of the top two list items is now clickable.
2. I changed `<div class="mdc-list-group__subheader">` to `<div mdcListGroupSubheader>` because it seemed more consistent with the way we use Angular MDC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/846)

Fix clickability of help menu list items

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts

* tell user when an audio file cannot be preview as is the case for .wma files
* users can play the .wma file once uploaded and converted to a .mp3
* handle .ogg audio files by using the lastInvalids event emitter in firefox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/842)

SF-1009 Inform user when previewing audio is not available

---

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss

- The contents of the list can start to disappear from view if wrapped
over several lines in the vertical space given to each list item.
This can happen if the project name is long, or if we append
"(already connected)".
- Increase the width of the two project lists to decrease the chance
of some of the menu item being obscured by wrapping. It only starts
to be a problem if it wraps over more than 2 lines.
- The #projects-menu min-width uses min() to help choose between
values suitable for different size viewports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/843)

SF-1104 Increase width of project selection list

---

deploy/dependencies.yml

While testing SF-1047 (server Ansible for ParatextData) on a dev machine by adding some Ansible into our existing dev machine Ansible files, the WritingSystemRepository directory was found to be something our dev machine ansible wasn't covering already. This PR adds that in. 
And also a cleanup while working in that area.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/849)

Setup: Add WritingSystemRepository, enhance

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

When viewing both `source` and `target` in the translate app the `source` was having Quill set to the RTL of the `target` project. This change now checks `isRightToLeft` from the `TranslateSource`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/853)

Added checks for RTL on both source and target

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts

* The answers component loads audio content through the cache
* Audio cache gets updated anytime local audio is uploaded
* When browser or add-to-homescreen is re-opened it will play cached answers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/848)

SF-1107 Access answer audio through cache

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts

* provide isRightToLeft data to components checking text, question dialog and text chooser dialog
* set the dir attribute in the quill editor to auto when showing the placeholder
**BEFORE**
**AFTER**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/854)

SF-1123 Set isRightToLeft on every instance of TextComponent

---

lgtm.yml

* restore normal C# build now that we are .NET Core 3.1 rather than buildless inspection only settings
* install node and npm
However it does take longer to complete, ~ 17mins instead of 7mins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/835)

SF-1057 Change LGTM.com custom build

---

test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

The `PutNotes_AddEditDeleteComment_ThreadCorrectlyUpdated` test has consistently broken on my laptop - I ran a quick step through and noticed that in ParatextService.cs, line 338:
```cs
var existingComment = existingThread?.Comments.FirstOrDefault(c => c.Id == comment.Id);
```
was consistently returning null.
Looking into it, it seems that the comment id is a concatenation of the thread, user, and date attributes.
To fix this, my change sets the date in the comment XML to a consistent value.
As to what causes the date value to be consistent for most other people I am not entirely sure - it could be raw CPU speed, CPU pipelining or caching, or the maybe the JIT doing a neat trick on platforms it can do it?
--- …

SF-1089 Fixed test breaking on some computers

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

- Check to ensure mediaDevices is defined
This is more of a generic fix that will apply to any device/browser that doesn't have access to `mediaDevices` i.e. any browser other than Safari on iOS will now receive the improved message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/866)

SF-1130 - Chrome on iOS fails to record audio

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts

- Reset translate engine on remote changes to the projectDoc
- Created a test to ensure the translate engine correctly starts if not initially started or stopped and then started again
As part of this fix it also resolved another issue where the translate engine would not start if it was initially disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/868)

SF-967 - Console error appears on Translate Overview page when translation suggestions remotely disabled

---

src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html

Checking overview
Answer question form
Import questions dialog
Create/edit question dialog
MdcDialog automatically spaces buttons by 8px when buttons have the `mdcDialogButton` directive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/869)

Add spacing around buttons

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- We don't currently support connecting to a project that isn't listed
in the PT Registry, like back translation projects can be.
- Omit such not-registered projects from the list returned by
ParatextService GetProjectsAsync().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/862)

SF-1121 Don't show not-registered projects in connect list

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

When adding a book, the book is appended to the end of the list of Texts in a SFProject. However, the front end SFProject represents the texts in a list that is sorted by bookNum. When we send an op to remove a specific index, it removes it correctly on the backend, but that index doesn't correspond to the correct text on the front end. Currently, I only see this being an issue on deleting books, but this can certainly be an app wide issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/865)

SF-982 Retrieve sorted texts without modifying project texts property

---

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
src/SIL.XForge.Scripture/Models/CheckingConfig.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

- CheckingConfig.cs: Changing default setting in model.
- connect-project spec: Using new default value in case it ever
matters or adds clarity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/871)

SF-1142 Disable project sharing by default

---

src/SIL.XForge.Scripture/Resources/SharedResource.resx
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/SharedResource.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

SFProjectService.cs:
- InviteAsync() no longer sends a link that anyone can use to join the
project, even with the project is being shared to "Anyone with a
link". All invitation emails are now sent with a code that is
specific to the invited email address.
- Clean up method a bit now that the functionality is simplified.
SharedResource.resx:
- Remove no longer used InviteLinkSharingOn.
- The InviteLinkSharingOff name is not very helpful, but I don't want
to change it lest it require re-translations. So I added a comment
to address the change. The name should probably be something like
LinkIsEmailAddressSpecific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/872)

SF-1141 Always invite with code

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/Models/TransceleratorQuestion.cs
src/SIL.XForge.Scripture/Services/TransceleratorService.cs
test/SIL.XForge.Scripture.Tests/Services/TransceleratorServiceTests.cs

- Answers are a feature of Transcelerator that I initially implemented support for, and then didn't use. It would have been good to rip this out before, but I left it.
- SF-1151 Is caused by an exception that is thrown when when `NodeTextOfLanguage(IEnumerable<XmlNode> nodes, string lang)` calls `SingleOrDefault()` on an `IEnumerable<string>` that has multiple stings. I assumed there would only ever be one example answer, with one at most one translation per language. However, there can be multiple example answers, with each answer having translations.
Here's the XML that was causing the error to occur:
``` xml
<Question id="Why is this true?" startChapter="3" startVerse="22">
<Q>
<StringAlt xml:lang="fr">Tell in your own words the basic meaning (theme) of what John said in these …
```

SF-1151 Fix error when Transcelerator question has multiple answers

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

The previous implementation mistakenly assumed that when a question is within a single chapter, endChapter will be defined and equal to startChapter. In reality it is undefined in this case, but with this fix no assumption is made as to whether it will be undefined or equal to startChapter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/875)

SF-1149 Include end verse when importing questions from Transcelerator

---

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss

- Removed unneeded flex layout options
This appears to have been a Safari specific issue rather than Chrome on iOS as it also happened on a Mac. It appears Safari can struggle with flex and calculating heights correctly when inside a `flex-direction: column`. It is likely there is a good combination of CSS that can be added if that property is really needed but, this instance, it simply didn't need to be there in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/879)

SF-1144 Overlapping text on connect project page in Safari

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

After importing a question from Transcelerator I went to edit the question and found this:
While the mistake was in the original import logic, it was unveiled by the recent fix in #875 (SF-1149 Include end verse when importing questions from Transcelerator). Questions with no end verse are getting saved with a range of e.g. "1-undefined".
This fix basically consists of two changes:
- The setting of `verse` on `verseRefData` is now conditional. Previously it would sometimes get set to `undefined`, but that's not the same as not setting it.
- Ensure the end verse actually exists before setting the verse range. Previously it just checked that it differs from the start verse, which is not sufficient.
--- …

Fix importing of questions on a single verse

---

src/SIL.XForge.Scripture/Resources/SharedResource.resx
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/SharedResource.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs

Questions or answers that are audio without any texts would appear as blank in Paratext. This adds a place holder for that situation in Paratext notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/876)

SF-1136 Indicate in Paratext Notes when responses are audio-only

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

* extract filtering controls from table header
* shorten some text to display on mobile
* stack reference filter fields on mobile
Before
After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/887)

SF-1160 Improve import question dialog layout and mobile view

---

src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html

This is essentially a sequel to #869, which addressed it in some places, but left several dialogs untouched.
The `mdcDialogButton` directive takes care of placing a small amount of spacing between buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/890)

Add spacing around several dialog buttons

---

src/SIL.XForge.Scripture/Models/Chapter.cs
src/SIL.XForge.Scripture/Models/TextInfo.cs
src/SIL.XForge.Scripture/Models/TranslateSource.cs

This is a hotfix to correct the issue on QA:
```
System.FormatException: An error occurred while deserializing the Texts property of class SIL.XForge.Scripture.Models.SFProject: Element 'permissions' does not match any field or property of class SIL.XForge.Scripture.Models.TextInfo.
---> System.FormatException: Element 'permissions' does not match any field or property of class SIL.XForge.Scripture.Models.TextInfo.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/893)

QA Only: A hotfix to ignore extra elements in the BSON

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/supported-browsers-dialog/supported-browsers-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/supported-browsers-dialog/supported-browsers-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

* iOS devices specifically mention using Safari
* supportedBrowser component updated to show OS specific messages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/891)

SF-1148 Improve message when audio recording is not supported

---

src/SIL.XForge.Scripture/ClientApp/angular.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.developmentBeta.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prodBeta.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.stagingBeta.ts
src/SIL.XForge.Scripture/Pages/Shared/_SelectLanguagePartial.cshtml
src/SIL.XForge.Scripture/Program.cs
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Startup.cs
src/SIL.XForge.Scripture/appsettings.Beta.json
src/SIL.XForge.Scripture/appsettings.DevelopmentBeta.json
src/SIL.XForge.Scripture/appsettings.StagingBeta.json
src/SIL.XForge.Scripture/appsettings.TestingBeta.json
src/SIL.XForge.Scripture/hosting.Beta.json
src/SIL.XForge.Scripture/hosting.DevelopmentBeta.json
src/SIL.XForge.Scripture/hosting.Staging.json
src/SIL.XForge.Scripture/hosting.StagingBeta.json
src/SIL.XForge.Scripture/hosting.TestingBeta.json
src/SIL.XForge.Scripture/hosting.json
src/SIL.XForge/Configuration/RealtimeOptions.cs
src/SIL.XForge/Controllers/UsersRpcController.cs
src/SIL.XForge/Services/AuthService.cs

- This change allows two SF apps to be run from the codebase at the
same time. One serves requests to beta.localhost:9000 and the
other serves requests to localhost:5000. This is to help with
development of a beta.scriptureforge.org to scriptureforge.org
transition.
- In production, Angular is precompiled and used from
ClientApp/Dist. In development, Angular is provided via
`ng serve`. SF Startup.cs will either start an `ng serve`, or
listen to an existing one, depending on
--start-ng-serve={yes,listen}.
- `dotnet run --start-ng-serve=yes --configuration=Development` will
result in Startup.cs using package.json script `start` to run
`ng serve`. `--configuration=DevelopmentBeta` will result in
script `startBeta` being used instead, to run
`ng serve --configuration=developmentBeta`.
- The …

SF-1155 Support beta.localhost:9000 and simultaneous localhost:5000

---

src/Migrations/SourceTargetSplitting/ObjectMigrator.cs

This fix for the develop branch fixes an issue where the book permissions were being written to the chapter permissions collection when the migrator was run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/900)

Fix chapter permissions migration

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
src/SIL.XForge.Scripture/Controllers/ParatextController.cs

This change does not wait until the user enables translation suggestions before fetching the projects and resources (as was requested in the issue), for a couple reasons:
- Almost all the delay was with updating the DOM, not with the network request.
- This change _does_ make the request for resources _significantly_ faster, by fetching in parallel with the request for projects, and by returning only the data that is actually needed.
- I thought it better to get this PR out now and get feedback rather than delaying it further. Additionally, since the loading speed has been dramatically improved, it warrants reassessing what further optimization is necessary, and gzipping the response may be a better alternative than lazy loading.
--- …

SF-1154 Allow selecting resource a project is based on

---

README.md

- It does not appear to be significant whether `ng serve` is running,
except for RAM usage.
- Inline the settings needed for CHROME_BIN.
- Use `npm test` so `--sourceMap=true` is pulled in, as well as
whatever other default parameters we want to write into package.json.
(rather than `ng test`).
- Document how to get --include to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/903)

docs: Update test-running instructions

---

src/Migrations/SourceTargetSplitting/ObjectMigrator.cs
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- only show source if the user has permission (frontend)
- if not on the project then no chapter permissions (backend)
- only get the Paratext username mapping once per project (instead of for every chapter)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/905)

Fix book permissions

---

src/Migrations/SourceTargetSplitting/ObjectMigrator.cs

- skip searching projects that don't have a source
See **Local scenario 6** in GDoc **Migration: Split Out Source Project**.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/906)

Fix NRE in migrator

---

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts

This was overlooked in #899.
Since it was an issue with one component not providing information to another component, there isn't any change to the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/907)

Prevent selecting a project as based on itself

---

src/RealtimeServer/common/realtime-server.ts
src/RealtimeServer/common/services/doc-service.ts
src/RealtimeServer/common/services/project-data-service.ts
src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/RealtimeServer/tsconfig.json
src/RealtimeServer/typings/sharedb/index.d.ts
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

In order to upgrade to sharedb v1.0.0 from the beta sharedb, we need to update to v1.0.0-beta.31 and allow users' browsers to update. This beta will be forward compatible to the v1.0.0 release. See [sharedb beta client compatibility](https://github.com/share/sharedb/wiki/Upgrading-to-sharedb@1.0.0-from-1.0.0-beta#beta-client-compatibility)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/897)

SF-1165a Update sharedb beta to prepare for future upgrade

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

- after PR #905 it had a 404 when cloning a resource
- this fix ensures paratextService.GetParatextUsernameMappingAsync doesn't get called for resources like the code was before the PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/917)

Fix error when cloning a resource

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- Querying for resources can get an ephemeral error, such as 401
Unauthorized. Trying again can be successful.
- Give the user an empty resource list rather than a 500 internal
server error popup dialog.
- There is still an underlying problem that has been around for maybe
a long time. Log the occurrence to bugsnag.
----
There is some more discussion about this in chat.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/918)

Return empty resource list if lookup error

---

src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts

Previously, if a user selected a project it would close the typeahead, but the input field would still be focused. Because of this, clicking the input would not open the typeahead again. The user would have to click outside the input to blur the element, and then click the input element again.
(If you want to test this, try selecting a project, and then "realize" you selected the wrong one and click in the input element again).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/920)

SF-1176 Allow re-opening project typeahead without blurring input

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html

- remove connect project button (available elsewhere)
- reorder SA project roles to place None and Administrator together at the top of the select (2 most commonly used values)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/924)

Misc SysAdmin cleanup

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/Models/SyncUser.cs
src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs
src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs
src/SIL.XForge/Configuration/DocConfig.cs
src/SIL.XForge/Configuration/RealtimeOptions.cs
src/SIL.XForge/Realtime/Document.cs
src/SIL.XForge/Realtime/IRealtimeServer.cs
src/SIL.XForge/Realtime/IRealtimeService.cs
src/SIL.XForge/Realtime/MemoryRealtimeService.cs
src/SIL.XForge/Realtime/RealtimeServer.cs
src/SIL.XForge/Realtime/RealtimeService.cs
src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
src/SIL.XForge/Services/IProjectService.cs
src/SIL.XForge/Services/ProjectService.cs
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

This PR is broken into two commits [for code review. We can squash to one commit for merging.]. The first commit adds some tests and makes some changes to allow for testing. Its commit message is:
SF-798 First add tests and prepare for delete-user implementation
- Add comments.
- Introduce IRealtimeServer to allow mocking.
- Add early-crash argument checking to some methods. This should be
the commit's only behavioural change.
- Expose RemoveUserFromProjectAsync() as internal for unit testing.
- Add tests for existing functionality.
- ProjectServiceTests Sites are expanded to be consistent with
TestProject documents, for these or follow-up tests.
The second commit makes the actual changes for SF-798. Some items to point out are:
- ProjectService RemoveUserAsync() can silently fail if …

SF-798 Remove user docs and project associations

---

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html
src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

This adds SF custom colors to be applied to angular material components. Material design has its defined [color palette](https://material.io/design/color), but it was difficult to adapt this to the SF theme we currently have, therefore this defines a custom color palette.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/930)

SF-1184 Add custom theming for angular material components

---

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

- Rather than sit at a blank page with a progress bar that keeps going
forever.
- Report to bugsnag so we can keep an eye on this happening.
-----
Animation showing behaviour when the user is in fact not on any project:
Animation showing behaviour when the user is on a project (i.e. another project):
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/927)

Tell the user and redirect if project is not found

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

- Added new static method handleBreadcrumb
This initial commit is targeted at buttons but it can be expanded to other elements as needed.
Aim of this is to resolve common struggles with Bugsnag trying to identify the label of buttons but not getting anything useful.
**BEFORE**
**AFTER**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/886)

Improve Bugsnag Breadcrumbs

---

src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs
src/SIL.XForge.Scripture/Services/DotNetCoreAlert.cs
src/SIL.XForge.Scripture/Services/IParatextDataHelper.cs
src/SIL.XForge.Scripture/Services/InternetSharedRepositorySourceProvider.cs
src/SIL.XForge.Scripture/Services/NotesFormatter.cs
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/PersistedParatextDataSettings.cs
src/SIL.XForge.Scripture/Services/PersistedPtxUtilsSettings.cs
src/SIL.XForge.Scripture/Services/SFHgRunner.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
src/SIL.XForge/Services/IUserService.cs
test/SIL.XForge.Scripture.Tests/Services/MockLazyScrTextCollection.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

Frequently when I work in C# land I come across unused imports. So I just went through and removed them all at once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/945)

Remove unused C# imports

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
src/SIL.XForge.Scripture/ClientApp/tsconfig.json

---
I'm looking at more strict or lint checks we can turn on. I like that noImplicitReturns makes us be more explicit. But the particular places it required a change in didn't seem very significant. And in import-questions-dialog.component.ts it seems conceptually wrong to return undefined in places where we don't want to add to the array.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/946)

Turn on noImplicitReturns

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

The button part of the refresh banner should now appear behind the menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/948)

SF-1190 Refresh banner button overlaps nav bar menu

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs

The problem that occurred was that if a source project existed, the AddUserToProject method would recursively call itself for the source project, which also creates a ProjectUserConfig. This change removes the unnecessary lines that add a ProjectUserConfig that has already been created.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/941)

SF-1178b Fix error from adding projectUserConfig twice

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- problem #1: an optimistic query will return the data in IndexedDB without permissions and then the server will return the data with permissions, on the first access after migration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/951)

SF-1162b fix missing permissions

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/ISFRestClient.cs
src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/JwtRestClient.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
src/SIL.XForge.Scripture/Services/SharingLogicWrapper.cs
test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

ParatextData started using HexId for Paratext project IDs. There are
several places where we could draw the line between code using a
string for PT project ID, and code using a HexId for PT project ID.
This commit converts to/from HexId when using a type from
ParatextData, and attempts to retain the string type for PT project
IDs in SF code.
Also the code for a Head registry request was move into Paratext Data
and this removes it from SF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/949)

SF-1171 Update to ParatextData 9.2.4-alpha8, account for HexId

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/Models/InviteeStatus.cs
src/SIL.XForge.Scripture/Resources/SharedResource.resx
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/SharedResource.cs
src/SIL.XForge/Models/ShareKey.cs
test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

* email link expires in 14 days
* resending an email invitation renews the 14 day valid period
* user can choose any email to access the project
* expired invitations show as expired on users page
* notify user the link will expire
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/954)

SF-753 Expire specific user invites and remove email constraint

---

src/SIL.XForge.Scripture/ClientApp/angular.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.developmentBeta.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prodBeta.ts
src/SIL.XForge.Scripture/ClientApp/src/environments/environment.stagingBeta.ts
src/SIL.XForge.Scripture/Pages/Shared/_SelectLanguagePartial.cshtml
src/SIL.XForge.Scripture/Program.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Startup.cs
src/SIL.XForge.Scripture/appsettings.Beta.json
src/SIL.XForge.Scripture/appsettings.DevelopmentBeta.json
src/SIL.XForge.Scripture/appsettings.StagingBeta.json
src/SIL.XForge.Scripture/appsettings.TestingBeta.json
src/SIL.XForge.Scripture/hosting.Beta.json
src/SIL.XForge.Scripture/hosting.DevelopmentBeta.json
src/SIL.XForge.Scripture/hosting.Staging.json
src/SIL.XForge.Scripture/hosting.StagingBeta.json
src/SIL.XForge.Scripture/hosting.TestingBeta.json
src/SIL.XForge.Scripture/hosting.json
src/SIL.XForge/Configuration/RealtimeOptions.cs
src/SIL.XForge/Controllers/UsersRpcController.cs
src/SIL.XForge/Services/AuthService.cs

- Realtime updates will only work if beta and non-beta sites share the
same realtime server. So use the same realtime server. It will be the
one started by the non-beta app.
- So changing environment.prodBeta.ts and environment.stagingBeta.ts
`realtimePort` to match the non-beta setting.
- The beta apps will end up starting a realtime server, listening on
port 9003, that is not used, as specified in appsettings.*Beta.json.
- So to use the beta app, first start the non-beta app before starting
the beta app, so that the beta app can use the non-beta app's realtime
server. For example, on a workstation with two terminals in
`src/SIL.XForge.Scripture`, run the following two commands. Don't run
the second one until the first one has completely started, which may
take a few minutes.
dotnet run …

SF-1155 Use same realtime server for beta

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts

Chromium stopped including a space in the date format for zh-CN, which broke a test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/965)

Fix date localization test so it can pass in both Chromium 87 and 88

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts
src/SIL.XForge.Scripture/Models/TranslateMetrics.cs

- Event timeStamp gives huge numbers in iOS Safari, but numbers of ms
on other platforms.
- So don't use Event timeStamp, and instead store the activity start
time another way, by writing to an activity whenStarted the ms
reported from `Date.now()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/959)

SF-1153 Store activity time, not use event.timeStamp 

---

src/SIL.XForge.Scripture/Controllers/ParatextController.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Models/Tokens.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/Models/TokensTests.cs
test/SIL.XForge.Tests/Services/TokenHelper.cs

- On the settings and connect project pages, we send two HTTP requests, one for projects and one for resources.
- Both requests cause the back end to send HTTP requests to Paratext.
- The access token for Paratext expires after 20 minutes and needs to be refreshed if it is expired.
- Previously only the projects endpoint refreshed the token (the request for resources did not, so if the token was expired, that request would fail).
- Now both requests cause the token to be refreshed, but if a refresh is in progress that the other request started, then a new refresh is not started (otherwise it would result in an error from Paratext).
--- …

SF-1181 Refresh access token if needed before fetching resources

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Models/ShareKey.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

* link sharing now uses a sharekey with a corresponding role
* the backend now expects a role whenever inviting a user
* the share control displays the share link with the sharekey
In order to test these changes, you must first run this command in the mongo shell:
```
use xforge
db.sf_project_secrets.updateMany(
{ },
{ $set: { "shareKeys.$[elem].projectRole": "sf_community_checker" } },
{ arrayFilters: [ { "elem.projectRole": { $exists: false } } ] }
)
db.sf_project_secrets.updateMany(
{ },
{ $set: { "shareKeys.$[elem].expirationTime": new Date(2021, 11) } },
{ arrayFilters: [ { "elem.expirationTime": { $exists: false } } ] }
)
```
--- …

SF-1199 Include project role in sharekey

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

The question ids provided by Transcelerator are only unique for a given reference. Previously the Scripture Forge side of the integration assumed ids were unique within the project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/972)

Fix Transcelerator import determining whether question is edited

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

Note that this only sorts by the starting book, chapter, and verse, and ignores the end chapter and end verse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/977)

Fix question sort order in import question dialog

---

src/SIL.XForge.Scripture/Controllers/ParatextController.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs

This isn't a very elegant solution, but I'm really not sure which abstraction layer should be responsible for checking whether we should proceed. One option is to allow an exception to be thrown, then catch it high up the stack. That doesn't seem very elegant either.
I would welcome arguments/reasons for why this should be done differently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/973)

SF-1181b Fix 401 error on connect project page

---

scripts/build-and-upload-beta.sh

- When deploying SF Beta, restart scriptureforge-web-app_beta, not
scriptureforge-web-app.
- APP_SUFFIX is a string like one of "_beta_qa", "_beta", "_qa", "".
From those options, derive "_beta" or "".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/983)

Deploy: Restart correct service

---

.vscode/launch.json

===
Significant parts are --enable-beta-realtime-server=yes and DevelopmentBeta environment variable value.
This isn't hugely significant,  but we can clean it up in the future when we presumably no longer have a Beta.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/986)

Add DevelopmentBeta launcher

---

scripts/build-and-ship

- 503.html was being installed manually. Automate it. Any error pages
in the ErrorPages directory will be included.
- `-progzlt` was quite close to `-a`, which is basically `progltD`. I
include `v` so we can see the transfer in the TC log.
- I did not include `--chmod`. The 503.html on scriptureforge-live has
permissions of 644. Testing to scriptureforge-qa shows it still uses
mod 644.
--- 
This relates to a discussion with Ira regarding our ansible, so probably don't merge this PR without  @irahopkinson 's approving first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/969)

Deploy: Install 503 error page

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts

- Adjusted http intercept handler to ensure the user is authenticated before adding access token to the header
This fix will ensure no requests to the backend will be made unless the user is authenticated with a valid access token that hasn't expired. Any requests made while there is an expired token will await auth0 (via `checkSession`) before it proceeds. This all happens silently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/992)

SF-1238 - Unauthorized error after 2 hours

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-questions-confirmation-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts

- Tests leave dialog and other content in the HTML overlay. This can
cause problems to following tests as they look for the presence or
properties of elements. Whether it's a problem can vary by the order
the tests are run in.
- test-utils.ts: Require that tests clean up the overlay by at least
removing added content (if not the whole overlay). Throw an error for
any test that does not clean up. Note that this only applies for tests
that use configureTestingModule.
- Adjust existing tests so that they clean up the overlay, such as by
clicking a dialog Close button.
- delete-project-dialog.component.spec.ts: Add an additional check
that the correct dialog result occurred, since more than one dialog
button was clicked.
- Add some expect().nothing().
- …

Require tests to clean up overlay

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts

Fixes test error using null linkSharingKey. The tests were not properly mocking the project service.
I also changed how we check for an empty string:
``` diff
- if (this.linkSharingKey.length < 1) {
+ if (this.linkSharingKey === ''") {
```
As far as I can tell, these are nearly identical. The main difference is that the latter will not crash when `linkSharingKey` is null or undefined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1000)

More accurately mock onlineGetLinkSharingKey

---

src/SIL.XForge.Scripture/ClientApp/src/manifest.json

- The Angular service worker isn't passing Chromium's check for
offline capability. This workaround makes the site pass Chromium's
check and does not appear to change what happens if a user goes to /
or /projects .
- This workaround can presumably be undone when
https://github.com/angular/angular/issues/41085 is fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1003)

SF-1239 Set manifest start_url to cached item

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

paratext-qa.thedigitalbiblelibrary.org is currently broken
We discussed this at the most recent planning meeting.
I don't think this needs to wait for the next release, because it only affects dev and testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1012)

Switch local DBL access from paratext-qa to qa subdomain

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

- To help do testing on QA and dev machines.
- Did not localize the 'Beta site' string that should not be showing
in production.
See animation:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1013)

Link to Beta site, but not when at Live

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.ts

- Changed beta dialog to login again on the event of a login_required event from the beta site
- Post message from beta to non-beta if a login is required
This issue occurs when the beta site fails to validate a token with auth0 for whatever reason which leaves it in a logged out state. The non-beta still thinks it is logged in and so keeps on trying to migrate.
The fix takes a prompt from the beta site that a login needs to occur and the non-beta site then triggers a login to occur. After the login has taken place the migration dialog will appear again and this time the beta site will load correctly.
Although I wasn't able to replicate the token issues on localhost there are quite a number of occurances in bugsnag. 
Here are a few of the responses returned from auth0 with the …

SF-1255 - Migration problem retrying

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

The user should be informed when the link sharing URL is not available due to being offline. Here are some screenshots showing two scenarios, one where the page is loaded and then the user goes offline, and the other where the user is already offline when the page is loaded.
Online, then going offline (share link still available) | Offline at the point of visiting the page
-------------------------------------------------------------------|----------------------------------------------------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1019)

SF-1232 Inform user when sharing link is unavailable offline

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration.component.ts

- Removed reliance on document referrer and instead did a frame check along with the migration path
This isn't full proof and it will stop being able to browse the site in beta mode but I believe we're beyond the need to do that now.
----
I tested this on my workstation and showed that it fixes the migration dialog loop in Firefox, and that Chromium still works ok.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1023)

- Only allow the migration component to run on beta

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

- Remove filtering on pending ops in sharedb-realtime-remote-store.ts
- Add filtering of pending ops prior to updating IndexDB
This update allows us to check for any pending operations from sharedb in order to determine if IndexDB needs to be updated. After that check we can filter out any operations that we don't need to store in IndexDB which is what was originally taking place in `SharedbRealtimeDocAdapter`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1022)

SF-1251 - Editing new offline data is not saved in IndexDB

---

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

* separate out scenarios when activating projects route
* if offline show a dialog message
* navigate to the last project upon closing the dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1001)

SF-1231 Handle when using a share link while offline

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss

- Change the scripture verse highlight background colour
Technically the contrast between the text colour and the background has decreased in percentage but the new background yellow is much deeper and easier to see on devices. We viewed this across multiple contrast and colour blindness filters to ensure it stood out intended - the previous colour did get washed out very quickly and became invisible. This will also help with monitors having a high contrast or brightness set which can also wash everything out.
This updates quill for both the translate and checking app.
**BEFORE**
**AFTER**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1027)

SF-1299 - Increase source highlight contrast

---

src/RealtimeServer/scriptureforge/models/sync.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/Models/Sync.cs
src/SIL.XForge.Scripture/Services/HgWrapper.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* compare the data version to the version of the hg repo
* if out of sync, skip pushing any changes
* do not allow editing text in a project that is out of sync
* add method to Paratext service to report the hg repo revision
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1039)

SF-1320a Detect when project data is out of sync with the hg repo

---

src/SIL.XForge.Scripture/Models/ParatextNoteThreadChange.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* detect when a Paratext comment has been permanently removed in Paratext
* remove the note from the note thread doc
* detect when a Paratext comment thread has been permanently removed
* delete the note thread doc when comment thread has been removed
* also refactor to get username mappings from Paratext service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1038)

Remove notes when permanently removed in Paratext

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

- fix TypeError · Cannot read property 'style' of null
- since DeltaUsxMapper may not set style, make it optional in TS in `UsxStyle` interface
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1043)

SF-1325 Fix type error style null

---

src/RealtimeServer/common/models/project-rights.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts

The data migration adds the property, but there are ways to end up with updated code and non-migrated data which causes errors. This is a temporary fix so we can ship. Long term the way we handle migrations will need to be improved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1050)

Temporarily fix userPermissions undefined error

---

.github/workflows/ci.yml

- don't need to build for Windows
- prep for moving up to node v16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1060)

Production build: remove windows, add node v16

---

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts

Also stop sending API requests to change permissions when the associated checkbox is disabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1053)

Prevent attempting to change user permissions while offline

---

src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Realtime/Json0/Json0OpBuilder.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

- Permissions were being updated in SF, but on Synchronization. This
means a PT user who joins a SF project won't have their expected PT
permissions until the next Synchronization.
- Separate out permissions updating in ParatextSyncRunner, leaving a
separate UpdateDocsAsync() and UpdatePermissionsAsync(). Move it into
SFProjectService, where it is now called both by
ParatextSyncRunner.RunAsync() and by
SFProjectService.AddUserToProjectAsync().
- Users can join a project in a number of ways. This commit handles a
user joining by connecting a project to SF for the first time
(SFProjectService.CreateProjectAsync()), joining a project by a link
(SFProjectService.CheckLinkSharingAsync()), or "connecting" an
already-connected project using the Connect Project page …

SF-1287 Update text permissions on user join

---

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
src/SIL.XForge.Scripture/Models/InviteeStatus.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs

While considering whether SF-1198 is complete (Allow inviting users to view translation) this seemed like something that was missing, as it's not possible to tell what role a user was invited to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1068)

Show invitee role on users page

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

When a user is re-invited with a different role the invitation role should be updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1069)

Update invitee role when user is re-invited

---

.vscode/settings.json
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Models/SFProjectSecret.cs
src/SIL.XForge.Scripture/Services/IJwtTokenHelper.cs
src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/IParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/ISyncService.cs
src/SIL.XForge.Scripture/Services/JwtTokenHelper.cs
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/Services/SyncService.cs
src/SIL.XForge/DataAccess/IUpdateBuilder.cs
src/SIL.XForge/DataAccess/MemoryUpdateBuilder.cs
src/SIL.XForge/DataAccess/MongoUpdateBuilder.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
test/SIL.XForge.Tests/DataAccess/MemoryUpdateBuilderTests.cs

This adds support for cancelling a sync that is queued or in progress.
Cancellation is handled via a `CancellationToken`, with this passed to logic that will accept it with the exception of ParatextData, which uses a static system-wide cancellation method (calling this would be catastrophic for any calls being made to ParatextData in other threads concurrently). The `ParatextSyncRunner.RunAsync()` method polls this value at specific places so that cancellation can be handled without causing corruption. If the job was cancelled after the data was downloaded from Paratext, but before it could fully be loaded into the database, the logic utilizing the `Sync.DataInSync` property from SF-1320a will ensure that the user cannot make modifications to the data until they complete a successful …

SF-1048: Added Cancel ability when synchronizing

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- Notes on blank segments will now appear
- show notes attached related segments in poetry
- Specifically handle conflict notes by setting the icon on the thread
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1041)

Show conflict note icon and note on blank segments

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.spec.ts
src/SIL.XForge.Scripture/Pages/Index.cshtml

- pass language through Auth0 so PT login is localized
- stop using Auth0 language picker
- also fixes using the locale from an invite link
This is a draft waiting on a dependent change. Please first review https://github.com/sillsdev/auth0-configs/pull/100. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1074)

SF-1033 localize PT login

---

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

This pull request fixes the following bugs found when using the cancel sync feature:
- Updates to the cancellation message (commit 8ffd282)
- When a sync is cancelled, the status was not being correctly updated in some cases (commit de70969)
- A TaskCancelledException is no longer logged when a CancellationToken request is caught in third party code (commit 278348e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1084)

SF-1048c: Fix cancel sync bugs

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/Realtime/RealtimeJsonService.cs
test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs
test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

This pull request should help reduce out of memory issues by fixing the following memory leaks:
- `ScrText` objects are now disposed after they have been created (commit 6d2f1385138df1dc7ad4a8d9341b9ef35d2e4689).
- The `RealtimeJsonService` now uses `JsonSerializer` instead of `JToken` to reduce memory use and object creation (commit d47f155c646e711aeb259b2ac18c3738aebccebb).
- Added `using` statements to tests that were missing them (commit a040d350fc581d7dc98a5f2414061c50c3eb4d8e)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1073)

SF-1219b: Fix remaining memory leaks

---

mongodb/TranslateMetrics/TranslateMetricsAggregation.mongodb

I created a folder for any `.mongodb` playground files we want to keep and share.
This playground aggregates translation metrics for a particular project book.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1081)

Translation Suggestion metrics aggregation

---

src/SIL.XForge.Scripture/ClientApp/src/app/app-routing.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/users-routing.module.ts
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Realtime/IRealtimeService.cs
src/SIL.XForge/Realtime/MemoryRealtimeService.cs
src/SIL.XForge/Realtime/RealtimeService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs

This pull request adds support for translators who are not administrators to sync.
As well as the UI change, the primary change reads the id of the last user to modify a chapter from MongoDB, and uses that user to synchronize the chapter they edited from SF to the local Paratext repo. This means that the correct permissions are employed, as the `ScrText` is used, utilizing the permission user who made the modification rather than the user who is performing the synchronization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1082)

SF-1357: Translators can now sync

---

src/SIL.XForge/Realtime/RichText/Delta.cs
test/SIL.XForge.Tests/Realtime/RichText/DeltaTests.cs

Char nodes in the text delta appear when words in a text have special meaning or formatting like a footnote.
This specific type of formatting is represented in the text docs as an op like this.
The cid property of a char node is generated and stored in our text docs, but are not stored in Paratext. So it can be safely ignored when processing delta diffs.
To test this, you can use a project with footnotes (the more embedded the better). The text doc for the book and chapter containing the footnote will increment the text doc version for every sync, even when there is no text changes. Then after this change, the text doc version number will not change for every sync.
--- …

SF-1348 Ignore cid object property on char nodes when comparing text deltas

---

src/SIL.XForge.Scripture/Services/IInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

This pull request makes the following changes:
**When a project is synchronized, an attempt is always made to unlock the repo**
If the connection between the SF server and the PT server is interrupted on sync, the lock can remain on the PT server for around 15 minutes. This change makes it so that before a sync, an unlock is performed. Nearly every time, this will return an error (as project is not locked). However, if the project was locked, it will be unlocked, and the sync will run successfully. This is done this way, as there is no accurate way to see if a sync failed because of a lock, except by reviewing the logs.
https://github.com/sillsdev/web-xforge/blob/a700ac6fc0324a2f8099ba9908bb1d4c31c1c19a/src/SIL.XForge.Scripture/Services/ParatextService.cs#L203-L211
**The ShareChanges …

SF-1367: Improved sync error checking and added auto-unlock

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

- Change usx-blank into an inline-block with a fixed width
- Move position of cursor to appear after usx-blank in order to keep it inside the usx-segment element
- Adjusted quill left/right handlers to work with new cursor position with usx-blank
**Please note that this fix is just related to data loss from going offline to online. If a bug other than that is found then check Jira as there may be a separate ticket for it.**
1. Load a project and navigate to a book in the translate app which has lots of blank segments
2. Load the same page in another browser or profile
3. Go offline (shutdown dotnet)
4. Insert text in to any of the segments across both browsers
5. Close down the tab in one of the browsers
6. Go online
7. OBSERVE: The browser that was left open should go online as normal
8. …

SF-1278 - Text lost, verse numbers duplicated, from multiple devices coming online

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

- To look for the directory where we intend to.
- Note that on Windows it was not causing a problem, but on Linux it
was including the backslash as part of the path segment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1105)

sync: Remove backslash from backup path

---

mongodb/Projects/projects_in_sync_state.mongodb

This is a trivially simple query, but I think it's worth having in the repo so we can easily check for projects that are in the syncing state without writing the query from scratch every time.
Also, since a query like this is typically (hopefully) going to return no results, it's hard to be confident a query was written correctly, since most incorrect queries don't find any results either (in a case like this I would typically modify the query to something like `{'sync.queuedCount': {$ne: 1}}` and check that it's returning a bunch of projects). Having a known-working version in the repo is therefore simpler than writing it from scratch every time.
In the past I've seen up to six or so projects that were all stuck in a syncing state on live.
--- …

Add query for projects that are in syncing state

---

src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/Models/TokensTests.cs
test/SIL.XForge.Tests/Services/TokenHelper.cs

This adds support for back translations by providing an alternate implementation of Registry functions for projects that are not found in the registry. The non-Registry implementations provide the same information as the Registry, but are slower, so are only used for projects where they are required.
Another feature added in this PR is that the Project FullName is updated if it is changed. These are changed only on the Registry, but in the case of Back Translations which are not in the Registry, this is required, as the FullName is loaded from the ScrText object.
Note that only the short name is shown when you connect to a project - this parallels Paratext - and so the short name will be updated with the full name on first sync.
--- …

SF-902: Back Translations

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/appsettings.json
test/SIL.XForge.Scripture.Tests/Services/MockLogger.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- To help diagnose the events that lead to problem situations.
- We can trim this down if needed.
- Output information about swallowed exceptions.
- The Log() method gets the project SF Id and user SF Id from the
object instance. But it can also be passed Ids to use (which is useful
in InitAsync(), where _projectDoc and _userSecret may not be set yet.
Otherwise it can fall back to "unknown", such as if we weren't given a
valid user id.
- Specifically specify the ParatextSyncRunner and EngineRuntime as
allowed for "Information" logging. This is redundant with "SIL" on the
line above, but if we remove "SIL" then (1) this makes it clear what
was something that was intended to be logged, and (2) it will be easy
to retain the logging of these.
--- …

sync: Add operational logging messages

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/appsettings.Development.json
src/SIL.XForge.Scripture/appsettings.json

- Clear trace listeners to stop showing ParatextData and hg output
during sync.
- Set log level filtering to show less on production server.
- Hiding email sends, some ParatextService messages.
- Showing info from sync or training engine.
- Set log level filtering to specifically show certain logging items
in development. These can be changed to Trace to see more
information.
- Show (faked) email sends.
- Show ParatextService messages.
- Hide most hangfire messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1110)

SF-1309 Reduce logging

---

src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This fix ensures that the DataInSync property is always written to the project doc outside of any transaction.
The second commit introduces a fix where a backup is restored at a revision that does not match our record in the project doc. In these cases, we mark that the data is in sync and the next time synchronized a full sync is done to save local edits.
A drawing of the scenarios can be found here. https://docs.google.com/drawings/d/1pCSxW-97I-iy0OFfR6ad7er6QpI8ePz3Sy27D11cNI8/edit
Acceptance tests:
Scenario 1
Bad scenario
1. Checkout branch SF-1371-a-bad and run command dotnet run.
2. Make a change to book text
3. Synchronize the project.
4. Go to book and observe that the book CAN be edited. Edit the book.
5. Checkout master branch and run command dotnet run.
6. Edit the book.
7. …

Exclude dataInSync from sync transaction

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

Before | After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1114)

Fix project select for long project names

---

src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.html

Autofilling the project name in the delete dialog doesn't make sense and can cause weird UI issues (see screenshot in issue).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1115)

SF-1373 Disable autofill in project delete dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- Turn off browser handling of drag and drop.
- Insert and remove plain text using deltas.
- In the made-up string, `x-dragstart-in-quill`, the `x-` is not
following any documentation for how to describe entries in
DataTransfer.types.
- text.component.html: Remove the disabling of drag-and-drop handling.
- text.component.ts: Add dragAndDrop to list of modules, and
specifying the TextComponent itself to pass to the DragAndDrop
constructor options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1097)

SF-1344 Remove formatting and newlines when drag and drop

---

scripts/db_tools/README.md
scripts/db_tools/text-doc-history.js
scripts/db_tools/utils.js

Likely more scripts to follow. Hence the use of a utils file and an attempt to centralize configurations regarding where the connections should be made to. The idea is that it should be very easy to run the scripts against localhost and then switch to running them against qa or live with only minimal changes (experience has shown that constantly having to edit the scripts to specify a different port number is slow and confusing).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1109)

Add script to print history of a text doc

---

src/SIL.XForge.Scripture/Services/HgWrapper.cs
src/SIL.XForge.Scripture/Services/IHgWrapper.cs
src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

When a bundle is restored into an initialized repository, the stage for all of the commits is marked as draft. As the commits in a backup are already on the repo server, these should be marked public.
This pull request moves `MarkSharedChangeSetsPublic` from `JwtInternetSharedRepositorySource` to `HgWrapper`, and calls this method when a backup is restored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1117)

SF1372: Restored changesets are now marked as public

---

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
src/SIL.XForge.Scripture/Controllers/ParatextController.cs

- When searching for a project or resource, typing the short name should find the project
- Resources should be shown with their respective short names
- When selecting a based-on project/resource, the field showing what is selected should include the short name
This applies to both the settings page and the connect project page, but they both use the same component, so it only needed to be changed in one place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1120)

SF-1374 Include short name when selecting or searching for a resource

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* remove the obselete note in line format from quill
* introduce note thread embed format to quill
* record embedded paratext note thread positions in text-view-model
* account for embedded note threads when sending ops to text doc
* account for note threads embedded into blank segments
* strip away note threads when switching texts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1122)

SF-1322 Support multiple note threads in a segment

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

The condition where the error would occur is:
- Checking sharing is disabled
- Translate sharing is enabled
- User opens share dialog and types email to invite
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1125)

SF-1364b Fix error calling isAlreadyInvited when checking has sharing disabled

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts

If the user clicks the import button before the list of books has been loaded, then the dialog will incorrectly state that no questions are available for import. This is because we only list questions that are for books that are available in the project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1134)

Fix incorrect message saying no import questions are available

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

- `npm audit fix` (this fixes high severity `tar`) and update npm
- that just leaves `glob-parent` (which is a devDependency only, maybe NG12 update will fix) and `quill`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1136)

Fix some npm vulnerabilities

---

src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts

Also disable max-len ESLint errors for lines with strings
A pre-commit hook still makes sure files are formatted according to Prettier rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1139)

Clean up test output and stop showing Prettier errors

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss

Resolves an issue where a `usx-blank` in at the start of a paragraph is larger than what it was intended to be.
Introduced via #1088 
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1146)

Ensure a blank in the first segment is smaller than other blanks

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- When dragging to an empty verse, a usx-blank element will be the
target. Use the parent element instead, which should be a usx-segment
element.
- When inserting into an empty verse, position the new text just after
the blank.
text-view-model.ts:
- In update(), call editor.updateContents() right away. Otherwise, the
`updateDelta` can contain outdated information by the time it is sent
to updateContents(), such as if multiple changes are happening to the
quill editor, such as in the case of inserting dropped text and
removing source text. Alternatively, the call to updateContents()
could continue to be deferred if we continue to call updateSegments()
earlier (to set segment boundaries) and then call updateSegments()
again, setting updateDelta, in the deferred processing so that the …

SF-1344c Handle drag-and-drop to empty verse

---

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts

- Refactored sync component lastSyncDate to return a date object
- Added new method to get toLocaleString()
This resolves an issue when toLocaleString() returns a format that then can't be fed back in to new Date() as it returns an invalid date error. i.e. `dd/mm/yyyy hh:mm:ss`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1156)

SF-1406 - Sync date comparison failing with alternative date formats

---

mongodb/Projects/UnusedResources.mongodb

Also include resource name so it can be searched for on system administration page
The way I originally wrote the script worked, but then I modified the first query (line 7) to fetch objects, rather than an array of string ids. That broke line 15. Unfortunately I didn't catch that until after it was merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1155)

Fix resource query incorrectly implemented in #1154

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/Models/NoteThreadChange.cs
src/SIL.XForge.Scripture/Models/TextAnchor.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- When I examined code about PT anchoring, it took me a bit to catch
on to some concepts and terminology. In this commit I have some
changes that I think will make some of these concepts more quickly
evident, such as by comments and renamed methods and variables.
editor.component.ts:
- I recognize that in getUpdatedTextAnchor(), the `embedIndex`
variable comes from `const [threadId, embedIndex] of
oldSegmentEmbeds.entries()` in updateSegmentNoteThreadAnchors(), and
therefore we won't expect `oldVerseEmbedPositions.values()` not to
contain it. But I propose that we have a warning for the exceptional
unexpected case of embedIndex not being in the set, at least for now,
as we get this positioning working.
ParatextServiceTests.cs:
- I think "related verse" can be a misleading string for the …

Clarify areas around PT anchoring

---

.vscode/settings.json
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- HEAD requests we previously used to check permissions for a resource are no longer working properly on the DBL QA server, and soon will not work on the live DBL server.
- The `/resources` endpoint on the DBL server is adding an `id` filter query so it is possible to fetch the metadata of just one resource.
So instead of a HEAD request to `server_address/api/resource_entries/the_resource_id`, a GET request is sent to `server_address/api/resource_entries?id=the_resource_id`. At present the live server does not recognize the `id` query and just ignores it, resulting in a large payload. This is inefficient. However, it *will* work because we look at the data that is returned and see if it includes the resource id we were looking for. Once this is deployed the DBL server can be updated and …

SF-1404 Use GET requests to check permissions from DBL

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

- Switch suggestions and note dialogs over to material
- Removed redundant imports for material modules in translate module
- Renamed property for `NoteThreadIcon`
- Adjusted null return check in `verseRefFromMouseEvent`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1171)

Code tidy-up post note dialog merge

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts

command.service.ts: Compose messages from the different kinds
of errors that can happen here.
I was able to test handling of a bad URL with a 400 error code, as
well as a -32000 Forbidden error and -32602 InvalidParams error. And I
tested what happens when turning off the server right before
http.post(). But I wasn't able to make a JsonRpcError or ErrorEvent.
translate-metrics-session.ts: Re-write handling conditions with less
logical operators for clarity. Letting `!online` check be a bit more
broad here.
===
Issue SF-1259 is no longer being reported in bugsnag. But I completed and am here proposing some enhancement to error reporting, that was done as part of seeking to address SF-1259.
This PR somewhat rolls back a recent commit by @irahopkinson so his attention would be good for at …

SF-1259 Improve CommandService error reporting

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

Verses that are combined have a verse segment ref that looks like `verse_1_2-3`. This change takes into consideration this format for a verse segment of a combined verse so that notes can be correctly embedded.
.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1176)

SF-1419 Get note threads to appear on combined verses

---

.vscode/launch.json
.vscode/tasks.json
README.md
src/SIL.XForge.Scripture/ClientApp/src/karma.conf.js

- It's not necessary to specifically stop and re-run the frontend or
backend 'in the debugger'. Rather, one can separately attach and
detach from  dotnet, ng, or Chromium without needing to restart them.
This can be a simpler experience.
- This patch gives explanatory names to the debug targets, and adds
attach targets for the frontend, backend, and frontend tests.
- Explain in README a process that can be followed to do this.
- Add item to launch Chromium and debug, but without also running the
frontend.
- Modify launcher names to be descriptive about whether they are
running the frontend.
- Modify launchers to use the newer type "pwa-chrome".
- Remove old Beta.
- Remove Migration launchers. Leave a commented out example to quickly
make one next time. Similar for tasks.json.
---
This …

debug: Revise targets, add attaches

---

src/SIL.XForge.Scripture/locales.json

After briefly reviewing Romanian localization, it appears to be working fine. This wasn't a thorough review though.
I'm enabling it now because users have asked for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1186)

Enable Romanian localization

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts

Based on some recent feedback to the login process around redirect issues with 3rd party cookies, as well as some of the other login redirect related issues, I've reworked some of the login process.
For context, when the app first loads if settings are available in local storage then the user will be logged in "offline". Once the app is fully loaded a background check is made (as long as they're online) with auth0 to get an updated token. When 3rd party cookies are blocked it means any check with auth0 will return "login required" and a redirect to auth0 takes place. 
After doing the recent auth service tests I noticed that the above was the intention but the reality is slightly different. When auth0 returns the user to SF it stores the result of the parsed hash in a promise. From then on …

Fix login redirect with 3rd party cookies

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

- When dragging to a segment with note embeds, the display-text-anchor
element isn't just a length 1 item to include in the calculation for
insertion position. It also contains the text that is anchored to.
Account for this, and adjust Chromium and Firefox tests to behave like
the browsers in this regard.
- text.component.spec.ts: Set `textAnchor` `length` to 7 to span the
text 'chapter'.
====
This was fixed on the way to addressing the actual SF-1417 issue.
This PR was previously described as "SF-1417b ...", and contained some refactoring. That refactoring was split out and applied onto master, which was then merged to develop, and this PR was rebased on top of the refactoring.
--- …

SF-1417c Account for text in display-text-anchor when drop

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts

This addresses a problem that would occur when auth0 issued a login required error either by the session expiring or from 3rd party cookies being blocked. If this instance occurred as well as the access token expiry (captured on first login and stored in local storage) also expiring AND the app first loaded OR the app loaded while offline and then came online an error dialog would occur due to the `checkUserNeedsMigrating` check that is run when the app first loads. 
This issue was minimized in a recent update that ensured if the access token had expired, and the user was online, it would check immediately and the user would be redirected to auth0 before the main app would ever need to run `checkUserNeedsMigrating`.
This is the most common scenario but the same dialog could have occurred …

Gracefully abort handling of HttpRequest intercepts when not authenticated

---

src/RealtimeServer/scriptureforge/models/note-thread.ts
src/RealtimeServer/scriptureforge/models/note.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/Models/Note.cs
src/SIL.XForge.Scripture/Models/NoteThread.cs
src/SIL.XForge.Scripture/Models/NoteThreadChange.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- Sync note/comment status as well as thread status
- Hide resolved threads from translate app
- Show relevant note icon if one is set on the note
- Force a maximum width on note dialog
Existing notes may need to be deleted before a sync - I had hit this issue but it may have just been a bug that I fixed afterwards. I had concluded that this was fine as, once rolled out, no one would have had notes in the first place so it isn't an issue.
This is one of my first real PRs for working in the backend so please be gentle with your replies for changes :) Do let me know if there are much better ways in C# to tackle anything. One thing I wanted to do but couldn't figure out is have an array/list of strings that I iterate through to compare changes from a document to a PT comment. We appear to …

SF-1323 - Hide note thread when a thread is resolved

---

src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
src/SIL.XForge.Scripture/ClientApp/src/styles.scss

- Set language options as a variable
- Updated share component to use new language fonts
Styling the material select component required styles added to the global styles file as per their documentation for styling overlaid components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1197)

Fix sharing invitation language font

---

src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/ITransceleratorService.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/Services/TransceleratorService.cs
test/SIL.XForge.Scripture.Tests/Services/TransceleratorServiceTests.cs

This was prematurely removed in #1182. We don't need it anymore, but existing clients call it, so we shouldn't remove it until #1182 is live on nearly all clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1199)

Re-add HasTransceleratorQuestions API endpoint

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/Realtime/RichText/Delta.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

Footnotes, endnotes and cross references appear in the text with a special symbol. The quill editor has been designed to show this symbol as an embed in the editor. The embed takes up a length of 1, which means that on the backend when we synchronize and update our note thread text anchors, the text anchor position should also account for the symbol.
This uses a space "\0" on the backend to represent a non-text insert e.g. blanks, footnote, endnote or cross reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1175)

Consider text footnotes length when calculating text anchor positions on sync

---

README.md

After doing a recent manual install on Windows I received an error trying to connect to any Paratext project. Nathanial also hit the same issue on his new machine after doing a manual install (on Linux). 
This step is already included in ansible setup so this PR adds the missing step to the manual process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1202)

Include additional step for manual development setup on Windows

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/typings/sharedb.d.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

When a note icon is deleted by the user in SF, the note icon's position will be recalculated and will reappear as it does in Paratext. When a user triggers an undo, the recreated note must be deleted so the previous note can be reinserted. The change performs two steps: (1) deleting the note that was recreated when the user first deleted a note. (2) reverts the position of the text anchor for the reinserted note and for all notes affected by the undo operation.
This change also refactors how we update a note's text anchor. The update method now accepts the update delta and uses it to calculate the note's updated position.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge …

SF-1428 Duplicate notes detected and cleaned up

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts

This change was not made in [the original PR](https://github.com/sillsdev/web-xforge/pull/1182) because I didn't know what the URL would end up being, so I just left a placeholder.
How to test this:
1. Click this button in the import dialog:
2. Ensure it takes you to a related help page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1207)

Link to helps for importing questions from CSV file

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts

There are several possible messages that can be shown at the bottom of the import questions dialog. Originally they were styled `visibility: hidden` until shown so the layout would not change at all once they were revealed. However, this is not great on mobile where screen space is very limited. For that reason this PR changes from using `visibility: hidden` to using `*ngIf`. This required changes to the tests. The changes to the UI are shown in the screenshots below. It is assumed at least one of the questions has already been imported (otherwise this message wouldn't show at all).
Description | Before this change | After this change
------------|--------------------|------------------
Initial dialog screen | ![](https://user-images.githubusercontent.com/6140710/145847414-7e7f825a-cb38-46 …

SF-1456 Remove excessive space in import question dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts

- In the Note dialog, like Paratext for an RTL project, show the verse
USFM marker on the right side, and display the note content RTL.
- The two added tests check existing behaviour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1203)

SF-1420 Note dialog RTL verse markup and content

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

In order to import Transcelerator questions a request needs to be sent to the back end. If offline, that causes an error (`Error invoking transceleratorQuestions: Http failure response for command-api/projects`).
Here's how it looks now:
This PR prevents such requests if we're known to be offline. That part was pretty simple. The tests required some significant changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1209)

SF-1451 Fix exception when import dialog is opened offline

---

src/RealtimeServer/scriptureforge/models/note.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- Check tag icon change during sync
PR addresses two points:
1. Setting the correct tag icon for a note which covers all the different statuses including resolving and reopening a thread
2. Ensuring the thread icon matches the correct tag icon (last used) in the list of notes
The end result will look similar to this:
I also changed the `Note` interface to set `content` as optional which is how the backend is treating it when saving to Mongo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1211)

SF-1430 - Note icon does not change into default flag icon in SF if note icon deleted in PT

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

This dramatically improves import speed, though it still gets slower over time. That should be improved in a future PR.
The total width of the chart is about 919 questions. The red line goes to about 162 questions. The two instances didn't take the same amount of time or import the same number of questions. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1214)

Improve question import speed by using NgZone.runOutsideAngular

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/csv-service.service.ts

One of the tests for the question import dialog couldn't use `fakeAsync` because Jasmine doesn't redefine FileReader, so reading files can't be controlled using `tick()` and `flush()` (you can `tick()` and `flush()`, but the FileReader doesn't fire its event handlers).
What I've done in this PR is pull the file parsing out into a separate service so it can be more easily mocked in the tests. Now a File object isn't actually needed in the tests, and `tick()` and `flush()` work.
I'm making this change because I'm going to need to write another test, and I couldn't figure out how to get it to work. It should be a lot easier after this.
--- …

Improve tests by making CSV parsing mockable

---

src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts
src/RealtimeServer/scriptureforge/services/question-service.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/Models/SFProjectUserConfig.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* add highlight class to unread note thread embeds
* record notes read in project user config doc
Unread note threads in Paratext appear with a border and a highlight colour behind the note icon. I chose to use only a border to identify an unread note thread, but I am open to suggestions on how to make it look clean in our app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1219)

SF-1445 Highlight unread note threads

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

The click subscriptions were not being updated correctly when a user deletes a note, and then they undo the deletion. This change records the note icon click subscription and refreshes all of the subscriptions when a note is deleted, and then the user undoes the deletion. In order to get it to work, it was also necessary to strip away the formatting on the note thread embed that gets re-embedded so that it wouldn't cause our formatting in quill to be in a bad state.
There was another bug where undo deleting-a-note would revert the position to a previous position even when it should not. So now it checks that there was a measurable text edit in addition to the note deletion before performing the undo and reverting the note thread position.
--- …

Update note icon click subscriptions for all icons in the verse

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

- discernTarget() still returns the <usx-segment> that is dropped
into, but also the specific element inside the usx-segment that was
dropped into, such as a <display-text-anchor>. This allows text to be
dropped into a thread anchoring area.
- determineInsertionPosition() processes a tree of nodes to determine
the length from the beginning of a <usx-segment> thru to the position
of the drop as reported by the browser.
- New tests specify behaviour for dropping into a note thread
anchoring area as well as a location that is in the anchoring area of
two note threads.
===
Handling of `<usx-blank>` elements can be somewhat rolled into this, but I want to do that in followup after this initial change is reviewed.
--- …

SF-1454 Handle dropping in more nodes

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/retrying-request.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/retrying-request.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/subscription-disposable.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/testing-retrying-request.service.ts

Previously our strategy for dealing with a lack of a good network connection was to try to detect whether the user was online (using the PwaService), and wait for the user to be online before initiating a request. This works to a degree, but if the request fails we treat it as a hard error and don't retry. The page is then essentially broken. One place where this could happen is in the import questions dialog, which immediately fetches the Transcelerator questions when the dialog opens, so they'll be ready if the user selects to import from Transcelerator.
A much better strategy is to keep trying as long as the error is only a network error. In order to make this as simple as possible for the components that use it, I've created a RetryingRequest class. There are a lot of doc comments for …

SF-1479a Retry request for Transcelerator questions when network fails

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts

This test started to fail on my machine. I'm not sure if Chromium updated very recently, or if some other package was updated and changed the localization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1236)

Update i18n tests to work with change to Chromium's date localization

---

scripts/db_tools/fix-doc.js

If a doc is corrupted in such a way that it's not a valid doc, then it's not possible to convert it into a valid doc by applying an op.
This script gets around that problem by deleting the doc and recreating it. It's still the same doc though; the version numbers keep climbing. Basically there's an op that says "delete everything" and then another op that says "create it in this state."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1235)

Add script to modify doc, even if it's corrupted

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

When hitting backspace on a blank segment, the editor history records information on the event but the user does not see any changes. However, if a note is embedded with the blank segment, hitting delete, and then undo will result in duplicate verses. I've put this change on master branch because this change is an improvement on the behaviour of blank segments as a whole.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1225)

SF-1470 Do not allow backspace or delete on non-text elements

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/Realtime/RichText/Delta.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

* GetVerseText gets the texts in the delta that also includes section headings
* determine note anchoring position using all text belonging to a verse
* handle anchoring notes to verse text on the front end
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1224)

SF-1467 Note can attach to text outside of verse reference

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

Previously the front end was trying to make sure it had a completely up to date list of existing questions before starting the import. This isn't possible while offline, so it never completed.
The root problem was a wrong assumption by me about what a realtime query's `ready$` really does (caused in turn by a lack of documentation). Hence the change to the test; I was mocking my wrong assumption into the test. It would have taken an actual e2e test to properly test this without my wrong assumption getting in the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1242)

SF-1451b Fix infinite loading indicator when importing offline

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

Previously when a user inserts text, remote users see the text update in real-time. Unfortunately, if text is inserted just after a note embed, remote users see the text inserted immediately before the note embed. The first commit changes the behaviour so that remote edits will always be inserted after the note icon if the edit occurs right at the icon's position. The second change listens the the textDoc's remote changes observable, and redraws the note icon based on the note thread's position data. It would be ideal to review the 2 commits separately.
The majority of the first change makes adjustments to the spec, where thread03 used to follow thread04. Because of this change, now thread04 follows thread03.
--- …

SF-1447 Correctly show remote edits following a note

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge/Services/IProjectService.cs
src/SIL.XForge/Services/ProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

Here's what the problem appears to be:
- Project B is based on Project A
- User 1 is on Project A as an observer, and Project B as an admin
- A user is removed from Project A in Paratext
- User 1 does a sync of Project B, which also syncs Project A
- The sync of Project A involves removing the user from the project that was removed already in Paratext
- The removal of the user fails, because the user is only an observer and doesn't have permission to remove a user
The solution is to just not check permissions when removing the user. If the user has permission to sync, and the project had a user removed, then the user can effectuate the removal of the user from the Scripture Forge project. The user isn't actually making a decision to remove a user from the project, only to update Scripture …

SF-1505 Fix permission error removing user during sync

---

mongodb/Projects/ProjectsWithInvalidDocs.mongodb

This is not that important of a script, but today when some problems were reported with some projects and it wasn't clear to me what the issue was, I wondered whether it might have something to do with a text being marked invalid and therefore not editable. Hence I wrote this script, which may be useful in the future.
Currently the output when run against live is:
```
176 of 238 projects have at least one doc that is marked invalid.
```
That's 74% of projects, which I found surprisingly high.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1259)

Add script to find projects that have docs marked invalid

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

Looking SF-1381 it seems that the reason the testers saw errors was because of an existing "_Restored" directory that prevented hg from restoring the backup. This ensures that any existing directories that need to be deleted are before attempting to restore the backup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1252)

SF-1381 Sync error when backup is restored but not used

---

src/RealtimeServer/scriptureforge/models/sf-project.ts
src/RealtimeServer/scriptureforge/services/question-service.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
src/RealtimeServer/scriptureforge/services/text-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/Models/ParatextSettings.cs
src/SIL.XForge.Scripture/Models/SFProject.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* prevent pushing changes if project is not editable
* add the editable property to SFProject
* prevent users from editing projects that are not editable
* check and update editable property on sync
* also consolidate project settings access methods like full name and is left to right
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1264)

SF-1509 Skip pushing book text if project is not editable

---

mongodb/Projects/ProjectsWhereLastSyncFailed.mongodb
scripts/db_tools/find-problems.sh

Previously the output would just list the short names of projects that failed the last sync. While useful, it doesn't indicate when the failed, so it's hard to notice when a project starts having trouble syncing.
Before:
```
AAA
BBB
CCC
```
After:
```
3 projects:
Thu, 10 Mar 2022 01:01:01 GMT AAA
Tue, 01 Mar 2022 02:02:02 GMT BBB
Wed, 26 Jan 2022 03:03:03 GMT CCC
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1271)

Update ProjectsWhereLastSyncFailed script to show when sync failed

---

src/RealtimeServer/scriptureforge/services/sf-project-service.ts

**Stack**:
- #1270
- #1269
- #1268
- #1267
- #1266
- #1274 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1274)

rts: guard when doc object has no keys

---

src/SIL.XForge.Scripture/Services/ISharingLogicWrapper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SharingLogicWrapper.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

* throw early if paratext id is not available to the user
* remove obselete null shared project logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1272)

SF-1508 Handle creating a shared project for derived projects

---

src/RealtimeServer/common/index.ts
src/RealtimeServer/common/web-socket-stream-listener.ts
src/SIL.XForge/Realtime/RealtimeService.cs

- to prevent CSWSH Cross-Site WebSocket Hijacking
- its better to verify the token before a connection is even established. Establishing a websocket connection is a bit expensive anyway. So you don’t want unauthorized people hogging connections.
- no longer verify token inside the ws
- also change deprecated request.connection to request.socket
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1276)

SF-1519 check  ws origin

---

.vscode/launch.json
.vscode/tasks.json
src/Migrations/SyncUserToPTUser/IProgramLogger.cs
src/Migrations/SyncUserToPTUser/ISyncUserToPTUserService.cs
src/Migrations/SyncUserToPTUser/Program.cs
src/Migrations/SyncUserToPTUser/ProgramLogger.cs
src/Migrations/SyncUserToPTUser/Startup.cs
src/Migrations/SyncUserToPTUser/SyncUserToPTUser.csproj
src/Migrations/SyncUserToPTUser/SyncUserToPTUserService.cs
src/Migrations/SyncUserToPTUser/build-dev
src/Migrations/SyncUserToPTUser/build-production

To hide pt usernames from users that should not have access, the sf-project model had the ParatextUsers property added, but this will be projected away for users who do not have access. Since SyncUsers in the SFProjectSecret model essentially shared the same purpose of mapping paratext usernames to an id used to mark notes, it made sense to merge the PT sync users from the SFProjectSecret model into the SFProject in the ParatextUsers property.
This tool can be run on the QA and Live servers to move the SyncUsers of each project secret to the corresponding project. The link to the run sheet can be found [here](https://docs.google.com/document/d/1sTk0Du8XxebFNbAlqVH-BHbyHGwqpAPTcmIDPPEBBC8/edit?usp=sharing)
--- …

Add SyncUser migration tool

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

This is an initial fix to improve performance. The change was originally suggested by Damien when we were investigating slow question import, but didn't get made at the time. As I've been investigating slowness in community checking, my attention was directed to this method by the debugger (if you pause the debugger when the page is slow, it often shows this method in the stack, which made it look like almost all of the time was being spent here).
Manual testing shows when you load a page from scratch, the time to first paint for 1500 questions is about 85% of what it was before this change. That's not massive, though for a change this small, it's surprising it makes even that much of a difference.
Here's my testing data (time for questions to show on screen, after entering URL in new …

SF-1516a Use IndexedDB getAll instead of looping

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

When a user clicks on the target editor, the focused event is fired even though the target editor never truly gets focused when it is read only. This fix is a work-around that sets the text component to not add yellow highlight to verses when the editor is read only. This restores the previous behaviour before we regressed this behaviour with another work-around to set the targetFocused field on the editor component.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1284)

SF-1521 Only highlight translate target editor when user can edit

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts

While working on improving performance in the Angular app, I discovered that the way I had implemented sorting questions was non-ideal for several reasons. We already had a way to sort questions in a query, and rather than use that, I had rolled my own. Questions would be sorted every time the `get questionDocs()` getter was used, which would be multiple times per round of change detection. This is not ideal, since sorting large numbers of things is slow, and there's no real reason to re-sort them. It also means if another component wanted sorted questions the same sorting logic could not be easily re-used.
Also I was filtering for questions that are not archived, which should have been done in the query itself.
Unfortunately, my original change involved somewhat confusing changes to the …

SF-1400 Sort questions in query rather than component

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/Services/ForbiddenException.cs

Looking in the list of projects was recently associated with an
InvalidOperationException, where `remotePtProjects.Single()` failed to
find the expected PT project id. Log more information when this
happens to assist in investigation.
---
**Stack**:
- #1297
- #1289
- #1288
- #1287 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1287)

Log unexpected problem looking up project role

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts

- @triviality/logger is not here used in a way that requires it in
production, and so it is added only to the development set of
dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1234)

drop: expect and hide console logs in tests

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts

- Adjust the order of quill inlines to ensure text-anchor is deeper than char
- Added styling for usx-char `em` style
The issue was how Quill ordered elements in the DOM and it placed the `<display-text-anchor>` above `<usx-char>` elements:
After adjusting the order it now appears correctly and the `usx-char` can be styled correctly as well:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1299)

SF-1531 - The error appears when opening the note icon if a note is created inside the special characters

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

The performance improvement is made by using the OnPush change detection strategy in the checking questions component. Since it can list a large number of questions, change detection in that component is particularly expensive, so reducing the number of times it is run speeds things up immensely.
There are two main "supporting changes" (changes that are not directly related to the issue at hand, but were necessary in order to make the main change:
- Add changes$ observable to RealtimeDoc and RealtimeDocAdapter
- Add docs$ observable to RealtimeQuery
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1301)

SF-1516c Optimize checking questions component

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts

- @triviality/logger is not here used in a way that requires it in
production, and so it is added only to the development set of
dependencies.
(cherry picked from commit 2cdf489f41ca7d437e40cfccaf322a52a80ca113)
---
**Stack**:
- #1308
- #1307
- #1306
- #1305
- #1304
- #1303
- #1302 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1302)

drop: expect and hide console logs in tests (#1234)

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

- The wrong closing tag can be removed. We may find success removing a
closing tag that matches an opening tag, but we can just remove all
unknown opening and closing tags, as with this change.
commit-id:ce153c40
---
**Stack**:
- #1311
- #1308
- #1307
- #1306
- #1305
- #1304
- #1303 ⮜

notes: don't remove the wrong closing tag

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

- Adjusted output of note icons to use any icon if specifically set on the note otherwise use the re-attached icon
Output should look like this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1296)

SF-1529 - Note icon does not appear when the user reattached a new txt and then selects a new icon

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

**Stack**:
- #1311
- #1308
- #1307
- #1306
- #1305
- #1304 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1304)

SF-1526a notes: improve conflict diff colouring

---

src/RealtimeServer/scriptureforge/models/note-thread.ts
src/RealtimeServer/scriptureforge/models/note.ts
src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/Models/Note.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

Adds to Note:
- Type
- ConflictType
- AcceptedChangeXml
Adds types:
- NoteType
- NoteConflictType
ParatextService.cs: Detect and compose incoming Note changes of Type,
ConflictType, and AcceptedChangeXml.
ParatxtSyncRunner.cs: Writing Notes to the SF DB should include the
new properties.
commit-id:84774793
---
**Stack**:
- #1311
- #1308
- #1307
- #1306 ⮜

SF-1526b notes: add conflict properties to model

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SyncService.cs
test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs

- Sometimes the QueuedCount is >1, or <0. Syncs can be cancelled. They
can be re-enqueued manually. Multiple syncs could be requested around
the same time.
- When setting the QueuedCount, also log a warning if the QueuedCount
is an unusual value, to assist in investigations.
commit-id:88b403db

sync: log when unexpected QueuedCount

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

There appears to be a difference in the result of a text editor position getFormat and calling getFormat on a string of text. This results in the remote inserts being applied with insufficient format attributes. This improves on that situation by grabbing all formatting of a character and adding it onto the formatting retrieved from a text editor position (excluding the text-anchoring info that appears to be working correctly).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1292)

SF-1524 Apply relevant attributes when applying remote text changes

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- Always set the target to focused if there is an open dialog
- Ensure the segment of a note is selected again after a note dialog is closed
The last point isn't being tested as the event trigger that causes the issue for this is actually part of the text component and it was starting to get a bit messy - probably better suited for a E2E test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1312)

SF-1536 - Focus is lost in the verse box when closing the close dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

This has been bugging me for a while. It's less noticeable after some recent performance improvements, but definitely still there. And on a slower network it might be even more noticeable.
How checking overview component looks while loading:
Before | After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1300)

Do not show no questions message until questions load

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

It looks like at least one project has all their notes duplicated for the user who initiated the sync. Synchronizing notes threads back to paratext comment threads is not ready, so we need to disable it for the time being.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1319)

Hotfix: Skip updating Paratext comment thread with notes

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

When a project has duplicate project notes in a thread, the sync with Paratext fails because ParatextService assumed that all project notes are unique. This change fixes that assumption and uses the last comment in the thread as the authoritative comment if multiple comments with the same ID exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1318)

SF-1546 Get sync to succeed with duplicate project notes

---

mongodb/Projects/ProjectsWhereLastSyncFailed.mongodb

Here's what the output of this script looks like now:
```
11 projects:
Wed, 27 Apr 2022 15:14:53 GMT 6269712535cb92ccefc73e5d AAAA
Wed, 27 Apr 2022 15:14:49 GMT 6269714335cb92ccefc73e5f BBBB
Tue, 29 Mar 2022 18:08:39 GMT 6269714a35cb92ccefc73e60 CCCC
Tue, 01 Mar 2022 13:33:29 GMT 6269714f35cb92ccefc73e61 DDDD
```
Having the project ID in the output makes it easy to look up the project in our logs to see what the error was.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1329)

Improve ProjectsWhereLastSyncFailed script to show project id

---

src/RealtimeServer/.npmrc
src/SIL.XForge.Scripture/ClientApp/.npmrc

Documentation for how npm handles .npmrc files: https://docs.npmjs.com/cli/v8/configuring-npm/npmrc
Documentation for the values that go in these files: https://docs.npmjs.com/cli/v8/using-npm/config
There are two values that get set in the config files:
```
save=true
legacy-peer-deps=true
```
Both of these can get set on the command line, but it would be annoying.
Newer versions of npm fail to install ClientApp because we're using a version of @angular-mdc/web that has a requiredAngularVersion of ^9.0.0, whereas web-xforge is using Angular 12. This config will tell npm to continue allowing us to ignore the version mismatch. Alternatively we could always run `npm i --legacy-peer-deps` or `npm ci --legacy-peer-deps` whenever we do an install.
`save=true` tells npm to update the …

Add .npmrc config files

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

This is the result of running `npm i` in ClientApp using npm@8.8.0 (yes, the version of npm makes a difference, unfortunately).
Of course it seems odd that running `npm i` should update `package-lock.json`. According to [this issue comment](https://github.com/npm/npm/issues/17979#issuecomment-332701215) the logic is as follows:
> 1. If you have a `package.json` and you run `npm i` we generate a `package-lock.json` from it.
> 2. If you run `npm i` against that `package.json` and `package-lock.json`, the latter will never be updated, even if the `package.json` would be happy with newer versions.
> 3. If you manually edit your `package.json` to have different ranges and run `npm i` and those ranges aren't compatible with your `package-lock.json` then the latter will be updated with version …

Update package-lock.json in ClientApp

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

There are several views in the import questions dialog, and most of them have a close button with the text "Close." However, two views had no close button. The dialog could be closed by clicking outside the dialog, but that's not very discoverable, and it's a bit harder to do on mobile because there's very little area outside the dialog itself. I've added the close button in the top right corner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1336)

Add close button to import questions dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts

Very often we have a project shortname, rather than a project name. The current system admin page only allows searching by name. This commit enables searching by shortname.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1330)

Search for projects by shortName on sysadmin page

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

We've been using XRegExp for two things:
1. Escaping strings to use them as part of a regex
2. [Unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes)
The former can be done using Lodash, and the latter is now supported in all modern browsers with the `u` flag added to a regex.
XRegExp is fairly sizeable (41.08 KB gzipped out of our total gzipped bundle size of 705.45 KB, making it 5.82% of our bundle) and we're not using it for much, so getting rid of it seemed like a good idea.
Unfortunately it's also used by @sillsdev/machine, which is one of our dependencies, so there's no actual reduction in bundle size. I didn't realize that until I'd made the change though, and it seems like something that's likely to …

Remove XRegExp dependency

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

* use update contents when inserted text dropped into a segment
* manually determine formatting at insertion position
* update test to expect dropped text in containing usx-segment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1332)

SF-1544 dnd: Insert text via updateContents

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.ts

Start by reading the issue and steps to reproduce: https://jira.sil.org/browse/SF-1557
This was caused by an interaction between Angular Material and Angular MDC. The mix of a MDC dialog and a Material mat-select within it caused the menu to appear behind the dialog. This problem only manifests itself if a Material dialog was opened prior to this dialog being opened.
I solved the problem by changing the dialog to use Angular Material. I'm fairly confident there are other workarounds, but this gets us closer to using only Angular Material.
Here's a before and after for the normal case, where everything is fine:
Before | After
----------|-------
As you can see, the main visual change is width. We didn't have a width set before; it was being chosen by Angular MDC as far as I can tell. So I …

SF-1557 Fix share dialog menus appearing behind dialog

---

mongodb/Projects/FindProjectsWithAnswers.mongodb

This script finds projects that have at least `n` answers. This is a more useful metric than how many questions a project has, since those can easily be added in bulk. Answers have to be created by another user.
Ideally this kind of information will end up on some dashboard, but for now this is better than anything we currently have. And in any case, when we do make a better system, it will be helpful to have something like this to base the query on.
When run against live this query returns 7 results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1343)

Add Mongo query to find projects with answers

---

mongodb/Projects/ActiveTranslateProjects.mongodb

This script finds projects that have a text that has had at least 100 edits over all time, and has been edited in the last 30 days.
I'm sure there are better metrics we could measure by, but this was something that was easy to query for, and seemed somewhat useful as a metric. I wrote this right before last week's meeting to find out what we actually had on the server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1344)

Add Mongo query to find active translate projects

---

src/RealtimeServer/common/diagnostics.ts
src/RealtimeServer/common/realtime-server.ts

Previously we were creating a new ShareDB connection every single time we check whether a user has permission to access a document (in order to determine whether a user can access e.g. a text, we have to look up the associated project and see if the user is on it). The [documentation for `Backend.prototype.connect()`](https://share.github.io/sharedb/api/backend#connect) says:
> Connects to ShareDB and returns an instance of a [`Connection`](https://share.github.io/sharedb/api/connection) client for interacting with ShareDB. This is the server-side equivalent of `new Connection(socket)` in the browser.
While not explicitly stated, this makes me believe creating thousands of connections for a single end user may cause performance issues. In my testing it appears this change reduces the …

SF-1556b Reuse ShareDB connections on back end to improve performance

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts

This was broken in #1342 "SF-1557 Fix share dialog menus appearing behind dialog" (cb494c620519e0bcc6313166558976db71b38f11)
Unfortunately I didn't test this as well as I thought I did.
Before this fix | After this fix
-------------------|-----------------
Disabling view encapsulation and using `!important` isn't the nicest solution, but the main alternative was to move the width specification to the component that opens the dialog and pass it in the config when calling `dialog.open()`. That seems like the wrong way to go, since we could easily start opening the dialog from a different place, and we don't want to have to write:
``` ts
this.dialog.open(ShareDialogComponent, {
width: '30em',
maxWidth: '90vw',
...
```
every time. In reality we would probably notice if the dialog width was …

SF-1557b Prevent scrollbar in share dialog on mobile

---

scripts/db_tools/text-doc-history.js

It's not clear exactly what occurred, but the way Mongo was being imported no longer works. The `utils.requireFromRealTimeServer` thing is non-standard, so I'm not super surprised. 
As far as I can tell, this is the only script that needed to be changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1355)

Fix text doc history script connection to Mongo

---

scripts/db_tools/.npmrc
scripts/db_tools/package-lock.json

If you try to run `npm ci` in `scripts/db_tools` before this change, using `npm@8.8.0`, it produces an error:
```
$ npm ci
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's @types/ws@7.4.5 does not satisfy @types/ws@8.2.0
npm ERR! Invalid: lock file's ws@7.5.0 does not satisfy ws@8.2.3
npm ERR! 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nate/.npm/_logs/2022-05-14T02_13_48_301Z-debug-0.log
```
- Newer versions of npm seem to have a stricter definition of whether a package.json is in sync with a package-lock.json. In any event, npm@8.8.0 claims they are out of sync and it needs to …

Fix package-lock.json in scripts/db_tools

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts

- add tests
- move matching getters and setters together in `text.component.ts`.
I couldn't add as many tests as I had hoped but we are at the limit of what we can unit test in multi-viewer scenarios. I've added a bunch of **Acceptance Checks** to the [issue](https://jira.sil.org/browse/SF-1552). Ideally these would be codified in E2E tests or at least BVTs.
Note this PR is currently against the `feature/multiCursor` branch.
Screenshot of the same viewer on the same device and browser having the same color cursor for them and for other viewers:
Screenshot of extra small screens with more than 1 viewer:
Screenshot of extra small and medium screens with more than 3 viewers:
Note the cursor colors don't all match between screens in the above screenshot for V* viewers because I did a code …

SF-1552b Multi-viewer toolbar

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts

When I initially implemented the sort order I overlooked that all capital letters would come before all lower case letters.
Note: The branch name says SF-1553b, but the commit and PR title say SF-1567. That's because I opened this PR with the assumption the issue was going to be added to the original issue for sorting, rather than created as a separate issue. Not a big deal, just something to be aware of. GitHub doesn't allow changing the name of the branch without creating a new PR, so far as I am aware.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1360)

SF-1567 Fix sorting of projects to be case insensitive

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts

A project on live managed to duplicate the chapter numbers in a text, which causes sync problems (it's not valid to have duplicate chapters).
This makes the text not editable, and shows a message to the user indicating that it has become corrupted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1353)

SF-1564a Mark texts with duplicate chapters as invalid

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

The note dialog would try to condense the information about the verse and assigned user on the same line on mobile viewports. This didn't look good when names and verse references were longer. This wraps the assigned user onto the second line, and moves the selected text menu button on the line with the selected text.
Before
After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1368)

SF-1566 Wrap assigned users on mobile viewports

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html

Steps to see the issue this fixes (taken from Jira issue):
- On mobile, place the cursor in the editor of the translate tool. This should open the on-screen keyboard.
- Tap the menu icon in the top left corner
- Observe that the keyboard stays open. 
You can then tell the keyboard to close itself (usually a down arrow on the keyboard), _but it reopens immediately_. This is a separate bug, but very closely related (and it makes this bug so much more annoying).
The nav menu needs to steal the focus from the editor, so the cursor will no longer be in the editor, and the keyboard will close.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1374)

SF-1577 Fix nav drawer not closing keyboard on mobile

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

- This adds a lot of lines of logging into PutBookText. But it's an
area that can throw an exception, where it would be useful to have a
better understanding of the situation.
- The extra logging is added to the <a href="Exception.Data">Exception.Data</a> to be printed out
by ParatextSyncRunner only if there was an exception.
- Additionally, throw on some invalid arguments.
- Rename some variables to clarify what they contain.
---
**Stack**:
- #1373
- #1369 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1369)

sync: log more PutBookText on exception

---

.vscode/extensions.json

This extension has the following message at the top of its readme:
> This extension has been deprecated as Visual Studio Code now has a bundled JavaScript Debugger that covers the same functionality. It is a debugger that debugs Node.js, Chrome, Edge, WebView2, VS Code extensions, and more. You can safely un-install this extension and you will still be able to have the functionality you need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1379)

Remove deprecated Chrome debugger extension from recommended list

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss

This mimics the behavior in Paratext.
Before | After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1380)

SF-1586 Make note icon size constant regardless of text size

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

I spent a good while thinking that our references to `HttpException` referred to `System.Web.HttpException`. They actually refer to `Paratext.Data.HttpException`, which wraps `System.Net.WebException` in the instances that I've seen.
I think it's less confusing to just fully qualify what is being referenced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1382)

Fully qualify all references to Paratext.Data.HttpException

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts

Steps to reproduce the problem:
1. Shut down back end or go offline
2. Go to a book with questions
3. Observe that the questions (and text) do not load
This was broken in #1301 when optimizing the checking component.
I remember not being sure exactly when to call `this._docs$.next(this._docs)` in this particular section of this method. Apparently I got it wrong. I think the previous version was determined experimentally, but I forgot about offline mode, and I don't think `this.adapter.ready` is true offline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1384)

SF-1593 Fix checking questions being unavailable offline

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

quill-scripture.ts CharInline.create(value) was receiving a UsxStyle[]
array in situations where the textdoc ops had an array for `char`
instead of just a single style. Process this incoming array, storing
it in __usx_value, and storing a space-delimited list of its styles in
the data-style attribute.
_usx.scss can match the style items in the space-delimited list using
`~=`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1381)

SF-1443 Handle char style array

---

mongodb/Texts/CorruptedTexts.mongodb

This just makes it one less set to find the corrupted texts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1389)

Make Mongo query for finding corrupted texts print ids

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

This PR fixes SF-1572 in the first commit. But the change required some further adjustment to the other tests to keep them running. I am including the followup change as a separate commit to make it easier to review the PR. **But both commit should be squashed together when submitted** with commit messages retained (other than any "commit-id" lines).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1387)

SF-1572 Clear presence when switching books

---

src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/typings/sharedb.d.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

Upgrading sharedb to version 1.9.2 during the multi-cursor feature has caused some unexplained synchronization issues that result in corrupted text docs. Until further notice, this change disables the multi-cursor feature and downgrades the sharedb version to one that does not show the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1394)

hotfix: disable multi-cursor feature and downgrade sharedb

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/app-routing.module.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.ts
src/SIL.XForge.Scripture/Pages/Index.cshtml
src/SIL.XForge.Scripture/Startup.cs
src/SIL.XForge/Controllers/UsersRpcController.cs
src/SIL.XForge/Services/IUserService.cs
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

- Converted `AuthService` to use the new Auth0 SPA package
- Enable use of refresh tokens which then automatically uses the offline scope
- Fixed tests setup to better replicate different logging in flows
- Improved handling of return URL to avoid redirect loops
- Used a new dedicated callback URL to know when to check with auth0 on handling the callback code
Updates made to auth0 configuration
- Added `http://localhost:5000/callback` as a new callback URL
- Removed old beta callback URLs
- Refresh token rotation enabled
- API access settings | enabled Allow Offline Access
There appears to be a few different circumstances to trigger an update to tokens:
- API token settings expiry is hit - this appear to be our main use of the `expires_at` setting
- Application ID Token expiration
Both of …

Convert auth service to use the new Auth0 SPA

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

This is initial work to get a right-to-left UI working. It is not intended to fully implement everything, just to have enough working so that when we start to pull in Arabic translations in the very near future, we'll have the interface mostly working correctly and we can meaningfully test the translations.
A few things to note:
- Angular Material seems to be able to do direction fine via the `BidiModule`. I couldn't find anything similar for Angular MDC. The dialogs that use MDC have to have the direction set on them in order to work properly. I only did this to the most important dialogs; I didn't actually go through every single dialog we have. For the simple dialogs it doesn't make much difference anyway.
- I had some challenges getting the app menu to work properly and ended up …

SF-1579 Implement rtl ui

---

src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Services/ISFProjectService.cs
src/SIL.XForge.Scripture/Services/ITransceleratorService.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/Services/TransceleratorService.cs
test/SIL.XForge.Scripture.Tests/Services/TransceleratorServiceTests.cs

The front end code that calls it was removed in #1182 and shipped in 3.8.5 on Nov 30, 2021 (a little over 6 months ago, so anyone using SF with any regularity updated a long time ago).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1391)

Remove obsolete HasTransceleratorQuestions endpoint

---

scripts/db_tools/doc-history.js
scripts/db_tools/fix-doc.js
scripts/db_tools/import-doc.js
scripts/db_tools/revert-doc.js
scripts/db_tools/text-doc-history.js
scripts/db_tools/utils.js

The function `requireFromRealTimeServer()` was used in the scripts before there was a pckage.json in the same folder. Now that we install the dependencies in the same folder, it is no longer needed, and we can call `require()` directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1398)

Remove requireFromRealTimeServer from scripts

---

src/RealtimeServer/common/realtime-server.ts
src/RealtimeServer/typings/sharedb/index.d.ts

It looks like it will be difficult to figure out how to hook into the realtime server to produce a valid test. I was not able to find the right way to set the src on the connection agent at the handshake stage.
There may still be issues involving using the dev tools to go offline, I see that when we use dev tools, the websocket reports that it is still open even though it cannot deliver the request. I propose that we get this fix to QA, and do some testing by disabling the network adaptor or unplugging the cable. I don't know if we can rely on using the dev tools to simulate the real world.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1399)

SF-1607 Provide the src property to backend op acknowledge message

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- I am not aware that this is happening as a bug, but when writing
test cases it seemed to be a hole that was open.
---
**Stack**:
- #1406
- #1405
- #1402 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1402)

text: disallow selection past current segment

---

scripts/db_tools/auth0-token-info.ts
scripts/db_tools/db-token-info.ts
scripts/db_tools/package-lock.json
scripts/db_tools/package.json
scripts/db_tools/show-jwt.ts
scripts/db_tools/utils.d.ts

This adds two scripts, one for showing the state of a user's access token in Mongo, and the other to show the access token in Auth0.
The package axios is added for sending HTTP requests. I don't know that much about axios, but it's what Auth0 uses in their examples of how to call their API from Node.js.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1388)

Add scripts to visualize Paratext auth tokens

---

src/SIL.XForge.Scripture/Services/IInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/JwtInternetSharedRepositorySourceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

- We have experienced various authentication problems. This change
adds two basic authentication checks for PT Registry and PT Archives.
- The checks try to do little, such as querying information about the
current user, rather than querying information about a particular
project the user may have access to.
- For PT Registry, the ParatextService CallApiAsync helper method is
used to query "userinfo".
- For PT Archives, ParatextData.dll is used to help query "listrepos".
_This is no longer in an spr. It can be merged independently._
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1410)

sync: report on authentication ability before sync

---

src/Help/UpdateHelp/Program.cs

Formatting in the TOC files have changed, so the help localization program had to be updated. You can see the changes in this [file](https://github.com/sillsdev/web-sf-helps/commit/78f57ebbb8f1c9df708c893c62282af235f00e64#diff-897f22b315d29c04aa801121953a18cdf72812b002e2e4878e99743f95d17e2c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1409)

Update helps localization program

---

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss

The progress indicator was accidentally hidden via CSS in #1411 (76a1ab6a4588d25e892ef889e140fc45adafc6fb)
Setting `align-items: center` on the parent of the `app-sync-progress` caused the `app-sync-progress` to shrink to the point of being invisible.
I'll have a followup PR with a bunch more changes, but this is sufficient to fix the regression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1417)

SF-1626b Restore sync progress indicator

---

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss

- Move sync failure support message above sync controls, where other messages are
- Make color of support messages consistent
- Use row-gap for spacing elements in flex containers, rather than margin
I've also avoided using fxLayout when it's just as easy to use CSS to do the styling. It seems odd and confusing to write something like:
``` css
.base-container {
align-items: center;
}
```
because there's no indication in our CSS that `.base-container` is a flex container, because we set that using `fxLayout="column"` in the template. There may be times that fxLayout makes producing the layout we want easier, and it makes sense to use it then. But I don't see the benefit in this particular case.
Here's how it looks with all elements visible:
And here's how that looks when the flex layout is …

Rework styling of sync component

---

.github/workflows/ci-lint-prettier.yml
.github/workflows/ci-production-build.yml

- Node v16 is what we're currently on
- Node v18 is current but not active
I initially created this PR with the production build run against both Node 16 and Node 18, but the Node 18 build failed somewhere in Webpack where it called a cryptographic hash function built in to Node. Presumably at some point in the future when we update Angular, Angular will specify a newer version of Webpack that has support for Node 18. At that point we should be able to remain on v16 while still having a build run against v18 to verify everything is working and that we can update when we are ready.
See https://nodejs.org/en/about/releases/
> Major Node.js versions enter Current release status for six months, which gives library authors time to add support for them. After six months, odd-numbered releases …

SF-1568b Update CI scripts to use Node 16

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

- Only part of the menu is now scrollable.
- Community checking no longer wraps in English when the scrollbar appears.
- Some incorrect behavior regarding when dividers are shown in the menu has been fixed (for example, for resources, previously a divider was shown under the list of books).
- I removed a few pixels of what I think was unnecessary padding at the top of the menu.
Before | After
----------|-------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1420)

SF-1555 Prevent admin pages from scrolling away

---

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

Many paragraphs styles exist that should not contain verse text. An example of this is section headings and titles. The schema for checking if the USX from Paratext does not allow us to define that there are two different types of "para" elements. So the next best thing is to explicitly add invalid "para" elements to the list of invalid nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1416)

SF-1599 Mark chapter invalid when para incorrectly contains verse

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj

This PR fixes an erroneous reference to thot-new-model.zip, which caused the build to fail on .NET 6.0 builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1427)

Fixed erroneous reference to thot-new-model.zip

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj

I spent a lot more time researching this than I would like, and I don't want to explain everything I found because it would probably take an hour to type out. But here's the basics:
- The production build failed on TeamCity
- It was running `npm install` in ClientApp
- ClientApp installs RealtimeServer, so RealtimeServer's prepare script is run
- The prepare script runs `tsc`, the TypeScript compiler, which it assumes is installed in node_modules
- But the packages haven't been installed, so it fails
Previously npm didn't run the prepare script in this situation; that changed in npm v7.20.0, which we upgraded to September 2021. Before that you could just run `npm install` in ClientApp and it should properly build RealtimeServer.
There were basically two options for fixing this:
1. Change …

SF-1641 Fix production build by building RealtimeServer before ClientApp

---

src/RealtimeServer/scriptureforge/models/sf-project.ts
src/SIL.XForge.Scripture/Models/ParatextResource.cs
src/SIL.XForge.Scripture/Models/ResourceConfig.cs
src/SIL.XForge.Scripture/Models/SFProject.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This pull request contains the following changes:
* Standardizes resource checking in `ParatextService` and `ParatextSyncRunner`
* Added a `ResourceConfig` child class of `SFProject` to track resource checksums and revision number
* `ResourceConfig` data is compared to the data from the Paratext feed to ensure that resource text data is only updated if the resource has changed
* Added unit tests for new resource manifest and revision checking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1430)

SF-1609 Improve Resource Sync Efficiency

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

After a stanza break `\b` marker is introduce, our segment refs are reset and they do not include the verse ref which look like "verse_1_15". For example this would be the output of this usfm before and after this change.
USFM
\c 1
\q \v 1 Some text
\b
\q more in same verse
Before
[{ insert: { chapter } }, { insert: { blank } }, { insert { verse } }, { insert: "Some text" }, { insert: { para: { style: "p" } }, { insert: { para: { style: "b" } }, **{ insert: "more in same verse", attributes: { segment: "q_1" } }**, { insert: { para } }
After
[{ insert: { chapter } }, { insert: { blank } }, { insert { verse } }, { insert: "Some text" }, { insert: { para: { style: "p" } }, { insert: { para: { style: "b" } }, **{ insert: "more in same verse", attributes: { segment: "verse_1_1/q_1" } }**, { …

SF-1462 Correctly define segments after stanza break

---

.github/workflows/build-and-test.yml
scripts/build-and-ship
scripts/build-production

- Add a GHA build that builds Scripture Forge, runs tests and linters. 
- This is ordered to fail first from linters, then build problems, then test problems.
- The production build is done differently than the development/testing build has been being done. This GHA build also exercises some of the production build's core steps. Furthermore, unit tests are then run in the environment that was built for production.
- This build now includes an explicit step to build the frontend (`npm run build`).
- This build now includes use of `ng lint`. This was not enabled before, perhaps for good reason, so we might not want to keep it on.
commit-id:b4b74849
--- …

ci: add build gha

---

scripts/build-production

The production build cleans `BUILD_OUTPUT/app/*`. Nothing is written
into BUILD_OUTPUT other than into app.
Adjust the build-production script to make it more clear what the
scope is of what is being deleted, and that we are not leaving
something else in parallel to app. Also delete the whole directory,
not just what `*` will match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1453)

ci: clarify production clean step

---

.config/dotnet-tools.json
.csharpierrc.yaml
.lintstagedrc.yml
.vscode/extensions.json
src/SIL.XForge.Scripture/ClientApp/.husky/pre-commit
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json

- Add dotnet csharpier tool, code extension.
- Configure lint-staged from repo root in .lintstagedrc.yml, rather
than ClientApp/package.json, and specify cwd, so C# files elsewere in
repo are included in pre-commit formatting.
- Upgrade lint-staged to a version that supports --cwd.
CSharpier can be installed by running `dotnet tool install csharpier`.
commit-id:974f9064
---
**Stack**:
- #1452
- #1406
- #1445
- #1444
- #1443
- #1405 ⮜

dev: configure formatting C# with CSharpier

---

.lintstagedrc.yml
src/SIL.XForge.Scripture/ClientApp/package.json

lint-staged is configured to format .ts, .html, and .yml files in
ClientApp. But we have these files in other locations in the
repository. Move the configuration so that files in other locations
will be formatted by lint-staged.
---
**Stack**:
- #1452
- #1406
- #1445 ⮜
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1445)

dev: format .ts, etc files from root

---

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/Realtime/RichText/Delta.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

* refactor canContainVerseText into a static method
* check that a paragraph break insert should be included in verse text
This is how the note threads were being affected before and after this change.
Before
After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1425)

SF-1462b Ignore length of paragraph breaks that cannot contain verse

---

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

- A node may be marked as "invalid-inline". It can happen again to the
same node, but crashes, due to the API method used. Mark the node as
invalid in a way that can be re-done without crashing.
- A situation of "invalid-block" double-marking did not trigger from
the app or tests, but I applied the same adjustment to the
"invalid-block" marking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1454)

SF-1660 Allow re-marking node as invalid

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

We previously allowed users to delete projects that are a source if translation suggestions was disabled. Now that source projects are shown even when translation suggestions are disabled, we must disallow a user to delete a project whenever it is a source project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1460)

SF-1657 Project is a source even when suggestions are disabled

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

When the undo operation includes inserting a blank, the blank segment was getting attributes stripped away incorrectly. This change adds a check that a blank segment does not get attributes stripped away which causes the history stack to be updated incorrectly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1447)

SF-1495 Retain attributes when undo inserts a blank

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html

Material's BidiModule needs the dir directive to be set in order for Material components further down the tree to set the correct direction.
Note that the bug can only be seen if you change the language and haven't refreshed the page yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1456)

SF-1654 Fix chapter dropdown for RTL UI

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

When we updated the settings page so a source project can be selected without enabling translation suggestions, we did not update the logic to add users to the source project. This change assumes that if a source project is selected, add the user to the source project if needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1464)

SF-1673 Add user to source project even when suggestions disabled

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts

We extend the QuillClipboard class to allow us to have custom handling when pasting text. This change adds to that custom handling to insert attributes alongside the text so that we do not create erroneous usx-segments. It was this erroneous segment created by pasting text that resulted in the note anchors being hidden in the DOM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1446)

SF-1640 Add attributes on the paste operation

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* detect and create suggestion engine only if conditions met on front end
* notify user when source project does not contain target books
* do not create translation engine if source books not available on back end
The recent update to Machine 2.5.11 has revealed some existing problems with how we handle building our translation engine using Machine. This corrects how we were using Machine by detecting whether we have texts to generate a translation suggestion engine with. In the event that no source texts are available for any book in our project, we skip over the step of creating a translation suggestion engine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1450)

SF-1656 Do not build machine project when target has no source books

---

deploy/dependencies.yml
deploy/vagrant/sfdev/Vagrantfile
deploy/vagrant/sfdev/base/provision

Deps:
- Don't set up symlink to npm in source repo, so not in way of a
globally installed npm.
- Use `dotnet tool update --global` for
dotnet-reportgenerator-globaltool, which works whether installed or
not.
- Install csharpier. Using `update` to align syntax with what was
helpful for `--global`.
Vagrant:
- The vagrant basebox was made with dotnet 3 and using an npm in the
source repo. Clean up `obj` dirs, to prepare for dotnet 6. Migrate to
a globally installed npm.
- Removing `sudo n lts` to have node version set to a specific value
from ansible.
- Increase inotify values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1466)

dev: update deps, vagrant

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts

The problem for all of these issues is that a MatDialog doesn't get the correct direction set if the direction changed after the page loaded (everything works fine if the locale hasn't changed since the page loaded).
Right now most of our dialogs are still MdcDialog, so the issue only affected a few dialogs. However, the number is likely to grow as we move towards Material, so I wanted a general solution to the problem. Hence the creation of a DialogService that sets the direction when the dialog is opened.
There are a some settings that can be set when opening a dialog that all seem like they should (generally) be the concern of the dialog itself. These include:
- Whether to autofocus the first focusable element
- The default width of the dialog
- Whether the user can use escape or …

SF-1633 SF-1634 SF-1631 Fix direction of dialogs when UI is set to RTL

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss

Before | After
You can't see it in the screenshots, but the main issue was that the slider causes a scrollbar. The other issue was the toggle was too close to the text.
This _doesn't_ fix the issue of the dialog flowing the wrong direction if the language has been changed, and the page hasn't been reloaded. A number of dialogs had that problem, and it's easier to fix them all at once.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1458)

SF-1677 Fix suggestions settings dialog for RTL UI

---

src/SIL.XForge.Scripture/Controllers/ParatextController.cs
src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge/Controllers/RpcControllerBase.cs
src/SIL.XForge/Controllers/UsersRpcController.cs
src/SIL.XForge/ExceptionLogging/ExceptionHandler.cs
src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs
src/SIL.XForge/ExceptionLogging/IExceptionHandler.cs
src/SIL.XForge/SIL.XForge.csproj
test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

This pull request improves reporting to Bugsnag in .NET as follows:
* Upgraded Bugsnag to 3.1.0 to improve .NET 6.0 support
* Fixed a scoping issue that stopped request data from being sent to Bugsnag
* The userId is now sent to Bugsnag
* Endpoint specific data is now sent to Bugsnag , including the projectId, endpoint method name, and any relevant parameters that do not expose PII
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1449)

SF-1608 Improve quality of Bugsnag reporting

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss

Note the lack of leading padding in the **Before** screenshot for RTL.
(These screenshots are now outdated. @marksvc pointed out that the padding was not the same in RTL and then I fixed it)
&nbsp; | LTR | RTL
----------|-------|------
Before | ![](https://user-images.githubusercontent.com/6140710/184756731-234ead66-80a7-472f-816e-dcba92137957.png) | ![](https://user-images.githubusercontent.com/6140710/184756752-c0fed527-ca9f-4258-b406-d31af4c2ee3e.png)
After | ![](https://user-images.githubusercontent.com/6140710/184756789-5dfe826e-5cf3-4f29-94d7-64e47723c564.png) | ![](https://user-images.githubusercontent.com/6140710/184756801-5d89fd2b-a3b4-4dcd-bcd8-430f74ea9ef0.png)
- - - …

SF-1681 Fix padding in community checking RTL UI

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts

- The overall dialog should have the direction of the UI
- The text of the note should have the direction of the project text
- In order to properly test this, you have to make sure it's working correctly when switching languages _without reloading the page_.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1479)

SF-1695 Fix footnote dialog when project or UI is RTL

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

This change enables the ability to update a text anchor when multiple edit positions exist in a delta. Currently, this only happens when a user edits text via a drag and drop, and then undoes the drag and drop. Previously, this would cause the text anchor to be updated incorrectly because we only handled the first edit (insert or delete) that we saw in the delta.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1442)

SF-1653 Update text anchor when multiple edits in a delta

---

src/RealtimeServer/common/models/site.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
src/SIL.XForge/Models/Site.cs
src/SIL.XForge/Services/ProjectService.cs
test/SIL.XForge.Tests/Services/ProjectServiceTests.cs

* add currentProjectId property on the Site class
* store the project id on the user's site in the data
* use the stored id when no project id exists in local storage
* modify user service currentProjectId to accept a user parameter
* add user service test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1468)

SF-1668 Store the current project id and navigate on login

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

To clarify the issue here:
- ShareDB has the concept of pending ops, which are ops that have not been sent to the server yet. A doc on the client has pending ops.
- A doc also can have an inflight op, which is an op that has been taken from position 0 of the pending ops array, and sent to the server, but no acknowledgement has been received from the server yet (so it's unknown whether it's been persisted on the server).
- If the connection is lost, ShareDB takes the inflight op and puts it back in pending ops at position 0, so it can be sent again later when the connection is restored.
- In order to make the data persist, we store the pending ops, and the inflight op, in IndexedDB. We combine them into a single array, so the inflight op (if it exists) is stored with the pending ops.
The …

SF-1700 Save inflight op to position 0 in IndexedDB

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts

- Pass additional auth config options to auth0 to enable passwordless login
- Use passwordless login by default when using a shared key
Default login/sign up screen shows an additional phone number option:
When choosing to login with phone number the user only sees an option to enter their phone number:
When using a shared link, and not currently logged in, passwordless is enabled and you see phone number login instead of email/password and PT is hidden:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1428)

SF-1596 Enable passwordless login

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.spec.ts

Builds have started to fail, I think due to a change in Chromium.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1489)

Fix test broken in Chromium 105

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

- Update presence when text ID changes
- Don't remove presence on blur
- Refactored presence logic from `text-view-model.ts` to `text.component.ts`
- Subscribe to a presence channel and a presence doc
- Display name while actively editing a document
- Added community checking test to ensure presence is disabled
This PR aims to resolve SF-1587, SF-1580, and SF-1611.
The core issue was the app trying to use document presence to also work for a general "viewing the book and chapter" presence as well. ShareDB offers two separate ways to handle this. This PR now subscribes to the TextDoc specific presence as well as a generic channel for who is viewing the same TextDoc.
New features introduced were:
- Showing a users name while they are actively updating the document
- Showing any viewer …

SF-1587 SF-1580 SF-1611 Multi-cursor fixes to presence logic

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* use the same function to toggle note threads
* do not re-embed notes if explicitly removed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1481)

SF-1663 Consolidate how note threads are embedded

---

src/SIL.XForge.Scripture/ClientApp/src/utils.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/utils.ts

When a drag and drop happens, we do a check using `hasFunctionProp(document, 'caretRangeFromPoint')`. Unfortunately, I implemented `hasProp` incorrectly, by using `hasOwnProperty`, which is too strict of a check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1503)

SF-1742 Fix drag and drop by fixing type guards

---

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/utils.spec.ts

We recently updated the version of TypeScript we're using. There is now an option called `useUnknownInCatchVariables`. See https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables
> In TypeScript 4.0, support was added to allow changing the type of the variable in a catch clause from `any` to `unknown`. Allowing for code like:
``` ts
try {
// ...
} catch (err) {
// We have to verify err is an
// error before using it as one.
if (err instanceof Error) {
console.log(err.message);
}
}
```
> This pattern ensures that error handling code becomes more comprehensive because you cannot guarantee that the object being thrown _is_ a Error subclass ahead of time. With the flag `useUnknownInCatchVariables` enabled, then you do not need the additional syntax (`: unknown`) nor a linter rule …

Fix type guards in connect project component

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss

* convert templates to use angular material
* use dialog service to launch dialogs with scripture views
* add mat flat button styling
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1469)

SF-1678 Convert scripture view dialogs to angular material

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts

This is probably only a partial fix.
I can't even test #1506 because of how pervasive this bug is. I don't know what all it takes to reproduce it, but logging in as the same user in two different browsers does it for me. Memory usage skyrockets as each browser keeps fighting to write currentProjectId to the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1507)

SF-1750 Fix multiple browsers causing infinite writing of currentProjectId

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

* make note dialog opens with text area by default
* show edit buttons on last note if user is the author
* detect when existing note content changes
* add note to thread if editing existing note is not selected
* get edit icons to display in mobile view
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1486)

SF-1704 Allow user to add a note and edit notes in existing thread

---

src/SIL.XForge.Scripture/ClientApp/angular.json

- Add publicHost to angular.json
"Issue" appears to be with webpack in Angular 13 using the domain the app is viewed in. As we are running via localhost:5000 it isn't allowed to connect to angular live dev tools at localhost:4200. This update states that we can.
Other suggestions were to set the `allowedHosts` property.
Can also be set manually at CLI: `ng serve --public-host localhost:4200`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1511)

SF-1752 - Fix live reload

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts

This was broken in d4a45e8175e9b1af9c7d57d6bd6efa54489e5881
I went back to the commit where this broke and went through each dialog that was switched from MDC to Material and verified that there are no more instances of those dialogs being opened using MDC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1508)

SF-1751 Fix error opening ScriptureChooserDialogComponent

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss

- Change usx-blank to inline-flex to avoid stacking child elements
This issue is only obvious if the Paratext font size has been increased to something large i.e. 20
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1506)

SF-1610 Larger cursor appears when presence is on a blank heading

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- SF cleans up at the end of the sync process. If the sync process is
abruptly terminated without being able to clean up, the sync process
makes poor assumptions next time about its state. Namely, it can think
that the data in sync.
- A better and future change can address checking and cleaning up at
the beginning of a sync. This change merely checks if we are in a bad
state and stops the sync.
- If the PT hg repo commit revision does not match the SF DB record of
what PT hg repo commit revision the project was syncronized to, stop
the sync. Except for a special case.
- Clearly there are code cleanup activities that can be done here.
This change prioritizes getting the behaviour changed.
Tests file:
- The test BackupRestoredPreviouslyRevNotMatching_WritesToPT seems to
request the bad …

SF-1743a Stop sync if repo mismatch

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts

- Implemented a new browser online status which doesn't rely on having an active connection to node
- Don't check for an access token when offline
- Pass getAccessToken() to sharedb for requesting the latest access token
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1491)

SF-1696 Fix connecting issue with Auth0 when loading PWA while offline

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* subscribe to the ready$ observable on the note thread query
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1514)

SF-1734 Display note thread icons when query is ready

---

src/SIL.XForge.Scripture/DataAccess/SFDataAccessApplicationBuilderExtensions.cs
src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs
src/SIL.XForge.Scripture/Models/NoteSyncMetricInfo.cs
src/SIL.XForge.Scripture/Models/SFProjectSecret.cs
src/SIL.XForge.Scripture/Models/SyncMetricInfo.cs
src/SIL.XForge.Scripture/Models/SyncMetrics.cs
src/SIL.XForge.Scripture/Models/SyncStatus.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/IParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SyncService.cs
test/SIL.XForge.Scripture.Tests/Models/NoteSyncMetricInfoTests.cs
test/SIL.XForge.Scripture.Tests/Models/SyncMetricInfoTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs

This pull request saves the results of each sync to Mongo in a new collection, `sync_metrics`. A new document is created in this collection for every sync.
The metrics recorded include:
* Project that is being synced
* User doing the sync
* Time sync was queued
* Time sync started
* Time sync finished
* Status of sync (queued, running, successful, failed, cancelled)
* On failure, the error message
* Whether this sync had to wait on another sync
* Whether a backup is created and/or restored
* Books in SF added/deleted/updated
* Books in PT updated
* Notes in SF added/deleted/updated
* Notes in PT added/deleted/updated
* Questions in SF deleted
* TextDocs in SF added/deleted/updated
* Resource User access in SF added or removed
* User access in SF removed from the project
* A log including: …

SF-1614 Save the results of each sync to the database

---

src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json

This brings the version of TypeScript in line with what we're using in ClientApp and db_tools
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1527)

Update TypeScript to 4.6.4 in RealtimeServer

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

How Matthew 1:21-22 looks before and after. The parentheses are inserted by the text chooser dialog, which I used for these screenshots.
Note that while this appears to be the most common way to show a reference in RTL, it's not the only way that is used.
Before | After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1528)

SF-1748 Properly display verse refs in RTL script

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

- Added checks inside submit handlers to deal with being offline
Part of the underlaying issue is ShareDB still submitting an event for anyone subscribed to the the document presence. This fix checks again to see if they are online and ensures cursors are removed if they are not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1519)

SF-1729 Ensure presence cursor is removed when going offline

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts

- Changed comparison of TextDocId from `===` to `isEqual()`
It is interesting that the tests didn't have an issue with the `===` comparison.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1529)

SF-1737 Yellow highlight does not appear for reference passages in the question dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts

* add handler when user presses ctrl + backspace or ctrl + delete
* delete characters up to the next space
* only delete characters when word is adjacent to an embed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1533)

SF-1699 Avoid deleting embeds when backspacing or deleting word

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts

- Clicking avatar in the toolbar will trigger a scroll to the segment of that viewer
The "scroll" simply uses the existing `setSelection` in quill which is the same when the document first loads and returns the user to their last known permission. This could be improved to a nicer animation scroll and even have the segment appear in the middle of the screen rather than the bottom.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1522)

SF-1727 Make presence avatars clickable and scroll to position in the document

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json

The checking overview page is trying to do three things at once:
- Manage questions
- Show project stats
- Show a user their own stats
Arguably these should be three separate components, but for now I've reworded things to try to clear things up.
- "Texts with questions" is extremely confusing, especially for community checkers.
-  The stats that are shown are confusing, because it's not clear what is being measured.
Mostly it's a change of wording, but also the number of questions  is no longer shown to checkers, because that stat is unlike the others. It's not that it's not a useful stat if shown in context, but as of now I think it just adds confusion (also, you can go to the all questions page and see the number of questions).
I'm not supper keen on some of my wording changes.
- Maybe …

Improve wording on checking overview page

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/Models/NoteThreadChange.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- Ensure NoteThreadChange tracks the currently set assignment
- Always display unassigned on blank string or when null/undefined as a fallback for old data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1535)

SF-1542 - Unassigned text does not appear on note dialog after note update

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
src/SIL.XForge.Scripture/ClientApp/tsconfig.json

See the documentation for useUnknownInCatchVariables: https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables
When you have this:
``` ts
catch (error) {
// what is the type of error here?
}
```
It used to be `any`. If you turn on `useUnknownInCatchVariables`, it's `unknown`. A recent TS update made `useUnknownInCatchVariables` the default in strict mode. Rather than going around and changing a bunch of code when updating TS, I just turned the setting off temporarily. Now I'm turning it back on so any future code we write will have to either explicitly write `catch (error: any)`, or (preferable) write type-safe code, using type guards from `src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts`
- - - …

Turn on TS option useUnknownInCatchVariables

---

mongodb/TranslateMetrics/TranslateMetricsAggregationByBook.mongodb
mongodb/TranslateMetrics/TranslateMetricsAggregationByChapter.mongodb

There's a query for finding the metrics for a book, and one for a chapter. I only modified the one for a book, since that's the level I was trying to produce data for, for a project that asked for some stats. The same thing could be done for the chapter level analysis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1551)

Modify translate metrics query to output CSV

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

Before | After
----------|-------
Yes, it's minor, but I was never able to fix it when I did the initial RTL work and it's been annoying me ever since.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1563)

SF-1788 Fix placement of nav component arrow icons

---

src/SIL.XForge.Scripture/Services/HgWrapper.cs
src/SIL.XForge.Scripture/Services/IHgWrapper.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- The SF synchronize process records if 'DataInSync' at the end. The
next time SF synchronizes, it considers 'DataInSync' as part of
determining if it is safe to write data. If SF is abruptly terminated
during synchronize, we may not set 'DataInSync' to false when we would
have, resulting in the next sync incorrectly thinking it can safely
write data.
- This commit changes the behaviour. At the beginning of each
synchronize, set the local hg repository to the revision that we know
we last successfully imported from, and consider that we are always
'in sync', and so can safely write data. This is to make the
synchronize process more resilient against problems that occur during
its operation.
- The current hg repo revision is now being logged, in addition to the
latest shared/public …

SF-1743c sync: ensure correct revision is checked out when sync starts

---

mongodb/Texts/TextsWithLotsOfEdits.mongodb

I created this query recently when asked for stats regarding a project. This just lists texts sorted by the number of edits it has had. This helps to get an idea where the most activity has been.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1555)

Add query for texts with lots of edits

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json

This relates this this security advisory: https://github.com/advisories/GHSA-qm95-pgcg-qqfq
Note: `npm audit` did not find any vulnerabilities in `src/RealtimeServer` or `scripts/db_tools`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1572)

Update socket.io-parser to 4.0.5 to fix potential vulnerability

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts

As far as I can tell, the main issue is that connecting a basic project (Stp22 in this case) created about 85,000+ question subscribe queries* for questions and 1,500,000+ text fetches
<sup>*A subscribe query is distinct from a fetch query in that the subscriber is asking for all future changes to the query in real time, which is presumably a much more expensive operation.</sup>
The problem is that rather than update the page with whatever changes come over the wire, we tend to completely recalculate everything from scratch every time something is updated. As an example, in the app component, every time the project doc was updated it would unsubscribe from any existing question queries and then create a new query for each book in the project.
A simple fix, which I have applied here, is to …

SF-1556 Prevent excessive queries from the front end

---

src/RealtimeServer/scriptureforge/models/sf-project.ts
src/RealtimeServer/scriptureforge/services/sf-project-service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/Models/ParatextSettings.cs
src/SIL.XForge.Scripture/Models/SFProject.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* add the noteIcon property to the SFProject
* use the CommentTags of a project to get the to do icon name
* set the noteIcon property at sync time
* set the tagIcon to the project noteIcon on new note threads
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1534)

Use the to do comment tag icon for the project for new note threads

---

src/SIL.XForge.Scripture/ClientApp/package-lock.json

This relates this this security advisory: https://github.com/advisories/GHSA-76p3-8jx3-jpfq
Note: `npm audit` did not find any vulnerabilities in `src/RealtimeServer` or `scripts/db_tools`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1592)

Bump loader-utils to 2.0.3 to fix vulnerablity

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html

- Change quill to use focusout instead of onBlur
[focusout](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event) operates slightly differently where it also checks the focus of its dependents rather than onBlur which only checks the element it was set on. This simple switch is enough to correctly trigger and set our `targetFocused` property resolving the issue of the editor not immediately gaining focus again after the keyboard closes and triggers a height calculation on the editor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1597)

SF-1577 Opening nav drawer doesn't close keyboard on mobile

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

Chromium appears to see word breaks in this script where Firefox does not.
Before | After
----------|-------
Both of these screenshots are of the `mdc-list`. The "before" screenshot shows more than the list because the overflow portion of the element is included and is hiding behind other elements. 
I did not address the project select on the connect project page for several reasons:
1. We're planning on removing the select from that page (replacing it with a list of projects), so it will become a non-issue.
2. The menu there is a lot wider, so overflow is less of an issue.
3. It's already behaving differently than the project select in the nav bar, even when I add `dir=auto` to it to try to bring it in line with the project select in the nav bar. So my plan of "fix it in the nav bar, …

SF-1809 Fix overflowing project name in project select in Firefox

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

Currently this can throw without revealing what user it threw for.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1586)

log: provide more information when failing to refresh PT token

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

- Moved questions query in the app component to after a valid project has been selected
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1615)

SF-1822 Fix race condition for querying documents before share link has resolved

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

This adds the ability to bulk archive and publish questions at the book or chapter level (rather than archiving or republishing questions only individually). A bulk operation will result in the user being prompted with a question like "Are you sure you want to archive all the questions in Genesis 4?"
Tests coming.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1550)

SF-1701 Allow archiving and republishing questions in bulk

---

.github/workflows/build-and-test.yml

This should be temporary. It appears the build fails when .NET 7.x is preinstalled, as code coverage does not get generated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1621)

Disable code coverage report to fix build

---

src/RealtimeServer/common/utils/eq.spec.ts
src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json

- jest-expect-message ships its own types, and @types/jest-expect-message is deprecated ue to being unnecessary
- Updated tsconfig.json to import types from jest-expect-message
See https://github.com/mattphillips/jest-expect-message#configure-typescript for jest-expect-message's documentation for how to configure types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1610)

Update jest-expect-message and remove @types/jest-expect-message

---

src/RealtimeServer/common/models/user.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts

`substr()` is non-standard
The following are the descriptions MDN gives for these methods:
For [`substr()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr):
> The `substr()` method returns a portion of the string, starting at the specified index and extending for a given number of characters afterwards.
For [`substring()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring):
> The `substring()` method returns the part of the `string` between the start and end indexes, or to the end of the string.
So when the first argument is 0, they should be equivalent.
- - - …

Replace deprecated substr with substring

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts

- Spin class is turned on if the queueCount indicates there is an active sync in the queue
- Remove sync failure icon if an active sync is in progress
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1620)

Added spin animation to the sync icon in the menu

---

src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

Adds type checking of the localization keys we pass around, albeit not within the HTML templates (at least for now).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1616)

Add type safe I18nKey type

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pseudo-localization.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pseudo-localization.ts

Currently when the test team tests a new feature, it's not possible to tell whether it's been properly localized, because the strings haven't been translated yet, so it will always fall back to English.
This adds a locale behind a feature flag, with each string being generated by applying a [Caesar cipher](https://en.wikipedia.org/wiki/Caesar_cipher) with a right shift of 1 (a becomes b, b becomes c, z becomes a).
Here's an example from the settings page:
Our i18n service already has the concept of an "unpublished" localization, and already hides them behind a feature flag, so hiding this behind a feature flag is just a matter of registering the locale with `production: false`.
- - - …

SF-1825 Add pseudo localization

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj

The error on the back end was "Input string was not in a correct format".
@ddaspit fixed the problem and published a new version of SIL Machine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1623)

SF-1826 Fix error calling getWordGraph

---

.github/workflows/build-and-test.yml

After discussion with @marksvc, it seems we aren't getting that much value from running on 22.04, and the number of builds is a bit unwieldy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1613)

Remove Ubuntu 22.04 build

---

.github/workflows/build-and-test.yml
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Tests/SIL.XForge.Tests.csproj

The coverlet dependency used to create the opencover XML file has known issues with the MSBuild component .NET 7.0 (see https://github.com/coverlet-coverage/coverlet/issues/1391). This doesn't just apply to the project running on .NET 7.0, but also to the presence of .NET 7.0 on the computer building the coverage file.
This pull request:
* Re-enables the coverage GHA
* Modifies the Test: Backend GHA to generate the opencover XML file using the workaround documented on [this issue](https://github.com/coverlet-coverage/coverlet/issues/1391)
* Updates MS Test to the latest version
* Updates Coverlet to the latest version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1 …

Fix Code Coverage on .NET 7.0

---

.config/dotnet-tools.json
src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Tests/Realtime/RichText/DeltaTests.cs

In particular this update fixes an odd tuple formatting quirk where the type parameters for a dictionary get split over multiple lines, resulting in a difficult to read method declaration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1632)

Update CSharpier to 0.21

---

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss

Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1634)

SF-1831 Specify min height on ql editor

---

src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json

While there are of course breaking changes going to v28 and then v29, it doesn't appear we're affected by any of them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1638)

Update Jest from v27 to v29

---

src/SIL.XForge.Scripture/ClientApp/angular.json

Angular prints warnings like this when building:
```
Warning: /home/nate/src/web-xforge/src/SIL.XForge.Scripture/ClientApp/node_modules/@sillsdev/machine/lib/tokenization/latin-word-tokenizer.js depends on 'xregexp'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
CommonJS modules are defined in a such a way that prevent effective tree-shaking.
These warnings are "fixed" only in the sense that they are suppressed, by adding these packages to a list to ignore. As far as I am aware, there really isn't much we can do about these modules except stop using these packages (or hope they eventually change how they package output). 
I've deliberately not added xregexp to the list here, so that we …

Fix Angular warnings regarding CommonJS and AMD modules

---

.github/codeql/codeql-javascript-config.yml
.github/workflows/codeql.yml

LGTM.com is shutting down and migrating code scanning to GitHub. I was expecting a PR to automatically be opened to migrate us to GHA, but it hasn't happened yet and the shutdown is quite soon, so I think they may not have been able to automatically generate a PR for our repo for some reason. This file was mostly generated by GitHub; I think the only change I made was to the list of branches under `on.push.branches`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1612)

Create codeql.yml to migrate from LGTM.com to GHA

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts

- It looks like doing detectChanges should be meaningful here. This
doesn't fix any current tests, but might help us in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1642)

test: detectChanges after addUserToProject in app.component spec

---

test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
test/SIL.XForge.Scripture.Tests/Services/JwtInternetSharedRepositorySourceTests.cs
test/SIL.XForge.Scripture.Tests/Services/MockCommentTags.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNoteExtensions.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/DataAccess/MemoryUpdateBuilderTests.cs
test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

This PR fixes many straightforward CodeQL warnings in the unit tests. This should reduce the CodeQL alert count, and mean that we can then start looking at the CodeQL warnings in the main project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1645)

CodeQL fixes in Unit Tests

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts

- correctly set EditorComponent.insertSuggestionEnd when segment is blank
- correctly position suggestion when segment is blank
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1601)

SF-1820 Suggestion incorrectly displays current word after inserting a suggestion

---

src/RealtimeServer/common/models/user.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts

* detect if user is online before opening dialog
* show message if user is offline
* convert edit name dialog to angular material
* add scss style to edit name dialog
* do not show name confirmation dialog when user is offline
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1532)

SF-1760 Allow auth0 account users to edit name while online

---

src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs

Now that we have upgraded to Jering 6.0, Jering now supports HTTP/2 for communication between .NET and Node.
In my testing, this reduced the thread count by at least 10%, which I attribute to the lack of HTTP connections being opened in separate threads (HTTP/2 is much more efficient at this - .NET 6.0 only has one connection open per server, with up to 100 streams of data for that connection).
The [source code for Jering](https://github.com/JeringTech/Javascript.NodeJS/blob/master/src/NodeJS/NodeJSServiceImplementations/OutOfProcess/Http/HttpNodeJSServiceOptions.cs) states that HTTP/2 may be more stable, but will be slower (I imagine due to the compression and mandatory encryption in http/2), however my testing did not show a speed decrease. The HTTP/2 server implementation in Jering …

Configure Jering to use HTTP/2

---

src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
src/SIL.XForge.Scripture/Services/SFBuildHandler.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
src/SIL.XForge.Scripture/Services/SyncService.cs
src/SIL.XForge/Realtime/Connection.cs
src/SIL.XForge/Realtime/IConnection.cs
src/SIL.XForge/Realtime/IRealtimeServer.cs
src/SIL.XForge/Realtime/MemoryConnection.cs
src/SIL.XForge/Realtime/RealtimeServer.cs
src/SIL.XForge/Services/ProjectService.cs
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

The `Dispose()` method of the `Connection` class calls the `Disconnect()` method in the RealtimeServer in a synchronous manner. As this code is supposed to be asynchronous (as an `HttpClient` is utilized by Jering to talk to the RealtimeServer), it will block the thread until the call is completed. If there are issues, this could result in thread pool starvation or worst case, a possible deadlock.
C# 8.0 added `IAsyncDisposable`, which means that classes that implement it can be disposed asynchronously by changing:
```C#
using IConnection conn = await _realtimeService.ConnectAsync();
```
to:
```C#
await using IConnection conn = await _realtimeService.ConnectAsync();
```
This Pull Request adds support for the `IConnection` interface to be `IAsyncDisposable` and updates `using` statements …

Update the RealtimeServer Connection to be IAsyncDisposable

---

src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
src/SIL.XForge.Scripture/Services/SFScriptureText.cs
test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs
test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/Realtime/RichText/DeltaTests.cs

Due to the sheer number of CodeQL warnings, many were missed in the unit tests. This PR fixes the remaining CodeQL messages in the unit tests, as well as two minor documentation related warnings in the main project.
After this PR is merged, the CodeQL count should be below 100, and the CodeQL warnings in the non-test projects can be addressed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1650)

Fix remaining CodeQL issues in Unit Tests

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge/SIL.XForge.csproj
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Tests/SIL.XForge.Tests.csproj

This Pull Request updates
* Hangfire.Mongo to 1.9.1 (fixes a Schema Deserialization bug when migrating to Hangfire.Mongo 1.9)
* Microsoft.NET.Test.Sdk to 17.4.1 (minor bug fixes)
* Microsoft.AspNetCore.Mvc.NewtonsoftJson to 6.0.12
* Microsoft.Extensions.Http.Polly to 6.0.12
* Microsoft.AspNetCore.Authentication.JwtBearer to 6.0.12
* Microsoft.AspNetCore.SpaServices.Extensions to 6.0.12
I noticed that the production build script is using the 6.0.404 SDK, so all other .NET dependencies are already version 6.0.12 - this PR will bring all .NET dependencies into line with each other.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1653)

Update .NET dependencies

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

When chapter one is removed from a book (see SF-1415), the editor will not select the new first chapter of the book. Instead, the chapter dropdown will be blank, and the user needs to manually select the first chapter.
This Pull Request updates the editor so that it will always select the first chapter of a book when that book is navigated to.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1656)

SF-1421 The correct first chapter is now selected if chapter 1 is missing from a book

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

Changes to how questions are imported
- Allow omitting book in references if it is specified in the file name
- Allow extraneous columns (data is now found by looking at headings)
Instructions before | Instructions after
--------------------------|----------------------
Note that this is not backwards compatible; whereas previously files were not supposed to have headings, now they require them.
There are two main goals with this project:
1. It should be possible to import files from unfoldingWord with no changes to them.
2. Any "reasonable" spreadsheet should be able to be easily modified to produce a format that can be imported. For example, before this change the reference and question column had to be the first and second columns respectively. While that's not a difficult change to …

SF-1618 SF-1619 Make question import more flexible

---

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts

Previously, if a user stated a sync, and another user was on the sync page, the sync component would not automatically update with the sync progress.
This Pull Request updates the sync component so that the project document is monitored, and on any changes, the sync properties are checked for changes, and the sync UI updated. This also fixes SF-1202.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1655)

SF-1313 The sync status now updates if another user starts a sync

---

src/SIL.XForge.Scripture/ClientApp/src/typings/quill.d.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts

This Pull Request fixes the following TypeScript lint issues:
* *src\SIL.XForge.Scripture\ClientApp\src\typings\quill.d.ts*
**30:48  warning  'ClientRect' is deprecated.**
* *src\SIL.XForge.Scripture\ClientApp\src\xforge-common\auth-http-interceptor.spec.ts*
**106:13  warning  'error' is deprecated. Http requests never emit an `ErrorEvent`. Please specify a `ProgressEvent`.**
* *src\SIL.XForge.Scripture\ClientApp\src\xforge-common\auth.service.spec.ts*
**597:18  warning  'btoa' is deprecated. Use `buf.toString('base64')` instead.**
* *src\SIL.XForge.Scripture\ClientApp\src\xforge-common\test-utils.ts*
**146:26  warning  'atob' is deprecated. Use `Buffer.from(data, 'base64')` instead.**
The following lint issue is not fixed, as #1648 removes the affected code:
* …

Fixed TypeScript Lint Issues

---

src/RealtimeServer/common/services/json-doc-service.ts
src/RealtimeServer/common/services/project-data-service.ts
src/RealtimeServer/scriptureforge/models/note-thread.ts
src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
src/RealtimeServer/scriptureforge/realtime-server.ts
src/RealtimeServer/scriptureforge/scripture-utils/utils.ts
src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
src/RealtimeServer/scriptureforge/services/note-thread-service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

This change separates the rights for PT and SF note threads. Note threads continue to use the same service in the realtime server, but permission to view note threads is based on the rights of the user to view pt notes and sf notes.
If desired, another step would be to further separate SF and PT notes into their own collections in mongo, but I do not see the need or benefit of that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1635)

Separate SF and PT note thread rights

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- Listen for remote doc changes on noteThreadQuery
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1659)

SF-1595 Refresh note icon in editor after remote doc change

---

.github/workflows/ci-lint-prettier.yml
.github/workflows/ci-production-build.yml

This Pull Request fixes the following warning for the "Angular Production Build" and "Lint and Prettier" workflows:
````
node 16.x on ubuntu-latest
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1664)

Updated workflow step actions to node.js v16

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge/SIL.XForge.csproj

This Pull Request updates:
* idunno.Authentication.Basic to 2.3.0
* Microsoft.AspNetCore.Mvc.NewtonsoftJson to 6.0.13
* Microsoft.Extensions.Http.Polly to 6.0.13
* Microsoft.AspNetCore.Authentication.JwtBearer to 6.0.13
* Microsoft.AspNetCore.SpaServices.Extensions to 6.0.13
.NET 6.0.13 fixes a DoS vulnerability [CVE-2023-21538](https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-21538).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1660)

Update dependencies to .NET 6.0.13

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

- Used project default font size for notes in the note dialog
- Fixed inspection issue with `NoteDialogComponent` being declared in multiple places
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1665)

SF-1592 Font size is not changing in the note dialog text

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

When a project with a resource is synced, users with access to the target project, but not access to the source project in SF, are granted access to the resource. Currently for all users, whether they have Paratext access or not, an attempt is made to grant each user meeting that criteria access to the source project, by checking whether or not they have access to the resource.
As resources can only be accessed by Paratext users, this fix updates the check for users without access to the resource to only check users with Paratext access.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1668)

SF-1779 Only update resource access for Paratext users on sync

---

src/RealtimeServer/scriptureforge/models/sync.ts
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/project-notification.service.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
src/SIL.XForge.Scripture/Models/ProgressState.cs
src/SIL.XForge.Scripture/Models/Sync.cs
src/SIL.XForge.Scripture/Services/INotifier.cs
src/SIL.XForge.Scripture/Services/NotificationHub.cs
src/SIL.XForge.Scripture/Services/NotificationHubExtensions.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SyncProgress.cs
src/SIL.XForge.Scripture/Services/SyncService.cs
src/SIL.XForge.Scripture/Startup.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs

[SignalR](https://dotnet.microsoft.com/en-us/apps/aspnet/signalr) is included with ASP.NET 6.0, and is a cross-platform method of providing push notifications to clients. It is flexible, and can be scaled using Redis if SF was to grow beyond one server.
This PR
* Changes the SF backend from updating `Sync.percentCompleted` with Paratext sync percentage updates to using a SignalR hub
* Adds a project notification service utilizing SignalR to the frontend
* Updates the Sync Progress component to use the new service (commit c8e17f5e181d09589f1d34c7115f656818c29adb)
* Added more sync reporting of the different sync phases (commit 0d2c22cd8dc573803060f61cd352c2d08e4b9d4a)
* Only shows indeterminate sync progress at the start of the sync (commit 258f4e9c190a66d528a9f21df1f80c8c123ace3d)
- - - …

SF-1844 Use SignalR for Sync Progress

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

When the source project does not contain all of the books of the target project, the source pane may not always display. This is because the `sourceText` variable of the editor component does not update when the `text` variable updates when the user changes to the next book.
This can occur when a target project is the entire bible, and the source project is the New Testament. In this case, when you connect to the project for the first time or log in after having the cursor last in an Old Testament book, and then click on a New Testament book, the source pane will not display as the `sourceText` variable has not updated to the new source text. This pull request fixes that.
- - - …

SF-1851 Update the source text in the editor when the target text changes

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/project-notification.service.ts
src/SIL.XForge.Scripture/Services/NotificationHub.cs
src/SIL.XForge.Scripture/Startup.cs
src/SIL.XForge/Controllers/UrlConstants.cs
src/SIL.XForge/Services/AuthServiceCollectionExtensions.cs

During implementation of the SignalR hub, the requirement to authorize connections was accidentally omitted. Due to SignalR's slightly different method of configuration than controllers, this was not picked up prior to merging.
* Enables authorization for the Project Notifications SignalR hub
* Modifies the Project Notification Service to send the access_token
* Updates the JwtBearer event handler to read the access_token from the query string if the request is for the Project Notifications SignalR hub (this is how SignalR sends the token)
* Code is adapted from https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-7.0
* See https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/ts/signalr/src/WebSocketTransport.ts#L75
- - - …

SF-1844a Add Authorization to the SignalR hub

---

src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Tests/Services/MockLogger.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

A hypothesis has been that this IssuedAt check may be preventing us
from storing a refresh token. This could be changed to always accept
the incoming token, but for now just log a note if this situation
occurs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1675)

SF-1549 log when ignoring incoming older token

---

src/SIL.XForge.Scripture/ClientApp/.eslintrc.json

Show a lint warning if a method doesn't have a return type set.
We decided against making this an error as there are 300 methods that need to be fixed. We decided that we can fix them as we come across them and then change the lint rule to an error in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1677)

Add return type warning to eslint

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

We've had a number of sync failures recently with very little insight into what went wrong because Jering.Javascript doesn't give a complete stack trace (nowhere in the stack trace does our code appear). The failures usually end with a log of "RunAsync: ParatextData SendReceive finished without throwing." followed by a Jering.Javascript exception.
I'm not certain that this is the right approach, but we clearly need to have more detailed logging of where things are going wrong.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1678)

Save sync metrics logs to DB as they are created

---

src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs

This Pull Request disables HTTP/2 support for Jering, automatically downgrading it to HTTP/1.1
Details are available at: https://github.com/JeringTech/Javascript.NodeJS/#remarks-29
This PR rolls back the change in #1652.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1685)

Disable HTTP/2 support for Jering on sf-live

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs

Reverts sillsdev/web-xforge#1678
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1684)

Revert "Save sync metrics logs to DB as they are created"

---

src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs

This Pull Request disables HTTP/2 support for Jering, automatically downgrading it to HTTP/1.1
Details are available at: https://github.com/JeringTech/Javascript.NodeJS/#remarks-29
This PR rolls back the change in #1651.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1695)

Disabled HTTP/2 support for Jering

---

src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs

When Scripture Forge restarts, Hangfire assigns a new server GUID. This replaces the previous server instance, and so any jobs that were scheduled for execution before reboot will be stuck in an aborted state, with the following status on the Job Details screen:
If another job is waiting for that job to finish (it will not start in this state), that job will check every 15 seconds to see if the preceding job has finished (it will not finish), until the maximum document size is reached and Hangfire crashes.
To resolve this, an `InvisibilityTimeout` setting was added to Hangfire, however this is not configured by default for the Mongo storage engine we use. See [Hangfire.Mongo's README.md](https://github.com/Hangfire-Mongo/Hangfire.Mongo#migration):
> NOTE: By default the parameter …

Stop Hangfire jobs deadlocking when a preceding job will not start

---

src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/NotesFormatter.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge/Realtime/RealtimeJsonService.cs
src/SIL.XForge/Realtime/RealtimeServer.cs
test/SIL.XForge.Scripture.Tests/Services/NotesFormatterTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This pull request improves memory use and speed during syncing by optimizing syncing for projects using Paratext Resources as sources, and optimizing the using of conversion to and from XML for texts and answers.
The changes in this pull request include:
* **Optimization:** Refactoring `ParatextSyncRunner` so that Paratext Resources will only be updated in MongoDB if they have changed (bebf204f02605b8e2913a9ae07121790dda5ad82)
* ~~**Optimization:** Optimizing the conversion of USFM to USX from ` String -> XmlWriter -> String -> XmlReader -> XDocument` to now be `String -> XmlWriter -> XDocument` (d023d0034690454ae35b75755031153fdfe3d965)~~ *Removed due to the requirement for `XDocument.Parse` to strip unnecessary whitespace for an accurate USX XDocument comparison.*
* **Optimization:** …

Sync Memory Use and Speed Optimizations

---

src/SIL.XForge.Scripture/Services/NotesFormatter.cs
test/SIL.XForge.Scripture.Tests/Services/NotesFormatterTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

The version number on community checking notes would increment with each synchronize operation. This was caused by a difference in newLine whitespace around the <p> tags around <bold>community checking question</bold> xml. I could not determine what was removing the newLine whitespace around Paragraph tags.
This change ensures that regardless of those newLine whitespaces so that child nodes in paragraph nodes retain style features.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1698)

SF-1870 Parse comment content idempotently

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss

- Enable autofocus for the note dialog
- Reduce height of the note dialog for smaller devices
- Only force focus on the target if there are no dialogs open
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1694)

SF-1868 Show mobile keyboard when adding a note

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

- Opened scope to allow for SFProjectRole.ParatextConsultant to use FAB
- Added missing return types
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1691)

SF-1867 Give PT Reviews the same note adding UI as SF Reviewers

---

src/RealtimeServer/scriptureforge/realtime-server.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
src/RealtimeServer/scriptureforge/services/sf-project-service.ts

Every migration test was running all migrations that were available, rather than just one. I updated the tests so you could specify both the version the document is currently at, and the migration version to stop at.
Probably we will want to do this for the other data migration tests as well, but I want to put this out first and decide on the best solution before changing them all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1707)

Fix project migration tests to prevent new migrations from being run

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.spec.ts

Chromium now uses a NARROW NO-BREAK SPACE between the minutes and the am/pm designation
It would probably behoove us to merge this sooner rather than later, because it's likely that our builds are going to start failing at any moment when GitHub Actions starts using Chromium 110 for the builds (which may be now already).
(For what it's worth, I don't actually know that it's Chromium itself; it could be a localization package that Chromium depends on that got upgraded on the system, but I think Chromium tends to ship such functionality internally rather than depend on system libraries)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1714)

Fix date format tests for Chromium 110

---

src/RealtimeServer/common/realtime-server.ts
src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs

This pull request:
* Performs migrations on batches of 10,000 documents
* Sends a log message when each batch is processed
* Suppresses the CodeQL warning "_Unexpected any. Specify a different type_" in realtime-server.ts
* Disables the Jering invocation timeout when a debugging parameter (`--inspect` or `--inspect-brk`) is specified for NodeJS
- The primary purpose of this is to stop debugging pauses or huge collections from causing an invocation timeout
- This can also be used to give the very long execution time required for some migrations, by specifying `--inspect` in the `node-options` environment variable, which will ensure that the migration process is not interrupted by Jering timing out the request to `Server.Start()`.
**Problem Summary**
When a collection has hundreds of …

Added support for batch migrating ShareDB documents

---

src/SIL.XForge.Scripture/Models/CheckingConfig.cs
src/SIL.XForge.Scripture/Models/NoteTag.cs
src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/NotesFormatter.cs
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* add the NoteTagId property on the CheckingConfig class
* create community checking tag if project has answers
* add tagsAdded element when getting note thread changelist
When community checking answers get synchronized with Paratext, any new and existing community checking answers will be exported and giving the default checking tag ID. If the default did not previously exist, then it creates a new one. If the 07conversation2 icon is already in use, that tag ID will be given to the question answers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1701)

SF-1865 Add default tag for community checking answers

---

src/Help/UpdateHelp/Program.cs

The csh-redirect.htm file has a heading that conflicts with another file. Since this file isn't part of the core help pages, we can just ignore this in the help localization process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1723)

Help: Ignore auxiliary files during localization

---

src/RealtimeServer/common/realtime-server.spec.ts
src/RealtimeServer/common/realtime-server.ts
src/RealtimeServer/scriptureforge/services/note-thread-migrations.spec.ts
src/RealtimeServer/scriptureforge/services/note-thread-migrations.ts
src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts

This pull request:
* Updates the note_threads migration to remove the `tagIcon` property.
* Stops logging migration progress to the console, as it was polluting tests and not displaying on live.
* Does not submit empty op collections to ShareDB on `submitMigrationOp`.
* Fixed incorrect `od` ops so that any future developers who copy them will not propagate the incorrect ops.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1722)

Migration fixes and clean ups

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

Previously this checked whether the role was reviewer or consultant, but we should be going by permissions, not by roles.
I also renamed some relevant variables to be about whether the commenting UI should be shown, rather than whether the user had a particular role.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1727)

SF-1890 Change add comment button logic to be permission based

---

src/RealtimeServer/common/index.ts
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge/Realtime/Connection.cs
src/SIL.XForge/Realtime/Document.cs
src/SIL.XForge/Realtime/IConnection.cs
src/SIL.XForge/Realtime/IRealtimeServer.cs
src/SIL.XForge/Realtime/MemoryConnection.cs
src/SIL.XForge/Realtime/RealtimeServer.cs
src/SIL.XForge/Realtime/Snapshot.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Tests/Realtime/ConnectionTests.cs

This Pull Request improves memory use and project sync speed for projects with very large numbers of comments, and many books (i.e. complete canons).
The following changes are included:
* Changed a regular expression used commonly in sync to compiled (reduced memory allocations)
* Updated the Realtime Server and sync process to retrieve multiple documents at once (lowers socket use and improves sync speed)
* Updated use of the Paratext `CommentManager` to:
- Remove the `CommentManager` from the MRU cache when the sync is completed (frees memory after sync completion)
- Removed the `ParallelDeserializer` for the `CommentList` data type (considerable reduction to sync memory use with the penalty of a slightly slower [in terms of milliseconds] sync)
* Suppressed the CodeQL warnings for …

Memory and Speed Optimizations to the Sync Process

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-role-info.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts

The display name for a role is now stored in our localization files, and that is the only place we should be getting it from. Having it elsewhere is just a source of potential trouble.
Unfortunately the system administration page was still using the old displayName, so it needed some changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1728)

SF-1892 Remove displayName from ProjectRoleInfo

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

Previously if you opened and close a note dialog, the verse would be selected because clicking on the icon actually also selected the verse. However, the UI would not look like the verse was selected.
To fix this issue, we avoid triggering selecting the verse if a user only clicked the note thread icon on the verse.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1733)

SF-1891 Do not select a verse when clicking note thread icon

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/Models/Note.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs

* delete comment threads when corresponding note thread is deleted
* ignore new comment threads where all notes are deleted
* update logic for when to delete a note thread
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1736)

SF-1900 Delete comments in a deleted note thread

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* store note thread doc values in variable at sync time
* throw if a note cannot be found when it should exist
* check the sync user ref on a note before creating a new comment
* some clean up
The primary problem for this issue was that we fetched the note thread docs from the realtime server twice. Once when we export the note thread doc changes to PT, and then a second time when we pull in the up-to-date note threads from PT. When we did this, the SyncUserRef property on the note threads were not up to date on the second set of note thread docs, which caused the sync to incorrectly assume that it needed to delete the existing docs and recreate them with the sync user as the owner. This fixes that problem as well as introduces an exception that is thrown if we have a sync user on a note, …

SF-1889 Attribute new SF notes to reviewer user on sync

---

src/RealtimeServer/scriptureforge/models/checking-config.ts

This was added to the C# model in
049f672a10e54ceb3a252999f1805245ff87d97b but was mistakenly omitted from the TS model.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1751)

Add noteTagId to CheckingConfig TS model

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

The getBaseVerse function is used in a few places in SF, but it did not take into account the format of segments for a combined verse (i.e. verse_1_5-6) which is a valid segment ref. This changes it to consider that format as the base verse, so when we open a dialog, we give the correct verse reference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1748)

SF-1883 Consider combined verse segments when opening note dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

- Added a string check for segment and context text
**Before**
**After**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1753)

SF-1919 - Hide option to "Show changes" when viewing a note if there are no changes

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

- Added a label to the textarea
- Changed the appearance to match answers appearance in community checking
**Before**
**After**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1754)

SF-1918 - Add label to adding note textarea

---

src/RealtimeServer/.eslintrc.json
src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts

ESLint has been complaining when we do things like:
``` ts
const [_, secondArg] = something.methodThatReturnsArrayOfTwoItems();
```
By convention an underscore leading a variable name indicates that it is used as a placeholder.
Docs for no-unused-vars: https://eslint.org/docs/latest/rules/no-unused-vars
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1758)

Configure ESLint to ignore unused variables that start with underscore

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This change syncs note thread docs in SF to Paratext before the Paratext send/receive occurs. These will be no changes unless a user intentionally enables the adding notes feature flag on the front-end.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1759)

SF-1765 Sync notes back to Paratext

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss

"Simplify" may be a misnomer here, but this seems to me to make more sense. Also, the background is now no longer set to white.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1762)

Simplify styling of notice component

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

On projects where there are texts are unavailable we should not allow a user to add a note. This change makes a snackbar appear when a user clicks the add note button when viewing a texts that is unavailable because a user is offline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1742)

SF-1905 Disable adding a note on unavailable text

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.ts

- I think the "add user" icon is a lot easier to understand than the "share" icon that is supposed to evoke the idea of a network. Some users may recognize it but I think it's less helpful in most cases.
- It probably can't be used in every situation that the share icon would be used, since it's possible to share something without adding a user to it.
In RTL mode:
I don't think flipping the icon is that important, but it's trying to convey "add person", so I think having the "+" come first makes the most sense.
I removed some CSS that wasn't actually being used because it wasn't imported into the component. It got added very recently in #1648.
- - - …

SF-1930 Replace share icon with add user icon

---

src/SIL.XForge/Controllers/UsersRpcController.cs

This endpoint was left here because it used to be automatically called the moment the app loaded, and if you remove an endpoint from the back end, and users are still using a older client, they'll get errors due to trying to call a non-existent endpoint. It's now been almost a year since it was used, so cleaning it up now makes sense.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1766)

Remove obsolete CheckUserNeedsMigrating endpoint

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/typings/sharedb.d.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-data-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts

- Add ability to interfere with ShareDB connection
- Store src and seq before sending to server
- Interfere with ShareDB connection to ensure src and seq are set
This PR is not polished. It probably calls for a *lot* of comments, and some other changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1557)

SF-1628 Fix src and seq not being correct after reconnection

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-questions-confirmation-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts

When writing dialog unit tests for #1731, I noticed that the class `ChildViewContainerComponent` was copy-pasted into each `*-dialog.spec.ts` file.
This PR updates all of these spec.ts files to instead use `ChildViewContainerComponent` declared in `test-utils.ts`.
I also took the opportunity to clean up some of the "Missing return type on function" @typescript-eslint/explicit-function-return-type warnings in the classes I was updating.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1761)

Improve ChildViewContainerComponent reuse

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

When a note gets inserted, the scripture editor responds to the new note too fast sometimes, and the note appears in the editor before our system has had the chance to mark it read. To prevent this race-condition from happening, we have to explicitly wait for the note ID to be recorded in the projectUserConfigDoc before saving the note.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1719)

SF-1878b Highlight note thread only if unread notes exist

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html

- Changed notice component to use [ng-content](https://angular.io/guide/content-projection)
- Updated the styling to use a column gap instead of a margin
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1768)

Upgrade notice component to use ng-content

---

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts

Previously the role and permissions checkbox label would not wrap, leaving all the wrapping to the name, which caused it to wrap a ton if it had to wrap.
Here's how it looks now (in French, where the issue was originally reported):
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1770)

SF-1464 Fix wrapping in user list

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/overlay-container.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/overlay-container.ts

- Dismiss an open bottom sheet in the editor on disposal
- Change location for material overlays to be child elements of <app-root>
- Update z-index for nav drawer and overlay to be higher than other material overlays
**Before**
**After**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1775)

SF-1935 - Close note bottom sheet when not in use

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

- Hide the assignment in the note header if the current user does not have a Paratext role
**Paratext users see**
**Non-Paratext users see**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1773)

SF-1937 - Hide user assignment in the notes dialog for commenters

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
src/SIL.XForge/Services/AuthService.cs
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

- Save any update to the Avatar URL (picture) in the user metadata in Auth0
- On receiving the user profile from Auth0, use the picture value from metadata if available
- Update presence information when the user doc changes
- Added return types
- Added a user doc to various tests that use the text component
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1772)

SF-1932 - Store updated avatar URL in Auth0 user metadata

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

This change adds the user label to the notes left by non-paratext users. Initially I tried to do this on the back-end, but there were some round-tripping issues that were becoming more complex. Instead, I decided to add the label on the front-end, and make the label invisible in the note dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1774)

SF-1917 Add reviewer label on note content

---

src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs

- Added additional endpoint for `CheckLinkSharing(projectId, shareKey)`
- Added additional endpoint for `LinkSharingKey(projectId, role)`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1780)

Add in compatibility endpoints for old clients using share keys

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts

This PR removes defaultNoteThread's mutability, so that tests which use this static property (which was a variable) can depend on its consistency.
The tests which this PR fixes are:
* "NoteDialogComponent deletes the thread if the last note is deleted" at note-dialog.component.spec.ts:499:39
* "NoteDialogComponent deletes the thread if the deleted note is the only active note" at note-dialog.component.spec.ts:525:39
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1782)

Fix for note dialog tests breaking for some runs

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss

Previously the style for the inputs in the import question dialog would get applied to the inputs in the create question dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1784)

Fix styles leaking from import question dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts

Now that translators and admins have the same UI for adding notes, we need to remove the commenter-selection class from leaking into the data since the user will be typing into a segment which is selected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1781)

SF-1946 Fix text deleted when synchronizing with note feature enabled

---

src/RealtimeServer/common/services/project-data-service.spec.ts
src/RealtimeServer/common/services/project-data-service.ts
src/RealtimeServer/scriptureforge/models/comment.ts
src/RealtimeServer/scriptureforge/models/note.ts
src/RealtimeServer/scriptureforge/services/question-migrations.spec.ts
src/RealtimeServer/scriptureforge/services/question-migrations.ts
src/RealtimeServer/scriptureforge/services/question-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
src/SIL.XForge.Scripture/Models/Answer.cs
src/SIL.XForge.Scripture/Models/Comment.cs
src/SIL.XForge.Scripture/Models/Note.cs
src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/NotesFormatter.cs
src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

**Overview**
Comments made in Paratext to Answers exported to Paratext from Scripture Forge were being lost on sync if a newer comment was made in Scripture Forge. This occurred because there was no accurate tracking of comments being deleted. To address that, this PR adds a deleted flag to Comments and Answers that is set when these are deleted, as opposed to the previous behavior which was the removal of the comment or answer from the question document.
**Changes in this Pull Request**
- Rename `tagsAdded` XML tag to `tagAdded` to conform to Paratext Comments XML tag name
- Fixed bug where the comment was incorrectly seen as modified when  no change had occurred
- Add a `deleted` flag to answers and comments
- Fixed a bug where comments created in Paratext are deleted when a newer …

SF-1924 PT comments on SF community checking answers lost after sync

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json

- Adding notes via the mobile bottom sheet now displays a textarea
- Users can now add notes via the bottom sheet form
- Refactored notes to be added via the editor component rather than the note dialog
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1765)

SF-1923 Use bottom sheet for commenters to add new notes

---

src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts

The position of a note thread in a verse is stored on the note thread model. When a translator updates texts that results in changing the position of the note thread position, it is necessary to allow the note thread record to be updated in mongoDB. This change allows translators to update the note thread model.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1777)

SF-1944 Allow translators to edit note thread position

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* ensure the updated verse segments resubscribes to click events
* change focused logic to account for bottomsheet
* also fixes SF-1941
SF-1941 prevented users from re-selecting the current verse to add a second comment because the usx segment element was not being subscribed to after the new note thread was created. This change causes toggleNoteThreadVerseRefs to emit, which causes the subscriptions to be re-created.
Then it would be possible to create a second comment. To allow clicking on the second comment to open a dialog, we needed to ensure that the note embed that gets inserted does not create an erroneous usx-segment. So we need to deselect the selected verse which has the commenter-selection class format that caused the inserting of the note embed to go wrong.
- - -
This change …

SF-1897 Deselect the current verse selection when opening note dialog

---

.vscode/settings.json
src/RealtimeServer/scriptureforge/models/sf-project-role.ts
src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
src/SIL.XForge.Scripture/Models/SFProjectRole.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs

This change updates the role names from reviewer to commenter, and observer to viewer. This change will clarify the role so that there is less confusion between checking reviewers and translation reviewers. The string in the backend will remain "sf_reviewer" and "sf_observer" since there is no real benefit to changing those strings which would require a migration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1796)

SF-1888 Change role names for SF reviewers and observers

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts

The Scripture Chooser and Checking Overview are not sorting books by canonical order. This PR addresses that bug, and also fixes a few `Missing return type on function` lint warnings in `scripture-chooser-dialog.component.ts`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1797)

SF-1414 Fix book sort order in Scripture Chooser & Checking Overview

---

mongodb/Questions/CountAnswersByMonth.mongodb

I've been using this query successfully for a good while now to count answers by the month they were added.
I wanted it to print out a total for every month regardless of whether any answers were added in that month, but unfortunately that requires a fairly verbose script at the end. It does make it easy to copy the output though and put it into a spreadsheet for plotting, which is what I've been doing with the results.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1801)

Add Mongo query to count answers by month

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.stories.ts

I've made several changes to the Storybook stories, mainly because I want the early stories we write to be exemplary since they're likely to be the basis for other stories.
- Where possible I replaced `StoryFn` with `StoryObj`, the preferred way of defining stories in Storybook 7 (in some cases `StoryFn` just works better).
- I updated how the metadata for each component is declared so we can avoid writing `as Meta`.
- I added a test to the share button stories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1800)

Update Storybook stories

---

src/SIL.XForge.Scripture/ClientApp/.storybook/main.ts
src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
src/SIL.XForge.Scripture/ClientApp/.storybook/story-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/mdc-dialog.stories.ts

This adds stories for all the MDC dialogs except the system admin delete user dialog, which is more complicated.
You can see the stories here: https://643eb1587a4d88f5ee921c56-yjkeljooff.chromatic.com/?path=/story/mdc-dialogs--question-answered
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1805)

Add MDC dialog stories

---

.github/workflows/chromatic.yml

I created the Chromatic workflow by copying one of our existing build workflows, which included building commits after they're merged, which isn't really necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1809)

Turn off Chromatic on push to master

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

* use the commenter selected verse when saving a note thread
The currentOrDefault verse for a text isn't the same as the commenter selected verse which will always be set when a user opens a note dialog or bottom sheet to add a new comment. This change abandons the use of currentOrDefault verse.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1792)

SF-1958 Show the commenter selected verse on bottom sheet

---

src/SIL.XForge.Scripture/Services/DotNetCoreAlert.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/LambdaTraceListener.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- ParatextData outputs messages using Trace and Alert. Capture these
to SyncMetrics.
- Bump up alert logging to Error level so errors also make their way
thru to the console output.
- May help investigate [SF-1968](https://jira.sil.org/browse/SF-1968) sync problem.
- SendReceiveAsync is only called in production from
ParatextSyncRunner, and all arguments are specified. Modified to make
all arguments required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1807)

log: record ParatextData errors during SendReceive

---

src/SIL.XForge.Scripture/Services/DotNetCoreAlert.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/LambdaTraceListener.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

- ParatextData outputs messages using Trace and Alert. Capture these
to SyncMetrics.
- Bump up alert logging to Error level so errors also make their way
thru to the console output.
- May help investigate SF-1968 sync problem.
- SendReceiveAsync is only called in production from
ParatextSyncRunner, and all arguments are specified. Modified to make
all arguments required.
(cherry picked from commit 9fc6800d72f15541978dd9ca1b548517a38f434e)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1810)

log: record ParatextData messages during SendReceive (#1807)

---

src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
src/SIL.XForge.Scripture/Services/SFScrTextCollection.cs

This Pull Request allows resources to have the same short name. It does this by:
* Support for loading resources from the `_resourcesById` directory
* Ensuring that checks for the existing resource file check the DBL Id, so that if a resource is being installed shares a short name with an existing resource, it is installed to the `_resourcesById` directory
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1812)

SF-1988 Support for resources with duplicate short names

---

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs

Extra-biblical books (like Introduction, Indexes, Extra Material) should not be editable in Scripture Forge. However, if one of these books has more than one chapter, and those subsequent chapters (2, 3, etc) are valid, they will be marked as valid and editable in Scripture Forge.
This Pull Request fixes this, by ensuring that if a book is defined as invalid (by not being in the valid books list in `usx-sf.xsd`), all subsequent chapters will be invalid too.
In addition, this PR enables the test `ToDelta_LineBreakWithinVerse`, which was noticed have accidentally had its Test attribute omitted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1798)

SF-1973 Flag all chapters of extra-Biblical books as invalid

---

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
src/SIL.XForge.Scripture/ClientApp/src/index.html

This Pull Request fixes Kayah Li script on Windows 10 and 11 by including the "Noto Sans Kayah Li" font.
Support for other scripts is not included, as testing a broad range of DBL resources in non-latin scripts all displayed correctly on Windows 10 and 11.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1816)

Fixed Kayah Li script on Windows

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss

The recent conversion of the header from MDC to Material caused the user menu to sometimes be so narrow as to look odd.
Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1828)

Fix user menu min width

---

src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge/Services/IUserService.cs
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

* get usernames from user ids from the user service
* add the SF user label to comments when pushing to PT
* interpret comment and note changes accounting for the note label
This change introduces the reviewer label to comments created in SF by users who do not have a paratext role on the project. Each time an admin or translator does a sync, the content of the SF note will be compared to the equivalent comment content in PT. This is a string comparison that interprets the strings with or without SF reviewer labels when needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1791)

SF-1917 Add reviewer name to note thread in PT

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss

I broke the layout of the share control on mobile in #1817 (the inputs are not full width like they should be):
To be fair, it was never great to begin with; the button was full width which looks very odd:
Here's how it now looks with this change:
And on desktop (where it's presumably the most likely to be used, it continues to look like this:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1832)

Fix share control appearance on mobile

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts

Before | After
-------|------
(In actual practice you can't get to the before state because the suggestions always show LTR, but once that is fixed this would be an issue).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1826)

Add translation suggestion story and fix RTL suggestions

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts

- Convert to Material
- Make "Stop Recording" button color primary. Some time ago while watching a user use SF, I noticed that the browser's permission prompt for recording audio had taken his focus away from the dialog, so by the time he'd figured out he needed to give permission and then recorded the audio, he was kind of lost and had trouble finding the "stop recording" button. Making the button color primary isn't going to totally fix that, but when a user is recording, stopping recording is always the expected next action, so it makes sense to make it as prominent as possible.
- I changed the file name of the recorded audio. Previously it was using the users's display name. I can't think of any benefit of doing this (it's not guaranteed to be unique, and it's not shown to users), and …

SF-2000 Update audio recorder component

---

src/SIL.XForge.Scripture/locales.json

Fairly little has been translated into Lao, but most of the most important strings for checkers are translated, so I think it makes sense to make it available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1838)

SF-2007 Enable Lao localization in production

---

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/autofocus.directive.ts

While experimenting with what it would take to convert the `CheckingCommentFormComponent` to Material recently, I ran into the problem that the `appAutofocus` directive did not work with the Material inputs. For MDC we would use the directive in the template by writing something like:
``` html
<mdc-text-field appAutofocus></mdc-text-field>
```
And then the MdcTextField component would be injected into `appAutofocus`. However, Material does inputs with a directive on an element, so as far as I'm aware we can't inject a component, only an element:
``` html
<input matInput type="text">
```
Hence, I've updated the directive to request an element rather than a component, and it continues to work with MDC, and should work with Material as well. I think it should generally work with any other …

SF-2004 Make appAutofocus directive work with non-MDC components

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

When connecting a project for the first time, or if a book is created, the note thread docs were not being created. This would lead to the comments in Paratext being deleted the next time a user does a sync. This fix ensures that note thread docs are updated regardless of whether a book exists or was just added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1814)

SF-1996 Add note threads when book is newly added on a sync

---

src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

Using the paratext username to determine if a user is a paratext user on the project is no longer acceptable because Paratext users can update their display name. This change detects if a user is a Paratext user on the project using the SF user id, and if so, then it does not add the SF user label to the note content.
In addition, update the currentPtUsers property in ParatextSyncRunner at the start of the sync so that it is up to date at the start of the sync.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1835)

SF-2002 Create SF user label only for user IDs without a paratext role

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

If note threads are refreshed while a user is interacting with note threads, responding to text edits is turned off and never turned back on. This change turns it back on so that text anchors get correctly updated when the text is edited.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1833)

SF-2003 Fix note anchors not updated after notes loaded

---

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
src/SIL.XForge.Scripture/locales.json

1. Right now the help links in the import questions dialog do not go to the right place anymore. I've updated them to link to the new help site.
2. I added a link to the manual
3. I fixed the locale paths (see comments)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1823)

SF-1998 Fix help links

---

src/SIL.XForge.Scripture/Services/ChapterEqualityComparer.cs
src/SIL.XForge.Scripture/Services/DictionaryComparer.cs
src/SIL.XForge.Scripture/Services/NoteTagEqualityComparer.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ChapterEqualityComparerTests.cs
test/SIL.XForge.Scripture.Tests/Services/DictionaryComparerTests.cs
test/SIL.XForge.Scripture.Tests/Services/NoteTagEqualityComparerTests.cs

This PR fixes a bug where the NoteTags were recreated in ShareDB for a Project on every sync.
I also took the opportunity to:
- Refactor the other equality comparers
- Create unit tests for the equality comparers
- Update hash code calculation to use the `HashCode` class which was introduced in .NET Core 2.1, rather than custom hash code generation
This PR comes from noticing unnecessary ops being created while optimizing the sync process.
These ops (which this PR stops the creation of) are:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1847)

SF-2021 Note tags are no longer updated on every sync

---

src/SIL.XForge/Services/AuthService.cs
src/SIL.XForge/Services/IAuthService.cs
src/SIL.XForge/Services/UserService.cs
test/SIL.XForge.Tests/Services/UserServiceTests.cs

- Update name, nickname, avatar on Auth0 profile if set to phone_number
*Notes*
* Decided to go with Anonymous rather than trying to generate a random name which may just cause other confusion
* Decided not to use any kind of gravatar type image which either needed an email address or storage for a randomly generated image in order for it to work in both the Auth0 profile and be accessible by our Angular Avatar component.
* As soon as a user updates their display name it will also update their avatar to something relevant
* When signing up for the first time on localhost auth0 tenant (sil-appbuilder) you get a oauth prompt which displays the phone number. At this point the name hasn't been updated. This prompt only appears on this tenant and is not displayed on QA/Live
* The implemented …

SF-1960 Set display name when a user signs up with a phone number

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts

~This may also fix [SF-1756](https://jira.sil.org/browse/SF-1756).~
It appears the problem is that `throttleTime()` by default does not emit the last value by default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1842)

SF-1459 Fix checking overview question list not always updating

---

codecov.yml

This Pull Request forces the Codecov errors to be informational. This previously worked, but a change to how Codecov loads the configuration caused a reduction in code coverage to give a red cross to a Pull Request or Commit.
When this PR had a commit included that removed tests, the following status displayed for Codecov:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1854)

SF-2029 Fixed Code Coverage failing Pull Requests

---

src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs

It was increased to 3 hours in #1853, but apparently not by enough. The job on live has still be restarting itself. I think it must be going just beyond 3 hours.
Long term this shouldn't be an issue, as we are moving to Serval.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1858)

Increase Hangfire Timeout to 4 hours

---

.github/workflows/chromatic.yml

Part of the reason Chromatic is so confused is because when we run our builds, by default we check out a merge of the PR branch to the target branch, rather than the tip of the target branch (this is GitHub being smart about making sure any builds will pass after merging, and not just on the PR branch).
However, since Chromatic needs to understand Git history to calculate baselines, [they recommend](https://www.chromatic.com/docs/github-actions#recommended-configuration-for-build-events) using the push event rather than the pull_request event. I didn't like that idea, so I instead opted to just explicitly tell `actions/checkout@v3` to check out the tip of the branch.
- - - …

tool: Update Chromatic workflow to build tip of branch

---

scripts/db_tools/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package-lock.json

This pull request updates the following vulnerable dependencies:
Dependencies of Karma:
* socket.io-parser (see https://github.com/sillsdev/web-xforge/security/dependabot/83)
* engine.io (Uncaught Exception vulnerability - https://github.com/advisories/GHSA-q9mw-68c2-j6m5)
Dependency of lint-staged:
* yaml (Uncaught Exception in yaml - https://github.com/advisories/GHSA-f9xv-q969-pqx4)
Dependency of the ping-rts DB tool:
* socket.io-parser (see https://github.com/sillsdev/web-xforge/security/dependabot/84)
These are only used in testing and development.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1865)

Update NPM dependencies flagged as vulnerable

---

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts

The right-to-left marker exists in the usfm of right-to-left projects on combined verses. This was causing problems because when we looked up text for a specific verse, if the right-to-left marker existed on the op, we would not get a match. This change helps to generate a verse ref that correctly matches what exists on the segment attribute of text ops so we can correctly look up the text strings in a text doc so they can be displayed in the note dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1864)

SF-1934 Fix RTL language marker not recognized in combined verses

---

src/SIL.XForge.Scripture/ClientApp/src/_usx.scss

The display of the va tag was different sizes depending on whether the marker was next to the base verse embed, or if it was in the middle of a verse. The marker next to a verse embed was smaller. This change bumps up the size of the va text so it is the  same size regardless of where it occurs. The images have been updated now.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1867)

SF-1506 Maintain consistent font size for va markers

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

This fixes a bug introduced in #1871
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1884)

SF-2057 Fix error opening note dialog

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/users/users.component.html

Only thing I changed functionally was switching between the normal and condensed delete audio file buttons. With MDC, the normal/full text would word-wrap as window width decreased, and with Material it does not. I opted to switch to the delete icon only over researching how to word-wrap. Can change this if desired.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1894)

SF-2071 Checking Audio to Material

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss

This was broken in #1874 9e19ac14ffb3e175eef51bb708572c3d3367d060
Before | After
-------|------
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1895)

SF-2077 Fix styling of role selection menu

---

deploy/dependencies.yml

The mongodb 4.0 key[1] seems to have expired without an updated key being available. Use mongodb 5.0[2].
The ansible page for apt_key shows[3] how to move away from deprecated apt-key. This patch also changes to use get_url instead of apt_key, following this example. This was also applied to the dotnet key. This change may fix something before it becomes a problem in a future version of Ubuntu.
Note that this change does not do everything needed to successfully _upgrade_ mongodb 4.0 instances to mongodb 5.0.
[1] https://www.mongodb.com/docs/v4.0/tutorial/install-mongodb-on-ubuntu/ 
[2] https://www.mongodb.com/docs/v5.0/tutorial/install-mongodb-on-ubuntu/ 
[3] https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html
- - - …

dev: use mongodb 5.0

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts

This is more of scaffolding than a feature.
The positioning of the element works fine. But it's not possible to see the very bottom of the chapter because this component covers it. That wasn't addressed by the original design and we'll need to work through how to address that at a later time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1899)

SF-2081 Create container for audio component over chapter

---

src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n-story.module.ts

Previously we only set the locale via `TranslocoService`, so `I18nService` was unaware of what locale was set.
Now we set it via `I18nService`, so everything works about as it does in the application.
This actually simplifies things signficantly.
And now we can write stories that rely on `I18nService` and they'll work correctly. I've added an example for `BookChapterChooserComponent` that previously wouldn't have worked correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1896)

Update I18nStoryModule to work with I18nService

---

.editorconfig

Although we use .NET 6.0, if a developer upgrades their .NET 7.0 SDK to version 7.0.304, the shared `dotnet format` will be updated to a version that automatically fixes the warning IDE0270, a warning that was not previously turned on in our .editorconfig.
This Pull Request updates our .editorconfig file to treat this warning as an IDE suggestion, meaning it will not be automatically fixed by `dotnet format`.
Documentation for this warning is non-existent on Microsoft's .NET documentation website at this time, but essentially it modifies `if x == null` checks to a null-coalescing operator.
For example, if IDE0270 is set to "warning", and the developer has the .NET 7.0.304 or higher SDK installed, this code block:
```cs
using ScrText scrText = ScrTextCollection.FindById(username, …
```

Fix support for developers with the .NET SDK 7.0.304 installed

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

When the editor is editable, there is different logic that determines when a user has selected a verse. This is because users can use the keyboard to jump to the next verse, so we cannot rely on click events. This was causing problems because the selection would change when a user clicks on a note icon to open the dialog, but we introduced logic to prevent the current commenter selection from being updated when the note dialog is open.
This change removes that faulty logic so the commenter selection is always up to date. This also adds extra logic to position the note FAB at text load and when the note dialog closes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/19 …

SF-2065 Update the selected verse when user opens a note dialog

---

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge/SIL.XForge.csproj
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Tests/SIL.XForge.Tests.csproj

As the build action is now using the .NET 6.0.410 SDK, this PR updates the .NET dependencies to 6.0.18 to keep these in line with the latest release of .NET 6.0.18 is a [security fix release](https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.18/6.0.18.md#notable-changes).
This PR also updates the following test dependencies to their latest versions:
* coverlet.msbuild
* Microsoft.NET.Test.Sdk
* NUnit3TestAdapter
A successful pre-merge build and test is sufficient to test these changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1914)

Update .NET dependencies and test dependencies

---

src/SIL.XForge.Scripture/Models/ParatextSettings.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This PR updates the WritingSystem.Tag on sync, loading this from the ScrText Project Settings.
This will update the writing system tag when the language code is changed on the Registry, or if WritingSystem.Tag is blank due to a previous bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1904)

SF-2083 Update Project WritingSystem.Tag on Sync

---

src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs
src/SIL.XForge.Scripture/Models/SyncMetrics.cs
src/SIL.XForge.Scripture/Services/IParatextDataHelper.cs
src/SIL.XForge.Scripture/Services/IParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextDataHelper.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Models/ParatextSyncResultsTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
tools/RepoInfo/Program.cs
tools/RepoInfo/RepoInfo.csproj
tools/RepoInfo/RepoInfo.sln

* Ensures that only the books that can be edited in Scripture Forge are updated in the Paratext repository on sync
* Parses the Paratext revisions to see what is changed, and only updates Scripture Forge's data in the areas that received changes
* Adds a RepoInfo tool to explain what has changed in each revision in a Paratext repository
These changes will help improve sync speed for larger projects, with a minimal improvement for small projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1845)

SF-1972 Sync Speed Improvements

---

src/SIL.XForge.Scripture/Controllers/AnonymousController.cs
src/SIL.XForge.Scripture/Controllers/LanguageController.cs
src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
src/SIL.XForge.Scripture/Controllers/ParatextController.cs
src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
src/SIL.XForge.Scripture/Models/Sync.cs
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge.Scripture/Services/ApiDocumentationExtensions.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/Services/SFDblRestClientFactory.cs
src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge.Scripture/Startup.cs
test/SIL.XForge.Scripture.Tests/Controllers/AnonymousControllerTests.cs

This Pull Request creates developer documentation for the Web APIs exposed by Scripture Forge using OpenAPI and Swagger.
Developer documentation is generated from the XML Documentation comments in the C# code. Enabling the generation of XML documentation also required errors in some of the XML CodeDoc comments to be corrected, as well as the return objects for some API endpoints to be strongly typed.
**Acceptance Test**
As this is a developer only feature, it is suitable for a developer to test this feature by visiting http://localhost:5000/swagger/index.html after building and running.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1916)

SF-2093 Add Developer Web API Documentation

---

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

Delete the note thread when the Paratext note has been permanently deleted. This change is to prevent orphaned note thread docs from being present in the mongoDB. However, because of how realtime doc deletion works, the note thread doc never gets completely removed from mongoDB, but will remain as a mostly empty record. See the image below.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1912)

SF-2086 Delete thread doc if all notes removed in Paratext

---

src/RealtimeServer/scriptureforge/models/verse-ref-data.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

Previously, it was assumed that a verse segment would contain only numbers, which we know is not true. This change makes an update so that a verse that contains letters like 6a will correctly be retrieved when getting verse segments that match a particular verseRef. This will ensure that note threads can be embedded on verses with letters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1911)

SF-2087 Show note thread on verses with letters

---

src/RealtimeServer/scriptureforge/models/audio-timing.ts
src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
src/RealtimeServer/scriptureforge/models/text-audio.ts
src/RealtimeServer/scriptureforge/models/text-info.ts
src/RealtimeServer/scriptureforge/realtime-server.ts
src/RealtimeServer/scriptureforge/services/text-audio-migrations.ts
src/RealtimeServer/scriptureforge/services/text-audio-service.spec.ts
src/RealtimeServer/scriptureforge/services/text-audio-service.ts
src/SIL.XForge.Scripture/Models/AudioTiming.cs
src/SIL.XForge.Scripture/Models/Chapter.cs
src/SIL.XForge.Scripture/Models/TextAudio.cs
src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs

* Adds support for a new `text_audio` to ShareDB to store audio timings and references to the MP3 files
* Adds a `hasAudio` flag to the chapter object (`sf_projects.texts[].chapters[].hasAudio`)
* Adds a migrator to set this flag to `false` for every chapter of every project
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1913)

SF-2088 Add model for Scripture Audio

---

src/SIL.XForge.Scripture/Migrator.cs
src/SIL.XForge.Scripture/Models/SyncMetrics.cs
src/SIL.XForge.Scripture/Services/JwtRestClient.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
src/SIL.XForge.Scripture/ViewComponents/FooterViewComponent.cs
src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs
src/SIL.XForge/Realtime/RealtimeService.cs
src/SIL.XForge/Utils/Product.cs

* Adds a new `ProductVersion` property to the `SyncMetrics` class, which is set when the sync starts running
* Centralizes retrieval of the product version in C# to a new `Product.Version` property
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1920)

SF-1991 Record Scripture Forge Version on Sync

---

src/RealtimeServer/scriptureforge/models/text-audio.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-type-registry.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-audio-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts

* register text_audio collection for indexedDB
* add query for text audio in checking component
* add scripture audio component
To get this to work, add the audio MRK_003.wav file to the /var/lib/scriptureforge/audio/<projectId> directory. To test the skip feature, you will need to add timing data. I created the timing data using the Add Timing Data on the checking app, and then manually edited the timing data in mongo. I needed to log out and back in to get the up to date timing data.
TODO: highlight the verse when the audio is playing the verse.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1928)

SF-2106 Add UI for scripture audio component

---

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss

This is a minor change I thought we wouldn't formally test, but I'll leave that call up to the reviewer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1935)

Minor improvements to users page roles paragraph

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs

This PR fixes three cases where the blocking `Dispose()` is called for `IConnection`, instead of the non-blocking `DisposeAsync()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1940)

Fix await using statements for ConnectAsync()

---

src/SIL.XForge/Configuration/RealtimeOptions.cs
src/SIL.XForge/Realtime/Connection.cs
src/SIL.XForge/Realtime/RealtimeService.cs
test/SIL.XForge.Tests/Realtime/ConnectionTests.cs

This PR adds the ability to disable the connection's document cache. This is of importance for Migrators, which will load every document in a collection just once, and not need to retrieve them again.
To enable this feature, add the following line to the Migrator's `Startup` class constructor:
```cs
Configuration["Realtime:DocumentCacheDisabled"] = "true";
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1929)

SF-2120 Add ability to disable the document cache

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts

The comment FAB didn't work right when the target language was RTL if the editor was on the right side of the screen. This change moves the FAB to be 20 pixels inside the left boundary of the editor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1938)

SF-2122 Adjust comment FAB for RTL target language

---

src/SIL.XForge.Scripture/Services/ParatextService.cs

If a Paratext comment has content where the bold or italics style is used, the content does not show correctly in SF. The reason is because we used contentNode.Elements() to get all elements in the content node. However, unformatted text nodes are not elements, so they were excluded. The result is that when a note is created in SF, the content would be missing the unformatted text if the content had mixed styles like bold or italics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1948)

SF-2132 Hotfix: Correctly handle note content with mixed styles

---

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts

I looked into rewriting the Suggestions Settings component, since the current patterns there (which I followed) are outdated. But I opted against this, since I believe it's been refactored in [the Biblical Terms task](https://github.com/sillsdev/web-xforge/pull/1731).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1915)

SF-2098 Suggestions Settings to Material

---

src/SIL.XForge.Scripture/Services/SFProjectService.cs
src/SIL.XForge/Services/ProjectService.cs
test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
test/SIL.XForge.Tests/Services/ProjectServiceTests.cs

The current logic that removes a user from a project crashes if the user has been deleted manually from the database, or if the SFProjectUserConfig is missing.
This Pull Request makes the remove user from project logic more resilient by checking whether the `User` or `SFProjectUserConfig` docs exist before modifying or deleting them.
I also took the opportunity to correct the method signatures of a couple of functions near to the change that my IDE flagged as incorrect.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1949)

SF-2123 Allow incorrectly or partially deleted users to be removed from projects

---

src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
src/SIL.XForge/Services/AudioService.cs
src/SIL.XForge/Services/IAudioService.cs
src/SIL.XForge/Services/ProjectService.cs
test/SIL.XForge.Tests/Services/AudioServiceTests.cs
test/SIL.XForge.Tests/Services/ProjectServiceTests.cs

This PR updates the check to see if an uploaded file is an MP3 to instead of checking for the file extension (which can sometimes be incorrect) to instead check for either presence of ID3 tags, or the MP3 frame header (0xFFE or 0xFFF) at the start of the file (excluding leading null characters).
A check for an null `IFormFile` being uploaded to the UploadAudio endpoint is also added, as uploading a file greater than the limit of 100MB in my tests resulted in this value being null.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1945)

SF-2125 Add stream checking for incoming MP3 data

---

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss

And changed cursor type to better indicate interactivity.
Another option would be to use ng-deep to override the padding of mat-list-item-content, which is causing the issue. This avoids ng-deep.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1950)

SF-2133 Fixed Alignment for Reviewer Questions Panel

---

src/SIL.XForge.Scripture/Controllers/HealthController.cs
src/SIL.XForge.Scripture/Models/HealthCheckComponent.cs
src/SIL.XForge.Scripture/Models/HealthCheckResponse.cs
test/SIL.XForge.Scripture.Tests/Controllers/HealthCheckControllerTests.cs

This Pull Request adds a `/health-check/` endpoint, accessible only from localhost, that can be used with the NodePing Agent. This will enable use to improve monitoring of Scripture Forge.
To test this, use http://localhost:5000/swagger/index.html. No authentication is necessary due to the localhost restriction.
Documentation is available in the document "Health endpoint" in the shared drive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1946)

SF-2129 Add Health Endpoint

---

src/RealtimeServer/scriptureforge/models/translate-config.ts
src/SIL.XForge.Scripture/Models/BaseProject.cs
src/SIL.XForge.Scripture/Models/ParatextSettings.cs
src/SIL.XForge.Scripture/Models/TranslateConfig.cs
src/SIL.XForge.Scripture/Services/ParatextService.cs
src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs

This Pull Request adds the following properties to a Project's `TranslateConfig`:
* `ProjectType` - The project type. This is a string corresponding to the `ProjectType` enum in ParatextData in PascalCase (like the enum's named constants).
* `BaseProject` (nullable) - details of the project the `sf_project` is based on.
* `ParatextId` - The base project's Paratext Id
* `ShortName` - The short name of the base project
This information, which can only be retrieved on sync from the ScrText settings can be used to determine if the Pre-Translation workflow can start.
**Notes**
- ProjectType has been made nullable and is not populated by a migrator because its value can only be retrieved from the ScrText.
- I also have included a minor clean up of the C# class TranslateConfig to use nullable …

SF-2128 Add ProjectType & BaseProject to TranslateConfig

---

test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Tests/SIL.XForge.Tests.csproj

When writing another PR, I noticed that the code coverage calculations were including the test projects, and so complaining that I was not testing them.
This PR adds an assembly attribute to the test projects that force them to be excluded from the code coverage calculations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1962)

Exclude Test Projects from Code Coverage Calculations

---

src/SIL.XForge.Scripture/ClientApp/src/_variables.scss

It's easy to see the difference between the old dark blue and black when they're side by side here, but when you aren't seeing them side by side, the dark blue isn't conveying the message very well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1969)

SF-2149 Make like color lighter

---

src/Help/UpdateHelp/UpdateHelp.csproj
src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
src/SIL.XForge/SIL.XForge.csproj
test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
test/SIL.XForge.Tests/SIL.XForge.Tests.csproj

This Pull Request updates .NET dependencies that can be updated without side effects, after I have tested and run them locally.
**Updates Serval.Client from 0.5.0 to 0.5.1**
Support for the latest Serval fixes.
**Updates .NET Dependencies from 6.0.18 to 6.0.20**
This brings the versions into line with what is used to build SF
**Updates EdjCase.JsonRpc.Router from 5.1.8 to 5.1.9**
A minor update that adds an option to disable compresion if we want to use other connection compression middleware (see https://github.com/edjCase/JsonRpc/releases/tag/5.1.9)
**Updates HtmlAgilityPack from 1.11.46 to to 1.11.50**
A minor bugfix update (see https://github.com/zzzprojects/html-agility-pack/releases)
**Updates IdentityModel from 6.0 to 6.1**
A minor update that fixes bugs and adds nullable …

.NET Dependency Updates

---

scripts/db_tools/package-lock.json
scripts/db_tools/package.json
src/RealtimeServer/package-lock.json
src/RealtimeServer/package.json
src/RealtimeServer/scriptureforge/models/verse-ref-data.ts
src/SIL.XForge.Scripture/ClientApp/package-lock.json
src/SIL.XForge.Scripture/ClientApp/package.json
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts

This PR updates the npm package `@sillsdev/scripture` to the latest version (1.4.0). This update is a requirement for the Biblical Terms feature to be rebased onto master.
This change:
* Updates Scripture Forge to use the correct constructors for `VerseRef`
* Replaces use of the `VerseRef.parse` function with the `VerseRef` constructor
* Replaces the previous Old Testament canon calculation code with `Canon.isBookOT()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1971)

SF-2152 Update to @sillsdev/scripture 1.4.0
