sillsdev/web-xforge

src/SIL.XForge.Scripture/Models/SFProjectResource.cs, src/SIL.XForge.Scripture/Models/SFProjectUserResource.cs, src/SIL.XForge.Scripture/Models/TextResource.cs, src/SIL.XForge/Models/ProjectResource.cs, src/SIL.XForge/Models/UserResource.cs, src/SIL.XForge/Services/ProjectUserService.cs, src/SIL.XForge/Services/RepositoryResourceServiceBase.cs
- call IUpdateBuilder.Set() with correct field type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/7)
=> Fix bug when updating an array property

src/SIL.XForge.Scripture/Models/SFProjectResource.cs, src/SIL.XForge/Models/ProjectResource.cs, src/SIL.XForge/Models/UserResource.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/9)
=> Resource relationships must use a collection interface

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-segmenter.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-styles.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/Services/DeltaUsxExtensions.cs, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/ShareDB/RichText/Delta.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxTestExtensions.cs
- table
- line break
- figure
- milestone
- ref
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/5)
=> Improve USX support

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts
* remove vulnerabilites (except tar)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/6)
=> Security audit - npm

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/answer.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-data.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/json-data.ts
- Can toggle on/off a like for an answer
- Updated Bootstrap to v4.3.1
- Updated JsonData to allow any type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/4)
=> Ability to like an answer

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/SFJsonApiServiceCollectionExtensions.cs, src/SIL.XForge/Realtime/IRealtimeService.cs, src/SIL.XForge/Realtime/RealtimeService.cs, src/SIL.XForge/SIL.XForge.csproj, src/ShareDB/Connection.cs, src/ShareDB/Document.cs, src/ShareDB/IConnection.cs, src/ShareDB/IDocument.cs, src/ShareDB/ShareDB.csproj
- easier to mock
- use Websocket.Client library
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/12)
=> Refactor ShareDB connection to implement an interface

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/json-api.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-data.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-offline-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/15)
=> Add code documentation to realtime classes

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question.ts, src/SIL.XForge.Scripture/Models/SFProjectUserEntity.cs
- Viewing a question will now save in the user project profile that they have read that question
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/13)
=> Mark an answer as read - (SF-286)

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/16)
=> Add code generator command line

src/SIL.XForge.Identity/Controllers/IdentityRpcController.cs, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/my-account.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/my-account.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-user-entry.component.ts, src/SIL.XForge/Models/Site.cs, test/SIL.XForge.Identity.Tests/Controllers/IdentityRpcControllerTests.cs
* Null check for user site.
* Display never logged in when last login date is less than unix time 0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/17)
=> Fix: SF-221 Add site value to user at log in

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/18)
=> Redirect without adding to browser history

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/19)
=> Redirect from a deleted project without adding to history

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-styles.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/20)
=> Add support for "unmatched" embed

src/SIL.XForge.Identity/Controllers/IdentityRpcController.cs, src/SIL.XForge/Controllers/ProjectsRpcController.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Identity.Tests/Controllers/IdentityRpcControllerTests.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
* ignored 3 tests because the MemoryRepository doesn't create dot dereferenced items like mongo does
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/21)
=> Fix Sites key serialization

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/email-invite.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/invite-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/invite-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-data.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-doc.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.ts, src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge.Scripture/Models/CheckingConfig.cs, src/SIL.XForge.Scripture/Models/SFProjectRoles.cs, src/SIL.XForge/Controllers/ProjectsRpcController.cs, src/SIL.XForge/Models/ShareOptions.cs, test/SIL.XForge.Tests/Controllers/ProjectsRpcControllerTests.cs, test/SIL.XForge.Tests/Controllers/TestProjectsRpcController.cs, test/SIL.XForge.Tests/Models/TestCheckingConfig.cs, test/SIL.XForge.Tests/Models/TestProjectEntity.cs, test/SIL.XForge.Tests/Models/TestProjectRoles.cs, test/SIL.XForge.Tests/Models/TestTaskConfig.cs
* Added sf_reviewer role and rights
* Added ProjectAdminRole to ProjectsRpcController
* Added tests to check if project share is enabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/10)
=> SF-220 Finish invite a friend

src/SIL.XForge.Scripture/appsettings.Development.json, src/SIL.XForge.Scripture/appsettings.Staging.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/24)
=> Use same site id for all environments

src/SIL.XForge.Scripture/ClientApp/src/identity/log-in/log-in.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/25)
=> Fix: SF-167 Redirect to referring URI after login

src/SIL.XForge.Identity/Controllers/IdentityRpcController.cs, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user.ts, src/SIL.XForge/Controllers/ProjectsRpcController.cs, src/SIL.XForge/Models/UserEntity.cs, src/SIL.XForge/Models/UserResource.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Identity.Tests/Controllers/IdentityRpcControllerTests.cs, test/SIL.XForge.Tests/Controllers/ProjectsRpcControllerTests.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
* Added tests to confirm EmailMd5 is set when user is created or updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/27)
=> SF-296 Add email md5 and use in the avatar component

src/SIL.XForge.Identity/Services/ExternalAuthenticationService.cs, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/identity/sign-up/sign-up.component.ts, src/SIL.XForge/Models/UserEntity.cs, test/SIL.XForge.Identity.Tests/Services/ExternalAuthenticationServiceTests.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
* Hash email when user uses external login
* Update last login from external login
* Use XFValidator in sign up component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/29)
=> Trim spaces in email to support gravatar email hash

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/paratext-project.ts, src/SIL.XForge.Scripture/Models/ParatextProject.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs
* replace rem with px
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/26)
=> SF-297 Display all projects on connect

src/SIL.XForge/Models/Resource.cs, src/SIL.XForge/Models/UserResource.cs, src/SIL.XForge/Services/ResourceServiceBase.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/30)
=> SF-299 Get UserService to return a partial UserResource

README.md, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-global.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sfdomain-model-config.generated.ts, src/SIL.XForge.Scripture/CodeGenerator/CodeGeneratorApp.cs
- Can add a comment to an answer
- Can edit a comment added on an answer
- Can delete a comment on an answer
- Updated code generator to include CommentData
- Updated readme file in regards to running the code generator from CLI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/28)
=> Comment on answer - (SF-148 & SF-152)

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/32)
=> Fix: SF-303 Update chapter only when changing texts

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts
- Resolved issue for the incorrect avatar and name appearing alongside answers
- Edit/Delete buttons for answers now only appear for the correct owner of the answer
- Updated checking owner spec to remove services not required
- Removed hack no longer required to refresh the avatar thumbnail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/34)
=> Fix: Checking answers

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
* checks verse ref is formatted and in range for project
* disable Add Question button while loading
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/31)
=> SF-267 Validate verse for question

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/35)
=> SF-306 fix connect existing project as non-admin

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/answer.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/comment.ts
- Date Created & Modified added to answers and comments
- Checking owner component updated to deal with UTC date string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/36)
=> Date/time stamp for checking answers & comments (SF-298)

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
- Show maximum of 3 comments per answer before 'show more' button appears
- Only show 2 comments if there are more than 3 comments per answer
- 'Show more' button to show all comments
- Comments are now ordered by the date they were entered with the most recent comment appearing at the bottom
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/37)
=> Show answer comments with 'show more' button (SF-149)

src/SIL.XForge/Controllers/ProjectsRpcController.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/38)
=> Fix: SF-304 Show inviter name in invitation email

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge/Realtime/realtime-server.js
* delete comments and answers properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/42)
=> Fix: SF-307 Insert answers at the beginning of array

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/global.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/email-invite.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/email-invite/email-invite.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
- Re-worked a number of aspects of the checking app to work better across all viewports - more work will need to be done when the final design is agreed upon
- Set the same breakpoints for scss mixins and Flex Layout - NOTE: This is currently in ui-common.module.ts which might want to go somewhere else?
- Adjusted when the main navigation draw is to open/close based on new breakpoints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/41)
=> Ensure all panels work correctly responsively (SF-158)

deploy/vagrant_xenial_gui/Vagrantfile, deploy/virtualbox_xenial_gui_creation/instructions.md, deploy/virtualbox_xenial_gui_creation/xforge-u1604.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/43)
=> SF-294 Clear different modified files. Update release box list

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/45)
=> Hide answers until current user has answered a question (SF-155)

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- Displays all questions across all chapters in a given text
- Summary circle is now based off all questions in a given text
- When changing questions also check and change the current chapter if applicable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/48)
=> Change chapter when clicking previous/next (SF-310)

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/scripture/verse-ref.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/scripture/verse-ref.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
* show verse format message after end reference is touched
* disallow special characters after scripture reference
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/44)
=> Fix: SF-267 Show question dialog errors one at a time

src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/test-headless.sh
Hook to question dialog.
Fix and enhance test runner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/47)
=> SF-199 Add Scripture chooser dialog

scripts/build-and-upload-beta.sh, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/appsettings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/60)
=> Setup Auth0 for live deployment

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
* fix error: Argument of type 'AbstractControl' is not assignable to parameter of type 'FormControl'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/61)
=> Fix production build error

src/SIL.XForge.Scripture/appsettings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/63)
=> Update realtime port for production

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/answer.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/like.ts, src/SIL.XForge.Scripture/Models/SFDomain.cs, src/SIL.XForge.Scripture/Models/SFProjectRoles.cs, src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs, src/SIL.XForge/Realtime/realtime-server.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/62)
=> Add Like model for Answers

scripts/build-and-upload-beta.sh
* seems the ng build optimizer includes the constant value internally
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/67)
=> Fix Angular build number

src/SIL.XForge.Scripture/Views/Shared/Home.cshtml
* simplify footer copyright and terms
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/69)
=> Fix home version to 3 digits

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-global.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- Unread answers/comments display a coloured background for 10 seconds
- Notification on questions panel reduces after 2 seconds
- Comments hidden by the show more button are only read once that button is clicked
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/71)
=> Mark answers and comments as being read (SF-309)

.github/FUNDING.yml
Add Give Direct funding URL taken from software.sil.org
This change will put a shiny new 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/72)
=> Create FUNDING.yml and enable sponsor button

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xfvalidators.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xfvalidators.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/56)
=> SF-324 Disallow just whitespace questions,answers,comments

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/73)
=> Update TC build location

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/74)
=> Fix: SF-311 Default scripture panel to half the screen size

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/77)
=> Disable end-reference if start-reference is invalid

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge.Scripture/Services/SyncJobManager.cs, src/SIL.XForge.Scripture/Services/SyncJobService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/79)
=> Only train suggestion engine on project creation

src/SIL.XForge/Controllers/UsersRpcController.cs, test/SIL.XForge.Tests/Controllers/UsersRpcControllerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/75)
=> SF-346 Extract account name from non-social Auth0 user

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/88)
=> SF-353: Translate overview displays books without a source

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json
* fix some npm vulnerabilities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/92)
=> security: upgrade npm@6.9.2

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/94)
=> SF-356: Pasting string w/ new lines corrupts text

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb/xforge-indexeddb-bucket.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb/xforge-indexeddb-source.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/jsonapi/xforge-jsonapi-source.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/domain-model.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/my-account/my-account.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/orbit-service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-offline-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/93)
=> Clear local data on log out

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
* convert rem to px
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/95)
=> SF-330 Question no wrap with ellipsis

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/97)
=> SF-360 fix SA Projects controls layout

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/98)
=> SF-362: Error when editing text with no paragraphs

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sync-job.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, src/SIL.XForge.Scripture/Models/SyncJobEntity.cs, src/SIL.XForge.Scripture/Services/MutexAttribute.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge.Scripture/Services/SyncJobManager.cs, src/SIL.XForge.Scripture/Services/SyncJobService.cs, src/SIL.XForge.Scripture/Startup.cs, src/SIL.XForge/DataAccess/DataAccessApplicationBuilderExtensions.cs, src/SIL.XForge/DataAccess/DataAccessClassMap.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
- new sync jobs are now enqueued if there is an active sync job
- continuously poll for an active sync job in sync component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/96)
=> SF-264: Fix sync cancellation

.vscode/launch.json, .vscode/tasks.json, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/104)
=> Launch .NET Core debugging without npm start

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/help-hero.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
* isolate my changes
* add HeloHero and tour flow control
* relocate HelpHero code properly
* properly reorganize code
* organizational changes and ensure authenticated users never repeat a tour
* put HelpHero types into a module
* alphabetize imports
* change unnecessary lets to consts
* implement fix for using the actual helphero node module
* fix lint
* Add semi-typings
* fix indent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/108)
=> add HelpHero tour flow control

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/answer.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/comment.ts, src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/Models/Answer.cs, src/SIL.XForge.Scripture/Models/Comment.cs, src/SIL.XForge.Scripture/Models/SFProjectEntity.cs, src/SIL.XForge.Scripture/Models/SyncUser.cs, src/SIL.XForge.Scripture/Models/TextInfo.cs, src/SIL.XForge.Scripture/Models/VerseRefData.cs, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/IDeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs, src/SIL.XForge.Scripture/Services/IParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs, src/SIL.XForge/Realtime/Json0/Json0Op.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/102)
=> Sync answers and comments to Paratext

test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/110)
=> Fix TextType

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json
* fix all vulnerabilities in ClientApp/package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/111)
=> security: update to npm@6.10.1

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sfproject-roles.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sfproject.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/mock-avatar.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/mock-avatar.module.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/users.component.html, src/SIL.XForge.Scripture/Models/SFProjectRoles.cs, src/SIL.XForge.Scripture/Services/SFProjectUserService.cs, src/SIL.XForge/Services/IProjectUserFilter.cs, src/SIL.XForge/Services/ProjectService.cs, src/SIL.XForge/Services/ProjectUserService.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectUserServiceTests.cs, test/SIL.XForge.Tests/Services/TestProjectUserService.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/105)
=> SF-202 add Users list

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/116)
=> SF-361 fix copying share link in Firefox

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/json-realtime-doc.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/115)
=> Refactor updating JSON0 real-time docs

src/SIL.XForge.Scripture/ClientApp/package-lock.json
* fix vulnerabilities after recent dependency additions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/118)
=> Security: update lodash

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
- Attaching an audio file will disregard any recorded answer
- Recording an answer will disregard any uploaded audio file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/123)
=> Upload an audio file to an answer (SF-351)

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
* also move edit button to the left since the data is right -aligned
* reorder help menu to match user menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/125)
=> SF-386 no wrap on user's name

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-control.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-control.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-control.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
* extract controls from share dialog into its own component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/126)
=> SF-349 project admin sharing

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/130)
=> SF-389 May not remove yourself from the project

README.md
* works for Windows or any OS
* note the audio folder is in its intended location rather than its current one
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/129)
=> Add Manual Setup to README

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
* load all comments of a book rather than for a chapter
* also fixes SF-332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/127)
=> SF-354 Show unread badge when see other responses enabled

src/SIL.XForge.Scripture/ClientApp/monitor-test-headless.sh, src/SIL.XForge.Scripture/ClientApp/test-headless.sh
* Improve output coloring to more quickly spot significant files and
notice whether a job has completed.
* Improve aesthetic and display by using less indentation, icons, and
more control over coloring.
* More specific matching of error messages.
* More useful kill message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/134)
=> Improve test-runner output

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
- Fix: Audio player now takes up full width of the answering panel
- Fix: Swapped the total duration a current time elements around on the audio player
- Fix: New question now shows the `Try Again` button after a recorded message
- New: Additional unit tests to ensure the correct buttons appear for recording or uploading
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/136)
=> Fixes to new audio combined component for checking app

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
* checking progress doughnut links to the overview page and vice versa
* add progress doughnuts for each book and overall
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/135)
=> SF-369a Reviewer Overview

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
* fix private property referred to in HTML
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/137)
=> Fix production build

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
* add the 4 Checking overview stat panels
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/138)
=> SF-369b Add overview stat panels

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-control.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-control.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share.component.spec.ts, src/SIL.XForge/Controllers/ProjectsRpcController.cs, test/SIL.XForge.Tests/Controllers/ProjectsRpcControllerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/133)
=> SF-345 Handle re-invites and already-members

src/SIL.XForge/Controllers/ProjectsController.cs, src/SIL.XForge/Controllers/UsersController.cs
- remove ApiController attribute from upload controllers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/147)
=> Fix audio upload

src/SIL.XForge/Services/ProjectService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/139)
=> SF-345 Revise email wording to explain signup; make link

src/SIL.XForge/Controllers/UsersRpcController.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/149)
=> Fix error when Auth0 calls webhook

src/SIL.XForge/Controllers/UsersRpcController.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/150)
=> Always use ResourceId instead of UserId in UsersRpcController

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question.ts, src/SIL.XForge.Scripture/Models/Question.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/140)
=> SF-370 Add archive question feature

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/answer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/142)
=> Ability to select a scripture range with an answer (SF-153)

deploy/dependencies.yml
Using `install || update` to handle both cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/143)
=> Ansible: Install reportgenerator. Don't falsely report npm prefix change

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
- Fix: Saving an answer while recording an audio clip will now stop the recording and then save
- Fix: Saving a question while recording an audio clip will now stop the recording and then save
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/148)
=> Audio recording saving when recording stop button hasn't been used (SF-396)

src/SIL.XForge.Scripture/Models/Answer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/156)
=> Updated Audio model for the backend to include the new ScriptureText field

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/share/share-control.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/155)
=> Do not crash if click Send invite twice

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/data-loading-component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.ts
- add DataComponent abstract base class
- fix project and user searching in system admin components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/157)
=> Handle loading status for multiple components

README.md, deploy/dependencies.yml, src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge.Scripture/appsettings.json, src/SIL.XForge/Configuration/AudioOptions.cs, src/SIL.XForge/Configuration/ConfigurationServiceCollectionExtensions.cs, src/SIL.XForge/Services/IProjectService.cs, src/SIL.XForge/Services/ProjectService.cs, src/SIL.XForge/Utils/AudioUtils.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, test/SIL.XForge.Tests/Services/ProjectServiceTests.cs, test/SIL.XForge.Tests/Services/TestProjectService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/128)
=> SF-352 Convert audio files to mp3

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
* move questions and comments previously used exclusively for the Reviewer tests into the main tests (now the numbers make sense again)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/158)
=> SF-369c Fully incorporate reviewer unit tests

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/162)
=> Fix sync component displaying wrong sync result

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
* show message if there are no published questions
* show message if there are no archived questions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/159)
=> SF-416 Show no question messages

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/160)
=> SF-410 Add download option to question audio

src/SIL.XForge.Scripture/Models/Question.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/164)
=> Fix failing Sync

src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge/Services/ProjectService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/166)
=> SF-412 Allow undefined project role parameter

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/161)
=> SF-403 Fix deleting answer in the wrong question doc

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/163)
=> SF-336 Allow changing scripture book and chapter reference

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
* instead of setting up a new one which would need to change once this was no longer beta.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/167)
=> Use existing issues email

deploy/dependencies.yml
* remove libmp3lame0 (is a dependency of ffmpeg)
* change to list instead of array
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/170)
=> refactor ffmpeg dependencies

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/165)
=> SF-404 Update read elements after reviewer answers question

src/SIL.XForge/Services/ProjectService.cs, test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/169)
=> SF-424 Allow non-project admin to invite on shared projects

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/168)
=> SF-402 Respond to remote questions and comments added

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge/Services/ProjectService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/175)
=> SF-418: Share link doesn't work when user already logged in

src/SIL.XForge/Models/ProjectSecret.cs, src/SIL.XForge/Models/ShareKey.cs, src/SIL.XForge/Services/ProjectService.cs, test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
- encoding emails are no longer necessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/176)
=> Refactor ShareKeys into a collection

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
* limit max width on large viewports
* indent Based On select to align
* fix share radio buttons on small viewport
* not fixed: the open select when scrolling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/177)
=> SF-283 Fix Settings layout

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sfproject.ts, src/SIL.XForge.Scripture/Models/SFProject.cs, src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/179)
=> SF-422 Remove download audio files in Settings

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/181)
=> SF-391 Message when saving before recording is stopped

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.html
* SF-400 Upload audio file
* SF-411 Republish icon
* SF-417 Select scripture in answer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/182)
=> Correct mobile view problems for checking

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/186)
=> SF-432 Warn on editing a question with answers

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-deleted-dialog/project-deleted-dialog.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/183)
=> SF-383 Respond to removed from project in realtime

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/187)
=> SF-431 Add helps page to the help menu

src/RealtimeServer/common/services/project-data-service.ts, src/RealtimeServer/scriptureforge/services/comment-list-service.ts, src/RealtimeServer/scriptureforge/services/question-list-service.ts, src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/192)
=> SF-445: Permission denied when adding an answer

src/RealtimeServer/common/models/site.ts, src/RealtimeServer/common/services/user-service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge/Models/Site.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/193)
=> SF-446: Remove last login property

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/typings.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/194)
=> SF-438, SF-439: Add key bindings for navigating segments

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
* The previous address still works but the new one properly records the reporter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/195)
=> Update issues email

src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs, src/SIL.XForge/Services/ProjectService.cs, src/SIL.XForge/Utils/StringUtils.cs, test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/191)
=> SF-405: Security risk uploading audio file

src/RealtimeServer/common/models/user.ts, src/RealtimeServer/common/services/doc-service.ts, src/RealtimeServer/common/services/json-doc-service.ts, src/RealtimeServer/common/services/project-data-service.ts, src/RealtimeServer/common/services/user-service.ts, src/RealtimeServer/common/utils.ts, src/RealtimeServer/scriptureforge/models/comment-list.ts, src/RealtimeServer/scriptureforge/models/question-list.ts, src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts, src/RealtimeServer/scriptureforge/models/sf-project.ts, src/RealtimeServer/scriptureforge/models/text-data.ts, src/RealtimeServer/scriptureforge/services/comment-list-service.ts, src/RealtimeServer/scriptureforge/services/question-list-service.ts, src/RealtimeServer/scriptureforge/services/sf-project-service.ts, src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts, src/RealtimeServer/scriptureforge/services/text-service.ts, src/RealtimeServer/typings/sharedb/lib/common.d.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- delete comments as a side-effect of deleting an answer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/197)
=> SF-322: Error when deleting answer with comments

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/190)
=> SF-419 Allow user to add an audio question with no text

src/SIL.XForge.Scripture/ClientApp/angular.json, src/SIL.XForge.Scripture/ClientApp/src/index.prod.html, src/SIL.XForge.Scripture/Views/Shared/_Layout.cshtml
* add for static Razor pages
* add for Angular
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/198)
=> SF-434 Add Google Analytics for live

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
This is the first part of a fix for SF-421. The second part is #200.
When switching from one question to another, the audio now stops playing.
Integration tests are passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/199)
=> Pause audio when switching questions

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/204)
=> SF-442 Get comment index from comment list doc

src/RealtimeServer/scriptureforge/services/question-list-service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/json-realtime-doc.ts
- update individual properties instead of replacing whole object
- fix equality checking in Json0OpBuilder
- delete all comments when a question is deleted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/206)
=> SF-451: Comments are deleted when answer is updated

src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge.Scripture/Services/ISFProjectService.cs, src/SIL.XForge.Scripture/Services/MachineAuthorizationHandler.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge/Controllers/RpcControllerBase.cs, src/SIL.XForge/Controllers/UsersRpcController.cs, src/SIL.XForge/Services/IProjectService.cs, src/SIL.XForge/Services/IUserAccessor.cs, src/SIL.XForge/Services/IUserService.cs, src/SIL.XForge/Services/ProjectService.cs, src/SIL.XForge/Services/UserAccessor.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/207)
=> Perform system permission checks in services

src/SIL.XForge.Scripture/Services/IParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
- update roles during sync
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/211)
=> SF-454: Project role not updated when changed in PT

src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/212)
=> SF-437: Scripture text not included in synced note

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
* User enters a valid start scripture reference
* The scripture box will load the chapter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/201)
=> SF-447 Display scripture passage on question dialog

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/scripture-utils/verse-ref-data-converters.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/214)
=> Unset unused properties in question/answer models

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.ts, src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge/Services/IProjectService.cs, src/SIL.XForge/Services/ProjectService.cs, test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs, test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
Add endpoints 'invitedUsers', 'uninviteUser'.
Show invitees in collaborators user list.
Hook up Cancel invite button.
---
There is still more in progress for SF-359, but this is a working initial chunk that can be reviewed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/210)
=> SF-359 Show invitees in user list. Handle canceling invitation

src/RealtimeServer/scriptureforge/models/sf-project.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge.Scripture/Models/SFProject.cs, src/SIL.XForge.Scripture/Models/SFProjectSettings.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
- add sourceName property to SFProject
- sort projects in ConnectProjectComponent and SettingsComponent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/216)
=> SF-263: Display source project even if user is not a member

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
* added audio icon to archived questions
* changed audio icon to headset
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/215)
=> SF-456 audio icon for archived Qs

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfadmin-auth.guard.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/217)
=> SF-448: "Cannot read property 'userRoles' of undefined"

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/213)
=> SF-443 Update answers read when editing an answer

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
* Part of SF-447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/218)
=> Fix console error on editing questions

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/221)
=> Land on getting started page when selecting help

src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, src/RealtimeServer/scriptureforge/models/sf-project-role.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts, src/SIL.XForge.Scripture/Models/SFProjectRole.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/223)
=> SF-463: Create community checker role

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/MachineAuthorizationHandler.cs, src/SIL.XForge/Services/IProjectService.cs, src/SIL.XForge/Services/ProjectService.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/226)
=> SF-462: Add read-only mode for observer/reviewer roles

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
* SF-455 disable player when audio is removed
* SF-459 notify user that recording has stopped
* SF-273 full width connect projects menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/219)
=> UI improvements

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/230)
=> SF-468: Editor doesn't fill horizontally on mobile

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/228)
=> SF-398 Layout checking overview on mobile

README.md
To help get going with vagrant machine after recent changes have been
needed to the dev environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/236)
=> Add post-provision steps to readme

src/SIL.XForge.Scripture/Services/ParatextService.cs
* switch to using "identification_name" instead of legacy "identification_systemId.fullname"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/242)
=> SF-487 Fix PT project name null

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/229)
=> SF-273 Set validator on project select on form submit

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/246)
=> SF-488: Suggestions still showing when disabled

src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/247)
=> SF-491: Training fails when book has no source

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
* if a user has been remove in PT then remove the user in SF on sync (instead of making them a Reviewer)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/245)
=> SF-483 Remove users on sync

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/users/collaborators/collaborators.component.ts
- Collaborators can now be filtered by email, so you can search for an invitee by email address
- Filter is now case-sensitive
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/251)
=> Make collaborators user filter case-insensitive and include email

src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/256)
=> SF-481b Add copyright to static footer

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss
- Fixes issue with the text panel and the question panel forcing the navigation bar off the viewport
- Updated question dialog to implement the checking text panel in a way that doesn't affect the checking app
- Fixed up various typing issues with recent change over to QuestionDoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/253)
=> Scrolling layout issues introduced to the checking app (SF-501)

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/249)
=> SF-359 Remove sa-user invitee handling, Refactor

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/250)
=> SF-359 Refresh user list after invites and uninvites

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/260)
=> SF-470 Comments marked as read in real-time

src/RealtimeServer/common/models/site.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/local-settings.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts, src/SIL.XForge/Models/Site.cs, src/SIL.XForge/Services/ProjectService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/262)
=> SF-511: Store last selected project locally

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/Services/ParatextService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/263)
=> Sort PT projects on backend

src/RealtimeServer/common/connect-session.ts, src/RealtimeServer/common/index.ts, src/RealtimeServer/common/realtime-server.ts, src/SIL.XForge.Scripture/Services/ISyncService.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge.Scripture/Services/SyncService.cs, src/SIL.XForge/Realtime/Connection.cs, src/SIL.XForge/Realtime/IRealtimeService.cs, src/SIL.XForge/Realtime/MemoryRealtimeService.cs, src/SIL.XForge/Realtime/RealtimeServer.cs, src/SIL.XForge/Realtime/RealtimeService.cs, src/SIL.XForge/Services/ProjectService.cs, src/SIL.XForge/Services/UserService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/267)
=> SF-514: Store user id for a real-time op

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/264)
=> SF-503 Disable duplicate comment forms when editing comments

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-styles.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- display first verse number in paragraph inside of para-contents
- fix verse number background getting cut off at beginning of line
- fix incorrect box-shadow when switching from checking component to
editor component
- fix right arrow navigation at end of a segment
- fix SF-516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/270)
=> Fix various issues in editor component

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts, src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge/Controllers/RpcControllerBase.cs
- added generic message dialog to NoticeService
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/271)
=> SF-476, SF-520: Handle invalid share URL

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
* Bugsnag is not properly packaged so we can't use it's types in production.
* Add a error reporting service so it can be injected and mocked for the exception handling service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/272)
=> SF-523 Refactor Bugsnag for production build

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/275)
=> SF-522: Use MDC typography for editor

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
PR #274 was mistakenly merged before tests were fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/276)
=> Fix broken tests that were merged in #274

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/261)
=> SF-498 Limit answer Scripture reference to question chapter 

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
* Also fixes SF-521
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/277)
=> SF-518 Show end reference error when editing a question

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/282)
=> Fix various paging issues on the collaborators component (SF-519)

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts, src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge/Controllers/RpcControllerBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/284)
=> SF-499: Error when user removed from project

src/SIL.XForge.Scripture/Services/SFProjectService.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/283)
=> SF-534 Make share project link with key always valid

src/RealtimeServer/common/services/project-data-service.ts, src/RealtimeServer/common/utils.ts, src/RealtimeServer/scriptureforge/services/question-service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/287)
=> SF-515: Remove id from "read" arrays in SFProjectUserConfig when object deleted

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
- Added new item to navigation drawer for All Questions
- When changing the chapter in the All Questions view the scripture dialog will now appear
- Amended scripture chooser dialog to allow for verse selection to be optional
- Project route will now automatically load the All Questions route on first load
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/266)
=> Show all questions across all books in the navigation drawer (SF-328)

src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/typings/arraydiff.d.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/query-parameters.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/288)
=> Query for question count in AppComponent

README.md
* add frontend TC report
* update README online badges
* identify code coverage badge as C# only
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/289)
=> Update TC code coverage

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/291)
=> SF-518 Different book error shows when editing scripture start

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/293)
=> Fix IndexOutOfRangeException in ParatextSyncRunner

src/RealtimeServer/common/models/project-rights.ts, src/RealtimeServer/common/models/project-role.ts, src/RealtimeServer/common/services/project-data-service.ts, src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, src/RealtimeServer/scriptureforge/models/sf-project-role.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-role-info.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/296)
=> SF-477: Observer should not be able to answer questions

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/297)
=> SF-495 can't like your own answer

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/280)
=> SF-467 Show scripture reference error in answer form

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
Liked | Not liked
-----|-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/301)
=> Highlight like button if user has liked answer

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/294)
=> SF-543: Doesn't load empty book

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/anchorable.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
- Fixed bug where question icon was showing for the same verse but on the wrong chapter/book when in All Questions mode
- Fixing typings that passed `QuestionDoc` even though it was expecting `Anchorable`
- Reset highlights and question icon if questions are removed while other questions are still visible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/292)
=> All questions shows question icon from other books (SF-546)

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-offline-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts
- update real-time queries locally
- update all test fixtures to use TestRealtimeService
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/302)
=> SF-562: Drawer not updated right away when question added

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/303)
=> Fix doc create so it works offline

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/295)
=> SF-492 update PT9 instructions, SF529 comment notifications

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/305)
=> SF-567: No questions shown when user logs in

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/306)
=> Use ng-bullet to speed up tests

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
* Fix in this area for the problem reported in SF-556
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/309)
=> Disable End Reference on load in Answer panel

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
* Also prevent end reference from going invalid immediately
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/310)
=> SF-557 Do not throw error when end reference invalid

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/308)
=> Simplify setup of test fixtures

src/SIL.XForge.Scripture/ClientApp/src/tsconfig.app.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/314)
=> Exclude compiling test classes in app build

src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
- use Injector to get dependencies
- set provider to "useClass" instead of "useExisting"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/315)
=> Correctly setup DI for ExceptionHandlingService

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/316)
=> SF-565: Invalid verse ref when start and end mismatch only by case

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/312)
=> SF-558: Unable to navigate the "all questions" page

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/317)
=> SF-568: Null reference exception when text contains a char style

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/318)
=> SF-570: Settings page not aligned properly on mobile view port

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
* TODO add tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/307)
=> SF-564 use rights when liking an answer

src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/319)
=> SF-573 Project admins can edit owned comments and answers only

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/320)
=> Clear scripture highlight for Add Question if a bad reference is typed

src/RealtimeServer/scriptureforge/scripture-utils/verse-ref.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/321)
=> SF-565 Handle insignificant zeros in scripture verses

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/322)
=> SF-575 Fix unread badge glitch

.vscode/launch.json, .vscode/tasks.json, README.md, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/karma.conf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/326)
=> Add VS Code launch configuration to debug Angular tests

.vscode/extensions.json, .vscode/launch.json, .vscode/settings.json
* so everyone can use the Angular Karma Test Explorer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/329)
=> Add Karma Test Explorer settings

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/328)
=> SF-598 Hide like icon if see other user responses is disabled

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/327)
=> Add issue email body template

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/332)
=> SF-607: Sync can incorrectly delete PT book data

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/337)
=> Fix incorrect editor height when switching texts

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/330)
=> SF-600 Do not enable translate task when user role is undefined

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
After attempting to refactor handling question creation into a utils class, it became clear that it would be complicated, so I chose to handle question creation separately in the checking component and the existing implementation in checking overview component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/335)
=> SF-604 Add question button to scripture panel

.vscode/settings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/339)
=> Enable source maps to show .ts files in stack trace from test explorer

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/338)
=> Ensure that query results are updated before ready

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/341)
=> Clear current project id when no longer valid

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/340)
=> SF-595 Fix select overflow on connect project page

src/RealtimeServer/common/connect-session.ts, src/RealtimeServer/common/realtime-server.spec.ts, src/RealtimeServer/common/realtime-server.ts
- do not cache project roles in user session
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/344)
=> SF-603: Incorrect permissions when project role changed in PT

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/local-settings.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/346)
=> SF-609: Error handling StorageEvent with an empty string value

src/SIL.XForge.Scripture/ClientApp/tslint.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/347)
=> Fix codelyzer lint rules

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/349)
=> Add realtimePort to production/staging environments

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Before | After
-------|------
Loading view:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/350)
=> SF-606 Auto scroll to verse in question dialog

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/351)
=> Check for null in write-status.component.html

NuGet.config, src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge/SIL.XForge.csproj, xForge.sln
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/353)
=> Update to release version of Machine

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/Services/ParatextService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/361)
=> Disable normalizing all text to NFC in Quill

src/SIL.XForge.Scripture/Pages/Index.cshtml
- avoids AntiforgeryValidationException
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/362)
=> Disable anti-forgery protection in Index.cshtml

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/usx-styles.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/364)
=> Fix USX styles

src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/365)
=> Navigate to a project when it is added remotely in StartComponent

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
- do not add blanks for a blank line
- remove blanks at the beginning of an implicit paragraph
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/372)
=> Handle blank line in TextViewModel

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- Added check for book usage when remote changes are made to the project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/369)
=> List of books does not automatically update (SF-623)

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/373)
=> SF-613 Move add question button left on scripture panel

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/374)
=> SF-586 and SF-587 Allow submitting form with enter button

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/375)
=> SF-580 Display message when like answer is disallowed

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
This will add the functionality to add a edit or archive a question in context. Part 2 will most likely come to refactor the handling of the response from the question dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/360)
=> SF-622 Edit or archive questions in question context

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/IDeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/378)
=> Handle multiple book elements in USX

src/SIL.XForge.Scripture/Pages/Index.cshtml
* revert 17e88b55913889c94ee4eda1b4a09722f06ca600
* this fix was added to prevent errors in logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/383)
=> Revert antiforgery fix

src/SIL.XForge.Scripture/Pages/Index.cshtml, src/SIL.XForge.Scripture/Pages/Index.cshtml.cs
* also add environment to subject for JIRA differentiation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/384)
=> SF-645 disable anti-forgery protection again

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/381)
=> SF-626 Fix mobile view checking app area cut off

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/380)
=> SF-628 Encode commas in email template

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/385)
=> SF-533 Add cancel button to edit name dialog

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/387)
=> SF-618 Display message when microphone access is denied

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/389)
=> Fix email input box in share component

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
* Remove unused method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/388)
=> SF-597 Only allow project admins to create and edit questions

README.md, src/RealtimeServer/scriptureforge/models/text-info.ts, src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts, src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/Models/Chapter.cs, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge.Scripture/Services/DeltaUsxExtensions.cs, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/IDeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, src/SIL.XForge.Scripture/usx-sf.rnc, src/SIL.XForge.Scripture/usx-sf.xsd, src/SIL.XForge.Scripture/usx.rnc, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxTestExtensions.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
- validate using modified USX schema
- add "isValid" property to Chapter model
- add data migration for model change
- display invalid chapters as read-only in editor
- highlight invalid portions of chapter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/386)
=> Validate USX from PT Data Access API

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
- logout if renewing access token fails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/390)
=> SF-631: Error when renewing access token

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-global-vars.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
* style a badge next to the question icon to indicate
* the number of questions only if there are more than one
* adds data question count attribute to qu
ill
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/392)
=> SF-591 Add number badge to question icon

src/SIL.XForge.Scripture/Pages/Index.cshtml, src/SIL.XForge.Scripture/Pages/Index.cshtml.cs, src/SIL.XForge.Scripture/Resources/Pages.Index.resx, src/SIL.XForge.Scripture/SharedResource.cs, src/SIL.XForge.Scripture/Startup.cs
* Enable view and data validation localization
* Use .resx file for all strings related to Index.cshtml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/401)
=> Internationalize the landing page [SF-667]

src/SIL.XForge.Scripture/ClientApp/src/_text.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- use same style to highlight in editor and checking components
- underline question segments
- refactor highlight formats
- simplify CheckingTextComponent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/407)
=> Make highlighting more consistent across tools

test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/405)
=> Update the test package reference to use the latest 2.1

src/SIL.XForge.Scripture/Pages/Index.cshtml, src/SIL.XForge.Scripture/Pages/Index.cshtml.cs, src/SIL.XForge.Scripture/Pages/RegisterSuccess.cshtml, src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml, src/SIL.XForge.Scripture/Resources/Pages.RegisterSuccess.resx, src/SIL.XForge.Scripture/SharedResource.cs
* internationalized RegisterSuccess
* internationalized footer link names
* set lower bound on test package reference
* allow any non whitespace full name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/406)
=> SF-667 RegisterSuccess page i18n

src/SIL.XForge.Scripture/ClientApp/src/_text.scss, src/SIL.XForge.Scripture/ClientApp/src/_usx.scss, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
- use percentages for indents
- improve translate tool UI on XS devices
- fix handling of initial blanks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/411)
=> Adjust indents according to editor width

deploy/dependencies.yml, scripts/build-and-upload-beta.sh
* installed dotnet-sdk-3.0 on TC
* update Ansible deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/412)
=> Fix TC build after dotnet upgrade

src/RealtimeServer/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
* waiting on sharedb-mongo to fix mongodb dependency
* waiting on npm to fix vulnerabilities
* also removed unused import
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/413)
=> fix some npm vulnerabilities

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
To avoid a bunch of not relevant remoteChanges$ subscriptions building
up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/417)
=> SF-617 Unsubscribe from previous question before subscribing to new one

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/416)
=> SF-670 Disable link sharing if checking is disabled

src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/419)
=> Fix flickering on translate overview view during sync

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/421)
=> SF-672 Enable or disable share button in real-time

src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/Models/SFProjectUserConfig.cs
* Stores the questionDoc of the most recent answered question
* Activates the stored questionDoc when going to the checking app
* Rename My projects option to Project Home
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/415)
=> SF-552 Save last active question in checking app

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/main.ts, src/SIL.XForge.Scripture/ClientApp/src/test.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
- replace "bson" with "bson-objectid"
- remove "moment" (only used by certain graphs in chart.js)
- remove "hammerjs" (only used by certain controls in Angular Material)
- added scripts to analyze bundle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/425)
=> Reduce size of bundle

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/427)
=> SF-691 Sort questions from oldest to newest

src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.scss
Description | Before | After
-------------|-------|------
Chapter select | ![Screen Shot 2019-11-19 at 22 58 39](https://user-images.githubusercontent.com/6140710/69208134-76e80e80-0b20-11ea-8b8f-bc947cc1d60e.png) | ![Screen Shot 2019-11-19 at 22 57 19](https://user-images.githubusercontent.com/6140710/69208140-7c455900-0b20-11ea-9097-14dc0704f367.png)
Menu item in chapter select | ![Screen Shot 2019-11-19 at 22 58 24](https://user-images.githubusercontent.com/6140710/69208144-823b3a00-0b20-11ea-98ae-8e1d127e2a00.png) | ![Screen Shot 2019-11-19 at 22 57 46](https://user-images.githubusercontent.com/6140710/69208147-86675780-0b20-11ea-8af6-c2d5e2585d64.png)
--- …
=> Fix styling of chapter nav component's select

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/430)
=> SF-663 Show newly added questions without full refresh

src/SIL.XForge.Scripture/Pages/Index.cshtml.cs, src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/439)
=> SF-536 Add Bugsnag to static pages

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts
Add tests for showing the share button to project admins even when sharing is disabled. This should have been in 0bdafcacaab7730bb6b13f3cd3f0d9499d9221ae.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/441)
=> SF-671 Add test for always showing share button to project admins

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/autofocus.directive.ts
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/442)
=> Change question answer field to textarea

src/RealtimeServer/common/index.ts, src/RealtimeServer/package-lock.json, src/RealtimeServer/package.json, src/RealtimeServer/tsconfig.json, src/RealtimeServer/typings/sharedb-mongo.d.ts, src/SIL.XForge.Scripture/ClientApp/package-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/448)
=> Update real-time server to use mongo 3 driver

src/SIL.XForge.Scripture/Controllers/LanguageController.cs, src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml, src/SIL.XForge.Scripture/Pages/Shared/_SelectLanguagePartial.cshtml, src/SIL.XForge.Scripture/Resources/Pages.Index.az.resx, src/SIL.XForge.Scripture/Resources/Pages.RegisterSuccess.az.resx, src/SIL.XForge.Scripture/Resources/SharedResource.az.resx, src/SIL.XForge.Scripture/SharedResource.cs, src/SIL.XForge.Scripture/Startup.cs
* Support language switching
* Add Azerbaijani localization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/447)
=> Localize backend into Azerbaijani 

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
Previously the active question was not saved when clicking on a book in the side bar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/450)
=> SF-552 Store question in checking app when clicking on book

src/RealtimeServer/package-lock.json, src/RealtimeServer/package.json, src/SIL.XForge.Scripture/ClientApp/package-lock.json
* Needed for running backend.
* Based on a larger fix Ira had demonstrated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/449)
=> Reintroduce mongodb-core

src/RealtimeServer/package-lock.json, src/RealtimeServer/package.json, src/SIL.XForge.Scripture/ClientApp/package-lock.json
This reverts commit 439ef5ea11046d942f64c07591ec10e0368c92ab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/452)
=> Revert "Reintroduce mongodb-core (#449)"

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
* This prevents community checkers with an account linked to pt being removed from
* a project after the project is synced
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/454)
=> SF-690 Do not remove community checker pt users from project

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
I *think* this finishes internationalizing all strings that are visible to community checkers, except error messages and the canon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/453)
=> Finish internationalizing community checking

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/456)
=> SF-705 List books in sidebar in canonical order

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
I missed a couple strings in my latest PR because I was looking mainly at templates. I've likely missed others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/457)
=> Internationalize rest of snackbar notifications for community checkers

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/462)
=> Internationalize checking app for admin users

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
Here's how it looked previously (note that it shows that verses 1-3 are selected):
Only white space is selected in the first verse, so it shouldn't count. And zero characters are selected in the third verse, so it shouldn't count (this is accomplished by selecting into verse three, and then working back to the very beginning of verse three).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/460)
=> SF-698 Show correct verse numbers when selecting text

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.module.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
- remove dependency on ng2-charts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/463)
=> Add donut chart component

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
* corresponding change in Auth0 pre-selects the passed language
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/464)
=> SF-666 pass selected language to Auth0

src/RealtimeServer/common/models/user.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts, src/SIL.XForge/Models/User.cs, src/SIL.XForge/Services/UserService.cs
* update cookie and UI locale from Auth0
* has a corresponding change in Auth0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/466)
=> SF-666b get Auth0 interface language

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts, src/SIL.XForge.Scripture/SharedResource.cs
* read and write locale to cookie (cookie is authority)
* rename util function
* improve findLocale robustness
* ensure Auth0 language is lowercase
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/469)
=> SF-666c improve UI language communication

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/473)
=> SF-637 Explicitly configure redo in quill keyboard module

src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This covers the translation of strings for the front-end translate app except for messages
returned from the translation suggestions engine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/475)
=> Internationalize translate app

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es_ES.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es_ES.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts, src/SIL.XForge.Scripture/Resources/Pages.Index.es.resx, src/SIL.XForge.Scripture/Resources/Pages.RegisterSuccess.es.resx, src/SIL.XForge.Scripture/Resources/SharedResource.es.resx, src/SIL.XForge.Scripture/SharedResource.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/480)
=> Add Spanish

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml, src/SIL.XForge.Scripture/Resources/Pages.Index.resx, src/SIL.XForge.Scripture/Resources/Pages.RegisterSuccess.resx, src/SIL.XForge.Scripture/Resources/SharedResource.resx
- Rename misspelled variable in checking.component.ts
- Convert line with tabs to spaces in _Layout.cshtml
- Remove unused imports in _Layout.cshtml
- Rename SharedResource.en.resx to SharedResource.resx for consistency
- Remove BOM from resx files for consistency
- Remove trailing white space from resx files
- Convert line endings to LF in resx files
- Add new lines at end of resx files
- Non-English resx files left alone so changes can be round-tripped
through Crowdin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/481)
=> Misc fixes in ResX and other files

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/491)
=> SF-729 Collapse top nav bar when scrolling content

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/492)
=> SF-730 Style text area in components to be full width

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/489)
=> SF-687 Allow split container to dynamically calculate height

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json
* update @angular-devkit/build-angular
* waiting on npm update to fix remaining low priority update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/501)
=> fix npm vulnerabilities

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
* move project deleted message to community checking i18n file
* i18n work on share component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/502)
=> SF-741 Finish internationalizing question dialog

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/506)
=> SF-746 Disable collapsing of single app in sidebar

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
* SF-662 also fixes archiving in book view
* add checking text component spec
* remove Readonly from inputs
* code functionality is working but the tests for it are not working so are commented. Followup PR pending.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/395)
=> SF-632 Fix editing question verse in book view

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/509)
=> SF-750 Default connect to a project with checking enabled

src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.ts
The chapter text would not change if selecting a new chapter because no event was emitted. Additionally, when changing books in the translate app sidebar, the currently selected book did not update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/508)
=> SF-749 Change text when selecting different chapter

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/511)
=> SF-707 Highlight remotely edited answers

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/513)
=> SF-757: Check for null view children in CheckingComponent

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/516)
=> SF-752: Await local query updates when a doc is updated

src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
* Adjust code to account for the optional members
* Fix tests for the editor component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/517)
=> SF-758 Mark member variables from template query as optional

src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
- Having notes in the DOM throws off the algorithm for determining what text was selected
- Also fix a bug in how the text selection event was debounced
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/523)
=> SF-744 Fix text selection dialog when notes are present

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts, src/SIL.XForge/Controllers/UsersRpcController.cs, src/SIL.XForge/Services/AuthService.cs, src/SIL.XForge/Services/IAuthService.cs, src/SIL.XForge/Services/IUserService.cs, src/SIL.XForge/Services/UserService.cs, test/SIL.XForge.Tests/Services/UserServiceTests.cs
* needed so change password uses the selected language
* use backend API to update user's interface  language
* fix tests and some spelling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/524)
=> SF-666e save language back to Auth0

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json
* and 2 other vulnerabilities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/536)
=> Update npm vulnerabilities

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/537)
=> SF-778 Internationalize the report issue email

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts, src/SIL.XForge.Scripture/locales.json
When there are helps for the current language it should link to the helps for that language. Otherwise fall back to English helps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/540)
=> SF-764 Link to helps for selected locale

src/SIL.XForge/Services/AuthService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/547)
=> Add logging to AuthService.GetAccessTokenAsync to debug error

src/SIL.XForge.Scripture/appsettings.Development.json, src/SIL.XForge.Scripture/appsettings.Staging.json, src/SIL.XForge.Scripture/appsettings.Testing.json, src/SIL.XForge.Scripture/appsettings.json, src/SIL.XForge/Configuration/AuthOptions.cs, src/SIL.XForge/Services/AuthService.cs
* specify the Management API audience since its different than the domain with a custom domain (live only)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/549)
=> SF-788 Fix login 403 error on live

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/550)
=> SF-791 Fix internationalization of translate app title

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
For what it's worth, I'm aware one of the translations into Azerbaijani is clearly incorrect, and have already raised an issue in Crowdin:
English:
```
"range_label": "{{ startIndex }} - {{ endIndex }} of {{ length }}"
```
The incorrect translation:
```
"range_label": "{{ startIndex }} {{ endIndex }}{{ length }}-dən"
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/551)
=> Update all translation files from Crowdin

src/SIL.XForge.Scripture/Pages/Shared/_SelectLanguagePartial.cshtml, src/SIL.XForge.Scripture/Resources/SharedResource.resx, src/SIL.XForge.Scripture/SharedResource.cs
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/552)
=> Fix tool tip for language selector on home page

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Previously the placeholder in the text doc did not automatically update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/561)
=> Fix internationalization of loading placeholder

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
Add padding when auto scrolling to a verse
Also remove the extraneous auto-scrolling code from the question dialog (it's unneeded because the auto scrolling code in checking-text.component.ts does the same thing now).
Here's how it looks now when it auto scrolls with 20px of padding on top:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/571)
=> SF-815b Add padding when auto scrolling to a verse

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Occasionally Firefox calculates the height a little too low, resulting in a scroll bar when there should be none. I haven't figured out why, it's quite rare, and it doesn't greatly harm the user experience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/575)
=> SF-817d Fix dynamic height of answer panel

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/578)
=> SF-816 Fix layout of answers count on checking overview

src/SIL.XForge.Scripture/locales.json
They'll also need to be enabled on the Auth0 side of things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/580)
=> Enable Chinese, Russian, Portuguese, and Indonesian in production

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/scroll-into-view.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Previously the comment and answer forms sometimes were not fully within the viewable area when they opened.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/581)
=> SF-833 Auto scroll to answer and comment forms

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/users/users.component.html
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/582)
=> SF-853 Remove mention of collaborators on users page

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
* Fix processing of xml string on our end to preserve
whitespace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/593)
=> SF-864 - Don't drop any whitespace

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/591)
=> SF-860 fix Sync on implied paragraph

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/599)
=> Fix word wrapping in language menu

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
* fixes issue introduced in SF-864
* Now it only preserves all whitespace in data by removing whitespace at the beginning of lines and removing line endings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/596)
=> SF-875 Remove whitespace at beginning of lines

.vscode/launch.json, src/Migrations/Migrations.csproj, src/Migrations/Program.cs
* console app to read the old way and write the new way
* will be manually run on the server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/601)
=> SF-879 Migrate USX files

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/602)
=> SF-814 Don't display Connect Project while loading

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json, src/SIL.XForge.Scripture/Resources/Pages.Index.kyu.resx, src/SIL.XForge.Scripture/Resources/SharedResource.kyu.resx, src/SIL.XForge.Scripture/locales.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/606)
=> Release kyu to production

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxTestExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/609)
=> SF-881 Retain empty SFM

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, src/SIL.XForge.Scripture/Services/DeltaUsxExtensions.cs, src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxTestExtensions.cs
* use empty embed
* Also add tests for double nested chars
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/616)
=> SF-881b Support empty char in text

src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs, src/SIL.XForge.Scripture/Services/GuidService.cs, src/SIL.XForge.Scripture/Services/IGuidService.cs, src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs, test/SIL.XForge.Scripture.Tests/Models/CharAttr.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs, test/SIL.XForge.Scripture.Tests/Services/DeltaUsxTestExtensions.cs, test/SIL.XForge.Scripture.Tests/Services/TestGuidService.cs
* support nested adjacent chars
* use GUID for CharIDs
* improve InsertChar arg cohesion
Note this branch is based on another that is pending review and merge first.
Note the last commit is an "improvement" I'm not convinced about, please check.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/611)
=> SF-882 Retain adjacent char elements

src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/630)
=> SF-906 Localize project roles when filtering users

src/SIL.XForge.Scripture/Services/IInternetSharedRepositorySource.cs, src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/636)
=> SF-922 Get full names for projects on Connect page

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
- workaround for MSBuild issue 1454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/645)
=> SF-899: Fix some localizations not displaying on index page

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/647)
=> Add note to readme about handling grub dialog

.vscode/settings.json
* Should prompt users to switch to the workspace version of TypeScript for IntelliSense
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/641)
=> Use repo TS version in VS Code

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/649)
=> SF-861b Navigate from checking overview on remote checking disabled

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Not sure whether this is the ideal solution. Open to suggestions for improvement.
(You can disregard my password manager's little button in the form field)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/663)
=> SF-937 Disable sharing by email while offline

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
- attribute attributors are removed from usx-segment by Quill when
wrapped in usx-para-contents
- move "direction-segment" format from an attribute attributor to the
SegmentInline class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/662)
=> Fix dir attribute not getting set on usx-segment

src/SIL.XForge/Services/EmailService.cs
* don't send from the beta subdomain. The main site has setup for avoiding SPAM, the subdomain doesn't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/671)
=> Always send email from main site

src/SIL.XForge.Scripture/appsettings.Development.json, src/SIL.XForge.Scripture/appsettings.Staging.json, src/SIL.XForge.Scripture/appsettings.Testing.json, src/SIL.XForge.Scripture/appsettings.json, src/SIL.XForge/Configuration/SiteOptions.cs, src/SIL.XForge/Services/EmailService.cs
* proper cleanup after `hotfix/emailDomain` #671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/674)
=> Define email-from-address in settings

src/SIL.XForge.Scripture/Services/ParatextService.cs
To help more quickly diagnose and fix issues during sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/675)
=> Output ParatextData.dll debugging info

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
In Chrome, focusing the email field in the share component, typing something, and then going offline causes an ExpressionChangedAfterItHasBeenCheckedError as ng-untouched changes from true to false. That's because going offline causes the form field to be disabled, which causes it to lose focus, causing ng-untouched to change to false. The point at which it happens in the digest cycle causes the error to occur. This issue is tracked as angular/angular#17793. The same happens with the filter text box on the users page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/679)
=> Fix ExpressionChangedAfterItHasBeenCheckedError when going offline

src/RealtimeServer/common/web-socket-stream-listener.ts, src/RealtimeServer/package-lock.json, src/RealtimeServer/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts, src/SIL.XForge.Scripture/Startup.cs, src/SIL.XForge/Services/PingApplicationBuilderExtensions.cs
- remove code that allows local requests full access
- do not connect websocket before logging in
- refactor AuthService to check if online by pinging the backend
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/678)
=> Fix security bug when authenticating in real-time server

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/autofocus.directive.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/browser-globals.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
- The issue didn't actually call for handling middle mouse button, but I thought it made sense to include it.
- In Firefox, clicking using the middle mouse button triggers the popup blocker, unless the element is a link. This is an edge case I haven't figured out how to deal with.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/690)
=> SF-918 Open new tab upon ctrl click or middle mouse button

src/SIL.XForge.Scripture/ClientApp/src/environments/environment.prod.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-test.ts, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts
* values must exist in each environment file (they don't inherit)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/694)
=> SF-769b fix production build

test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/705)
=> Format file

.vscode/launch.json
Replacing the previous one. Maybe it should be added instead?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/709)
=> Launch migrator from vscode debugger

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
* navigate to the translate app to the book of the current question
* if community checking is remotely disabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/711)
=> SF-861c Set translate book for paratext user if checking disabled

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json
* `git add` is is included implicitly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/712)
=> security: update lint-staged

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/audio.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/audio.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-offline-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/audio-data.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/offline-data.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-query.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts
* cache question audio when navigating to checking app and online
* requesting question audio through audio service returns cached audio
* question audio in answer panel and question dialog works offline
* if audio url has changed the audio service will refresh its cache
* audio of answers remain unchanged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/696)
=> SF-962 Store question audio for offline use

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts
Previously, when the user was offline we were waiting for the realtime query to hear back from the server. Obviously, that never happened, so we never showed the new question icons in the text doc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/720)
=> SF-993 Show question icons in text doc when offline

src/SIL.XForge/SIL.XForge.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/721)
=> SF-977 SF-999 Bump JsonRpc.Router to 4.0.6 to fix no method matched

src/RealtimeServer/common/services/project-data-service.spec.ts, src/RealtimeServer/common/services/project-data-service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/724)
=> SF-966: Allow editing of an entity that was inserted in the same submit

.vscode/launch.json, .vscode/tasks.json, src/Migrations/PtdaSyncAll/Program.cs, src/Migrations/PtdaSyncAll/PtdaSyncAll.csproj, src/Migrations/PtdaSyncAll/build-dev, src/Migrations/PtdaSyncAll/build-production
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/718)
=> Migrator: Add usage documentation

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
* corrections for commit "Refactor audio upload into generic file upload"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/730)
=> Minor corrections after PR #723

src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/731)
=> Enable PWA in production (QA and Live)

deploy/vagrant_xenial_gui/Vagrantfile
For cleaner local git repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/740)
=> vagrant: Allow specifying vagrant RAM without modifying versioned file

src/SIL.XForge/ExceptionLogging/ExceptionHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/741)
=> Provide detailed error message in EnsureSuccessStatusCode

src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge/ExceptionLogging/ExceptionHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/746)
=> Merge qa logging hotfixes back to master

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/750)
=> SF-1004 Allow offline upload audio answers in Chrome incognito mode

src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/751)
=> SF-1014 Specify data collection for audio when creating a question offline

src/SIL.XForge.Scripture/Pages/LearnMore.cshtml, src/SIL.XForge.Scripture/Resources/Pages.LearnMore.resx
* From review by APEX copy writer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/756)
=> SF-541f Refactor Learn More text

src/SIL.XForge.Scripture/ClientApp/ngsw-config.json
- I got the list of URLs we serve from `app-routing.module.ts`
- I have tested this and believe it is working correctly, but I'm not 100% certain it's right. I would recommend testing by whoever reviews this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/759)
=> Change ngsw config to list only URLs to respond to

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-offline-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/offline-store.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts
* detect if space is limited and notify user early on
* reject storing addition data in offline store when quota exceeded
* prompt user with dialog with information about freeing space if quota exceeded
* catch errors related to storage quota exceeded in exception handler and show error snackbar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/762)
=> SF-964 Prompt user if storage quota on their device is limited or exceeded

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts
- update to latest version of Machine, which fixes duplicate suggestions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/768)
=> SF-953: Duplicate translation suggestions

src/Migrations/PtdaSyncAll/Program.cs
Commit "Migrator: Run synchronizations asynchronously" is ready for review, tho depends on unmerged code.
Another commit is part of this PR but shouldn't be: Dependency commit "Migrator: Make PtdaSyncAll sync all" is PR #739.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/764)
=> Migrator: PtdaSyncAll: Run synchronizations asynchronously 

src/SIL.XForge/Services/PingApplicationBuilderExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/770)
=> Ensure that ping endpoint is never cached

src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs, src/Migrations/PTDDCloneAll/Program.cs, src/Migrations/PTDDCloneAll/Startup.cs
* Use the existing text docs instead of recreating them after cloning Paratext projects
* Keep old projects files in folder with cloned Paratext projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/771)
=> Clone projects while using existing text documents

src/SIL.XForge.Scripture/ClientApp/angular.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/offline.html, src/SIL.XForge.Scripture/ClientApp/src/sf-service-worker.js
- Created `offline.html` to handle redirect script in to the app
- Created a wrapper service worker to allow additional event handling for `fetch` events
This PR adds additional functionality to our service worker that will return `offline.html` if a request is made for the `/` path. The `offline.html` page does a simple check to see if the user is logged in and then redirects them back in to the app. The purpose of this is to direct users in to the app who are offline and visit www.scriptureforge.org directly.
- The service worker is only loaded once the angular app is loaded. This means the offline page is not available until the service worker is initialized. I believe this is fine as the purpose of this PR is to provide a way back into the app while offline and visiting the `/` path
- …
=> SF-1032 - Redirect user to app from home page when offline

.vscode/launch.json, src/Migrations/PtdaSyncAll.Tests/SyncAllServiceTests.cs, src/Migrations/PtdaSyncAll/ISyncAllService.cs, src/Migrations/PtdaSyncAll/Program.cs, src/Migrations/PtdaSyncAll/SyncAllService.cs
This PR depends on unsubmitted PR #766. I will plan to rebase this PR on master after its dependency is submitted. But someone else can if they beat me to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/774)
=> Migrator: PtdaSyncAll: Allow a subset of projects to be synchronized

.vscode/launch.json, src/Migrations/PtdaSyncAll.Tests/SyncAllServiceTests.cs, src/Migrations/PtdaSyncAll/ISyncAllService.cs, src/Migrations/PtdaSyncAll/Program.cs, src/Migrations/PtdaSyncAll/SyncAllService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/777)
=> Migrator: PtdaSyncAll: Specific admin, Reword, Inspect doesn't sync

src/SIL.XForge.Scripture/ClientApp/src/sf-service-worker.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/779)
=> Removed console logs from service worker

src/SIL.XForge.Scripture/ErrorPages/503.html
- Created a template for a server 5xx page
I wasn't sure where this was to sit in our repository so let me know if it should be placed somewhere else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/781)
=> SF-1042 - Design nice site unavailable page

src/SIL.XForge.Scripture/Pages/LearnMore.cshtml
* the new video links reduce/normalize the music and effect volume (from user feedback)
* hot fix because 1 previous video was deleted too early
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/792)
=> Update learn more video links

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
When the app loads, it immediately redirects back to the home page. This was caused by a bug in Webkit that causes storage events to be fired in the tab where they originate, rather than only in other tabs: https://bugs.webkit.org/show_bug.cgi?id=210512
The workaround is to check that the old value for `user_id` is not nullish. I also check that the value is different from the previous value, just in case some browser would fire an event for "changes" to the value that don't actually change the value.
I've made a CodePen that demonstrates what each browser it's opened in does: https://codepen.io/Nateowami/full/GRZxYbp
In browsers that implement the storage event properly, it only fires if you open that in two tabs.
I haven't tested my changes in Safari 13.1 (loading pages from my machine …
=> SF-1038 Fix broken login in Safari 13.1

src/Migrations/PTDDCloneAll.Tests/CloneAllServiceTests.cs, src/Migrations/PTDDCloneAll.Tests/PTDDCloneAll.Tests.csproj, src/Migrations/PTDDCloneAll/CloneAllService.cs, src/Migrations/PTDDCloneAll/ICloneAllService.cs, src/Migrations/PTDDCloneAll/IPTDDSyncRunner.cs, src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs, src/Migrations/PTDDCloneAll/Program.cs, src/Migrations/PTDDCloneAll/Startup.cs, src/SIL.XForge/Services/FileSystemService.cs, src/SIL.XForge/Services/IFileSystemService.cs
* moved cloning functionality to a CloneAllService class
* added test to CloneAllService
* inject and use FileSystemService to handle file system requests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/802)
=> Allow cloning a subset of SF projects in migration tool

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
The problem was caused by attempting to get the token from the URL after it had already been removed from the URL. That lead to sending a request to Auth0 to check the session, and in browsers that block third-party cookies, the request would fail, leading to the user being logged out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/805)
=> SF-1038b Fix tryOnlineLogIn failing when 3rd party cookies are blocked

src/SIL.XForge.Scripture/Services/ParatextService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/807)
=> Use short name in GetProjects if metadata is not present

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
* get issue email from environment
* fix up unneeded async
* add checkbox label tag and align vertically
**Note:** This change is non-functional and doesn't need merging until after the migration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/806)
=> Cleanup after PR #804

src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs
- 5 projects failed to sync during migration stage 1 when they got a
500 Internal Server Error fetching a book from PTDA. But in one or
more of these cases, there were no text changes in SF anyway, and so
in that situation we can skip fetching the book in stage 1 and get it
from migration stage 2.
**Note that this PR is targetting branch `sync-all-build`, which is where the PtdaSyncAll stage1 migrator tool gets built from.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/808)
=> PtdaSyncAll: Skip failed PT book fetch if unneeded

src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs
- To provide more context for responding to permission failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/811)
=> PtdaSyncAll: Print the chapter diff

src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs
- The index out of bounds error on migrating 3 projects appears to be
a situation where the project doc has no project 'texts' entry for a
book, but there is a book .usx file on disk. This causes the
PtdaSyncRunner to try to 'sync' rather than 'clone' the book, leading
it down a path where it has a problem because it expects TextInfo
Chapters.Count to be >0. Instead, just clone the book again.
- The situation may have been originally caused by a synchronization
that only partially cloned, leading to a .usx file on disk, and even
chapter text docs, but no text info written to the project doc.
- Because we don't understand the nature of why the project metadata
is invalid/corrupted, or what activity may have been done in the
project, we want to preserve existing data. So print any chapter …
=> PtdaSyncAll: Warn and re-clone if no textinfo

src/SIL.XForge.Scripture/Services/ParatextService.cs
* The output was helpful during development of ParatextService
* It can be uncommented on a local machine when needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/816)
=> Comment out the output from ParatextService

src/RealtimeServer/scriptureforge/models/sf-project.ts, src/RealtimeServer/scriptureforge/models/translate-config.ts, src/SIL.XForge.Scripture/Models/SFProject.cs, src/SIL.XForge.Scripture/Models/TranslateSource.cs, src/SIL.XForge.Scripture/Services/IParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
* set the IsRightToLeft property as a final step during synchronization with paratext
* expose a paratext project's rightToLeft setting to the front end
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/825)
=> SF-1090 Set IsRightToLeft property on project on sync

.vscode/settings.json, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge/Services/AudioService.cs, src/SIL.XForge/Services/AuthService.cs
* fixes 4 of the outstanding 10 alerts
* the remaining 6 are false positives. These could be fixed by SF-1057
* also fix settings json error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/828)
=> Fix LGTM.com alerts

deploy/dependencies.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/829)
=> Upgrade to node LTS v12

deploy/dependencies.yml, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/833)
=> Sync: Update location for ParatextData Internet settings

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
Oops, another git repo will also need an update to the location specified to get an InternetSettings.xml file. I don't think such updates will need to be done urgently, but at least eventually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/834)
=> Config: Mention other place to update for PTD version

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
* Show that scripture book does not exist if online
* Show that scripture text is unavailable if offline
* Show book is empty if book does not contain chapters
* Add text.component tests
* Put generic SFProject and TextData construction in test-utils
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/832)
=> SF-935 Show useful messages on scripture panel when text is unavailable

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts
When switching to offline and online mode, sometimes a network call is made when the app is technically offline, so the result is an error. This adds an extra guard by allow the app to process any lifecycle things before attempting to send the metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/838)
=> Send metrics on timeout to prevent errors from being offline

src/Help/UpdateHelp/Program.cs, src/SIL.XForge.Scripture/locales.json
- remove unused items
- add Google search
- fix translation keys - include both titles and headings in translations
- escape XML and JSON string translations
- also publish help for es
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/845)
=> SF-886b Fix search for other languages

deploy/dependencies.yml
- Or you can get an error saying you don't have the key for the repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/847)
=> Setup: Install packages.microsoft.com key before adding repo

src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
- Ensure question offline data has finished loading before updating any new offline data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/844)
=> SF-1097 - Reload and add question error

README.md, deploy/playbook_focal.yml, deploy/vagrant_xenial_gui/Vagrantfile, deploy/virtualbox_xenial_gui_creation/Vagrantfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/851)
=> Setup: Update playbook to reflect working in Ubuntu 20.04

deploy/dependencies.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/852)
=> Setup: Use bionic mongodb on focal

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
* questionDoc is passed along for saving the answer
* block user from clicking save answer multiple times during upload
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/855)
=> SF-1051 Specify question doc when saving an answer

src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/859)
=> SF-876 Automatically redirect user from page not found page

src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
This has bothered me for a while particularly on the clone (Connect Project) where the progress stays on 0% for about a minute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/860)
=> Clone and Sync progress indeterminate until non-zero

deploy/vagrant/sfdev/base/provision
Now implemented conditionally in dependencies.yml.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/857)
=> vagrant: Remove mongodb focal workaround

src/SIL.XForge.Scripture/Services/SharingLogicWrapper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/874)
=> Fix comment referring to SharingLogic

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
Previously, when reimporting questions, if the verse reference had changed, the user was not prompted to confirm reimporting the question.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/881)
=> SF-1152 Fix prompting when reimporting question with changed reference

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
* avoid making a network request unless a user is online
* query for transcelerator questions when returning online
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/885)
=> SF-1159 Hide import questions button when offline

src/Help/UpdateHelp/Program.cs, src/SIL.XForge.Scripture/locales.json
- I've created the Google Programmable Search Engine for fr
- this adds its ID
- the language help site has been verified on Google Search Console
- publish fr help and fix localName
The help for fr is now active but the search will take some time for Google to crawl and index it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/882)
=> Add help search engine for fr

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
Before | After
-------|------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/889)
=> Fix table width in import questions dialog

src/SIL.XForge.Scripture/Services/ParatextService.cs, test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/901)
=> Ensure that admin always has permission to update book texts

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
When we show the login error dialog (which I get a _lot_ locally) it's not possible to tell what the actual error was unless it's logged. Currently most errors get logged right before being reported to Bugsnag. However, since we don't handle these errors the same, they don't get logged. This change gives developers the option of opening the console to see what the actual error is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/870)
=> Log authentication errors to console

scripts/build-and-upload-beta.sh
- corresponding values have been placed in TC for QA and Live
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/911)
=> Add PT resource password for TC

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/913)
=> doc: How to generate sf.min.css

src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change will detect if the current selection is a valid project or resource, and will show an error if it is not.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/921)
=> SF-1175 Show error on invalid selection in project select component

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
(Also fix a minor mistake in the tests).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/922)
=> Fix deprecation warnings in project-select component

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/926)
=> doc: Add link to Microsoft .NET library design guidelines

src/SIL.XForge.Scripture/Services/ParatextService.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/919)
=> Add unit test for resource cloning fix

src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
* the project input is valid if the name is that of a selectable project
* also disable component when parent element is offline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/929)
=> SF-1175b Allow manual selection in project select

src/SIL.XForge.Scripture/ClientApp/angular.json, src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts, src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
When a source project exists, the progress represents the entirety of synchronizing both the source and target projects.
* extract the sync progress bar into its own component
* sync progress automatically detects if a source project exists and updates accordingly
* sync progress is implemented as an angular material component
* add theming to angular material component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/923)
=> SF-1177 Show progress as source and target projects combined on sync

src/RealtimeServer/common/models/project-role.ts, src/RealtimeServer/scriptureforge/models/sf-project-role.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts, src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs, src/SIL.XForge.Scripture/Services/SFProjectService.cs, src/SIL.XForge/Services/IProjectService.cs, src/SIL.XForge/Services/ProjectService.cs
* Add an endpoint to return a user's role on a project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/932)
=> SF-1178 Access source project only if user has permission

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts
To test this you need to build for testing the pwa. After the build finishes you will need to wait approximately 30 seconds, and you may need to navigate to a different page. Then the banner will appear asking you to refresh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/935)
=> SF-1035 Add prompt when app version has changed

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge.Scripture/Services/SFScriptureText.cs
- fixes a crash in Machine that can occur when training some projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/933)
=> Update to latest version of Machine

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge.Scripture/Services/SFScriptureText.cs
- this hotfix is already on master. sf-live should be reset when it is time to upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/937)
=> hotfix: Update to latest version of Machine (cp #933)

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/936)
=> SF-1173 Fix project select autocomplete menu to input element

src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
This reverts commit d41071848f96b96af12b56cbf30efe875c783eaf.
More information is in SF-1197.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/942)
=> Revert "Tell the user and redirect if project is not found (#927)"

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/947)
=> Fix import questions function to always return a promise

src/SIL.XForge.Scripture/ClientApp/tsconfig.json
====
( https://www.typescriptlang.org/tsconfig#noFallthroughCasesInSwitch )
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/953)
=> Turn on noFallthroughCasesInSwitch TypeScript compiler option

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
* Do not access source project if user not on the project
* Fix regression that hides source text if offline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/939)
=> Fix error when a user tries to sync without source project permission

src/SIL.XForge.Scripture/Services/SFScrTextCollection.cs
- ParatextData ScrLanguage.LoadWsDef() can try to read an ldml file
that isn't there. Back in ScrText.CreateLayoutEngine() we catch this
and try to find or make it in other ways with
ScrTextCollection.GetLanguage().
- One possible way is via SFScrTextCollection.CreateWsDef(). The code
being introduced here was copied (and modified) from ParatextBase.
- The problem of an ldml file not being present when it's asked for
can happen when using certain DBL resources, such as those that were
made with Paratext 7, prior to ldml files being included.
- A better solution for the problem would be to _migrate_ the
resource to a newer version/format. But fetching from SLDR will let us
proceed for now.
- Rename SFScrTextCollection.cs to correspond to class name.
--- …
=> SF-1162 Fetch ldml for resource if not present

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/955)
=> SF-1204 Do not show link sharing in dialog when link sharing is disabled

src/SIL.XForge.Scripture/Services/SFProjectService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/956)
=> SF-733b Include locale in invitation email link

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
My testing when I was working on this was flawed, making it appear the change in #956 was sufficient, when it actually needed this change as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/958)
=> SF-733c Fix login language when user clicks invitation link

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
* also SF-1206 show connecting state immediately on clicking connect on connect project page
* adjust sync progress component to initialize when a project doc is provide
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/952)
=> SF-1167 Prevent import dialog from opening multiple times

src/SIL.XForge.Scripture/Startup.cs, test/SIL.XForge.Scripture.Tests/I18N/SharedResourceTests.cs, test/SIL.XForge.Scripture.Tests/StartupTests.cs
- support production builds
- also change tabs to spaces in SharedResourceTests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/964)
=> SF-1213 Whitelist SPA routes

src/SIL.XForge.Scripture/Startup.cs, test/SIL.XForge.Scripture.Tests/StartupTests.cs
- development needs to allow at least one post request
- include favicon and map files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/966)
=> SF-1213b add whitelist for post and update routes

src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj, src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs, src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs, test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/968)
=> Add Biblical terms to training corpus if available

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
The project$ member needs to be a behavior subject so that it emits the current value when an observer subscribes to it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/974)
=> Fix share link blank when opened from checking app

src/SIL.XForge.Scripture/Services/IInternetSharedRepositorySourceProvider.cs, src/SIL.XForge.Scripture/Services/ISFRestClientFactory.cs, src/SIL.XForge.Scripture/Services/InternetSharedRepositorySourceProvider.cs, src/SIL.XForge.Scripture/Services/JwtRestClient.cs, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge.Scripture/Services/SFDblRestClientFactory.cs, src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs, test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
* Remove application product version in RESTClient constructor parameters
* Set OverrideApplicationAgent in RESTClient constructor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/976)
=> Update RESTClient application agent header

src/SIL.XForge.Scripture/appsettings.json
- To assist in identifying the cause of using lots of memory. Logging
Information messages from SIL will show when training begins and ends.
For example,
> info: SIL.Machine.WebApi.Services.EngineRuntime[0]
>       Build started (1234)
> info: SIL.Machine.WebApi.Services.EngineRuntime[0]
>       Build completed in 232.7947ms (1234)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/978)
=> SF-1219 Log 'Information' on server from SIL namespace

src/SIL.XForge.Scripture/Startup.cs
- account for 'DevelopmentBeta' environment
This is needed to get QA working again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/981)
=> SF-1156b add endpoint to server whitelist

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/975)
=> SF-1224 Add DBL to based on explanation

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-progress-dialog/import-questions-progress-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-progress-dialog/import-questions-progress-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/982)
=> SF-1214 Improve question import speed and show progress

src/SIL.XForge.Scripture/Services/SFProjectService.cs, test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/989)
=> SF-1199b remove magic strings

.editorconfig, src/SIL.XForge.Scripture/Pages/Index.cshtml, src/SIL.XForge.Scripture/Pages/LearnMore.cshtml, src/SIL.XForge.Scripture/Pages/Shared/Components/Footer/Default.cshtml, src/SIL.XForge.Scripture/Resources/Pages.LearnMore.resx
- also lazy load images
@nigel-wells do you still have your copywriter to check this content?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/988)
=> SF-1233 Add offline video

.gitignore
====
I keep getting a .pyc in a subdirectory, that this will ignore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/987)
=> Broaden .pyc ignore

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts
Checking if the user needs migration, while offline, results in an error dialog. Don't do it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/993)
=> SF-1237 Wait for user to come online before checking if needs migration

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-deleted-dialog/project-deleted-dialog.component.html
----
This is a followup from a prior PR's comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/995)
=> SF-1237 Refactor test method

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
- Enabled JavaScript redirect from beta to non-beta unless referral is non-beta
This PR should only be merged once we're happy the beta migration work from SF-1156 is working as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/984)
=> SF-1228 - Redirect beta to live via the app

src/SIL.XForge.Scripture/ClientApp/angular.json, src/SIL.XForge.Scripture/ClientApp/src/environments/environment.pwa-testBeta.ts
- To enable local offline testing of beta site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1008)
=> Introduce pwaTestBeta

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/ClientApp/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1009)
=> Update npm packages to fix vulnerabilities

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1016)
=> Fix internationalization of beta migration dialog

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.ts
- Directing to community site rather than the email address instead or
also, since the email address isn't working at present.
The message appears after a small number of retries. Each retry is currently after 10 seconds. I included mention of being online since it's possible to be offline while this dialog is showing if the Internet is turned off.
See animation. Clicking on the ask for help link opened the result in a desktop-size tab, so it looks funny in the demo. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1015)
=> SF-1256 Hint to user about incognito or other migration help

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
- Clear local storage
- Delete indexDB data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1018)
=> SF-1262 - Clean up local beta site data

src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
I assume that this is important enough to be a hotfix, but since we are shipping anyways we could put this on master.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1020)
=> SF-1248 Show source even if user does not have edit rights on target text

src/SIL.XForge.Scripture/ClientApp/src/_text.scss
- Change the scripture verse highlight background colour
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1028)
=> SF-1299 Increase source highlight contrast

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
- Ensure `checkSession` is only run once to avoid overlapping requests
- On error for auth0 trigger a `logIn` rather than `logOut`
- Report error to bugsnag for when renewing token fails
Although this task was primarily around triggering a login rather than a logout (which deletes data) I needed to find a way to trigger auth0 errors in order to test that it works. After understanding the errors I was able to resolve them at the same time.
One of the underlying issues with auth0 errors is when local storage `expires_at` is triggered at the same time the `tryOnlineLogIn` is triggered. Both call auth0 `checkSession` which generates a cookie and nonce in local storage and the end up stomping on each other. This occurrence can happen if someone has been logged in, shuts the browser down while …
=> SF-1276 - Auth0 timeout deletes offline data

src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, src/RealtimeServer/scriptureforge/models/sf-project-role.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-role-info.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
- Created a new translate observer role
- Added role selection to the share component for admins
- Added share button to the translate app for admins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/979)
=> SF-1201 Allow inviting users from the translate app

src/Migrations/PTDDCloneAll/CloneAllService.cs, src/Migrations/PTDDCloneAll/IPTDDSyncRunner.cs, src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1034)
=> Add full synchronize ability to console app

src/Help/UpdateHelp/Program.cs, src/SIL.XForge.Scripture/locales.json
The help site is already up https://help.scriptureforge.org/pt_BR/ but search is waiting on Google to index it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1033)
=> Add Brazilian Portuguese help

src/SIL.XForge.Scripture/ClientApp/package-lock.json, src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1035)
=> SF-1215 Delete Paratext notes from books deleted in Paratext

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1044)
=> SF-1326 Fix error for checker user when book is deleted

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts, src/SIL.XForge.Scripture/ClientApp/tsconfig.json
- no compile errors except in prod build
- fixes for prod build
- needed to disable "strictInputTypes"
- helps VSCode checks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1045)
=> Make Angular compiler strict

src/SIL.XForge.Scripture/Services/SFProjectService.cs
This was missed in #1042 7559b3ac60e9166f1e50b4b30e4e46f2e3391eea
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1046)
=> SF-1297b Fix permission checking for TransceleratorQuestions endpoint

.github/workflows/ci.yml
- does a production build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1048)
=> GA build test

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1049)
=> SF-1249 Disallow inviting checkers when checking is disabled

src/SIL.XForge.Scripture/ClientApp/package-lock.json
This should fix the Dependabot alerts for `dns-packet` and `browserslist`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1054)
=> Update packages with npm audit fix

src/RealtimeServer/common/web-socket-stream-listener.ts, src/RealtimeServer/revert-docs.js, src/RealtimeServer/typings/sharedb/lib/client.d.ts
- includes a script to revert text docs to a previous version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1058)
=> Allow tools to connect to the ShareDB server locally

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
- add announcements and community support links to Help menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1059)
=> SF-1334 Add to Help menu

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bugsnag.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
- Navigation triggered outside Angular zone
- Bugsnag.leaveBreadcrumb() was called before Bugsnag.start()
- run timeout outside of ngzone
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1056)
=> Fix warnings when running Angular tests

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bugsnag.service.ts
This was broken in a87af728cf12e2dfc2c446038ad8b8513751a86b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1065)
=> Fix injection of BugsnagService

src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1052)
=> SF-1300 Prevent editing settings while they are still loading

deploy/vagrant/sfdev/Vagrantfile, deploy/vagrant_xenial_gui/Vagrantfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1070)
=> vagrant: Update base box location

src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1072)
=> SF-1353 Fix message when user does not have permission to edit question

src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
The event handler for `ParatextSyncRunner.UseNewProgress()` was not being deregistered, resulting in the `ParatextSyncRunner`, the `Connection`, and any `Document` objects remaining in memory after sync.
This pull request now fixes that memory leak by correctly de-registering the event handler.
The result of which is that GC can now dispose of these objects when required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1075)
=> SF-1219a: Fixed event handler leak

src/RealtimeServer/package.json, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1079)
=> SF-1365 Disable drag and drop to translate editor

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
- also rationalize tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1085)
=> SF-1048d remove sync cancelled message

src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1087)
=> SF-1048f fix sync finished logic

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1091)
=> SF-1033b L10n for Link with Paratext

mongodb/Texts/CorruptedTexts.mongodb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1092)
=> Add Mongo query to search for corrupted texts

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1102)
=> doc: sync process

src/Help/UpdateHelp/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1103)
=> Improve Help Update error reporting

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1111)
=> doc: How to do a production build locally

scripts/build-and-ship, src/SIL.XForge.Scripture/Services/ParatextService.cs, src/SIL.XForge.Scripture/Startup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1112)
=> Add comment, fix typos

src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1107)
=> Display project short name

src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1116)
=> SF-1344b Copy selection if hold ctrl key when dragging

mongodb/TranslateMetrics/TranslateMetricsAggregation.mongodb, mongodb/TranslateMetrics/TranslateMetricsAggregationByBook.mongodb, mongodb/TranslateMetrics/TranslateMetricsAggregationByChapter.mongodb, src/RealtimeServer/scriptureforge/scripture-utils/canon.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts
- should increment offered suggestion count when inserting suggestion
- should not increment accepted suggestion if the content doesn't change
- also fixed metric aggregation of word counts
Commits are separate if you want to see which fix goes with which test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1113)
=> SF-1370 Fix translate metrics

src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1119)
=> SF-1376 Fix import questions dialog to only import filtered questions

src/SIL.XForge.Scripture/Pages/Index.cshtml, src/SIL.XForge.Scripture/Pages/LearnMore.cshtml, src/SIL.XForge.Scripture/Resources/Pages.Index.resx, src/SIL.XForge.Scripture/Resources/Pages.LearnMore.resx
This is on request from PT to improve Paratext website's ranking on Google.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1124)
=> Add Paratext links to static pages

mongodb/TranslateMetrics/TranslateMetricsAggregationByBook.mongodb, src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts
Some cleanup that didn't make it in the earlier work on SF-1370 but I thought there would be more work to fix `productiveCharacterCount` however we have not been able to reproduce that issue after the first changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1132)
=> SF-1370b cleanup

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts
This was broken in #1099 
The tests were outputting this error message about 4 times because I didn't write the tests properly.
```
WARN: TypeError: You provided 'null' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
TypeError: You provided 'null' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
at subscribeTo (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm2015/internal/util/subscribeTo.js:27:1)
at subscribeToResult (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm2015/internal/util/subscribeToResult.js:11:23)
at CombineLatestSubscriber._complete (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/_esm2015/internal/observable/combineLatest.js:52:43)
at …
```
=> Fix test errors in share control component

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
Mark and I looked at this today and came up with a test that is much easier to read and follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1138)
=> Improve import question button test in checking overview

src/SIL.XForge.Scripture/ClientApp/src/app/core/machine-http-client.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
- also fix deprecated `tap` signature (see second commit)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1137)
=> SF-1354 ignore 504 for machine and command

src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1140)
=> SF-1400 Sort questions by canonical order

src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts, src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1143)
=> SF-1402 Fix link sharing being shown when it's not available

mongodb/Users/InviteLink.mongodb, mongodb/Users/UsersNeedMigrating.mongodb
- also, users still to migrate Mongo query
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1142)
=> Mongo query to reconstruct invite link

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1147)
=> doc: add Quill, Delta

mongodb/Texts/CorruptedTexts.mongodb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1152)
=> Update script to find corrupted text docs

mongodb/Projects/UnusedResources.mongodb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1154)
=> Add query to find unused resources
